### ISSUE TITLE
Multiple-Nodes javabatch deployment

### ISSUE THREAD

**Issue by albertwang-ibm** [IBM/FHIR#100]
During Connectathon, we found the job submission was very slow, from the logs, looks like the job submission response was only returned after the job was actually finished. We hope separating job dispatch and executor can make the job submission faster.

**Comment by prb112** [comment]
While working on #633 I thought we should probably add an array to "batch-uri": "https://localhost:9443/ibm/api/batch/jobinstances" so it could work even if a specific node it was pointed to failed.

**Comment by albertwang-ibm** [comment]
> While working on #633 I thought we should probably add an array to "batch-uri": "https://localhost:9443/ibm/api/batch/jobinstances" so it could work even if a specific node it was pointed to failed.

I have just created issue #636 for simplify the batchclient and configuration.

**Comment by albertwang-ibm** [comment]
I have run multiple deployment tests in my local and in CDT, I can not reproduce the job submission delay issue which happened during Connectathon 22. 
Configuring separated job schedulers and executors makes the configuration and workflow more complicated - have to add new configurations and the job can only be submitted to the fhir server instance with scheduler configured.   

So, I would prefer to continue our current simple deployment architecture to allow each fhir server instance to act as executor for its received job request, and leverage load balance to send the request to the alive server.   

Test 1:
     In local env, run multiple instances of fhir servers which share the same local DB2 javabatch  database and without separation of job scheduler and Job executor. test jobs were submitted in few seconds.

Test 2: 
     In local env, run multiple instance of fhir servers which share the same IBM Cloud DB2 javabatch  database and without separation of job scheduler and Job executor. Test jobs were submitted in few seconds.

Test 3:
      In CDT env, run multiple instance of fhir servers which share the same IBM Cloud DB2 javabatch  database and without separation of job scheduler and Job executor. Test jobs were submitted in few seconds.

Test4: 
      In local env, run multiple instance of fhir servers which share the same local DB2 javabatch  database and with MQ and separated job schedulers and Job executors. Test jobs were also submitted in few seconds.

Test5: 
      In local env, run multiple instance of fhir servers which share the same IBM Cloud DB2 javabatch  database and with MQ and separated job schedulers and Job executors. Test jobs were also submitted in few seconds.

**Comment by prb112** [comment]
> > While working on #633 I thought we should probably add an array to "batch-uri": "https://localhost:9443/ibm/api/batch/jobinstances" so it could work even if a specific node it was pointed to failed.
> 
> I have just created issue #636 for simplify the batchclient and configuration.

I investigated this approach in my PR.  It does not work as you'd think.  The start method actually starts the job on the local Jar.

**Comment by prb112** [comment]
Closed in discussion
