### ISSUE TITLE
Support simple calculation of patient age in fhirpath

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#1014]
**Is your feature request related to a problem? Please describe.**
The FHIR spec defines some special search parameters at https://www.hl7.org/fhir/R4/patient-profiles.html#search

One of the most useful ones there is "age".

To properly support this parameter, we need to be able to express age in fhirpath...the difference between the Patient.birthDate and the current date in Years.

**Describe the solution you'd like**
1. add support for the fhirpath date/time built-ins:
  ```
  now() : DateTime
  Returns the current date and time, including timezone offset.

  timeOfDay() : Time
  Returns the current time.

  today() : Date
  Returns the current date.
  ```

2. set these at the beginning of evaluate due to:
> To ensure deterministic evaluation, these operators should return the same value regardless of how many times they are evaluated within any given expression (i.e. now() should always return the same DateTime in a given expression, timeOfDay() should always return the same Time in a given expression, and today() should always return the same Date in a given expression.)

3. define a fhirpath function named `duration` or `calculateDuration` or similar which takes 3 operands:
* an "initial" Date or Datetime
* a Date or Datetime to diff it with
* the unit you want back (one of the time units at http://hl7.org/fhirpath/#datetime-arithmetic)

Then you could calculate the age like `calculateDuration(Patient.birthDate, today(), 'years')`

**Describe alternatives you've considered**
Overloading `-` is another option, but feels odd to me since `+` wouldn't make any sense.

**Additional context**
In my opinion, the fact there's no simple age calculation in FHIRPath is a *big* gap.
There's some good discussion on this at https://chat.fhir.org/#narrow/stream/179266-fhirpath/topic/Age.20from.20birthdate.3F

**Comment by prb112** [comment]
This is a good one.
