### ISSUE TITLE
No longer able to map unauthenticated users to the FHIRUsers security-role

### ISSUE THREAD

**Issue by albertwang-ibm** [IBM/FHIR#1020]
We were using a configDropin to map special-subject EVERYONE to the FHIRUsers role (since authentication is being handled by a gateway).
Now, with the latest changes, this isn't working and it results in the health check failing with HTTP 401.

**Comment by lmsurpre** [comment]
Reproduced locally just by adding a config override like this:
```
    <!-- webApp security is provided via IAM in IBM Cloud -->
    <webAppSecurity singleSignonEnabled="false" useAuthenticationDataForUnprotectedResource="false"/>
    <webApplication id="fhir-server-webapp">
        <application-bnd id="binding">
            <security-role id="users" name="FHIRUsers">
                <special-subject type="EVERYONE"/>
            </security-role>
        </application-bnd>
    </webApplication>
```
and hitting a protected endpoint.

But I was NOT able to reproduce locally for the `$healthcheck` endpoint, so not sure what is going on there.

**Comment by lmsurpre** [comment]
I created a tiny reproducing case and openened it as an issue for OpenLiberty at https://github.com/OpenLiberty/open-liberty/issues/12050.
We might need to revert the change to the use of `@RolesAllowed` until that can get addressed (or else come up with an alternative for our cloud deploy).

**Comment by lmsurpre** [comment]
Our workaround has been to add the Authorization header via our kubernetes ingress.  That said, I really thought the Liberty team would have this addressed by now; we might need to do something here...

**Comment by prb112** [comment]
This feature is going to be in the next release.

**Comment by lmsurpre** [comment]
I confirmed that this is working now by adding a configDropin with the following content to a local deploy;
```
<server>
    <webApplication id="fhir-server-webapp">
        <application-bnd id="bind">
            <security-role id="users" name="FHIRUsers">
                <special-subject type="EVERYONE"/>
            </security-role>
        </application-bnd>
    </webApplication>
</server>
```

with liberty 22.0.0.3 this is finally behaving as expected; I am able to invoke protected endpoints like `$healthcheck` without specifying a username/password:
```
$ curl -k -i 'https://localhost:9443/fhir-server/api/v4/$healthcheck'
HTTP/2 200 
date: Fri, 01 Apr 2022 19:05:37 GMT
content-length: 0
content-language: en-US
```
