### ISSUE TITLE
Remove dead code in fhir-persistence-schema

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#1021]
Paul and I noticed that there are a few places in the fhir-persistence-schema with commented out code or classes that don't get called at all.  Keeping these around complicates our lives and makes it harder to know where we should make certain changes.

1. AdminSchemaGenerator
2. FhirSchemaGenerator.buildProcedures()

**Comment by prb112** [comment]
```

**Comment by prb112** [comment]
PR https://github.com/IBM/FHIR/pull/1056
