### ISSUE TITLE
Enhance BulkExport to be able to support multiple resource Types

### ISSUE THREAD

**Issue by albertwang-ibm** [IBM/FHIR#103]
We need to figure out a way to support multiple resource types inside the javabatch job or we will have to ask the operation codes to send multiple job requests - one for each resource type and then consolidate the results.

**Comment by lmsurpre** [comment]
After this task, we should only have a single export implementation (or details explaining why there is more than one).
Currently we have a chunked and non-chunked version.  My assumption is that the chunked version is more performant.  However, Albert thinks it may be hard to support multi-resource export using chunked approach.
