### ISSUE TITLE
Some manual e2e tests never run because testng.xml is out-of-date in fhir-server-test

### ISSUE THREAD

**Issue by JohnTimm** [IBM/FHIR#1053]
There are a handful of manual e2e tests that never run because testng.xml is out-of-date. Testng.xml should be updated to include all server integration tests and we can work out specific issues from there.

**Comment by lmsurpre** [comment]
Or better yet, maybe we change / remove testng.xml altogether so that new tests are picked up automatically (by default).

**Comment by JohnTimm** [comment]
I think we originally decided to go the testng.xml route so that we could easily remove or disable tests until they are fixed or removed.
