### ISSUE TITLE
Import and Export - Confirm the Operation Outcomes and Automate the Tests

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#1054]
Import and Export are complicate features. 

We need end2end tests automated: 
1. Setup automation 
2. Confirm that the files for $import are written
>               "url": "test-import.ndjson_oo_success.ndjson", 
>               "url": "test-import.ndjson_oo_failure.ndjson", 
3. Confirm that $export content is correct

**Comment by prb112** [comment]
Be sure to switch on the export/import to default enabled...per pr comment https://github.com/IBM/FHIR/pull/1088/checks

**Comment by lmsurpre** [comment]
This was added to the pipeline as part of the PR which added minio support:  https://github.com/IBM/FHIR/issues/1242
Further improvements should be made when we expose the support for file-based import/export:  https://github.com/IBM/FHIR/issues/1055
