### ISSUE TITLE
Touchstone content-type check failed for delete 200 OK response

### ISSUE THREAD

**Issue by albertwang-ibm** [IBM/FHIR#1086]
The tests were passed when server returned 204 (no content) before, with the recent change to respond 200 OK with operationoutcome, touchstone does the content-type header check and the check failed.

Touchstone error links:
(1) https://touchstone.aegis.net/touchstone/scriptexecution?exec=202005131220248895660111&qn=/FHIR4-0-1-Advanced/Patient/05-delete/fhir-api-r4-patient-delete-01-base#WAITING_OPER
(2) https://touchstone.aegis.net/touchstone/scriptexecution?exec=202005131220248895660111&qn=/FHIR4-0-1-Advanced/Patient/05-delete/fhir-api-r4-patient-delete-02-conditional-single#WAITING_OPER
(3)https://touchstone.aegis.net/touchstone/scriptexecution?exec=202005131220248895660111&qn=/FHIR4-0-1-Advanced/Patient/05-delete/fhir-api-r4-patient-delete-03-conditional-multiple#WAITING_OPER

**Comment by lmsurpre** [comment]
In all 3 cases, I believe this is an issue with the Touchstone tests.
I confirmed that the DELETE response properly honors the client Accept header, its just that these tests fail to send one.
I've written their support team to inform them.
