### ISSUE TITLE
FhirPersistenceDataAccessException on search with multiple _lastUpdated search parameters

### ISSUE THREAD

**Issue by mjdisc** [IBM/FHIR#1087]
A Condition search with multiple _lastUpdated search parameters fails with a FhirPersistenceDataAccessException .

I'm able to reproduce this on FHIR 4.1.1 and FHIR 4.2.2. 
Here is the 4.2.2 URL I used: 
https://us-south.wh-fhir.dev.cloud.ibm.com/wh-fhir-dev/api/v4/Condition?_lastUpdated=ge2018-09-01T00:00:00Z&_lastUpdated=le2020-05-01T00:00:00Z&_count=100&_tag=http://ibm.com/watson-health-wpd/pdm/data-type%7Cprimary

On a 4.1.1 system being used in PDM test, I have access to the logs and found this:
5/13/20 11:30:54:695 CDT] 00000783 com.ibm.fhir.persistence.jdbc.dao.impl.FHIRDbDAOImpl         E Failure retrieving count.
SQL=SELECT COUNT(R.RESOURCE_ID)  
FROM Condition_LOGICAL_RESOURCES LR JOIN 
	( SELECT * FROM Condition_RESOURCES IR WHERE (LAST_UPDATED <= ?)) 
	  AND ((LAST_UPDATED >= ?)) R ON R.LOGICAL_RESOURCE_ID=LR.LOGICAL_RESOURCE_ID AND R.RESOURCE_ID = LR.CURRENT_RESOURCE_ID AND R.IS_DELETED <> 'Y'  
	  JOIN (SELECT DISTINCT LOGICAL_RESOURCE_ID FROM Condition_TOKEN_VALUES  WHERE (PARAMETER_NAME_ID=162 AND ((TOKEN_VALUE = ? AND CODE_SYSTEM_ID = ?)))) 
	  Condition0 ON Condition0.LOGICAL_RESOURCE_ID = R.LOGICAL_RESOURCE_ID JOIN (SELECT DISTINCT LOGICAL_RESOURCE_ID FROM Condition_TOKEN_VALUES  WHERE 
	  (PARAMETER_NAME_ID=162 AND ((TOKEN_VALUE = ? AND CODE_SYSTEM_ID = ?)))) Condition1 ON Condition1.LOGICAL_RESOURCE_ID = R.LOGICAL_RESOURCE_ID
  searchArgs=[2020-04-30 19:00:00.999999, 2018-08-31 19:00:00.0, primary, 164, PDMTEST_PRI, 163] [probeId=c0-a8-30-57-4041ea6a-9a31-4254-9516-ec0f7860f349]
com.ibm.db2.jcc.am.SqlSyntaxErrorException: DB2 SQL Error: SQLCODE=-104, SQLSTATE=42601, SQLERRMC=(;T_UPDATED <= ?)) AND;ON, DRIVER=4.26.14

I think the second ')' in this clause is misplaced: (LAST_UPDATED <= ?))  . 

Note that if I remove one of the _lastUpdated search parameters from my queryString, the query works. fine.

**Comment by prb112** [comment]
Mark it's merged.  it'll be in 4.2.2.
