### ISSUE TITLE
Some Benchmarks no longer work without the FHIRBenchmarkRunner.property(key, value) method

### ISSUE THREAD

**Issue by JohnTimm** [IBM/FHIR#1091]
The last round of revisions to the `fhir-benchmark` module removed the use of the FHIRBenchmarkRunner.property method which sets system properties used by the benchmark itself. This broke several of the benchmarks including:

FHIRParserValidatorBenchmark
FHIRPathEvaluatorBenchmark
FHIRValidatorBenchmark

**Comment by lmsurpre** [comment]
The tests now run.  We could do work to make them more consistent, but thats lower priority and would be a separate issue.
