### ISSUE TITLE
bulkexport performance test

### ISSUE THREAD

**Issue by albertwang-ibm** [IBM/FHIR#1128]

**Comment by albertwang-ibm** [comment]
| ResourceTypes  | DB2| PostgreSQL|
| ------------- | ------------- | ------------- | 
| Patient+Careplan |  630.5/Second | 720.6/Second |
| 6 | 151.10 | |
| 8 | 185.67 | |

**Comment by lmsurpre** [comment]
there was an performance issue causing Patient and Group export to be near 10 resources/second and this shows we've improved on that a lot
