### ISSUE TITLE
Support dropping of tenants for tenant-aware dbs

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#1129]
**Is your feature request related to a problem? Please describe.**
fhir-persistence-schema supports the creation of multiple tenants within a single schema of the same db.  By placing each tenant in their own partition / tablespace, it should be possible to erase that tenant's data by detaching the partition and dropping the tablespace.
However, there are a couple additional commands we should do as well to clean up the FHIR_ADMIN tables.

fhir-persistence-schema already exposes an action called `--drop-tenant` but its not fully implemented.
Specifically, this section calls into three unimplemented methos:
```
        // Remove all the tenant-based data
        pdm.removeTenantPartitions(adapter, schemaName, tenantId);
        pdm.dropOldTenantTables();
        pdm.dropTenantTablespace();
```

**Describe the solution you'd like**
Implement the methods AND add logic to update

Also, test and document what happens when you try to reprovision a tenant with the same name as one that was previously dropped.
In at least one case, a user was trying to delete and recreate a tenant due to some unusual issue and we don't have this type of action tested/documented.

**Describe alternatives you've considered**
One alternative is to remove the half-baked `--drop-tenant` action and make tenant removal a set of manual SQL steps to execute.

**Comment by punktilious** [comment]
Drop tenant and some supporting utility functions is now implemented and merged to master. Documented [here](https://github.com/IBM/FHIR/blob/master/fhir-persistence-schema/docs/DropTenant.md).
