### ISSUE TITLE
Investigate OAuth Provider Options

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#1134]
Currently, we support OAuth 2.0 through the support from Liberty and you can enable this behavior by enabling the "oidcProvider" dropin.

However, there are many options for external providers as well and we should get some experience with at least some of these:
* KeyCloak
* IBM Cloud AppID
* OpenShift OAuth

**Comment by albertwang-ibm** [comment]
The Social Login feature (liberty 20.0.0.1+) has several pre-configured providers (e.g., Google, GitHub, and Facebook) but you can also configure additional providers (e.g. Instagram). OpenShift’s OAuth server and OAuth Proxy sidecar can now be configured as additional providers too. 
(1) liberty 20.0.0.1+ supports liberty oauth client + openshift auth server integration.
https://openliberty.io/blog/2020/01/17/openshift-oauth-server-social-login-liberty-20001.html
(2) openshift auth server support a long list of IDPs for oauth.
https://docs.openshift.com/container-platform/4.4/authentication/understanding-identity-provider.html
https://access.redhat.com/documentation/en-us/red_hat_single_sign-on/7.3/html/release_notes/red_hat_single_sign_on_7_3
(3) open liberty does have plan to support ES384/DS384.
https://github.com/OpenLiberty/open-liberty/issues/12213#issuecomment-644241175

**Comment by lmsurpre** [comment]
I looked into AppId on IBM Cloud and found the following limitation:
* AppId limits custom scopes to some combination of lowercase letters, `.`, and `-`; whereas SMART scopes include camelCase, `/`, `*`, and `_`

However, I did get Liberty to validate the tokens from AppId with the following config:
```
<server description="fhir-server">

    <!-- Enable features -->
    <featureManager>
        <!-- mpJwt-1.1 is already enabled in the default server.xml, but it doesn't hurt to repeat it here -->
        <feature>mpJwt-1.1</feature>
    </featureManager>

    <!-- Override the application-bnd binding of the main webapp -->
    <webApplication contextRoot="fhir-server/api/v4" id="fhir-server-webapp" location="fhir-server.war" name="fhir-server-webapp">
        <application-bnd>
            <security-role id="users" name="FHIRUsers">
                <group access-id="group:https://us-south.appid.cloud.ibm.com/oauth/v4/{tenantId}/{role}"/>
            </security-role>
        </application-bnd>
    </webApplication>

    <!-- The MP JWT configuration that injects the caller's JWT into a
         ResourceScoped bean for inspection. -->
    <mpJwt id="jwtConsumer"
           jwksUri="https://us-south.appid.cloud.ibm.com/oauth/v4/{tenantId}/publickeys"
           audiences="{aud}"
           userNameAttribute="sub"
           groupNameAttribute="roles"
           issuer="https://us-south.appid.cloud.ibm.com/oauth/v4/{tenantId}"
           signatureAlgorithm="RS256"
           authFilterRef="filter"/>

    <authFilter id="filter">
        <requestUrl urlPattern="/fhir-server" />
    </authFilter>
</server>
```

This worked well from Inferno except for the following error:
* Token response contained unrequested scopes: appid_default, appid_readuserattr, appid_readprofile, appid_writeuserattr, appid_authenticated

I could not find a way to prevent AppId from including these scopes.

**Comment by lmsurpre** [comment]
I also investigated RedHat SSO / KeyCloak and was able to configure this to pass the Inferno SMART app launch. Just as in AppId, I was able to track the patient id as a custom attribute for a user and map that into a custom claim on the access_token.

One thing I was not able to configure in KeyCloak (or in AppId for that matter) is the additional launch attributes suggested by SMART on the token response payload.

I did find https://igia.github.io/docs/igia-keycloak~introduction which extends KeyCloak with a custom login protocol that "implements an alternative Token endpoint that includes the additional SMART launch context parameters in the REST access token response".

However, I think it will be better to create a small microservice which fronts our authorization service, extracts the patient_id claim from the access token, and adds it to the token response. This approach should work for either KeyCloak or AppId (assuming we can workaround the limitations mentioned above for AppId).

**Comment by lmsurpre** [comment]
Other aspects when choosing an auth provider:
* the FHIR bulkdata spec requires authorization servers to be capable of validating signatures with at least one of RS384 or ES384
* the authorization server should be cost-effective, even when scaling to large numbers of users / potential users
