### ISSUE TITLE
Maven module / project layout restructuring

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#1136]
1. move server-related "spi" interfaces into a single package inside of fhir-server
* FHIROperation
* FHIRPersistence
* FHIRPersistenceInterceptor
* FHIRNotificationSubscriber

2. move fhir-operation-X projects under a directory called `ext-operations`
3. move fhir-notification-X projects under a directory called `ext-notification-adapters`
4. move fhir-ig-X projects under a directory called `ext-implementation-guides`
5. move fhir-persistence-X projects under a directory called `ext-persistence-layers`

**Comment by JohnTimm** [comment]
My personal preference is to keep them in folders with a singular noun:

`operation`
`persistence`
`notification`
`conformance`

**Comment by lmsurpre** [comment]
> My personal preference is to keep them in folders with a singular noun:
So no "ext" prefix even?

And while we're documenting our dissenting, my personal preference was to not move the persistence projects under `ext-persistence-layers`, because we only have 1.
`fhir-persistence-proxy` and `fhir-persistence-schema` are not separate persistence layers.  Maybe they should be renamed to `fhir-persistence-jdbc-proxy` and `fhir-persistence-jdbc-schema`?

**Comment by prb112** [comment]
Marking this as closed, as https://github.com/IBM/FHIR/issues/1232 addresses the yet to be considered/implemented Notification and Persistence moves.

**Comment by lmsurpre** [comment]
Thanks Paul, will leave my notes on the un-finished bits in the new issue.
