### ISSUE TITLE
Refactor naming

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#114]
"decoration names" can be updated to current working name:  IBM Server for HL7 FHIR
Product Name
WAR Name

package names
	* com.ibm.watson.health.fhir -> com.ibm.fhir
groupid
	* com.ibm.watson.health -> com.ibm.fhir
	* update sonatype?
	* ~update bintray/jcenter~
	* ~use github package registry~
	

URL namespace?
	* http://ibm.com/watson/health/fhir -> http://ibm.com/fhir

obvious impacts test code and other package name references as well

**Comment by lmsurpre** [comment]
Looks like we didn't need to rename anything in bintray/jcenter ...I think its fine that the team name is still "ibm-watson-health".

I investigated github package registry and got something working, but it doesn't support SNAPSHOTs.  We can reconsider this if we find bintray/jcenter to be problematic.

Finally, lets hold off on the Sonatype OSSRH package registration since we're not sure if thats needed to get into Maven Central or not.  It may be possible to get in directly from bintray...

**Comment by prb112** [comment]
Paul to change to "IBM FHIR Server"

**Comment by prb112** [comment]
PR https://github.com/IBM/FHIR/pull/271

**Comment by prb112** [comment]
Put in Review/QA

**Comment by prb112** [comment]
Reviewed with Lee and agreed to Close as Done
