### ISSUE TITLE
SetTenant is called more than necessary for multi-tenant schemas (DB2)

### ISSUE THREAD

**Issue by punktilious** [IBM/FHIR#1141]
**Describe the bug**
In FHIRDbDAOImpl, getConnection() calls executeRowAccessFeature() which invokes the SET_TENANT stored procedure to configure the connection (database session) for multi-tenant access. This only needs to be called once at the start of the database transaction (per real connection) but currently is executed multiple times. This is functionally safe, but slower because it involves several unnecessary round-trips to the database, which is something we try to avoid.

**To Reproduce**
Run any FHIR persistence operation.

**Expected behavior**
Minimize the number of times SET_TENANT is called. Also, consider supporting a non-tenant-based variant of the DB2 schema.

**Additional context**
Issue #1032

**Comment by lmsurpre** [comment]
We do have https://github.com/IBM/FHIR/issues/840 already for the single-tenant variant of the DB2 schema.

**Comment by prb112** [comment]
I think this one is addressed in #1144 's commit

**Comment by punktilious** [comment]
Closed by commit for #1144 .
