### ISSUE TITLE
New drop schema options don't work for Oauth and JBatch schemas

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#1167]
**Describe the bug**
For 4.2.2 we introduced `--drop-schema-fhir`, `--drop-schema-oauth`, and `--drop-schema-batch` actions on the fhir-persistence-schema cli app.
However, based on the current implementation, it seems like the `--drop-schema-oauth` and `--drop-schema-batch` options don't work.

**To Reproduce**
1. `java -jar ./fhir-persistence-schema-${VERSION}-cli.jar --prop-file db2.properties --schema-name FHIRDATA --create-schemas`
2. `java -jar ./fhir-persistence-schema-${VERSION}-cli.jar --prop-file db2.properties --drop-schema --drop-schema-oauth --drop-schema-batch --confirm-drop`

**Expected behavior**
It drops the FHIR_OAUTH and FHIR_JBATCH schemas.

**Comment by prb112** [comment]
Related to this... https://github.com/IBM/FHIR/issues/1129

**Comment by prb112** [comment]
the code underneath is not implemented, when 1129 is implemented it should resolve the above as well

**Comment by lmsurpre** [comment]
I think this one is a little different.  `dropSchema` vs `dropTenant`.  We think this one has more to do with the fact that PhysicalDataModel.drop is only dropping objects with a "SCHEMA_GROUP_TAG" tag of `FHIRDATA` or `FHIR_ADMIN`.

**Comment by holger-stenzhorn** [comment]
Just for curiosity... Is this also related to #1795?

**Comment by prb112** [comment]
PR https://github.com/IBM/FHIR/pull/2775 addresses the drop. The tags were missing.

**Comment by d0roppe** [comment]
With the latest changes to main, the fhir_jbatch and fhir_oauth schemas are cleaned out.  No tables remain in those schemas now with the --drop-schema-batch and --drop-schema-oauth.  But the actual schema is not dropped.  closing this issue. and opening a new issue for empty schemas not being dropped.
