### ISSUE TITLE
Drop schema does not remove metadata from FHIR_ADMIN.TENANTS

### ISSUE THREAD

**Issue by punktilious** [IBM/FHIR#1176]
**Describe the bug**
After running the schema admin -drop-schema --drop-schema-fhir command, there is still metadata in the FHIR_ADMIN.TENANTS table.

**To Reproduce**
Use the schema admin tool to drop a schema:

```
--prop-file fhir.properties
--schema-name NAME_OF_SCHEMA_TO_DROP
--drop-schema
--drop-schema-fhir
--confirm-drop
```

**Expected behavior**
Metadata related to the dropped schema should be removed, as if the schema was never provisioned in the first place. It should be possible to create the schema again with the same name after it has been dropped.

**Additional context**
As a workaround, always use a previously unused schema name.

Initially, this issue encompassed both FHIR_ADMIN.TENANTS and FHIR_ADMIN.VERSION_HISTORY, but the VERSION_HISTORY table is now cleaned up as per #2136

**Comment by lmsurpre** [comment]
As part of this issue, we should discuss/consider the design for having multiple schemas and/or dbs for a single tenant.  Can a single tenant be associated with multiple schemas?
If so, I'm not sure that removing tenants is the right behavior on delete-schema.

My current preference would be to find a design where tenants and schemas are mostly orthogonal/independent.  Something like this:
1. A tenant can be added/removed
2. A schema can be added/removed
3. A tenant can be allocated to a schema (creating the table partitions and tablespace)
4. A tenant can be dropped from a schema (detaching the table partitions and dropping the tablespace)

**Comment by prb112** [comment]
Team: We talked about this and decided this issue requires a design discussion.

**Comment by prb112** [comment]
QA: Robin actually added this.         `--delete-tenant-meta tenantName  deletes tenant metadata given the tenantName`
