### ISSUE TITLE
Remove CXF from the server webapp

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#1179]
Liberty already provides JAX-RS 2.1 support (using CXF) and so we really shouldn't need to package our own version.

The one thing preventing it is our use of CXF-specific classes from FHIRUrlParser in fhir-provider:
```java
import org.apache.cxf.jaxrs.impl.MetadataMap;
import org.apache.cxf.jaxrs.utils.JAXRSUtils;
```

One option is to flip it to provided, but I'm not sure about that since liberty's use of CXF is more of an internal detail.

It only seems to be used from a couple places, so hopefully it wouldn't be too difficult to stop using these CXF-specific APIs:
![image.png](https://images.zenhubusercontent.com/5d6ff0e89320850001a28a98/018cae0e-4884-4372-b0e7-624c62056089)

Note: we DO want to continue packaging a working JAX-RS client implementation with our fhir-client, so I think

**Comment by prb112** [comment]
Team discussion: There may be performance implications for it. 
If we chose not to do this, let's upgrade CXF.

**Comment by prb112** [comment]
I poked at this one a bit today. 
We could mark them provided, and not bundle and it works. 

However, there are a couple more locations that reference CXF 

```
./fhir-provider/src/main/java/com/ibm/fhir/provider/util/FHIRUrlParser.java:11:import org.apache.cxf.jaxrs.impl.MetadataMap;
./fhir-provider/src/main/java/com/ibm/fhir/provider/util/FHIRUrlParser.java:12:import org.apache.cxf.jaxrs.utils.JAXRSUtils;
./fhir-client/src/main/java/com/ibm/fhir/client/impl/FHIRClientImpl.java:37:import org.apache.cxf.feature.LoggingFeature;
./fhir-client/src/main/java/com/ibm/fhir/client/impl/FHIRClientImpl.java:782:            // true: If need, tell Apache CXF to use the Async HTTP conduit for PATCH operation as the
./fhir-client/src/main/java/com/ibm/fhir/client/FHIRClient.java:100:     * Indicates whether or not to enable to CXF Logging feature which will log all request and response messages
```

And pom.xml references

```
./fhir-server-test/pom.xml:90:            <groupId>org.apache.cxf</groupId>
./fhir-server-test/pom.xml:91:            <artifactId>cxf-rt-frontend-jaxrs</artifactId>
./fhir-provider/pom.xml:41:            <groupId>org.apache.cxf</groupId>
./fhir-provider/pom.xml:42:            <artifactId>cxf-rt-frontend-jaxrs</artifactId>
./fhir-parent/pom.xml:17:        <cxf.version>3.3.6</cxf.version>
./fhir-parent/pom.xml:145:                <groupId>org.apache.cxf</groupId>
./fhir-parent/pom.xml:146:                <artifactId>cxf-rt-rs-client</artifactId>
./fhir-parent/pom.xml:147:                <version>${cxf.version}</version>
./fhir-parent/pom.xml:150:                <groupId>org.apache.cxf</groupId>
./fhir-parent/pom.xml:151:                <artifactId>cxf-rt-frontend-jaxrs</artifactId>
./fhir-parent/pom.xml:152:                <version>${cxf.version}</version>
./fhir-parent/pom.xml:155:                <groupId>org.apache.cxf</groupId>
./fhir-parent/pom.xml:156:                <artifactId>cxf-rt-transports-http-hc</artifactId>
./fhir-parent/pom.xml:157:                <version>${cxf.version}</version>
./fhir-client/pom.xml:41:            <groupId>org.apache.cxf</groupId>
./fhir-client/pom.xml:42:            <artifactId>cxf-rt-rs-client</artifactId>
./fhir-client/pom.xml:55:            <groupId>org.apache.cxf</groupId>
./fhir-client/pom.xml:56:            <artifactId>cxf-rt-transports-http-hc</artifactId>
```

It's a hard one to cleanly change.

**Comment by lmsurpre** [comment]
The client definitely needs a JAX-RS implementation and today we use CXF...I think that one is fine.
Its probably fine to user the CXF rest client directly in fhir-server-test as well.

I think its only the `fhir-provider` thats the problem...can we remove the dependency on `org.apache.cxf.jaxrs.impl.MetadataMap` and `org.apache.cxf.jaxrs.utils.JAXRSUtils` ?

**Comment by lmsurpre** [comment]
We should be sure to measure performance after making the dependency change

**Comment by tbieste** [comment]
Need clarification on this one.
Is the requirement to just change the dependency of cxf-rt-frontend-jaxrs in fhir-provider/pom.xml to provided?
Or is it to change from using `org.apache.cxf.jaxrs.impl.MetadataMap` and `org.apache.cxf.jaxrs.utils.JAXRSUtils` to some other implementation, and completely remove the dependency?

**Comment by prb112** [comment]
> Need clarification on this one.
> Is the requirement to just change the dependency of cxf-rt-frontend-jaxrs in fhir-provider/pom.xml to provided?
> Or is it to change from using `org.apache.cxf.jaxrs.impl.MetadataMap` and `org.apache.cxf.jaxrs.utils.JAXRSUtils` to some other implementation, and completely remove the dependency?


Can you investigate removing completely from the fhir-server code  (e.g. through the provider)? 
If it needs too stay in the fhir-client, that is OK.

**Comment by tbieste** [comment]
I'll keep trying to get this clean up, but running into this from fhir-server testcases right now:

java.lang.RuntimeException: java.lang.ClassNotFoundException: org.glassfish.jersey.internal.RuntimeDelegateImpl
	at javax.ws.rs.ext.RuntimeDelegate.findDelegate(RuntimeDelegate.java:154)
	at javax.ws.rs.ext.RuntimeDelegate.getInstance(RuntimeDelegate.java:121)
	at javax.ws.rs.core.Response$ResponseBuilder.newInstance(Response.java:864)
	at javax.ws.rs.core.Response.status(Response.java:592)
	at javax.ws.rs.core.Response.status(Response.java:603)
	at javax.ws.rs.core.Response.ok(Response.java:638)
	at com.ibm.fhir.server.resources.WellKnown.smartConfig(WellKnown.java:63)

**Comment by prb112** [comment]
Confirmed it works.
