### ISSUE TITLE
TouchStone metadata capabilities test errors

### ISSUE THREAD

**Issue by albertwang-ibm** [IBM/FHIR#1180]
Validation of response body against profile 'http://hl7.org/fhir/StructureDefinition/CapabilityStatement' by FHIR specification's Validation Engine produced the following results:

-  ERROR: Search parameter names must be unique in the context of a resource. [searchParam.select(name).isDistinct()]. Location: CapabilityStatement.rest[0].resource[60] (line 8499, col 18).
-   ERROR: Search parameter names must be unique in the context of a resource. [searchParam.select(name).isDistinct()]. Location: CapabilityStatement.rest[0].resource[71] (line 10241, col 18).
-   ERROR: Search parameter names must be unique in the context of a resource. [searchParam.select(name).isDistinct()]. Location: CapabilityStatement.rest[0].resource[109] (line 15444, col 18).

**Comment by prb112** [comment]
Commit was actually merged in 4.3.0
