### ISSUE TITLE
Extend validation rules to include constraints from parent Definition 

### ISSUE THREAD

**Issue by seltsamD** [IBM/FHIR#1189]
**Is your feature request related to a problem? Please describe.**
I have two StructureDefinition for some Resource (e.g.Patient).
1. An abstract with the name "BaseStructureDefinition ".
 ` "id": "BaseStructureDefinition",
"baseDefinition": "http://hl7.org/fhir/StructureDefinition/Patient"`
2. And "ChildStructureDefinition ". 
 ` "id": "ChildStructureDefinition ",
"baseDefinition": "BaseStructureDefinition",`

For the validation, I must set both profiles if I want to validate my resource based on ChildStructureDefinition.

**Describe the solution you'd like**
Add to the validation process "inheritance" to handle validation rules also by parent Definition declared in baseDefinition property (maybe just in case custom StructureDefinition)

I also have some questions related to this theme:

1.  Is it possible to implement validation by StructureDefinition in case there is not a snapshot element, but differential?
2. May I exclude default validation rules and validate resource just by custom StructureDefinition?

**Comment by prb112** [comment]
I discussed this issue with @JohnTimm and @lmsurpre 

We currently use Snapshots not differentials.  Snapshots take into account the composition of the Child and Parent profiles.  

Please let us know how we can further help.
