### ISSUE TITLE
FHIR validation does not generate constraint for cardinality when vocabulary constraint exists on same field

### ISSUE THREAD

**Issue by michaelwschroeder** [IBM/FHIR#1194]
We've defined a Condition profile and set the minimum cardinality to 1 for the Condition.code field. In addition, we've defined an extensible binding to a value set for that same field. When generating constraints for the field, it appears the FHIR server validation generates only a vocabulary constraint in the form of Condition.code.memberOf(...). If the Condition.code field is not specified in a resource to be validated, the memberOf() function returns empty, and thus no validation issue is generated.

**Comment by JohnTimm** [comment]
When we the element is required, we generate:
```
Condition.code.memberOf(...)
```

When the element is optional, we generate:
```
Condition.code.exists() implies (Condition.code.memberOf(...))
```

The first few lines of `MemberOfFunction` look like this:
```
if (context.isEmpty()) {
    return empty();
}
```

This is what we need to generate when a cardinality constraint AND a vocabulary constraint exist on the same element:
```
Condition.code.exists() and Condition.code.memberOf(...)
```

**Comment by JohnTimm** [comment]
The workaround for this issue is to create a handwritten constraint on the element that looks something like this:
```
{
    "key": "my-condition-1",
    "severity": "error",
    "human": "The 'code' element is required",
    "expression": "Condition.code.exists()"
}
```
