### ISSUE TITLE
patch response missing OperationOutcome

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#120]
https://touchstone.aegis.net/touchstone/scriptexecution?exec=201908231432318334944596&qn=/FHIR4-0-0-Advanced/Patient/06-patch/XMLPath/fhir-api-r4-patient-patch-00-xmlpatch-missing#WAITING_OPER

Multi-leveled
* potential issue on unencoeed media type in the URL
* generally we want to configure Liberty/JAX-RS to return OperationOutcome for things we don't support
* maybe more

**Comment by albertwang-ibm** [comment]
touchstone knows that we don't support xml patch via checking capabilitystatement.
