### ISSUE TITLE
JSON Schema Clarification on required and minItems Validation Keywords

### ISSUE THREAD

**Issue by CHFJr** [IBM/FHIR#1203]
The Draft 4 version of the JSON Schema Specification (the version used with Swagger 2.0) is silent on the relationship between the "required" and "minItems" keywords. Is it possible to have a required property of type array that has a minItems value of 0, or should the minItems always be 1? In either case, can validators and generators enforce this situation?

**Comment by lmsurpre** [comment]
Yes, I agree that we should add the "minItems" key (and keep the "required" one as well) to better reflect that a 1..* field in FHIR requires both the presence of the element and at least one entry.
My only real concern on this on is whether/how "minItems" is intended to work with null.  In FHIR, it is permitted to have an array element of null (with a corresponding non-null element in the extension array for this element).
However, since we took the approach of excluding primitives, I think I'm fine to include minItems either way.

**Comment by lmsurpre** [comment]
I confirm that `minItems` now appears in the generated definitions.

For example, for swagger/OpenAPI 2.0:
```
        "OperationOutcome": {
            "allOf": [
                {
                    "$ref": "#/definitions/DomainResource"
                },
                {
                    "type": "object",
                    "properties": {
                        "issue": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/OperationOutcome_Issue",
                                "description": "An error, warning, or information message that results from a system action."
                            },
                            "minItems": 1
                        }
                    },
                    "required": [
                        "issue"
                    ]
                }
            ],
```

And for OpenAPI 3.0:
```
            "OperationOutcome": {
                "allOf": [
                    {
                        "$ref": "#/components/schemas/DomainResource"
                    },
                    {
                        "type": "object",
                        "properties": {
                            "issue": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/components/schemas/OperationOutcome_Issue",
                                    "description": "An error, warning, or information message that results from a system action."
                                },
                                "minItems": 1
                            }
                        },
                        "required": [
                            "issue"
                        ]
                    }
                ],
```

In both cases, it seems to work just fine in the swagger editor / openapi ui including with liberty
