### ISSUE TITLE
Verify XMLPatch tests are not counted against us when "CapabilityStatement" checkbox checked

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#121]
https://touchstone.aegis.net/touchstone/scriptexecution?exec=201908231432318334944596&qn=/FHIR4-0-0-Advanced/Patient/06-patch/XMLPath/fhir-api-r4-patient-patch-01-xmlpatch-add#WAITING_OPER

https://touchstone.aegis.net/touchstone/scriptexecution?exec=201908231432318334944596&qn=/FHIR4-0-0-Advanced/Patient/06-patch/XMLPath/fhir-api-r4-patient-patch-02-xmlpatch-remove#WAITING_OPER

https://touchstone.aegis.net/touchstone/scriptexecution?exec=201908231432318334944596&qn=/FHIR4-0-0-Advanced/Patient/06-patch/XMLPath/fhir-api-r4-patient-patch-03-xmlpatch-replace#WAITING_OPER

no need to implement XML Patch right now (should be separate task), but we should either:
A. update our capabilitystatement so we properly advertise or capability; or
B. open touchstone support ticket if they don't honor it

**Comment by albertwang-ibm** [comment]
we already advertised "Patch Formats 	application/json-patch+json", but touchstone failed to honor this.

**Comment by albertwang-ibm** [comment]
I had sent email to touchstone support team, waiting for answer now...

**Comment by albertwang-ibm** [comment]
Touchstone support team confirmed that the failed XML patch test cases will not be counted in the conformance report if choose "Supported in Capabstmt" option.
