### ISSUE TITLE
Add export to local file support to bulkdata export batchjob

### ISSUE THREAD

**Issue by albertwang-ibm** [IBM/FHIR#1211]
This is a sub-task of issue #1055, we want to be able to export to local file dir (which could be a mounted nfs/cos/s3 bucket etc) also, need to change the bulkdata export job to achieve this.

The job will check if COS bucket info is provided, if yes, then export to COS, otherwise export to local dir configured in fhir-server-config.json.

**Comment by prb112** [comment]
https://github.com/IBM/FHIR/issues/1055 already describes what Lee would like.

**Comment by albertwang-ibm** [comment]
minio is used by some users as bulkdata import/export source/target, so it's a better choice for us to enable in our CICD pipeline for integration test. so, we are going to support minio first.

**Comment by lmsurpre** [comment]
Export to the local filesystem seems to be working nicely.  Will leave any additional comments in #1055
