### ISSUE TITLE
reverse chaining (_has parameter)

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#1218]
**Is your feature request related to a problem? Please describe.**
 reverse chaining (_has parameter)

**Describe the solution you'd like**
This feature was introduced to FHIR Searchin STU3. Its very useful for implementing queries like "find me all the patients that have a condition with a code of xyz".

https://www.hl7.org/fhir/search.html#has

the format is like: `Patient?_has:Condition:patient:code=xyz`

**Describe alternatives you've considered**
None, standards based

**Additional context**
Original Git Issue  `reverse chaining (_has parameter) #458`

**Comment by lmsurpre** [comment]
I've deployed these changes and tested reverse chaining with the following queries like the following:
`get(base + '/Patient?gender=female' + '&' + '_has:Condition:patient:code=http://snomed.info/sct|44054006' + '&_count=1')`
