### ISSUE TITLE
Cardinality constraint not being honored in profile validation

### ISSUE THREAD

**Issue by michaelwschroeder** [IBM/FHIR#1221]
I've set the cardinality of a field (in this case Observation.component) to 0..0 in a profile, but when I validate against an Observation resource that includes that field, I do not get a validation error.
[StructureDefinition-pdm-general-observation-lab-result-quantitative-profile.txt](https://github.com/IBM/FHIR/files/4764629/StructureDefinition-pdm-general-observation-lab-result-quantitative-profile.txt)

**Comment by JohnTimm** [comment]
The cardinality constraint on `Observation.component` is being overridden by the value set constraint on `Observation.component.code` and the value set constraint on `Observation.component.referenceRange.type`. These constraints conflict with each other. The cardinality constraint `0..0` (prohibited) should take precedence.

**Comment by JohnTimm** [comment]
I added some "short-circuit" logic to the `ConstriantGenerator` so that if an element definition is prohibited, then it will generate something that looks like this:
```
component.exists().not()
```
which will take precedence over any child constraints
