### ISSUE TITLE
Multi-tenancy. Tables added to schema need to be created with all tenant partitions

### ISSUE THREAD

**Issue by punktilious** [IBM/FHIR#1222]
**Describe the bug**
If a new table is added to the schema, the multi-tenant (Db2) variant must ensure that all the tenant partitions are specified in the create table DDL.

**To Reproduce**
1. deploy initial schema to Db2
2. Add a new table to the existing physical data model.
3. update the schema in Db2
4. try to populate the new table with data for an existing tenant.

**Expected behavior**
New tables should support all existing tenants.

**Additional context**
N/A

**Comment by lmsurpre** [comment]
I agree we should have this capability, but I don't think there is anywhere we add a table during schema migration and so I'm not sure if I agree with the label.  Are there any existing issues caused by this?

**Comment by punktilious** [comment]
It's a bug in the code, even though it's not a bug in the FHIR server itself, because as you point out we do not (yet) add new tables to the schema. Perhaps we need a different tag to distinguish.

**Comment by punktilious** [comment]
Closed in #1604.
