### ISSUE TITLE
tenant-specific Resource and DomainResource search params only apply to specific types

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#1237]
**Describe the bug**
Under certain circumstances, tenant-specific extension search parameters defined for base "Resource" or "DomainResource" are not properly applied to all resource types on the server.

Update:  it turns out that the `typeToParamMap` being passed to `ParametersUtil.assignInheritedToAll(typeToParamMap)` for extension-search-parameters will only include resource types with extension-search-parameters defined.
That means that the following loop will only add these Resource/DomainResource search parameters to resource types that are explicitly listed as the "base" for at least one SearchParameter in the same extension-search-parameters bundle:
```
for (Entry<String, ParametersMap> entry : searchParameterMap.entrySet()) {
```

**To Reproduce**
1. Define a Search parameter (e.g. 'favorite-color') with a base of `["Resource"]`
2. Attempt to search a concrete type like Patient by this search parameter 

Note the response includes error text like the following:
> Search parameter 'favorite-color' for resource type 'Patient' was not found.

**Expected behavior**
A search parameter with a base of Resource should apply to all resource types.
A search parameter with a base of DomainResource should apply to all domain resource types.

**Additional context**
On the create path, we call `SearchUtil.getSearchParameters(String resourceType)`.

On the query path, we call `SearchUtil.getApplicableSearchParameters(String resourceType)`.

From what I can tell, these two methods do basically the same thing.  They both:
1. load the built-in parameters from `ParametersUtil.getBuiltInSearchParametersMap(String resourceType)`
2. filter them via `SearchUtil.filterSearchParameters()`
3. load the tenant-specific parameters via `getUserDefinedSearchParameters(String resourceType)` (which eventually calls `ParametersUtil.buildSearchParametersMapFromBundle`); and
4. add the tenant parameters to the applicable built-in ones.

This complication made the root cause of this issue harder to find; I think we should remove one of these two as part of the fix.

**Workaround**
list all resource types in the base field instead of Resource:
```
"base": ["Account",
      "ActivityDefinition",
      "AdverseEvent",
      "AllergyIntolerance",
      "Appointment",
      "AppointmentResponse",
      "AuditEvent",
      "Basic",
      "Binary",
      "BiologicallyDerivedProduct",
      "BodyStructure",
      "Bundle",
      "CapabilityStatement",
      "CarePlan",
      "CareTeam",
      "CatalogEntry",
      "ChargeItem",
      "ChargeItemDefinition",
      "Claim",
      "ClaimResponse",
      "ClinicalImpression",
      "CodeSystem",
      "Communication",
      "CommunicationRequest",
      "CompartmentDefinition",
      "Composition",
      "ConceptMap",
      "Condition",
      "Consent",
      "Contract",
      "Coverage",
      "CoverageEligibilityRequest",
      "CoverageEligibilityResponse",
      "DetectedIssue",
      "Device",
      "DeviceDefinition",
      "DeviceMetric",
      "DeviceRequest",
      "DeviceUseStatement",
      "DiagnosticReport",
      "DocumentManifest",
      "DocumentReference",
      "EffectEvidenceSynthesis",
      "Encounter",
      "Endpoint",
      "EnrollmentRequest",
      "EnrollmentResponse",
      "EpisodeOfCare",
      "EventDefinition",
      "Evidence",
      "EvidenceVariable",
      "ExampleScenario",
      "ExplanationOfBenefit",
      "FamilyMemberHistory",
      "Flag",
      "Goal",
      "GraphDefinition",
      "Group",
      "GuidanceResponse",
      "HealthcareService",
      "ImagingStudy",
      "Immunization",
      "ImmunizationEvaluation",
      "ImmunizationRecommendation",
      "ImplementationGuide",
      "InsurancePlan",
      "Invoice",
      "Library",
      "Linkage",
      "List",
      "Location",
      "Measure",
      "MeasureReport",
      "Media",
      "Medication",
      "MedicationAdministration",
      "MedicationDispense",
      "MedicationKnowledge",
      "MedicationRequest",
      "MedicationStatement",
      "MedicinalProduct",
      "MedicinalProductAuthorization",
      "MedicinalProductContraindication",
      "MedicinalProductIndication",
      "MedicinalProductIngredient",
      "MedicinalProductInteraction",
      "MedicinalProductManufactured",
      "MedicinalProductPackaged",
      "MedicinalProductPharmaceutical",
      "MedicinalProductUndesirableEffect",
      "MessageDefinition",
      "MessageHeader",
      "MolecularSequence",
      "NamingSystem",
      "NutritionOrder",
      "Observation",
      "ObservationDefinition",
      "OperationDefinition",
      "OperationOutcome",
      "Organization",
      "OrganizationAffiliation",
      "Patient",
      "PaymentNotice",
      "PaymentReconciliation",
      "Person",
      "PlanDefinition",
      "Practitioner",
      "PractitionerRole",
      "Procedure",
      "Provenance",
      "Questionnaire",
      "QuestionnaireResponse",
      "RelatedPerson",
      "RequestGroup",
      "ResearchDefinition",
      "ResearchElementDefinition",
      "ResearchStudy",
      "ResearchSubject",
      "RiskAssessment",
      "RiskEvidenceSynthesis",
      "Schedule",
      "SearchParameter",
      "ServiceRequest",
      "Slot",
      "Specimen",
      "SpecimenDefinition",
      "StructureDefinition",
      "StructureMap",
      "Subscription",
      "Substance",
      "SubstanceNucleicAcid",
      "SubstancePolymer",
      "SubstanceProtein",
      "SubstanceReferenceInformation",
      "SubstanceSourceMaterial",
      "SubstanceSpecification",
      "SupplyDelivery",
      "SupplyRequest",
      "Task",
      "TerminologyCapabilities",
      "TestReport",
      "TestScript",
      "ValueSet",
      "VerificationResult",
      "VisionPrescription"]
```

**Comment by lmsurpre** [comment]
This also relates to #264 and #713 in that our handling of system-wide search parameters like these is sloppy.  We need to decide whether search parameters defined for the type "Resource" (i.e. all resources) should get written to the Resource tables and that could affect how we choose to define them in the SearchParameters map.

For now, I think I'll just add them for all applicable resource types, so they will be in the map entries for all resource types (as well as the entries for the "Resource" and "DomainResource" keys as well).

**Comment by renom** [comment]
Do I understand it right, at the moment each resource has to be listed in the base field explicitly? So that providing just `"base" : ["DomainResource"]` wouldn't be enough to have a SearchParameter for all the resources? (as it described in [the FHIR reference page](https://www.hl7.org/fhir/searchparameter.html#srch) `If the extension's context specifies multiple resources, SearchParameter.base must be set to "DomainResource".`)
