### ISSUE TITLE
Investigate github pages templates

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#124]
Component we want on the site:
* introductory material / marketing (check internal/old site for inspiration)
* getting started with IBM FHIR Server
* overview of component?
* link to Wiki for "setting up for contributing to the IBM Server for FHIR"
* javadocs

Places for docs:
* GitHub Pages
    * /docs
    * separate branch
* Developer Guide
    * on github pages?
    * appropriate for:
    * not appropriate for:  setting up a workspace
* Wiki
    * appropriate for:  "contribute to" materials
    * not appropriate for:  end user documentation
* External sites (e.g. javadoc.io)

acceptance criteria:  present to the team our options for page templates / processes.  team must resolve on a single path.

***Downstream Action***: Create a Task to implement

**Comment by prb112** [comment]
**pending** 
- javadoc
- fixups for the site
- reconcile the site/master

**Comment by prb112** [comment]
PR https://github.com/IBM/FHIR/pull/327
