### ISSUE TITLE
Slices with 0..1 cardinality being treated as required

### ISSUE THREAD

**Issue by michaelwschroeder** [IBM/FHIR#1243]
I've defined a profile based on Observation with multiple slices defined over the component field. All slices are defined with a cardinality of 0..1. However, if any one of these slices is not specified in the resource being validated, FHIR validation returns an error like this:

"Code:[invariant];Details:[generated-pdm-general-observation-genetic-sequence-variation-profile-9: Constraint violation: component.exists() implies (component.where(code.where(coding.where(system = 'http://loinc.org' and code = '48013-7').exists()).exists() and value.as(CodeableConcept).exists() and (referenceRange.exists() implies (referenceRange.all((type.exists() implies (type.memberOf('http://hl7.org/fhir/ValueSet/referencerange-meaning', 'extensible'))))))).exists())];Expression:[Observation];Severity:[error]"

The profile is attached.
[StructureDefinition-pdm-general-observation-genetic-sequence-variation-profile.txt](https://github.com/IBM/FHIR/files/4799096/StructureDefinition-pdm-general-observation-genetic-sequence-variation-profile.txt)

**Comment by JohnTimm** [comment]
This is a systemic issue related to the treatment of slices. The form `x implies y` is used for optional slices and the slice discriminator must be used in both 'x' and 'y' parts of the expression.

**Comment by prb112** [comment]
Added to 4.3.0, and merged.
