### ISSUE TITLE
Resource validation warning message returned for optional attribute not present in the resource.

### ISSUE THREAD

**Issue by mjdisc** [IBM/FHIR#1255]
I found this issue while validating FHIR R4 resources through PDM.

I have an observation that asserts conformance to a particular profile. I have an intentional non-conformance in Observation.referenceRange.type (an invalid system in the first coding). The message returned by FHIR for that attribute is correct. But lumped in with that message is an error about 'appliesTo'. In our profile, it's an optional attribute. And it's not present in the Observation I'm testing.
Here's the profile:  
[StructureDefinition-pdm-general-observation-lab-result-ast-profile.json.txt](https://github.com/IBM/FHIR/files/4806548/StructureDefinition-pdm-general-observation-lab-result-ast-profile.json.txt)
Here's the Observation resource:
[Observation.json.txt](https://github.com/IBM/FHIR/files/4806557/Observation.json.txt)

Here's the diagnostics that are in the returned OperationOutcome Issue:
 "diagnostics": "Code:[invariant];Details:[generated-pdm-general-observation-lab-result-ast-profile-9: Constraint violation: referenceRange.exists() implies (referenceRange.all((type.exists() implies (type.memberOf('http://hl7.org/fhir/ValueSet/referencerange-meaning', 'required'))) and (appliesTo.exists() implies (appliesTo.memberOf('http://hl7.org/fhir/ValueSet/referencerange-appliesto', 'required')))))];Expression:[Observation];Severity:[error]"

I think it's confusing to include the stuff in the message about appliesTo, especially when it's not required and not included in the payload.

**Comment by prb112** [comment]
@mjdisc this may be related. https://github.com/IBM/FHIR/issues/1243 John just merged a fix for these 0..1 constraints.  I'll ask John to double check.

**Comment by prb112** [comment]
Discussed with John.  

To do so would require a major redesign, and works-as-designed.  

Thank you

Please let us know how we can further help.
