### ISSUE TITLE
support for custom resource

### ISSUE THREAD

**Issue by kesavkolla** [IBM/FHIR#1259]
How to add a custom resource to the system? I want to create a new structuredefinition to represent some custom resource and would want to get FHIR operations done on that resource.

**Comment by prb112** [comment]
If you are looking to implement your own resource type, you should first look at the [Basic](https://www.hl7.org/fhir/r4/basic.html) resource, and then you should create a Profile and post that profile to the IBM FHIR Server to constrain the behavior of the basic resource using a [Profile](https://www.hl7.org/fhir/r4/profiling.html#using). You would then use the Basic endpoint to post the resource and subsequently constrain the resource to meet your needs.

**Comment by prb112** [comment]
Per discussion with the team, this would be above and beyond what the spec supports.  Today we recommend you profile the Basic resource.
