### ISSUE TITLE
All subsection links are broken in the FHIR Server User's Guide

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#1261]
**Describe the bug**
I think our site builder used to create section links like `#21-installing-a-new server` for a section title like `2.1 Install a new server`.
Now it produces `#2.1-installing-a-new-server` and so all the links to sections with a `.` in them are broken.

**To Reproduce**
1. Go to https://ibm.github.io/FHIR/guides/FHIRServerUsersGuide
2. Try clicking a link for one of the subsections (e.g. `2.1`)

**Expected behavior**
All links work

**Additional context**
Maybe our site changed when we upgraded version of Gatsby?
I like that these links work in github (e.g. see https://github.com/IBM/FHIR/blob/master/docs/src/pages/guides/FHIRServerUsersGuide.md#21-installing-a-new-server ) and so I'd prefer to update our site builder to generate the section sublinks in the same way that github does it.

**Comment by prb112** [comment]
I'm pretty sure I know where it's coming from it gatsby-config.js (I think we can easily change)
