### ISSUE TITLE
Support conflict resolution for search parameter conflicts

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#1272]
**Is your feature request related to a problem? Please describe.**
For 4.3.0, I introduced a warning to surface search parameter conflicts (multiple parameters with the same code which are applicable to one or more of the same resource types).
For different definitions with the same code and the same expression, I log an info message.
For different definitions with the same code and a different expression, I log a warning message.

When I raised my concern about these conflicts on chat.fhir.org I was surprised by the response.
https://chat.fhir.org/#narrow/stream/179166-implementers/topic/Why.20do.20IGs.20redefine.20search.20parameters.20from.20the.20base.20spec.3F

Currently, there is no way for users to exclude the built-in search parameters other than to use a searchFilter in their fhir-server-config.  Unfortunately, because that filter config is done at the code level, it will exclude both the base spec SearchParameter AND the IG's SearchParameter.

We need to figure out how to let operators decide which search parameters we should use.

**Describe the solution you'd like**
I think we should update our searchFilter config to support filtering searchParameters by url 
instead of by code.

**Describe alternatives you've considered**
An alternative I considered is to move the base spec's SearchParameters out of the fhir-registry and move them to userlib and have the operator pick and chose which libraries to include.  That way, they could easily chose whether to include all base spec searchparameters or none of them; it would be up to the operator to package a set SearchParameters that don't conflict with one another.

**Comment by tbieste** [comment]
Verified that testcases exist and run successfully, and successfully performed a search with a search parameter in the config file (with the new config file format), while a search with a search parameter not listed for the resource type failed (as expected).
