### ISSUE TITLE
Swagger Generator RegEx Error

### ISSUE THREAD

**Issue by CHFJr** [IBM/FHIR#1277]
The Swagger Generator isn't creating the proper RegEx string for base64Binary

Within the profiles-types.json file the RegEx is
  "valueString" : "(\\s*([0-9a-zA-Z\\+/=]){4}\\s*)+"

However, the generated Swagger file is
  "pattern": "(\\s*([0-9a-zA-Z\\+\\=]){4}\\s*)+"

The problem is with the forward slash (/), for some reason it comes out as an escaped backslash (\\).

I've changed machines since generating the Swagger resources, so I'm not sure which version I ran with. I can update and test again if needed. 

Please note that this editor changes the RegEx. I'm not sure how to stop that behavior.

**Comment by CHFJr** [comment]
Here is an image of what I see that includes all the characters.
![RegEx](https://user-images.githubusercontent.com/66623272/85607389-0fe48800-b622-11ea-8cc5-363d73434c77.png)

**Comment by tbieste** [comment]
Looks like the Swagger file is using the definition from the FHIR spec for Base64, which does not include the forward slash:  https://www.hl7.org/fhir/datatypes.html#base64Binary
However, Base64 does include the forward slash, so looks like the right thing to do is update the Swagger file generator to match what is in profiles-types.json.

**Comment by lmsurpre** [comment]
https://jira.hl7.org/browse/FHIR-28139 is the corresponding issue for updating the spec

**Comment by lmsurpre** [comment]
I searched the code for instanced of the old regex and confirmed that they've all been switched over.
Unfortunately, HL7 applied the wrong regex in FHIR-28139 (at lest in my opinion) and so I opened https://jira.hl7.org/browse/FHIR-31746.
Based on the discussion there, they might go with the slightly longer (but slightly more correct) `/^(?:[A-Za-z\d+/]{4})*(?:[A-Za-z\d+/]{3}=|[A-Za-z\d+/]{2}==)?$/`

**Comment by lmsurpre** [comment]
@tbieste think we should go with this slightly longer pattern instead?

**Comment by tbieste** [comment]
I think at this point we go with what we have. If HL7 later decides to go with a new pattern, then we can change to be consistent with that. At least now it does accept all the valid characters, which it didn't before.

**Comment by lmsurpre** [comment]
works for me
