### ISSUE TITLE
Postgres connection timeout

### ISSUE THREAD

**Issue by sridhar-shivraj** [IBM/FHIR#1281]
while posting a large bundle there is connection timeout after 120 seconds.
Even after adding the socketTimeout=0 in the connectProperties , connection timeout after 120 seconds.

```
"default": {
                    "type": "postgresql",
                    "connectionProperties": {
                        "serverName": "localhost",
                        "portNumber": 5432,
                        "databaseName": "fhirdb",
                        "user": "fhiruser",
                        "password": "change-password",
                        "currentSchema": "fhirdata",
			"socketTimeout": 0
                    }
}
```

**00009bc7 com.ibm.tx.jta.embeddable.impl.EmbeddableTimeoutManager      I WTRN0006W: Transaction 00000172E5C5BE53000000012865CE9C1494C99A328B344FC9E38C285820417EA54DA49E00000172E5C5BE53000000012865CE9C1494C99A328B344FC9E38C285820417EA54DA49E00000001 has timed out after 120 seconds.**

**Comment by prb112** [comment]
HI @sridhar-shivraj 

Please provide the curl or a synthetic bundle so we can reproduce.  
Please also provide the messages.log file. 

Also in your server.xml you will need to enable tracing such that we can trace the slowdown.

Thank you

**Comment by punktilious** [comment]
Liberty provides options in server.xml for increasing the transaction timeout (default is 120s). However, we should first look at what is causing the long processing time. Longer transaction times may expose other timeouts (e.g. client connection, firewalls) that might also need to adjusted.

**Comment by sridhar-shivraj** [comment]
@prb112 here is the message.log and synthetic bundle,  the synthea bundle is 488 resources(2.06MB) this is taking more than 2 min
[message.log](https://github.com/IBM/FHIR/files/4831394/message.log)

[Concepción765_Delvalle807_b0c5ee2c-0413-4e81-9736-d5b49940132d.json.zip](https://github.com/IBM/FHIR/files/4831399/Concepcion765_Delvalle807_b0c5ee2c-0413-4e81-9736-d5b49940132d.json.zip)

**Comment by punktilious** [comment]
Use something like this ```        <logging traceSpecification="*=info:com.ibm.fhir.*=finer" traceFormat="BASIC"/>
``` to enable tracing. The output will be trace.log, not messages.log. The file gets quite large, so it's helpful if you start the server and make a single request with the bundle then stop. Don't forget to disable tracing after.

**Comment by prb112** [comment]
Thanks @sridhar-shivraj  I'm familiar with the synthetic bundles.  We have loaded the ndjson equivalents.  

As @punktilious mentioned, it's helpful to have logs, in your server.xml turning on tracing shows us the path of the processing.  More importantly, it's very helpful to have the full messages.log and trace.log.

In our testing we're averaging over 200 resources a second.  What the limited message shows us is there must be a lot of SearchParameter values extracted and being persisted in your case.

**Comment by sridhar-shivraj** [comment]
@prb112 @punktilious full messages.log and trace.log
[trace.log](https://github.com/IBM/FHIR/files/4836677/trace.log)
[messages.log](https://github.com/IBM/FHIR/files/4836678/messages.log)


> Liberty provides options in server.xml for increasing the transaction timeout (default is 120s). However, we should first look at what is causing the long processing time. Longer transaction times may expose other timeouts (e.g. client connection, firewalls) that might also need to adjusted.

when i change <transaction totalTranLifetimeTimeout="600"/> the bundle is posted succesfully but i am not getting an response back from the server 
[message (1).log](https://github.com/IBM/FHIR/files/4836734/message.1.log)

**Comment by prb112** [comment]
@sridhar-shivraj what is the response code?  

the default return preference is minimal. https://www.hl7.org/fhir/r4/http.html#ops

You have to set a header `Prefer: return=representation` or OperationOutcome

**Comment by prb112** [comment]
The reason you didn't get a response, is a broken pipe, some downstream entity closed the stream.  This is what @punktilious was warning about changing the transaction timeout

**Comment by sridhar-shivraj** [comment]
> client connection

@prb112 @punktilious  were you able to findout what is causing the long processing time from the trace.log i have sent you

**Comment by prb112** [comment]
@sridhar-shivraj we haven't had time to investigate.  We'll get to investigate some point over the next few days.

**Comment by punktilious** [comment]
@sridhar-shivraj I ran this locally on my laptop using our docker Postgres container and it doesn't get near the timeout:
```
Completed request[13.234 secs]: tenantId:[postgres1] dsId:[default] user:[fhiruser] method:[POST] uri:[https://localhost:9443/fhir-server/api/v4/] status:[200]
```

(the first request after server startup may take a little longer, until the optimizer kicks in).

Can you provide any details of how you are running this and where your database is located? Is it running on a laptop? Do you have a hard drive or SSD?

**Comment by kesavkolla** [comment]
@punktilious our PostgreSQL is also running in docker container with SSD disk. The FHIR server is also running in container in same machine.  It's a datacenter server 3.7 GH 16 core CPU, 64GB RAM.  I don't see any cpu spike or RAM outage on the server. It's beefy enough machine.

**Comment by punktilious** [comment]
Unfortunately the trace.log file rolled so it doesn't contain the full request. I can see each resource takes approximately 64ms, so for ~500 resources, that would be about 30 seconds. There is obviously some time missing from earlier in the request. To see this, we need to configure rolling in the <logging> element:
```
 <logging traceSpecification=... maxFileSize="20" maxFiles="5"/>
```

This will roll up to 5 files, each 20MB. Note that this applies to all the Liberty logging files. Make sure you have sufficient disk space.

**Comment by sridhar-shivraj** [comment]
@punktilious for each resource it is taking 640ms(0.64sec) not 64ms so to post 500 resources it is taking around 5-6 min

**Comment by punktilious** [comment]
The 64ms time I was referring to comes from this
```
Successfully inserted Resource. id=34196 executionTime=64.031297ms
```
which is the time taken in milliseconds to insert the resource into the database. It would still be helpful if you could provide the complete trace so that we can look at the end-to-end time.

**Comment by sridhar-shivraj** [comment]
[trace.log](https://github.com/IBM/FHIR/files/4879645/trace.log)
@punktilious here is the complete end-to-end trace.log of single transaction

**Comment by punktilious** [comment]
Thank you @sridhar-shivraj I will review and post an update later today.

**Comment by punktilious** [comment]
@sridhar-shivraj You mentioned that both FHIR server and database are running on the same physical machine, however I'm seeing very long times for very simple select statements, for example, one of the simplest selects we do reads from a small table. Your timings show 
```
[7/6/20 14:04:45:137 UTC] 0014b3ea PostgreSqlRes 2   DB read resource type id complete. executionTime=68.998852ms
[7/6/20 14:04:49:158 UTC] 0014b3ea PostgreSqlRes 2   DB read resource type id complete. executionTime=65.804808ms
[7/6/20 14:04:50:438 UTC] 0014b3ea PostgreSqlRes 2   DB read resource type id complete. executionTime=65.71147ms
[7/6/20 14:04:51:329 UTC] 0014b3ea PostgreSqlRes 2   DB read resource type id complete. executionTime=65.872912ms
...
```

If I compare this to a similar trace on my system under load I see:
```
[7/1/20, 16:52:52:985 EDT] 000000d7 ResourceDAOIm 1   DB read resource type id complete. executionTime=3.515413ms
[7/1/20, 16:52:53:470 EDT] 000000ba ResourceDAOIm 1   DB read resource type id complete. executionTime=3.837826ms
[7/1/20, 16:52:53:470 EDT] 00000105 ResourceDAOIm 1   DB read resource type id complete. executionTime=3.505962ms
[7/1/20, 16:52:53:907 EDT] 00000087 ResourceDAOIm 1   DB read resource type id complete. executionTime=5.506443ms
...
```

The consistency of your timings (65ms+) to me hints at some sort of latency in the network path between the FHIR server and database. Are you definitely connected to the database you are expecting to?

**Comment by prb112** [comment]
Hi @sridhar-shivraj were you able to get your issue addressed?

**Comment by sridhar-shivraj** [comment]
Hi @prb112  there was some latency issue on our side, we were able to resolve it, thank you and your team for the help resolving it

**Comment by prb112** [comment]
Excellent news. Thank you.
