### ISSUE TITLE
FHIRPath CLI

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#1283]
**Is your feature request related to a problem? Please describe.**
Currently, java project can use our fhirpath implementation by 
1. including a dependency like this:
```
<dependency>
    <groupId>com.ibm.fhir:fhir-path</groupId>
    <artifactId>fhir-path</artifactId>
    <version>4.3.0</version>
</dependency>
```
and
2. writing code like this:
```
FHIRPathEvaluator.evaluator().evaluate(resource, fhirpath);
```

This works ok, but I think would be cool to build an all-in-one shaded cli jar for our fhirpath module so that we can execute this more easily from the command line:
```sh
java -jar fhir-path-$VERSION.jar resource fhirpath
```

**Describe the solution you'd like**
Introduce a main that takes arguments for the resource content and the fhirpath string to execute.

Ideally, we could pass resource content from
* a file
* a string (raw command line arg); or
* stdin (so we can pipe to it)

One convention I've seen used is to interpret `-` as an indicator that we should read from stdin instead of a string or file, but I'm not tied to that.

Look at the `fhir-persistence-schema` and `fhir-swagger-generator` projects for examples on how to create the shaded all-in-one jar.

**Describe alternatives you've considered**
The alternative is to let clients do this themselves or use a different fhirpath engine for simple command-line stuff (e.g. the node fhirpath module).

**Additional context**

**Comment by lmsurpre** [comment]
It would also be nice to:
1. allow some way to pass jar files to extend the registry for fhirpath operations like `memberOf`; and
2. provide some way to see supplemental issues that were generated during the evaluation, maybe by printing those to System.error by default (with an option to suppress that)

**Comment by erodrago** [comment]
Would like to try out this issue @lmsurpre

**Comment by prb112** [comment]
@erodrago please go right ahead.  if you have any questions, come find us on Zulip. https://chat.fhir.org/#narrow/stream/212434-ibm

**Comment by erodrago** [comment]
Alright thanks @prb112

**Comment by prb112** [comment]
PR https://github.com/IBM/FHIR/pull/2130

**Comment by lmsurpre** [comment]
Java isn't the best for quick little cli utilities like this because the JVM is still a bit heavy to start.  I'd love to see if we could compile it to a native image using graalvm sometime...
