### ISSUE TITLE
Improve error message when extension has the wrong value type

### ISSUE THREAD

**Issue by sumanrajuk** [IBM/FHIR#1292]
**Describe the bug**

FHIR Server returns a vague error message when extension has the wrong value type

**To Reproduce**
With information about what we did:

1. define an extension with value type decimal and register it with the server; then
2. create and instance with an extension that has this url but of type string
3. invoke the server's `$validate` endpoint with this instance
Note : I am using FHIR Server 4.2.3.

**Server response includes the below error messages**

{
            "severity": "error",
            "code": "invariant",
            "details": {
                "text": "generated-communication-priority-sequence-1: Constraint violation: url = 'http://ibm.com/fhir/cdm/StructureDefinition/communication-priority-sequence'"
            },
            "expression": [
                "Communication.extension[3]"
            ]
        },
        {
            "severity": "error",
            "code": "invariant",
            "details": {
                "text": "generated-ext-1: Extension must conform to definition 'http://ibm.com/fhir/wh-engagement/StructureDefinition/communication-priority-sequence'"
            },
            "expression": [
                "Communication.extension[3]"
            ]
        },

NOTE : Expecting a more useful error message.

**Comment by lmsurpre** [comment]
I think there was something else going on here.
note how the definition url doesn't match the expected url:
`http://ibm.com/fhir/wh-engagement/StructureDefinition/communication-priority-sequence` 
`http://ibm.com/fhir/cdm/StructureDefinition/communication-priority-sequence`

We ran our own test and while the error message isn't super friendly, I think its sufficient to point a technical user in the right direction in terms of what to check:
```json
{
    "severity": "error",
    "code": "invariant",
    "details": {
        "text": "generated-us-core-ethnicity-3: Constraint violation: extension('text').where(value.as(string).exists()).exists()"
    },
    "expression": [
        "Patient.extension[0]"
    ]
}
{
    "severity": "error",
    "code": "invariant",
    "details": {
        "text": "generated-ext-1: Extension must conform to definition 'http://hl7.org/fhir/us/core/StructureDefinition/us-core-ethnicity'"
    },
    "expression": [
        "Patient.extension[0]"
    ]
}```
