### ISSUE TITLE
Remove deprecated commit() and rollback() methods from FHIRPersistenceTransaction

### ISSUE THREAD

**Issue by punktilious** [IBM/FHIR#1304]
**Describe the bug**
The FHIRPersistenceTransaction API has changed. To support backward compatibility, the commit() and rollback() methods have been kept, but are now flagged as deprecated. They should be removed in a future release. This will require consumers of the JDBC persistence component to update their transaction handling code to use the new (simplified) pattern.

This change is designed to promote greater consistency in how transactions and related errors are handled.

**Expected behavior**
FHIRPersistenceTransaction should support only begin(), end() and setRollbackOnly()

**Comment by prb112** [comment]
Feels like an easy 4.7.0 one
