### ISSUE TITLE
Remove unused constants from FHIRDbConstants

### ISSUE THREAD

**Issue by punktilious** [IBM/FHIR#1305]
**Describe the bug**
Following the connection refactor work in #1144 there are likely to be constants in FHIRDbConstants which are no longer used. These can be removed.

**Comment by prb112** [comment]
Were these already removed?

**Comment by punktilious** [comment]
Not yet.

**Comment by mohanrao** [comment]
@punktilious Can i take this to learn more about this repo ?

**Comment by punktilious** [comment]
Sure, go for it!
