### ISSUE TITLE
Carin-BB: Update Integration Tests for STU 0.4.0

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#1310]
**Is your feature request related to a problem? Please describe.**
Update Integration Tests for STU 0.0.1

**Describe the solution you'd like**
- Implement Tests for Carin-BB STU 0.4.0 (this should only be an update)
   - e.g. Query all EOBs for a patient within a date range.
   - one for each EOB type
- Update `fhir-examples` content to match the CarinBB examples/tests

CARINBlueButton_Coverage_Patient_SearchParameter | Retrieve coverages for a patient
-- | --
CARINBlueButton_ExplanationOfBenefit_Created_SearchParameter | The creation date for the EOB
CARINBlueButton_ExplanationOfBenefit_Identifier_SearchParameter | The business/claim identifier of the Explanation of Benefit
CARINBlueButton_ExplanationOfBenefit_Insurer_SearchParameter | The party responsible for the claim
CARINBlueButton_ExplanationOfBenefit_Patient_SearchParameter | The reference to the patient
CARINBlueButton_ExplanationOfBenefit_ServiceDate_SearchParameter | Date of the service for the EOB
CARINBlueButton_ExplanationOfBenefit_Type_SearchParameter | The type of the ExplanationOfBenefit

**Describe alternatives you've considered**
None

**Additional context**
http://build.fhir.org/ig/HL7/carin-bb/search.html
http://build.fhir.org/ig/HL7/carin-bb/artifacts.html#other

**Comment by lmsurpre** [comment]
moved to icebox to ensure we wait for the next revision of the IG -- they had quite a lot of issues after moving to FSH
