### ISSUE TITLE
davinci-pdex-plan-net: Create Integration Tests

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#1314]
**Is your feature request related to a problem? Please describe.**
davinci-pdex-plan-net: Create Integration Tests

**Describe the solution you'd like**
- create integration tests - https://build.fhir.org/ig/HL7/davinci-pdex-plan-net/artifacts.html#other 
- add data to fhir-examples https://build.fhir.org/ig/HL7/davinci-pdex-plan-net/searchParameters.html

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by lmsurpre** [comment]
We think our test and profile coverage is reasonable and sufficient at this point.
