### ISSUE TITLE
ConstraintGenerator does not include type check on exists clause for required vocabulary constraints that include a choice type

### ISSUE THREAD

**Issue by JohnTimm** [IBM/FHIR#1321]
Required vocabulary constraints that include a choice type are generated as follows:

`element.exists() and element.as(<type name>).memberOf('<value set>', <binding strength>')`

If `element.as(<type name>)` evaluates to the empty set `{}`, then `memberOf` also returns an empty set an the entire expression evaluates to the empty set. What should generated instead is:

`element.as(<type name>).exists() and element.as(<type name>).memberOf('<value set>', <binding strength>')`

**Comment by prb112** [comment]
Fix is reviewed and in 4.3.1
