### ISSUE TITLE
Query: Do you support running multiple versions of FHIR side-by-side on the same server ?. 

### ISSUE THREAD

**Issue by madhub** [IBM/FHIR#1328]
Do you support running multiple versions of FHIR side-by-side on the same server ?. 
Is it possible to configure FHIR server conform to particular version say, STU3 instead of latest R4

**Comment by prb112** [comment]
@madhub Currently, we only support FHIR R4 (4.0.1).  Our conformance is described at https://ibm.github.io/FHIR/Conformance/ We have no plans to support earlier versions than R4, and will revisit when R5 is released.

**Comment by prb112** [comment]
Closed as no further followup
