### ISSUE TITLE
Bulk Data Audit Logging

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#1332]
**Is your feature request related to a problem? Please describe.**
The Bulk Data code does not call the REST Audit Log, such as `RestAuditLogger.logBundle(httpServletRequest, responseBundle, startTime, new Date(), status);`

**Describe the solution you'd like**
Create an Audit Log for Start, Stop of the Bulk Data Operation (each type), and highlight the accessed data. 

**Describe alternatives you've considered**
Implement a REST Audit Logger

**Additional context**
N/A

**Comment by prb112** [comment]
In Progress

**Comment by prb112** [comment]
PR in progress... WIP while I work on other issues, https://github.com/IBM/FHIR/pull/1682

**Comment by lmsurpre** [comment]
@prb112 please comment if you don't think this is appropriate for the current sprint

**Comment by d0roppe** [comment]
Verified the bulk data export commands are logged to the Audit log.
