### ISSUE TITLE
FHIR validation generates incorrect constraint when reference is expected to be of a specific type

### ISSUE THREAD

**Issue by michaelwschroeder** [IBM/FHIR#1337]
I've defined a profile over the Procedure resource in which I expect the subject field to be a Patient reference. Here is the snapshot of the subject field:

```
      {
        "id": "Procedure.subject",
        "path": "Procedure.subject",
        "short": "Who the procedure was performed on",
        "definition": "The person, animal or group on which the procedure was performed.",
        "alias": [
          "patient"
        ],
        "min": 1,
        "max": "1",
        "base": {
          "path": "Procedure.subject",
          "min": 1,
          "max": "1"
        },
        "type": [
          {
            "code": "Reference",
            "targetProfile": [
              "http://hl7.org/fhir/StructureDefinition/Patient"
            ]
          }
        ],
        "constraint": [
          {
            "key": "ele-1",
            "severity": "error",
            "human": "All FHIR elements must have a @value or children",
            "expression": "hasValue() or (children().count() > id.count())",
            "xpath": "@value|f:*|h:div",
            "source": "http://hl7.org/fhir/StructureDefinition/Element"
          },
          {
            "key": "pdm-general-1",
            "severity": "error",
            "human": "reference is a required element",
            "expression": "reference.exists()",
            "source": "http://ibm.com/fhir/pdm/StructureDefinition/pdm-general-procedure-profile"
          }
        ],
        "mustSupport": true,
        "isModifier": false,
        "isSummary": true,
        "mapping": [
          {
            "identity": "workflow",
            "map": "Event.subject"
          },
          {
            "identity": "w5",
            "map": "FiveWs.subject[x]"
          },
          {
            "identity": "v2",
            "map": "PID-3"
          },
          {
            "identity": "rim",
            "map": ".participation[typeCode=SBJ].role"
          },
          {
            "identity": "w5",
            "map": "FiveWs.subject"
          }
        ]
      },
```

During validation, the following constraint is generated by FHIR:

```
Constraint: Constraint [id=generated-pdm-general-procedure-profile-6, level=Rule, location=(base), 
description=Constraint violation: subject.exists() and subject.resolve().is(Patient), expression=subject.exists() and 
subject.resolve().is(Patient), modelChecked=false, generated=true]
```

However, if my subject field looks like the following, that constraint evaluates to 'true':

```
            "subject" : {
               "reference" : "simplestring"
            },
```

I *think* what is happening is that the `subject.resolve()` part of the expression is returning an empty collection, and thus the `is(Patient)` is not evaluated.

This constraint seems to work:
```
"subject.exists() and subject is Patient"
```

Attached is full profile.
[StructureDefinition-pdm-general-procedure-profile.json.txt](https://github.com/IBM/FHIR/files/4939011/StructureDefinition-pdm-general-procedure-profile.json.txt)

**Comment by prb112** [comment]
The constraints are being generated in such away it uses the ResolveFunction.  The resolve function uses this REGEX - 

`((http|https)://([A-Za-z0-9\\\/\.\:\%\$\-])*)?(Account|ActivityDefinition|AdverseEvent|AllergyIntolerance|Appointment|AppointmentResponse|AuditEvent|Basic|Binary|BiologicallyDerivedProduct|BodyStructure|Bundle|CapabilityStatement|CarePlan|CareTeam|CatalogEntry|ChargeItem|ChargeItemDefinition|Claim|ClaimResponse|ClinicalImpression|CodeSystem|Communication|CommunicationRequest|CompartmentDefinition|Composition|ConceptMap|Condition|Consent|Contract|Coverage|CoverageEligibilityRequest|CoverageEligibilityResponse|DetectedIssue|Device|DeviceDefinition|DeviceMetric|DeviceRequest|DeviceUseStatement|DiagnosticReport|DocumentManifest|DocumentReference|DomainResource|EffectEvidenceSynthesis|Encounter|Endpoint|EnrollmentRequest|EnrollmentResponse|EpisodeOfCare|EventDefinition|Evidence|EvidenceVariable|ExampleScenario|ExplanationOfBenefit|FamilyMemberHistory|Flag|Goal|GraphDefinition|Group|GuidanceResponse|HealthcareService|ImagingStudy|Immunization|ImmunizationEvaluation|ImmunizationRecommendation|ImplementationGuide|InsurancePlan|Invoice|Library|Linkage|List|Location|Measure|MeasureReport|Media|Medication|MedicationAdministration|MedicationDispense|MedicationKnowledge|MedicationRequest|MedicationStatement|MedicinalProduct|MedicinalProductAuthorization|MedicinalProductContraindication|MedicinalProductIndication|MedicinalProductIngredient|MedicinalProductInteraction|MedicinalProductManufactured|MedicinalProductPackaged|MedicinalProductPharmaceutical|MedicinalProductUndesirableEffect|MessageDefinition|MessageHeader|MolecularSequence|NamingSystem|NutritionOrder|Observation|ObservationDefinition|OperationDefinition|OperationOutcome|Organization|OrganizationAffiliation|Parameters|Patient|PaymentNotice|PaymentReconciliation|Person|PlanDefinition|Practitioner|PractitionerRole|Procedure|Provenance|Questionnaire|QuestionnaireResponse|RelatedPerson|RequestGroup|ResearchDefinition|ResearchElementDefinition|ResearchStudy|ResearchSubject|Resource|RiskAssessment|RiskEvidenceSynthesis|Schedule|SearchParameter|ServiceRequest|Slot|Specimen|SpecimenDefinition|StructureDefinition|StructureMap|Subscription|Substance|SubstanceNucleicAcid|SubstancePolymer|SubstanceProtein|SubstanceReferenceInformation|SubstanceSourceMaterial|SubstanceSpecification|SupplyDelivery|SupplyRequest|Task|TerminologyCapabilities|TestReport|TestScript|ValueSet|VerificationResult|VisionPrescription)\/[A-Za-z0-9\-\.]{1,64}(\/_history\/[A-Za-z0-9\-\.]{1,64})?`

It's a selective REGEX where the only requirement is the last part `[A-Za-z0-9\-\.]{1,64}(\/_history\/[A-Za-z0-9\-\.]{1,64})?`

**Comment by prb112** [comment]
I'd recommend establishing a second constraint to enable the restriction to `Patient/`

**Comment by JohnTimm** [comment]
https://github.com/IBM/FHIR/blob/781c7ff8c679356287005906a600ad707df0f484/fhir-path/src/main/java/com/ibm/fhir/path/function/ResolveFunction.java#L52-L58

We are lenient in checking references so that we can still index `opaque` references where the type cannot be inferred. This is currently working as designed.

**Comment by JohnTimm** [comment]
@michaelwschroeder `subject.exists() and subject is Patient` is not a "workaround" as `subject is Patient` will always return `false` in this context because the type of the `subject` element is `Reference`.

**Comment by michaelwschroeder** [comment]
Thanks John and Paul for the explanation. I'm fine with closing as working as designed
