### ISSUE TITLE
Remove or refactor fhir-replication-api

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#134]
fhir-replication-api defines an API for "replication events" that can be used to broadcast create/update/delete interactions to a messaging/event engine (e.g. Kafka).
To assist with reliable delivery of messages, the server writes a fhir-replication record to the database within the managed transaction.
However, when there is nothing processing these records (i.e. no separate component deleting rows in this table like in a simple deploy), it will grow unbounded.
We should either remove this project or refactor it so that it can be disabled.
Additionally, some of the metadata fields on these tables are not appropriate for a general-purpose fhir server implementation.

**Comment by prb112** [comment]
PR https://github.com/IBM/FHIR/pull/301
