### ISSUE TITLE
Constrain Search based on SearchParameters and CapabilityStatements

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#1351]
**Is your feature request related to a problem? Please describe.**
In the FHIR Search specification, there are complicating conditions for each [SearchParameter](https://www.hl7.org/fhir/r4/searchparameter.html) where multipleOr, multipleAnd, accepted comparators and chains. 

Also, one must consider profile specific constraints which limit the usage of particular codes and combinations of codes https://build.fhir.org/ig/HL7/carin-bb/search.html

**Describe the solution you'd like**

1. Update SearchUtil.java to enforce the following restrictions of a registered (or in extension-search-parameter.json) SearchParameter:

- multipleOr
- multipleAnd
- comparator
- modifier

2. Update SearchUtil.java to enforce the following restrictions of fhir-server-config.json:

- supported searches
- supported _includes
- supported _revincludes

**Describe alternatives you've considered**
Controlling these restrictions from fhir-server-config.json.  That can be done as follow-on work to this, in another GitHub issue, to amend the search restrictions enforced by this issue.

**Additional context**
None

**Comment by kmbarton423** [comment]
Today had an Inferno search fail which was using "identifier" vs "id".  There is no enforcement of unique identifiers so in this situation, data for multiple patients was being retrieved by the search.  Search fails as unauthorized.  Not sure if there is anything programmatic that can be done here but this could be a very confusing.  Just something to consider when finalizing any interceptor behaviors.

**Comment by prb112** [comment]
> Today had an Inferno search fail which was using "identifier" vs "id". There is no enforcement of unique identifiers so in this situation, data for multiple patients was being retrieved by the search. Search fails as unauthorized. Not sure if there is anything programmatic that can be done here but this could be a very confusing. Just something to consider when finalizing any interceptor behaviors.

HI Karen, I think that's a data quality issue.  Is there anything you need Troy or I to look at with regards to data retrieval and constraining the retrieval? Thanks, Paul

**Comment by tbieste** [comment]
@prb112 
After reading through it again, trying to confirm my understanding if this is one requirement, or multiple things in one. If I'm off-base, I could use another call to talk through things about it.

> In the FHIR Search specification, there are complicating conditions for each SearchParameter where multipleOr, multipleAnd, accepted comparators and chains.
Based on the description, am I correct that the idea to have the Search interceptor (which gets registered by being put in the userlib directory?) that would read the registered search parameters and check the multipleOr, multipleAnd, accepted comparators and chains? Shouldn't that be something handled by the actual search when the SearchParameter is looked up?  Or is the idea for this to be represented in fhir-server-config.json?

> Also, one must consider profile specific constraints which limit the usage of particular codes and combinations of codes https://build.fhir.org/ig/HL7/carin-bb/search.html
For this part, we talked about adding configuration info to the fhir-server-config.json to support having a restricted list of Supported Searches, Supported _includes, and Supported _revincludes.   This configuration would be read by the Search interceptor to enforce the restricted searches.

> Develop an interceptor which controls the access to specific codes based on the functionality presented.
> The solution must be multi-tenant

**Comment by prb112** [comment]
> @prb112
> After reading through it again, trying to confirm my understanding if this is one requirement, or multiple things in one. If I'm off-base, I could use another call to talk through things about it.
> 
> > In the FHIR Search specification, there are complicating conditions for each SearchParameter where multipleOr, multipleAnd, accepted comparators and chains.
> 
> Based on the description, am I correct that the idea is to have the Search interceptor (which gets registered by being put in the userlib directory?) that would read the registered search parameters and check the multipleOr, multipleAnd, accepted comparators and chains? Shouldn't that be something handled by the actual search when the SearchParameter is looked up? Or is the idea for this to be represented in fhir-server-config.json?

I think we can hook on without a full interceptor or registered Service Loader. 

Exactly, when the SearchParameter is looked up, and backed by either the fhir-server-config.json or the CapabilityStatement to verify. 

> 
> > Also, one must consider profile specific constraints which limit the usage of particular codes and combinations of codes https://build.fhir.org/ig/HL7/carin-bb/search.html
> 
> For this part, we talked about adding configuration info to the fhir-server-config.json to support having a restricted list of Supported Searches, Supported _includes, and Supported _revincludes. This configuration would be read by the Search interceptor to enforce the restricted searches.

Right.

**Comment by tbieste** [comment]
> Exactly, when the SearchParameter is looked up, and backed by either the fhir-server-config.json or the CapabilityStatement to verify. 

What do you mean by this part?

**Comment by prb112** [comment]
>>  Shouldn't that be something handled by the actual search when the SearchParameter is looked up? Or is the idea for this to be represented in fhir-server-config.json?
>     Exactly, when the SearchParameter is looked up, and backed by either the fhir-server-config.json or the CapabilityStatement to verify.

If I understood correctly, you are suggesting at the time of looking up the SearchParameter confirming the combination of search parameters from the fhir-server-config.json or CapabilityStatement.  Which makes sense to me.

**Comment by tbieste** [comment]
> If I understood correctly, you are suggesting at the time of looking up the SearchParameter confirming the combination of search parameters from the fhir-server-config.json or CapabilityStatement. Which makes sense to me. 

Yeah, I think that sounded like a good approach.

> In the FHIR Search specification, there are complicating conditions for each SearchParameter where multipleOr, multipleAnd, accepted comparators and chains.

Is adding support to enforce the values of specifically the 4 fields of: "multipleOr", "multipleAnd", accepted "comparators" and "chains" what this part of the requirement is really saying?  I wasn't clear if this was a requirement or just related info.

**Comment by prb112** [comment]
Oh - sorry - I didn't cover this... yes - we should look at each SearchParameter too. and see if there are conditions for use for multipleOr, multipleAnd, and prefixes supported.  This is pretty detailed.

**Comment by tbieste** [comment]
ok, we should probably meet again tomorrow morning, then.  Sounds like there's more to this one.  Some parts having to do with a Search interceptor (if any), some not, etc.  We'll get it ironed out.

**Comment by prb112** [comment]
Sure - let's meet right after DSU

**Comment by tbieste** [comment]
After further discussion, instead of discovering the valid list of search parameters, includes, and revIncludes from the CapabilityStatement, they with be discovered by looking at the FHIR configuration (fhir-server-config.json).  Issue #1449 is also in need of changes to the fhir-server-config.json, so a "resources" section will be added to the fhir-server-config to support both of these issues.

Here's an example:
```
"resources": {
      "includeOmittedResourceTypes": true,
      "ExplanationOfBenefit": {
        "interactions": ["read",
        "vread",
        "history",
        "search"],
        "searchIncludes": ["ExplanationOfBenefit:patient",
        "ExplanationOfBenefit:provider",
        "ExplanationOfBenefit:care-team",
        "ExplanationOfBenefit:coverage",
        "ExplanationOfBenefit:insurer"],
        "searchRevIncludes": [],
        "searchParameters": {
          "patient": {
            "url": "http://hl7.org/fhir/us/carin-bb/SearchParameter/explanationofbenefit-patient",
            "required": true
          },
          "type": {
            "url": "http://hl7.org/fhir/us/carin-bb/SearchParameter/explanationofbenefit-type"
          },
          "identifier": {
            "url": "http://hl7.org/fhir/us/carin-bb/SearchParameter/explanationofbenefit-identifier"
          },
          "date": {
            "url": "http://hl7.org/fhir/us/carin-bb/SearchParameter/explanationofbenefit-service-date"
          },
          "reference": {
            "url": "http://hl7.org/fhir/us/carin-bb/SearchParameter/explanationofbenefit-some-ref"
          }
        }
      }
    }
```

**Comment by tbieste** [comment]
Updated fhir-server-config.json example:

{
    "__comment": "FHIR Server configuration",
    "fhirServer": {
        "resources": {
            "open": true,
			"CarePlan": {
				"searchParameterCombinations": ["patient+category+status+date",
				"patient+category+status",
				"patient+category",
				"patient+category+date"]
			},
            "ExplanationOfBenefit": {
                "interactions": [
                    "read",
                    "vread",
                    "history",
                    "search"
                ],
                "searchIncludes": [
                    "ExplanationOfBenefit:patient",
                    "ExplanationOfBenefit:provider",
                    "ExplanationOfBenefit:care-team",
                    "ExplanationOfBenefit:coverage",
                    "ExplanationOfBenefit:insurer",
                    "ExplanationOfBenefit:*"
                ],
                "searchRevIncludes": [],
                "searchParameters": {
                    "_id": "http://hl7.org/fhir/SearchParameter/Resource-id",
                    "_lastUpdated": "http://hl7.org/fhir/SearchParameter/Resource-lastUpdated",
                    "patient": "http://hl7.org/fhir/us/carin-bb/SearchParameter/explanationofbenefit-patient",
                    "type": "http://hl7.org/fhir/us/carin-bb/SearchParameter/explanationofbenefit-type",
                    "identifier": "http://hl7.org/fhir/us/carin-bb/SearchParameter/explanationofbenefit-identifier",
                    "service-date": "http://hl7.org/fhir/us/carin-bb/SearchParameter/explanationofbenefit-service-date"
                }
            },
			"Patient": {
				"searchIncludes": ["Patient:general-practitioner"],
				"searchRevIncludes": ["MedicationRequest:intended-performer"],
				"searchParameterCombinations": ["","_id","multiple-birth-count","multiple-birth-count-basic"]
			},
            "RelatedPerson": {
                "searchParameterCombinations": ["*"]
            },
			"Resource": {
				"searchIncludes": ["MedicationRequest:patient"],
				"searchRevIncludes": ["Provenance:target"],
				"searchParameterCombinations": ["","_id"]
			}
        }
    }
}
