### ISSUE TITLE
Db2 docker warning ADM4000W  A catalog cache overflow during build integration tests

### ISSUE THREAD

**Issue by punktilious** [IBM/FHIR#1356]
**Describe the bug**
During the build, we see:
```
 2020-07-23T20:15:59.587930410Z MESSAGE : ADM4000W  A catalog cache overflow condition has occurred.  There is 
db2_1          | 2020-07-23T20:15:59.587933710Z           no error but this indicates that the catalog cache has exceeded the 
db2_1          | 2020-07-23T20:15:59.587937111Z           configured maximum size.  If this condition persists, you may want to 
db2_1          | 2020-07-23T20:15:59.587940411Z           adjust the CATALOGCACHE_SZ DB configuration parameter.
```

This may be being triggered by the REOPT hint being used now for better search query performance. The Db2 containers don't have much memory, and our schema is quite large, so there might be competition for space between the catalog and package caches.

**To Reproduce**
Run an integration build

**Expected behavior**
Build should complete without this warning.

**Additional context**
Look out for this issue on larger systems to see if it is a bigger problem.

**Comment by prb112** [comment]
This warning is not new.  I do not think we should worry about it at this time.  It's a warning.

**Comment by prb112** [comment]
Reviewed as a team in a chat
