### ISSUE TITLE
Use timestamp prefix for identity strings to reduce random reads during ingestion

### ISSUE THREAD

**Issue by punktilious** [IBM/FHIR#1362]
**Is your feature request related to a problem? Please describe.**
Currently logical id values are generated as UUID strings. These are distributed at random across an index. This causes issues during ingestion (creation of new resources) when the indexes become too large to fit in memory. The random access means that physical reads are inevitable, and the proportion of physical reads increases as the index grows (unless more memory is assigned).

**Describe the solution you'd like**
By prefixing a timestamp string (e.g. millis since epoch) to the identity string, we can push the inserts to the right hand side of the b-tree, greatly reducing the number of blocks required to be accessed, and therefore improving the cache hit rate for ingestion.

**Describe alternatives you've considered**
Allocate increasing amounts of memory as the database grows.

**Additional context**
For PostgreSQL, this issue is exacerbated by "full page writes". PostgreSQL logs the entire page the first time it is modified after a checkpoint (to address potential corruption caused by split writes in the case of an OS crash). The random nature of UUID causes significant write amplification in the transaction logs.

**Comment by prb112** [comment]
Reviewed as a team in chat.
