### ISSUE TITLE
add_any_resource stored procedure, p_source_key not used 

### ISSUE THREAD

**Issue by punktilious** [IBM/FHIR#1365]
**Is your feature request related to a problem? Please describe.**
p_source_key is passed a UUID which previously was used to guarantee idempotence in replication scenarios.

**Describe the solution you'd like**
This is no longer used in the procedure, and can be removed as a parameter.

**Describe alternatives you've considered**
Leave it unchanged.

**Additional context**
Because this changes the signature of the procedure, some care is required to ensure the old procedure is removed.

**Comment by prb112** [comment]
Turned out I did this anyway in the current code, I've moved this to in progress

**Comment by lmsurpre** [comment]
I think this got split out into https://github.com/IBM/FHIR/pull/1567 ...not yet closed

**Comment by prb112** [comment]
PR waiting review
