### ISSUE TITLE
Storing references in their own parameter table may be more efficient

### ISSUE THREAD

**Issue by punktilious** [IBM/FHIR#1366]
**Is your feature request related to a problem? Please describe.**
Currently reference values e.g. "Patient/some-id-value" are stored as string parameters (e.g. observation_str_values). This leads to repeated large entries in the str_values indexes, make worse by the fact that we store both upper and lower case even though the lower case value is never used. Because these are identifiers (which are essentially random), range scanning does not make sense (e.g. WHERE value > ?).

**Describe the solution you'd like**
1. Implement a new <resourceType>_reference_values table.
2. Update JDBC persistence layer to store reference parameters into this table
3. Update search queries to use this table for chained reference joins.

The reference parameter table should look something like this:

```
CREATE TABLE observation_reference_values (
    resource_type_id.       INT     NOT NULL,
    parameter_name_id       INT     NOT NULL,
    reference_value     VARCHAR(64) NOT NULL,
    logical_resource_id  BIGINT     NOT NULL,
    CONSTRAINT pk_observation_reference_values PRIMARY KEY (resource_type_id, parameter_name_id, reference_value, logical_resource_id)
)
```

An index on logical_resource_id is also required,  plus FK constraints to the reference and logical_resources tables.

**Describe alternatives you've considered**
Do not change the current implementation.

**Additional context**
Consider how the schema and search queries may be leveraged to resolve include/revinclude queries where we may want to deliver dependencies of a resource before the resource itself rather than forcing the client to have to page through an entire result set.

**Comment by prb112** [comment]
Of interest - https://github.com/IBM/FHIR/issues/1329
