### ISSUE TITLE
Resolve absolute references to the current fhir server similar to relative ones

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#1375]
**Is your feature request related to a problem? Please describe.**
[FHIR spec](https://www.hl7.org/fhir/search.html#reference) says that for a server at example.com, the following should be treated as equivalent:

```
<patient>
  <reference value="Patient/123"/>
</patient>
```

```
<patient>
  <reference value="http://example.org/fhir/Patient/123"/>
</patient>
```

Similarly, I think the following two search expressions should be equivalent:
```
Observation?patient=Patient/123
```
```
Observation?patient=http://example.org/fhir/Patient/123
```

**Describe the solution you'd like**
On the way in, we should detect absolute references to resources on the "current host" and normalize them to relative paths.

**Describe alternatives you've considered**
An alternative is to convert everything to an absolute URI, but thats a bigger departure from our status quo.

**Additional context**
Relates to discussions wrt enforcing referential integrity between resources.

**Comment by prb112** [comment]
This may exist already in #300 please confirm and add a test for this case

**Comment by prb112** [comment]
Team discussion: sprint 19 since the work is done

**Comment by prb112** [comment]
Moving to Review/QA. 

@lmsurpre can you confirm? if not, move to Sprint 20

**Comment by lmsurpre** [comment]
Robin confirmed that with #1604 then this one will be resolved.  When the full URL matches the URL of the fhir server, we strip off the URL prefix and store just the relative reference.
