### ISSUE TITLE
Support bulk loading of resources via REST for high load testing

### ISSUE THREAD

**Issue by punktilious** [IBM/FHIR#1402]
As a performance engineer, I want to load large volumes of synthetic FHIR patient bundle data from a cloud object storage location using high concurrency via the REST API so that I can measure the performance of the system under high load conditions, and see how performance of the system evolves over time.

Read data from one or more cloud object storage buckets.

Each instance of the client loader will support multiple threads.

The client loaders can run in stateless containers

Multiple client loader instances can run simultaneously. Client loaders will coordinate their activity using a shared common service so that only one loader instance will attempt to upload a given patient bundle.

The number of threads can be configurable.

TLS options shall be configurable (to measure overheads of different cipher suites, for example).

Each active thread shall use a dedicated connection to avoid the overhead of TLS connection setup.

Performance summary information shall be written to log files and may be also written to a database or message queue for further analysis.

The client loaders shall be configurable to enable validation-only mode, using only the `$validate` endpoint which involves no database activity inside the FHIR server.

The client loader is not intended to emulate user access patterns. Its focus is stressing the REST API for data ingestion.

**Comment by prb112** [comment]
Merged
