### ISSUE TITLE
Establish process/procedure for rebuilding old images

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#1412]
Currently, we build and push our Docker image to DockerHub as part of our release process.

This works, but ends up leaving vulnerable images because the underlying layers get patched but we never re-build our images on top of them.

What we *should* be doing is rebuilding the images at some interval so that our image is always up-to-date at the lower levels (OS, Java, Liberty, etc), probably via either [autobuilds](https://docs.docker.com/docker-hub/builds/) or [GitHub Actions scheduled events](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events)

As a forcing function, Docker recently changed their terms of service and will start deleting stale images that haven't been rebuilt in the last 6 months.

**Comment by prb112** [comment]
Team to setup a side discussion on how to approach

**Comment by prb112** [comment]
Proposal
- Rebuild on a Schedule 
- All Tags

Go from there.

**Comment by lmsurpre** [comment]
now that it only rebuilds the latest (4.11.0), we finally have an automated image rebuild!

first success: https://github.com/IBM/FHIR/actions/runs/2200236782

**Comment by d0roppe** [comment]
This seems to be building correctly now. Closing issue.
