### ISSUE TITLE
chained search with modifier :missing causes internal error

### ISSUE THREAD

**Issue by kmbarton423** [IBM/FHIR#1413]
Working on cloud tenant running IBM FHIR server 4.3.2

Issued via Postman
GET {{base}}{{contextRoot}}Observation?subject:Patient.gender:missing=true

Response (500 Internal Server Error):
{
    "resourceType": "OperationOutcome",
    "id": "ac-1e-f9-a6-e634f01e-1476-4690-8c08-a53d18328c50",
    "issue": [
        {
            "severity": "fatal",
            "code": "exception",
            "details": {
                "text": "FHIRPersistenceDataAccessException: Server error: failure retrieving count"
            }
        }
    ]
}

Expected successful search attempt.

Info from LogDNA provided.
[2020Aug14LogDNA.txt](https://github.com/IBM/FHIR/files/5074955/2020Aug14LogDNA.txt)

**Comment by lmsurpre** [comment]
Got around to searching this one and it turns out we already had an issue for it:  #473
That said, I think we should turn that one into the "feature request" for supporting this properly and keep this one (#1413) to fix the error message...specifically, we should return a good message that indicates that we don't support modifiers on chained parameters.

**Comment by kmbarton423** [comment]
Verified the following behavior on cloud tenant:
    "version": "4.4.0",
    "name": "IBM FHIR Server",
    "status": "active",
    "date": "2020-08-24T18:02:12.529Z",
    "publisher": "IBM Corporation",
    "description": "IBM FHIR Server version 4.4.0 build id development"

GET {{base}}{{contextRoot}}Observation?subject:Patient.gender:missing=true

Returned status ->  400 Bad Request
{
    "resourceType": "OperationOutcome",
    "id": "ac-1e-ce-12-85028320-9037-4d8f-b945-20fb16e318e0",
    "issue": [
        {
            "severity": "fatal",
            "code": "not-supported",
            "_code": {
                "extension": [
                    {
                        "url": "http://ibm.com/fhir/extension/not-supported-detail",
                        "valueCode": "interaction"
                    }
                ]
            },
            "details": {
                "text": "Modifier 'missing' is not yet supported for chained parameters [code=subject]"
            }
        }
    ]
}
