### ISSUE TITLE
Investigate legal/licensing relating to use of ucum-essence.xml file in UCUM validation/formatting/convert functionality

### ISSUE THREAD

**Issue by michaelwschroeder** [IBM/FHIR#1418]
We need to determine requirements for using ucum-essence.xml file, either directly or as a source of derivative work, in UCUM code processing, including validation, formatting, and conversion.

**Comment by JohnTimm** [comment]
https://unitsofmeasure.org/trac/wiki/TermsOfUse

**Comment by JohnTimm** [comment]
My initial thoughts are that we need to a) download the text version of the UCUM license and add it to the ucum-essence.xml file itself (as an XML comment) and b) get it reviewed by legal

https://unitsofmeasure.org/trac/wiki/TermsOfUse?format=txt

**Comment by michaelwschroeder** [comment]
Use of the ucum-essence.xml file was approved by Noah Sharkan in IP law on 10/07/2020, given the following conditions are met:

> I reviewed the terms (https://ucum.org/trac/wiki/TermsOfUse) in view of your described use. While you are incorporating UCUM content into a software program, the software will include the UCUM code, definition value and unit fields in their entirety, right? (This is a requirement of section 7).  Assuming this is the case, then I don't see an issue with using the xml file as proposed and including it in the OSS project, so long as you comply with the requirements discussed below and you don't think you have an issue complying with any other terms of the UCUM license. 
>  
> Per Section 6 of the UCUM license, you'll need to include a copy of the Copyright Notice and License (you can download a plaintext copy at the link above, bottom of the page) within the same folder of the OSS project that includes the xml file. Including the copy in the same folder as the xml file is done so that the copy is accessible "on the same Internet page from which the [UCUM xml file] is available for download".
>  
> Per Section 7, you'll need to include the exact notice specified in section 7 on the OSS project page such that the notice is "accessible on the same Internet page from which the product is available for download".
