### ISSUE TITLE
Honor CodeSystem.caseSensitive during validation

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#1454]
**Is your feature request related to a problem? Please describe.**
One of the PDEX PlanNet examples includes a code that has casing which does not match the Display value in the Codesystem.
Currently, our validator considers this an error.

The `$validate-code` operation (both ValueSet and CodeSystem variants) says this on the subject:
> Whether displays are case sensitive is code system dependent

When I look at the CodeSystem resource, I see CodeSystem.caseSensitive but the description makes it sound like its just for the codes and not for the display values:  https://www.hl7.org/fhir/codesystem-definitions.html#CodeSystem.caseSensitive

Assuming this should apply to the display value too, then I think we should follow their recommendation on this:
> If this value is missing, then it is not specified whether a code system is case sensitive or not. When the rule is not known, Postel's law should be followed: produce codes with the correct case, and accept codes in any case.

**Describe the solution you'd like**
1. When CodeSystem.caseSensitive is populated, we should honor it when we validate both the codes and their display values
2. When CodeSystem.caseSensitive is NOT populated, we should follow the guidance in the specification and perform a case-insensitive match

Optionally, in case number 2, we could chose to emit a warning (or not).

**Describe alternatives you've considered**
We could ignore this guidance and chose to be more rigorous, but being more strict that the other validators makes me nervous.

**Additional context**
One complicating factor is that this caseSensitive field is on the CodeSystem (and not the ValueSet).  This could be very bad for us since we lean more heavily on ValueSet checks.  We may want to cache this value somewhere (maybe as part of the existing code system cache we have) so that we don't need to read the CodeSystem resource to do validation.

**Comment by JohnTimm** [comment]
I don't think this will be too much of an issue for us in terms of determining case sensitivity and the implications for performance. I think this will likely be isolated to `DefaultTermServiceProvider` which is where the value set cache is built up. I think we would have a change in two spots: 1. normalize the case when building the value set cache (if the code system is case insensitive) and 2. normalize the case of the code we are checking (if the code system is case insensitive). We also want to handle this when doing a Lookup operation.
