### ISSUE TITLE
Improve CapabilityStatement to support Security

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#1480]
**Is your feature request related to a problem? Please describe.**
CapabilityStatement enables a Security feature which some clients are looking at to determine the authentication protocol and CORS support to use. Refer to https://www.hl7.org/fhir/CapabilityStatement.html

[Scenario 0: Demonstrate support authentication and authorization](https://confluence.hl7.org/pages/viewpage.action?pageId=91983711)
- Read Server's capability statement to decide if server requires authentication
- If server requires authentication
- Follow SMART App Launch IG to start client

**Describe the solution you'd like**
- Implements https://www.hl7.org/fhir/capabilitystatement-definitions.html#CapabilityStatement.rest.security
- Changes based on what is enabled on the server using fhir-config?

**Describe alternatives you've considered**
None

**Additional context**
Identified as part of a connectathon.

**Comment by lmsurpre** [comment]
we already populate CapabilityStatement.rest.security with the OAuth endpoints that are configured in our fhir-server-config.  For example, here is a snippet from our CapabilityStatement for the upcoming connectathon:
```json
"rest": [
        {
            "mode": "server",
            "security": {
                "extension": [
                    {
                        "extension": [
                            {
                                "url": "token",
                                "valueUrl": "https://cluster1-573846-250babbbe4c3000e15508cd07c1d282b-0000.us-east.containers.appdomain.cloud/auth/realms/master/protocol/openid-connect/token"
                            },
                            {
                                "url": "authorize",
                                "valueUrl": "https://cluster1-573846-250babbbe4c3000e15508cd07c1d282b-0000.us-east.containers.appdomain.cloud/auth/realms/master/protocol/openid-connect/auth"
                            },
                            {
                                "url": "register",
                                "valueUrl": "https://cluster1-573846-250babbbe4c3000e15508cd07c1d282b-0000.us-east.containers.appdomain.cloud/auth/realms/master/clients-registrations/openid-connect"
                            }
                        ],
                        "url": "http://fhir-registry.smarthealthit.org/StructureDefinition/oauth-uris"
                    }
                ],
                "service": [
                    {
                        "coding": [
                            {
                                "system": "http://terminology.hl7.org/CodeSystem/restful-security-service",
                                "code": "SMART-on-FHIR"
                            }
                        ],
                        "text": "OAuth2 using SMART-on-FHIR profile (see http://docs.smarthealthit.org)"
                    }
                ]
            },
```

That said, I think we always include this in our CapabilityStatement (irregardless of how the underlying liberty server is configured) and so I do agree that it would be better to let the server config drive this section of the CapabilityStatement.

**Comment by lmsurpre** [comment]
Here's what I'm thinking for this one:  

1. combine our existing "oauth" and "authFilter" fhir-server-config property groups into a single new group called "security".

2. introduce new properties like:
* fhirServer/security/enabled (default=true)
* fhirServer/security/service (default=Basic, allowed values from https://www.hl7.org/fhir/valueset-restful-security-service.html

3. only serve up the Oauth extensions in the CapabilityStatement when fhirServer/security/service is set to `OAuth` or `SMART-on-FHIR`

4. only serve up the `.well-known/smart-capabilities` endpoint when fhirServer/security/service is set to `SMART-on-FHIR`

@prb112 @JohnTimm thoughts?

**Comment by lmsurpre** [comment]
OK, I implemented something close to this in https://github.com/IBM/FHIR/pull/1526

**Comment by prb112** [comment]
Looks great
