### ISSUE TITLE
Add Bundle.entry.search to Search Response

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#1494]
**Is your feature request related to a problem? Please describe.**
Add Bundle.entry.search mode and score to Search Response
![image](https://user-images.githubusercontent.com/3016328/92753717-26b09600-f358-11ea-9f34-5ca7676c804a.png)

**Describe the solution you'd like**
1 - Downstream consumers need to know the state of the Search.

**Describe alternatives you've considered**
N/A

**Additional context**
Link to Spec - https://www.hl7.org/fhir/bundle.html and https://www.hl7.org/fhir/bundle-definitions.html

**Comment by prb112** [comment]
PR 1503 identified an issue with Reflexsive references. 
The difficulty in including match versus outcome is hard to differentiate as we only return resources. 
To best differentiate, we may need to return back from the persistence layer the indications of INCLUDE or MATCH. 

Tests that must be done: 
1 - Search on Patient: _include=Observation:derived-from or _include=Patient:link on the Patient Resource
and show that the include is properly marks the resources included. 
2 - Test with only match of a single resource
3 - Test with match + include of different resources
```
I suspect a change has to be made at the persistence layer to do this efficiently.

**Comment by michaelwschroeder** [comment]
A potential solution is to replace the count query on include searches with a query that returns resource IDs. Those results could then be used to determine the set of MATCH resources vs. INCLUDE resources.

**Comment by d0roppe** [comment]
stretch goal for sprint 21

**Comment by michaelwschroeder** [comment]
I believe by adding a derived SORT_ORDER column to the search query to enable sorting of the MATCH resources before the INCLUDE resources will allow us, in combination with the `pageSize` and `totalCount` values in the searchContext, to determine which returned resources are MATCH vs. INCLUDE, regardless of resource type. For example, if we know all MATCH resources come first in the result set, then we can determine the number of MATCH resources based on `pageSize` and `totalCount`. If `totalCount` > `pageSize`, then the first `pageSize` resources in the result set are MATCH. If `pageSize` > `totalCount`, then the first `totalCount` resources in the result set are MATCH. Remaining resources in the result set are INCLUDE.

Here's an _include query:

```
SELECT
   RESOURCE_ID,
   LOGICAL_RESOURCE_ID,
   VERSION_ID,
   LAST_UPDATED,
   IS_DELETED,
   DATA,
   LOGICAL_ID 
FROM
   (
      SELECT
         RESOURCE_ID,
         LOGICAL_RESOURCE_ID,
         VERSION_ID,
         LAST_UPDATED,
         IS_DELETED,
         DATA,
         LOGICAL_ID 
      FROM
         (
            SELECT
               R.RESOURCE_ID,
               R.LOGICAL_RESOURCE_ID,
               R.VERSION_ID,
               R.LAST_UPDATED,
               R.IS_DELETED,
               R.DATA,
               LR.LOGICAL_ID 
            FROM
               (
                  SELECT
                     LOGICAL_ID,
                     LOGICAL_RESOURCE_ID,
                     CURRENT_RESOURCE_ID 
                  FROM
                     Patient_LOGICAL_RESOURCES ILR 
                  WHERE
                     ILR.LOGICAL_ID IN 
                     (
                        ? 
                     )
               )
               LR 
               JOIN
                  Patient_RESOURCES R 
                  ON R.RESOURCE_ID = LR.CURRENT_RESOURCE_ID 
                  AND R.IS_DELETED = 'N' 
            ORDER BY
               R.LOGICAL_RESOURCE_ID ASC OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY
         )
         RESULT 
      UNION ALL
      SELECT
         R.RESOURCE_ID,
         R.LOGICAL_RESOURCE_ID,
         R.VERSION_ID,
         R.LAST_UPDATED,
         R.IS_DELETED,
         R.DATA,
         LR.LOGICAL_ID 
      FROM
         Organization_RESOURCES R 
         JOIN
            Organization_LOGICAL_RESOURCES LR 
            ON R.LOGICAL_RESOURCE_ID = LR.LOGICAL_RESOURCE_ID 
            AND R.RESOURCE_ID = LR.CURRENT_RESOURCE_ID 
      WHERE
         R.IS_DELETED = 'N' 
         AND R.RESOURCE_ID = LR.CURRENT_RESOURCE_ID 
         AND 
         (
            LR.LOGICAL_ID IN 
            (
               '17575e1056a-28decf48-9dac-45de-95e8-5e0d433b76c0'
            )
         )
   )
   COMBINED_RESULTS
```

If we add SORT_ORDER columns (`1 AS SORT_ORDER` for the target resource sub-query and `2 AS SORT_ORDER` for the include sub-query) and an `ORDER BY SORT_ORDER` to the combined results, the MATCH resources will be returned first in the result set:

```
SELECT
   RESOURCE_ID,
   LOGICAL_RESOURCE_ID,
   VERSION_ID,
   LAST_UPDATED,
   IS_DELETED,
   DATA,
   LOGICAL_ID
FROM
   (
      SELECT
         RESOURCE_ID,
         LOGICAL_RESOURCE_ID,
         VERSION_ID,
         LAST_UPDATED,
         IS_DELETED,
         DATA,
         LOGICAL_ID,
         1 AS SORT_ORDER 
      FROM
         (
            SELECT
               R.RESOURCE_ID,
               R.LOGICAL_RESOURCE_ID,
               R.VERSION_ID,
               R.LAST_UPDATED,
               R.IS_DELETED,
               R.DATA,
               LR.LOGICAL_ID 
            FROM
               (
                  SELECT
                     LOGICAL_ID,
                     LOGICAL_RESOURCE_ID,
                     CURRENT_RESOURCE_ID 
                  FROM
                     Patient_LOGICAL_RESOURCES ILR 
                  WHERE
                     ILR.LOGICAL_ID IN 
                     (
                        ? 
                     )
               )
               LR 
               JOIN
                  Patient_RESOURCES R 
                  ON R.RESOURCE_ID = LR.CURRENT_RESOURCE_ID 
                  AND R.IS_DELETED = 'N' 
            ORDER BY
               R.LOGICAL_RESOURCE_ID ASC OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY
         )
         RESULT 
      UNION ALL
      SELECT
         R.RESOURCE_ID,
         R.LOGICAL_RESOURCE_ID,
         R.VERSION_ID,
         R.LAST_UPDATED,
         R.IS_DELETED,
         R.DATA,
         LR.LOGICAL_ID,
         2 AS SORT_ORDER
      FROM
         Organization_RESOURCES R 
         JOIN
            Organization_LOGICAL_RESOURCES LR 
            ON R.LOGICAL_RESOURCE_ID = LR.LOGICAL_RESOURCE_ID 
            AND R.RESOURCE_ID = LR.CURRENT_RESOURCE_ID 
      WHERE
         R.IS_DELETED = 'N' 
         AND R.RESOURCE_ID = LR.CURRENT_RESOURCE_ID 
         AND 
         (
            LR.LOGICAL_ID IN 
            (
               '17575e1056a-28decf48-9dac-45de-95e8-5e0d433b76c0'
            )
         )
   )
   COMBINED_RESULTS
   ORDER BY SORT_ORDER
```

**Comment by michaelwschroeder** [comment]
As part of this work item, we will limit the number of included resources returned to 1000 (current maximum page size). If more than 1000 included resources are returned by the query, the request will fail with a 400 code and appropriate message. In the future, the plan is to allow both the max page size and the max number of included resources returned to be configurable via configuration properties (https://github.com/IBM/FHIR/issues/1868)

**Comment by d0roppe** [comment]
Tested and verified that included resources on a search are marked as
            "search": {
                "mode": "include",
                "score": 1
            }
           
and resources that match the search are marked as:
            "search": {
                "mode": "match",
                "score": 1
            }

And if the total number of included resources exceed 1000 for the current page you get this error:
            "severity": "error",
            "code": "business-rule",
            "details": {
                "text": "Number of returned 'include' resources exceeds allowable limit of 1000"
            }
