### ISSUE TITLE
Create performance measurements for CMS Payer Interop scenarios

### ISSUE THREAD

**Issue by punktilious** [IBM/FHIR#1508]
**Is your feature request related to a problem? Please describe.**
Create access/search queries which can be executed at scale to drive read load into the FHIR server.

**Describe the solution you'd like**
Use random patient ids from the resource bundles loaded by fhir-bucket to drive CMS Payer Interop search/access scenarios.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by d0roppe** [comment]
Local Random Patient selection has now been implemented in JMeter test plan.

**Comment by d0roppe** [comment]
Have added Random patient selector to the JMeter test form a CSV file I can download from the db console.  This seems to work well and quick for getting random patients as requested by this issue.

**Comment by d0roppe** [comment]
JMeter test for this now in master branch.  should this task be closed?  @lmsurpre
