### ISSUE TITLE
Create new project fhir-meter to host performance artifacts 

### ISSUE THREAD

**Issue by punktilious** [IBM/FHIR#1509]
Create a new top level folder "performance" and move fhir-bucket into it to avoid cluttering the top level.

Create a new project fhir-meter to host artifacts related to performance measurement. Also locate this project in the performance folder.

**Comment by prb112** [comment]
PR 1573

**Comment by d0roppe** [comment]
New performance/fhir-meter created and added test related to #1508

**Comment by prb112** [comment]
I am considering this completed https://github.com/IBM/FHIR/tree/master/performance/fhir-meter 

moving to Review q/a

**Comment by lmsurpre** [comment]
> Create a new top level folder "performance" and move fhir-bucket into it to avoid cluttering the top level.

this piece will come later.
