### ISSUE TITLE
Manage Build and Images for Profiles and Profiles modules

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#1511]
**Is your feature request related to a problem? Please describe.**
Manage Build and Images for Profiles and Profiles modules

By default, the build includes every module related to the Profiles. The modules include mcode, patient access, and provider IGs.

**Describe the solution you'd like**
Remove the igs from the main package, 
Build an image without the jars included. 
Add automation to add the jars in for testing purposes

**Describe alternatives you've considered**
include all igs, but it increases the total size

**Additional context**
n/a

**Comment by tbieste** [comment]
@prb112 I'm ready to start on this.  Can you walk me through the details a bit more of how you'd like to see this done?

**Comment by prb112** [comment]
sure - let. me give you a tour tomorrow of what I was thinking.

**Comment by prb112** [comment]
Please rebase when https://github.com/IBM/FHIR/pull/1489 is merged

**Comment by prb112** [comment]
Works great - good tests, and now we're testing all Profiles
