### ISSUE TITLE
_elements option should not be applied to the _include option on a search.

### ISSUE THREAD

**Issue by d0roppe** [IBM/FHIR#1516]
**Describe the bug**
When issuing a search and specifying the _elements option to include specific elements only, it should not be applied to the resources returned due to the _include option.  https://www.hl7.org/fhir/search.html#elements
Currently it is applied to all returned resources. 

**To Reproduce**
Run a query with _elements=identifier&_include=<resource>:*

**Expected behavior**

**Additional context**

**Comment by prb112** [comment]
#1494 should be tackled at the same time.

**Comment by d0roppe** [comment]
stretch goal for sprint 21

**Comment by d0roppe** [comment]
Verified that with this fix, the _elements is not applied to the included resources.
