### ISSUE TITLE
Support for variables in JSON configuration files like 'fhir-server-config.json'

### ISSUE THREAD

**Issue by holger-stenzhorn** [IBM/FHIR#1517]
**Is your feature request related to a problem? Please describe.**
Currently variables are supported in XML configuration files such as `server.xml` or `oauthResourceServer.xml` only.

**Describe the solution you'd like**
It would be great if variables could be supported in JSON configuration files like `fhir-server-config.json` as well to be able to define them in a central place and (re)use them in both XML and JSON configuration files.

As an example you can find an excerpt from `fhir-server-config.json` with variables used in a datasource definition:
```
"datasources": {
    "default": {
        "type": "postgresql",
        "connectionProperties": {
            "serverName": "${postgres_hostname}",
            "portNumber": "${postgres_portnumber}",
            "databaseName": "${postgres_database_name}",
            "user": "${postgres_username}",
            "password": "${postgres_password}",
            "currentSchema": "${postgres_database_schema}"
          }
    }
}
```

**Describe alternatives you've considered**
Currently all property values need to be hard-coded in JSON configuration files (resulting in duplicate efforts and chances to introduce errors). A very hacky (and wacky) workaround to this is to employ variables in the JSON files anyway and replace them "on-the-fly" with `sed`. 

**Additional context**
n/a

**Comment by lmsurpre** [comment]
I've always wanted this too.  We've used the described workaround to get by in various deploys.
Another approach we've used with our kubernetes deployments is to mount a persistent store (e.g. via https://cloud.ibm.com/docs/containers?topic=containers-object_storage) at fhir-server/config and keep the tenant configs in there.

In terms of implementing this one, I don't think it would be so bad.
My thought was to support resolving these values from environment variables via some simplistic usage of the [Apache Commons StringSubstitutor](https://commons.apache.org/proper/commons-text/javadocs/api-release/org/apache/commons/text/StringSubstitutor.html).
The liberty "server.xml" config file is more flexible than this, but I don't think that we need full parity with that.

**Comment by holger-stenzhorn** [comment]
> In terms of implementing this one, I don't think it would be so bad.

Yes, you are right: I checked the code and if you want to keep the change simple then only in the class `ConfigurationService` the method `public static PropertyGroup loadConfiguration(InputStream is)` needs to be changed.

> My thought was to support resolving these values from environment variables via some simplistic usage of the Apache Commons StringSubstitutor.

So if this "simplistic" approach is acceptable then basically all you would need to add/change in `ConfigurationService` is:
```java
import org.apache.commons.io.IOUtils;
import org.apache.commons.text.StringSubstitutor;

import java.io.StringReader;
import java.nio.charset.StandardCharsets;
```
```java
public static PropertyGroup loadConfiguration(InputStream is) throws Exception {
    String templatedJson = IOUtils.toString(is, StandardCharsets.UTF_8);
    String resolvedJson = StringSubstitutor.replace(templatedJson, System.getenv());
    try (JsonReader reader = JSON_READER_FACTORY.createReader(new StringReader(resolvedJson))) {
        JsonObject jsonObj = reader.readObject();
        reader.close();
        return instantiatePropertyGroup(jsonObj);
    }
}
```
...and add the dependencies to the `pom.xml`:
```xml
<dependency>
    <groupId>commons-io</groupId>
    <artifactId>commons-io</artifactId>
    <version>2.8.0</version>
</dependency>
<dependency>
    <groupId>org.apache.commons</groupId>
    <artifactId>commons-text</artifactId>
    <version>1.9</version>
</dependency>
```

**Comment by JohnTimm** [comment]
@holger-stenzhorn Please open a pull request with your proposed solution along with some unit tests.
