### ISSUE TITLE
modifier 'NOT' is not supported for search parameter 'code' of type TOKEN

### ISSUE THREAD

**Issue by gk-zhang** [IBM/FHIR#1521]
**Describe the bug**
According to Fhir Restful API specification of search function on type "token" (https://www.hl7.org/fhir/search.html#token), Modifier ":not" can be used to do a reverse matching of a code. 
However, ibm fhir server doesn't seem to have this implemented. It returned "Found unsupported modifier 'NOT' for search parameter 'code' of type TOKEN" if a query such as: "GET [base]/Patient?gender:not=male" was given.

**To Reproduce**
1. Assume the fhirserver can be accessed through: https://localhost:9443/fhir-server/api/v4  

2. Use curl to query the Patients who are not male, i.e.:
>curl -k -u fhiruser:change-password 'https://localhost:9443/fhir-server/api/v4/Patient?gender:not=male'

3. It returned:
{
  "resourceType": "OperationOutcome",
  "id": "7f-0-1-1-9a6ba086-44a8-4dd5-a7a8-0020d0ccb03c",
  "issue": [
    {
      "severity": "fatal",
      "code": "processing",
      "details": {
        "text": "FHIRPersistenceException: Found unsupported modifier 'NOT' for search parameter 'gender' of type TOKEN"
      }
    }
  ]
}

**Expected behavior**
Modifier ":not" is expected to be used for reverse matching for type "token". A query such as "GET [base]/Patient?gender:not=male" is expected to return all the Patients who are not male.

**Comment by lmsurpre** [comment]
https://ibm.github.io/FHIR/Conformance#search-modifiers covers which search modifiers are currently supported, but I do agree this would be a good one to support.  Thanks for the write-up.

**Comment by gk-zhang** [comment]
Thanks a lot for the quick reply! I have just opened a feature request issue: https://github.com/IBM/FHIR/issues/1522

**Comment by lmsurpre** [comment]
Thanks @gk-zhang.  I think we could have just treated this issue as the enhancement request, but the new one looks good too.  Lets close this one in favor of #1522.
