### ISSUE TITLE
Support PATCH as part of a bundled request (batch and transaction)

### ISSUE THREAD

**Issue by kathipavan** [IBM/FHIR#1525]
Hi Team,
Could you please enhance FHIR server to support patch as part of a bundled request (batch and transaction).

Thank you,
Pavan.

**Comment by lmsurpre** [comment]
Specifically, I think its `FHIRRestHelper.processEntriesForMethod` that will need to be updated to support PATCH.
Outside of batch/transaction, we support JSON Patch and FHIRPath Patch (not XML Patch).  JSON Patch could maybe be supported through passing of Binary resources within the bundle, but honestly I’d probably just focus on FHIRPath Patch instead (assuming it meets the needs of your project).

**Comment by kathipavan** [comment]
The feature is working fine in dev environment
