### ISSUE TITLE
Refactor fhir-term module

### ISSUE THREAD

**Issue by JohnTimm** [IBM/FHIR#1530]
The `fhir-term` module should be updated as follows:

1. Add support to `FHIRTermService` for multiple `FHIRTermServiceProvider` instances:
```java
	private FHIRTermServiceProvider findProvider(CodeSystem codeSystem) {
            return providers.stream()
			.filter(provider -> provider.isSupported(codeSystem))
			.findFirst()
			.orElse(null);
	}
```
2. Add methods to `FHIRTermServiceProvider` interface:
	`boolean isSupported(CodeSystem)`
	`Concept findConcept(CodeSystem, Code)`
	`Concept findConcept(CodeSystem, Code, Code)`

3. Remove methods from `FHIRTermServiceProvider` interface:
	`boolean isExpandable(ValueSet)`
        Consider removing `validateCode(ValueSet, ...)` methods
        Consider removing `expand(ValueSet)` method
	
4. Update methods in FHIRTermService class:
	`boolean isExpandable(ValueSet`) should be updated to call `ValueSetSupport.isExpandable(ValueSet)`
	`ValidationResult validateCode(ValueSet, ...)` methods should be updated to call `ValueSetSupport.validateCode(ValueSet, ...)`
        Consider removing dependency on FHIRTermServiceProvider interface

5. Add implementation for new methods in `DefaultTermServiceProvider`:
	`boolean isSupported(CodeSystem)` -> `CodeSystem.content = 'complete'`
	`Concept findConcept(CodeSystem, Code)` -> calls `CodeSystemSupport.findConcept(...)`
	`Concept findConcept(CodeSystem, Code, Code)` -> calls `CodeSystemSupport.findConcept(...)`

6. Updated methods and inner classes in ValueSetSupport
	Update `isExpandable` to use `FHIRTermService.getInstance().isSupported(CodeSystem)`
	Update `createDescendOfFilter`, `createGeneralizesFilter`, `createIsAFilter`, `createIsNotFilter` to use `FHIRTermService.getInstance().findConcept(...)` method
	Update `DescendantOfFilter`, `GeneralizesFilter`, `IsAFilter`, `EqualsFilter` to use `FHIRTermService.getInstance().findConcept(...)` method

7. Centeralize code set caching: move code set caching from `DefaultTermServiceProvider` back into the `ValueSetSupport` class

**Comment by JohnTimm** [comment]
Proposed simplified `FHIRTermServiceProvider` interface:
```
public interface FHIRTermServiceProvider {
    boolean isSupported(CodeSystem);
    Concept findConcept(CodeSystem, Code);
    Concept findConcept(CodeSysten, Code, Code);
    LookupOutcome lookup(CodeSystem, Code, LookupParameters);
    LookupOutcome lookup(CodeSystem, Code);
    ConceptSubsumptionOutcome subsumes(CodeSystem, Code, Code);
    ConceptMap closure(CodeSystem, Code);
    ValidationOutcome validateCode(CodeSystem, Code, String, ValidationParameters);
    ValidationOutcome validateCode(CodeSystem, Code, String);
    TranslationOutcome translate(ConceptMap, Uri, String, Code, TranslationParameters);
    TranslationOutcome translate(ConceptMap, Uri, String, Code);
}
```

**Comment by lmsurpre** [comment]
I think we need to update the javadoc for `subsumes`:
```
    /**
     * Find the concept in tree rooted by the provided concept that matches the specified code.
     *
     * @param codeSystem
     *     the code system
     * @param codeA
     *     the root of the hierarchy to search
     * @param codeB
     *     the code to match
     * @return
     *     the code system concept that matches the specified code, or null if not such concept exists
     */
    boolean subsumes(CodeSystem codeSystem, Code codeA, Code codeB);
```

It returns a boolean but the javadoc implies it will return a Concept

**Comment by lmsurpre** [comment]
was just reading at https://www.hl7.org/fhir/operation-codesystem-subsumes.html
> The “A” Coding that is to be tested. The code system does not have to match the specified subsumption code system, but the relationships between the code systems must be well established

we don’t support subsumption testing across codesystems, right?  is that a limitation of the current interface?

**Comment by lmsurpre** [comment]
I opened https://github.com/IBM/FHIR/pull/2181/files with my recommended javadoc updates.

**Comment by lmsurpre** [comment]
> was just reading at https://www.hl7.org/fhir/operation-codesystem-subsumes.html
> 
> > The “A” Coding that is to be tested. The code system does not have to match the specified subsumption code system, but the relationships between the code systems must be well established
> 
> we don’t support subsumption testing across codesystems, right? is that a limitation of the current interface?

I discussed this with @JohnTimm  and he wanted to keep just the single-system variant for now (since this is all we support at the moment).  If/when we get a FHIRTermServiceProvider implementation that can test for subsumption across systems, we'll need to update the interface to support that.
