### ISSUE TITLE
Improve Instructions related to how-to configure IBM FHIR Server on DockerHub

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#1540]
**Is your feature request related to a problem? Please describe.**
Improve Instructions related to how-to configure IBM FHIR Server on DockerHub

**Describe the solution you'd like**
Improve the inline documentation to describe layer or volume configuration or externalized parameters

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by prb112** [comment]
Draft posted to https://github.com/IBM/FHIR/wiki/Docker-Hub---Draft 
@ldettman @lmsurpre  please review when you are available - no rush. 

```
### Copy the configuration as a Layer

Create your own Dockerfile and add a layer to copy your configuration to the image

```
FROM ibmcom/ibm-fhir-server:your-version
COPY --chown=1001:0 fhir-server-config.json /opt/ol/wlp/usr/servers/fhir-server/config/default
COPY --chown=1001:0 overrides/ /opt/ol/wlp/usr/servers/fhir-server/configDropins/
```

### Put the Configuration into a Volume
Copy the existing [configurations](https://github.com/IBM/FHIR/tree/master/fhir-server/liberty-config/config/default) files to a local folder `<local_fhir_config_dir>`

Create a folder for overrides on your local system `<local_liberty_overrides_dir>`

Run your Docker with the local folders mounted as volumes

```
 docker run -p9443:9443 ibmcom/ibm-fhir-server -v <local_fhir_config_dir>:/opt/ol/wlp/usr/servers/fhir-server/config/
    -v <local_liberty_overrides_dir>:/opt/ol/wlp/usr/servers/fhir-server/configDropins/overrides
```

Note: other combinations and volume mounts are possible. The power with this technique is your configuration is not on ephemeral storage.
```

**Comment by prb112** [comment]
Next action: post review, update docker hub https://hub.docker.com/repository/docker/ibmcom/ibm-fhir-server

**Comment by ldettman** [comment]
Reviewed and looks good.

**Comment by lmsurpre** [comment]
Looks good to me too.

Maybe insert one word on this line to make it clear its for server.xml overrides and not fhir-server-config overrides?
From
> Create a folder for overrides on your local system <local_liberty_overrides_dir>
to
> Create a folder for server.xml overrides on your local system <local_liberty_overrides_dir>

**Comment by prb112** [comment]
Done, going to make the edit and update
