### ISSUE TITLE
Audit event logging and the event streams dependency needs investigation

### ISSUE THREAD

**Issue by ldettman** [IBM/FHIR#1541]
**Is your feature request related to a problem? Please describe.**
Audit logging is enabled only through event streams.

**Describe the solution you'd like**
An audit logging capability that is not tightly coupled with event streams and provides flexibility in configuration for writing audit event entries to something like object store. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by prb112** [comment]
RestAuditLogger needs some cleanup 

```
    private static final String HEADER_IBM_APP_USER = "IBM-App-User";
    private static final String HEADER_CLIENT_CERT_CN = "IBM-App-cli-CN";
    private static final String HEADER_CLIENT_CERT_ISSUER_OU = "IBM-App-iss-OU";
    private static final String HEADER_CORRELATION_ID = "IBM-DP-correlationid";
```

logConfig doesn't connect to any code

**Comment by prb112** [comment]
In process,branch under development

**Comment by prb112** [comment]
PR in progress... WIP while I work on other issues, https://github.com/IBM/FHIR/pull/1682

**Comment by prb112** [comment]
> RestAuditLogger needs some cleanup
> 
> ```
>     private static final String HEADER_IBM_APP_USER = "IBM-App-User";
>     private static final String HEADER_CLIENT_CERT_CN = "IBM-App-cli-CN";
>     private static final String HEADER_CLIENT_CERT_ISSUER_OU = "IBM-App-iss-OU";
>     private static final String HEADER_CORRELATION_ID = "IBM-DP-correlationid";
> ```
> 
> logConfig doesn't connect to any code

While these aren't technically used, it's best to leave in place as they provide useful utility. 
I opted not to remove logConfig as it may be a requirement in the future to log the configuration changes.
