### ISSUE TITLE
Update Kafka configuration 

### ISSUE THREAD

**Issue by ldettman** [IBM/FHIR#1542]
**Is your feature request related to a problem? Please describe.**
Kafka has not been visited for some time and needs to be updated to latest user libraries to ensure cloud portability.

**Describe the solution you'd like**
Ability to configure Kafka compatible services from different cloud platforms.

**Describe alternatives you've considered**
n/a

**Additional context**
May need configuration options for different platforms.

**Comment by prb112** [comment]
In process, and active development

**Comment by prb112** [comment]
PR in progress... WIP while I work on other issues, https://github.com/IBM/FHIR/pull/1682
