### ISSUE TITLE
Audit event logger to use service loader pattern

### ISSUE THREAD

**Issue by ldettman** [IBM/FHIR#1545]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Update AuditEventLogger to use the Java ServiceLoader Pattern as used by the operation framework. 

**Describe alternatives you've considered**
Consider inclusion in the transaction. Verify with compliance if this is necessary as it adds additional complication. 

**Additional context**
n/a

**Comment by prb112** [comment]
Team agreement to remove label 'cloud portability'

**Comment by prb112** [comment]
The current methodology ensures that there is no missed AuditEvent. Using a ServiceLoader pattern implies async, and the current method is sufficient for the purposes.
