### ISSUE TITLE
Documentation on how to use Keycloak with FHIR

### ISSUE THREAD

**Issue by ldettman** [IBM/FHIR#1546]
**Is your feature request related to a problem? Please describe.**
Want to use Keycloak with FHIR server but don't know how. 

**Describe the solution you'd like**
Provide documentation on how to use Keycloak with the FHIR server. For extra credit it would also include best practices and how to avoid pitfalls. 
Also figure out where to store the output

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by lmsurpre** [comment]
I created the following blog post for this:  https://github.com/Alvearie/alvearie.github.io/pull/35/files 

I'm not sure how much of that belongs in our repo vs just having somewhere to point to.  Feedback welcomed.

**Comment by prb112** [comment]
> I created the following blog post for this: https://github.com/Alvearie/alvearie.github.io/pull/35/files
> 
> I'm not sure how much of that belongs in our repo vs just having somewhere to point to. Feedback welcomed.

maybe a cross link would be just fine?

**Comment by lmsurpre** [comment]
TODO:  replace current section of the user's guide with a link to keycloak project. https://ibm.github.io/FHIR/guides/FHIRServerUsersGuide#53-openid-connect-and-oauth-20

**Comment by tbieste** [comment]
Verified documentation in IBM FHIR Server Users Guide.
