### ISSUE TITLE
Document audit event logger

### ISSUE THREAD

**Issue by ldettman** [IBM/FHIR#1549]
**Is your feature request related to a problem? Please describe.**
Documentation needed for the audit event logger.

**Describe the solution you'd like**
Refine documentation for the audit event logger. Include lack of tenant identity. 

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

Related to: https://github.com/IBM/FHIR/issues/1531

**Comment by prb112** [comment]
In CADF we log the tenantId

```
new CadfResource.Builder(logEntry.getTenantId() + "@" + logEntry.getComponentId(),
```

**Comment by prb112** [comment]
Closing out per discussion with Liz
