### ISSUE TITLE
Document cloud portability features

### ISSUE THREAD

**Issue by ldettman** [IBM/FHIR#1550]
**Is your feature request related to a problem? Please describe.**
Need to understand cloud portability features and aspects. 

**Describe the solution you'd like**
Documentation on cloud portability regarding compatible services, platforms (ie RH OpenShift), etc.

The destination of the cloud portability documentation would be Git Hub. 

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by lmsurpre** [comment]
We will need to open a new issue if we want to support helm charts, operators, or what-have-you
