### ISSUE TITLE
FHIR Server Startup - Bootstrapping Derby Error

### ISSUE THREAD

**Issue by ceekaay** [IBM/FHIR#1554]
**Describe the bug**
I am using a Raspberry Pi 4 (4 GB) and followed the instructions in the blog entry (https://ibm.github.io/FHIR/blog/raspberrypi4howto). After a successful build and installing or using fhir-server-distribution.zip I get always the following error. I want to use the embedded derby db.

[console.log](https://github.com/IBM/FHIR/files/5324199/console.log)

[messages.log](https://github.com/IBM/FHIR/files/5324182/messages.log)

**To Reproduce**
1. Unzip fhir-server-distribution.zip in home directory
2. Run `./fhir-server-dist/install.sh  ~/fhir-server`
3. Edit the jvm.options file (-Xmx1024M and -Xms1024M)
4. Start server <WLP_HOME>/bin/server start fhir-server
5. Try to access https://<server.ip>:9443/fhir-server/api/v4/

**Expected behavior**
JSON Output with "ALL OK" message

**Additional context**
Raspberry Pi 4 (GB) - Raspberry Pi OS (32-bit) Lite (Debian Buster)
Tried Releases: 4.4.1 (own build) and 4.4.0 released version
Tried OpenJDK 8 and 11

**Comment by prb112** [comment]
This error happens most frequently on memory constrained environments. 

```
[WARNING ] [ONCE] Not supported in Derby: ALTER TABLE APP.APPOINTMENT_STR_VALUES ALTER COLUMN ROW_ID SET CACHE 1000
[ERROR   ] DSRA0304E:  XAException occurred. XAException contents and details are: .
[ERROR   ] DSRA0302E:  XAException occurred.  Error code is: XA_RBROLLBACK (100).  Exception is: null
[ERROR   ] Encountered an exception while bootstrapping the FHIR database
java.sql.SQLNonTransientConnectionException: No current connection.
[ERROR   ] transaction rollback failed
No Global Transaction exists to commit.
[ERROR   ] Encountered an exception while initializing the servlet context.
javax.transaction.RollbackException
[ERROR   ] SRVE0283E: Exception caught while initializing context: java.lang.RuntimeException: Encountered an exception while initializing the servlet context.
	at com.ibm.fhir.server.listener.FHIRServletContextListener.contextInitialized(FHIRServletContextListener.java:199)
	at com.ibm.ws.webcontainer.webapp.WebApp.notifyServletContextCreated(WebApp.java:2433)
	at [internal classes]
Caused by: javax.transaction.RollbackException
	at com.ibm.tx.jta.impl.TransactionImpl.stage3CommitProcessing(TransactionImpl.java:978)
	at [internal classes]
	at com.ibm.fhir.server.listener.FHIRServletContextListener.bootstrapFhirDb(FHIRServletContextListener.java:290)
	at com.ibm.fhir.server.listener.FHIRServletContextListener.bootstrapDerbyDatabases(FHIRServletContextListener.java:220)
	at com.ibm.fhir.server.listener.FHIRServletContextListener.contextInitialized(FHIRServletContextListener.java:181)
	... 2 more
```

I was pretty sure we fixed this recently.  @punktilious @lmsurpre thoughts?

**Comment by prb112** [comment]
We chatted about this on the team meeting - 

The solution is to increase your server.xml timeout

```
either:
A. finding server.xml and adding this line in there:
<transaction totalTranLifetimeTimeout="480s" />
OR (for docker)
B. following the steps at https://hub.docker.com/r/ibmcom/ibm-fhir-server to specify a server.xml override

<server>
    <logging traceSpecification="com.ibm.fhir.*=fine" traceFileName="stdout" />
    <transaction totalTranLifetimeTimeout="480s" />
</server>
```

**Comment by ceekaay** [comment]
> 
> 
> We chatted about this on the team meeting -
> 
> The solution is to increase your server.xml timeout
> 
> ```
> either:
> A. finding server.xml and adding this line in there:
> <transaction totalTranLifetimeTimeout="480s" />
> OR (for docker)
> B. following the steps at https://hub.docker.com/r/ibmcom/ibm-fhir-server to specify a server.xml override
> 
> <server>
>     <logging traceSpecification="com.ibm.fhir.*=fine" traceFileName="stdout" />
>     <transaction totalTranLifetimeTimeout="480s" />
> </server>
> ```

This works. Thank you!

**Comment by prb112** [comment]
Excellent
