### ISSUE TITLE
Getting FHIR notifications for all resources including those not listed in the 'includeResourceTypes' field

### ISSUE THREAD

**Issue by luisgarcc** [IBM/FHIR#1577]
**Description**
I setup a FHIR instance with Kafka notifications enabled and configured the `includeResourceTypes` options to only include notifications about `Patient`, `Condition`, `Procedure` and `Observation` resources, as I started using the FHIR server I realized that I was getting notifications about all FHIR resources that I was using, not just those listed.

**To Reproduce**
1. Setup a FHIR server with Kafka notifications enabled
2. Configure the `notifications.common.includeResourceTypes` to include `Patient`, `Condition`, `Procedure` and `Observation` resources
2. Generate some patients with synthea
3. Post the synthea patients to the FHIR server
4. See the topic will include notifications about all resources generated by synthea

**Expected behavior**
I was expecting to only see notifications about the desired resources.

**Additional Context**
I am attaching the fhir-server-config.json file that I am using.

[fhir-server-config.zip](https://github.com/IBM/FHIR/files/5367004/fhir-server-config.zip)

**Comment by prb112** [comment]
I'm able to reproduce this.

**Comment by prb112** [comment]
We missed setting the tree set properly.
