### ISSUE TITLE
Posting bundles are not returning warnings in the OperationOutcome

### ISSUE THREAD

**Issue by mpayne2** [IBM/FHIR#1594]
I have a bundle with 3 claim entries which each entry generates warnings if posted to FHIR individually, none of the warnings are returned in the OperationOutcome when I post them in the bundle.  This happens on both transaction and batch types.

The only time I get the warnings back for an entry is if the entry also had an error.
In my test, none of my claims have the narrative set which should generate a warning message.  When I set one of the claims to have an error, like setting the code but not the code system in claim.item.quantity, I get the error and warning for that entry.

I expected to get all the warnings in the OperationOutcome for all entries when I specify the Prefer header to return=OperationOutcome.

Here is my sample:
{
 "resourceType": "Bundle",
  "id": "bundle-transaction",
  "type": "batch",
  "entry": [ {
    "resource": {
      "resourceType": "Claim",
      "id": "0010",
      "meta": {
        "versionId": "1",
        "lastUpdated": "2020-03-24T19:42:52.014+00:00",
        "source": "#anRjJex8JdtnGhIV",
        "tag": [ {
          "system": "https://smarthealthit.org/tags",
          "code": "Covid19 synthetic population from Synthea"
        } ]
      },
      "status": "active",
      "type": {
        "coding": [ {
          "system": "http://terminology.hl7.org/CodeSystem/claim-type",
          "code": "institutional"
        } ]
      },
      "use": "claim",
      "patient": {
        "reference": "Patient/0001",
        "display": "Deon400 Lebsack687"
      },
      "billablePeriod": {
        "start": "2014-11-05T05:00:20-06:00",
        "end": "2014-11-05T05:15:20-06:00"
      },
      "created": "2014-11-05T05:15:20-06:00",
      "provider": {
        "reference": "Organization/7a208ea5-66f6-392a-8472-059d61de2410",
        "display": "MIDWEST ANESTHESIA PARTNERS LLC"
      },
      "priority": {
        "coding": [ {
          "system": "http://terminology.hl7.org/CodeSystem/processpriority",
          "code": "normal"
        } ]
      },
      "facility": {
        "reference": "Location/21bd6648-ed47-44ec-98a3-da7b6d47eab7",
        "display": "MIDWEST ANESTHESIA PARTNERS LLC"
      },
      "supportingInfo": [ {
        "sequence": 1,
        "category": {
          "coding": [ {
            "system": "http://terminology.hl7.org/CodeSystem/claiminformationcategory",
            "code": "info"
          } ]
        },
        "valueReference": {
          "reference": "Immunization/e810c578-db45-448a-b30c-852c8597a5b4"
        }
      } ],
      "insurance": [ {
        "sequence": 1,
        "focal": true,
        "coverage": {
          "display": "UnitedHealthcare"
        }
      } ],
      "item": [ {
        "sequence": 1,
        "productOrService": {
          "coding": [ {
            "system": "http://snomed.info/sct",
            "code": "162673000",
            "display": "General examination of patient (procedure)"
          } ],
          "text": "General examination of patient (procedure)"
        },
        "encounter": [ {
          "reference": "Encounter/e5762d2a-03ce-4e2d-908a-1c58bd9776c9"
        } ]
      }, {
        "sequence": 2,
        "informationSequence": [ 1 ],
        "productOrService": {
          "coding": [ {
            "system": "http://hl7.org/fhir/sid/cvx",
            "code": "140",
            "display": "Influenza, seasonal, injectable, preservative free"
          } ],
          "text": "Influenza, seasonal, injectable, preservative free"
        },
        "net": {
          "value": 123.88,
          "currency": "USD"
        }
      } ],
      "total": {
        "value": 113.86,
        "currency": "USD"
      }
    },
         "request": {
            "method": "PUT",
		    "url": "Claim/0010"
    }
  }, {
    "resource": {
      "resourceType": "Claim",
      "id": "0011",
      "meta": {
        "versionId": "1",
        "lastUpdated": "2020-03-24T19:42:52.014+00:00",
        "source": "#anRjJex8JdtnGhIV",
        "tag": [ {
          "system": "https://smarthealthit.org/tags",
          "code": "Covid19 synthetic population from Synthea"
        } ]
      },
      "status": "active",
       "type": {
        "coding": [ {
          "system": "http://terminology.hl7.org/CodeSystem/claim-type",
          "code": "pharmacy"
        } ]
      },
      "use": "claim",
      "patient": {
        "reference": "Patient/0001"
      },
      "billablePeriod": {
        "start": "2020-03-12T06:00:20-05:00",
        "end": "2020-03-12T07:20:20-05:00"
      },
      "created": "2020-03-12T07:20:20-05:00",
      "provider": {
        "reference": "Organization/5e3b4e0b-ba90-321f-aa5e-0c7b3d13d7ad",
        "display": "RUSH OAK PARK HOSPITAL"
      },
      "priority": {
        "coding": [ {
          "system": "http://terminology.hl7.org/CodeSystem/processpriority",
          "code": "normal"
        } ]
      },
      "prescription": {
        "reference": "MedicationRequest/cf6db5e8-6b9b-4e8c-a594-0713f29020cc"
      },
      "insurance": [ {
        "sequence": 1,
        "focal": true,
        "coverage": {
          "display": "UnitedHealthcare"
        }
      } ],
      "item": [ {
        "sequence": 1,
        "productOrService": {
          "coding": [ {
            "system": "http://snomed.info/sct",
            "code": "185345009",
            "display": "Encounter for symptom (procedure)"
          } ],
          "text": "Encounter for symptom (procedure)"
        },
        "encounter": [ {
          "reference": "Encounter/56beaca0-399d-4307-becb-2541ee389ffe"
        } ],
        "quantity": {
            "code": "aCode"
        }
      } ],
      "total": {
        "value": 232.27,
        "currency": "USD"
      }
    },
         "request": {
            "method": "PUT",
		    "url": "Claim/0011"
    }
  }, {
    "resource": {
      "resourceType": "Claim",
      "id": "0012",
      "meta": {
        "versionId": "1",
        "lastUpdated": "2020-03-24T19:42:52.014+00:00",
        "source": "#anRjJex8JdtnGhIV",
        "tag": [ {
          "system": "https://smarthealthit.org/tags",
          "code": "Covid19 synthetic population from Synthea"
        } ]
      },
      "status": "active",
       "type": {
        "coding": [ {
          "system": "http://terminology.hl7.org/CodeSystem/claim-type",
          "code": "institutional"
        } ]
      },
      "use": "claim",
      "patient": {
        "reference": "Patient/0001",
        "display": "Deon400 Lebsack687"
      },
      "billablePeriod": {
        "start": "2011-11-02T06:00:20-05:00",
        "end": "2011-11-02T06:15:20-05:00"
      },
      "created": "2011-11-02T06:15:20-05:00",
      "provider": {
        "reference": "Organization/7a208ea5-66f6-392a-8472-059d61de2410",
        "display": "MIDWEST ANESTHESIA PARTNERS LLC"
      },
      "priority": {
        "coding": [ {
          "system": "http://terminology.hl7.org/CodeSystem/processpriority",
          "code": "normal"
        } ]
      },
      "facility": {
        "reference": "Location/21bd6648-ed47-44ec-98a3-da7b6d47eab7",
        "display": "MIDWEST ANESTHESIA PARTNERS LLC"
      },
      "supportingInfo": [ {
        "sequence": 1,
        "category": {
          "coding": [ {
            "system": "http://terminology.hl7.org/CodeSystem/claiminformationcategory",
            "code": "info"
          } ]
        },
        "valueReference": {
          "reference": "Immunization/f0c868a7-c834-443a-9cdb-a21f09b7b248"
        }
      }, {
        "sequence": 2,
        "category": {
          "coding": [ {
            "system": "http://terminology.hl7.org/CodeSystem/claiminformationcategory",
            "code": "info"
          } ]
        },
        "valueReference": {
          "reference": "Immunization/52c68af0-84bb-456c-9fed-69de75913b6e"
        }
      } ],
      "insurance": [ {
        "sequence": 1,
        "focal": true,
        "coverage": {
          "display": "UnitedHealthcare"
        }
      } ],
      "item": [ {
        "sequence": 1,
        "productOrService": {
          "coding": [ {
            "system": "http://snomed.info/sct",
            "code": "162673000",
            "display": "General examination of patient (procedure)"
          } ],
          "text": "General examination of patient (procedure)"
        },
        "encounter": [ {
          "reference": "Encounter/43af77af-0df4-4771-bc66-b79f33313d70"
        } ],
        "quantity": {
            "code": "aCode"
        }
     }, {
        "sequence": 2,
        "informationSequence": [ 1 ],
        "productOrService": {
          "coding": [ {
            "system": "http://hl7.org/fhir/sid/cvx",
            "code": "140",
            "display": "Influenza, seasonal, injectable, preservative free"
          } ],
          "text": "Influenza, seasonal, injectable, preservative free"
        },
        "net": {
          "value": 123.88,
          "currency": "USD"
        }
      }, {
        "sequence": 3,
        "informationSequence": [ 2 ],
        "productOrService": {
          "coding": [ {
            "system": "http://hl7.org/fhir/sid/cvx",
            "code": "113",
            "display": "Td (adult) preservative free"
          } ],
          "text": "Td (adult) preservative free"
        },
        "net": {
          "value": 123.88,
          "currency": "USD"
        }
      } ],
      "total": {
        "value": 113.86,
        "currency": "USD"
      }
    },
         "request": {
            "method": "PUT",
		    "url": "Claim/0012"
    }
  } ]
}

**Comment by michaelwschroeder** [comment]
The way bundle entries are currently processed is that first we loop through them to run validation, and save any warnings/errors from validation. Then we loop through the entries again to do the actual create or update processing (only for the entries that do not have validation errors). When we successfully create or update, we set a single informational issue of OK in a new  OperationOutcome, and set that OperationOutcome in the response entry, overwriting the existing OperationOutcome from the validation step containing any validation warnings. Thus the validation warnings are not seen on final output.

**Comment by prb112** [comment]
Moved to Review/QA

**Comment by mpayne2** [comment]
Tested it and I'm getting the warnings back for all entries within the bundle.
