### ISSUE TITLE
Add support for deploying via Helm chart

### ISSUE THREAD

**Issue by chgl** [IBM/FHIR#1602]
**Is your feature request related to a problem? Please describe.**

The server is currently not available as a Helm chart, making installation on Kubernetes less convenient.

**Describe the solution you'd like**

Provide a Helm chart the make it easier to install the application in Kubernetes.

**Describe alternatives you've considered**

**Additional context**

I could definitely work on this starting in 1-2 weeks. I think it should be fairly straight-forward, the biggest challenge will probably be setting up the database/applying the schema using the persistence cli tools.

**Comment by lmsurpre** [comment]
We definitely have a lot of this working on our internal deploys...I can see about opening some of that up and pushing it to github.  I also recently read the following post:  https://helm.sh/blog/helm-turns-five/ and so I think the timing is good.
* Helm stable and incubator chart repositories will now be hosted by GitHub
* There is now an official Helm Chart Releaser GitHub Action:  https://github.com/marketplace/actions/helm-chart-releaser

**Comment by chgl** [comment]
> We're also using helm for a few of our internal deploys...I can see about opening some of that up and pushing it to github.

That would be great, thank you!

+1 for helm-chart-releaser & https://github.com/norwoodj/helm-docs

Let me know if I can help setting it up or give feedback at some point.

**Comment by luisgarcc** [comment]
For what is worth we have a bare bones FHIR chart, with limited configurability to suit some demos we have been doing.

It's available in the [alvearie health-patterns](https://github.com/Alvearie/health-patterns/tree/main/clinical-ingestion/helm-charts/fhir) repository in case someone might want to use it in the mean time, while the official chart from the FHIR team is published.

**Comment by lmsurpre** [comment]
Extracting a standalone helm chart from the one we use within our internal deploy pipeline proved a bit more difficult than I was expecting.  I created a draft pull request #1602 with a "clean base" but left quite a few TODOs in the description.  Will try getting back to this one when I have a chance.

**Comment by lmsurpre** [comment]
The initial version of this chart is now committed to https://github.com/Alvearie/alvearie-helm/tree/main/ibm-fhir-server.
Additional enhancements will be handled via issues on that other repo.
