### ISSUE TITLE
Restrict access to reindex custom operation

### ISSUE THREAD

**Issue by punktilious** [IBM/FHIR#1620]
**Is your feature request related to a problem? Please describe.**
The reindex custom operation being introduced in #1366 is not an end-user function and should be restricted to admin users only.

**Describe the solution you'd like**
Ensure that authenticated users with admin privileges can call the reindex custom operation.

**Describe alternatives you've considered**
Rely on external API management to hide the function, but security should be multi-layered and so this would be less than ideal.

**Comment by prb112** [comment]
A couple things to know... 

1 - Operation.java is annotated with @RolesAllowed("FHIRUsers"), it should be annotated with the additional role that should  be allowed to perform this operation. 
2 - web.xml only specifies two mappings fhirusers fhiradmin (so fhiradmins should probably be used) 
3 - Update the method you want with a context
```
@POST
    @Path("${operationName}")
    public Response invoke(@PathParam("operationName") String operationName, Resource resource, @Context SecurityContext secContext) {
        log.entering(this.getClass().getName(), "invoke(String,Resource)");
        Date startTime = new Date();
        Response.Status status = null;

        try {
            checkInitComplete();

            FHIROperationContext operationContext =
                    FHIROperationContext.createSystemOperationContext();
            operationContext.setProperty(FHIROperationContext.PROPNAME_URI_INFO, uriInfo);
            operationContext.setProperty(FHIROperationContext.PROPNAME_HTTP_HEADERS, httpHeaders);
            operationContext.setProperty(FHIROperationContext.PROPNAME_METHOD_TYPE, HttpMethod.POST);
            operationContext.setProperty(FHIROperationContext.PROPNAME_SECURITY_CONTEXT, secContext);
```

pump it in the operationContext
4 - in the operation get the property and convert back to Security Context
5 - call secContext.isUserInRole(role)

**Comment by prb112** [comment]
I'm doing the same thing in fhir-operation-erase

**Comment by prb112** [comment]
After a review, we've decided to leave the current open behavior of the $reindex operation. We have marked this as invalid.
