### ISSUE TITLE
No error message issued when passing in a incorrect resource on _revinclude.

### ISSUE THREAD

**Issue by d0roppe** [IBM/FHIR#1629]
**Describe the bug**
When searching with the following get statement:
https://localhost:7000/fhir-server/api/v4/Patient?_id=<patient-id>&_revinclude=Provedance:*
there is no resource Provedance, but the fhir server did not issue an error.  it just dropped it and processed the search.
 
"url": "https://localhost:9443/fhir-server/api/v4/Patient?_count=10&_id=<patient-id>&_page=1"

**To Reproduce**

**Expected behavior**
With the fact that the resource type is an error it should give a error message vs dropping the _revinclude

**Additional context**

**Comment by kmbarton423** [comment]
lenient vs strict mode consideration

**Comment by michaelwschroeder** [comment]
If running in strict mode, an error will be returned if an invalid target resource type is specified in a `_revinclude` query parameter. If running in lenient mode, the error message will be logged and the invalid `_revinclude` query parameter will be ignored.

In addition, changes will be made to `_include`/`_revinclude` processing to handle errors more consistently when running in lenient mode. Currenty, if multiple `_include` or `_revinclude` query parameters are specified and an error is found in one of them, all will be ignored, with the exception of a bad search parameter being found. In that case, only the query parameter with the bad search parameter is ignored. With the new changes, when running in lenient mode, if an error is found processing a query parameter, only that query parameter will be ignored. Any valid `_include` or `_revinclude` query parameters will be included in the search query. Note that this applies only if running in lenient mode. If running in strict mode, any error found will result in a failed search request.

**Comment by d0roppe** [comment]
Verified that in strict mode now this throws an error 400 and does not process the search. And in lenient mode the error part of the command is ignored and dropped, and the search is processed.
