### ISSUE TITLE
Clean up fhir-bucket CLI args to make it easier to run reindex

### ISSUE THREAD

**Issue by punktilious** [IBM/FHIR#1640]
Allow fhir-bucket to run reindex without having to specify other configuration parameters for features which are not relevant to reindex.

**Comment by punktilious** [comment]
As reported on chat.fhir.org, running reindex requires that the FHIRBUCKET schema exists. This shouldn't be necessary if all a user wants to do is drive the reindex.

**Comment by lmsurpre** [comment]
follow the documentation at https://github.com/IBM/FHIR/tree/main/fhir-bucket#1-reindex---driving-the-reindex-custom-operation and confirm:
1. the arguments seem reasonable / not excessive
2. they work as advertised

**Comment by d0roppe** [comment]
Created a new issue #3272 and closing this issue as the documentation is better, but could use some updates.
