### ISSUE TITLE
Investigate alternative strategy for InclusionQuerySegmentAggregator#executeIncludeSubQuery

### ISSUE THREAD

**Issue by punktilious** [IBM/FHIR#1647]
InclusionQuerySegmentAggregator#executeIncludeSubQuery executes a query whose results are then used to build a second query. There may be better performing alternatives which can be executed inline as a subquery.

**Comment by michaelwschroeder** [comment]
Closing this issue. It has been addressed by the _include/_revinclude re-design in issue #1158 and by the new query builder implementation.
