### ISSUE TITLE
Poor performance for some search queries using implicit date ranges

### ISSUE THREAD

**Issue by punktilious** [IBM/FHIR#1653]
**Describe the bug**
Searches using implicit ranges are resulting in index range scans with only one bound. For example:
```
Claim?created=2015-10-16
```
will generate a predicate (something) like this:
```
CP1.DATE_START >= '2015-10-16 00:00:00.0' AND CP1.DATE_END <= '2015-10-16 23:59:59.999999'
```

This requires a range scan of the index for DATE_START and a another scan on a second index for DATE_END. Both scans could pull in huge row counts, and the query may ultimately fail with a transaction timeout.

**To Reproduce**
Load the database with a lot of data, then run a query with an implicit date range, such as:
```
Claim?created=2015-10-16
```
**Expected behavior**
Query should return in a time proportional to the amount of data meeting the predicate condition, not the overall amount of data in the database.

**Additional context**
Because we know that `DATE_END >= DATE_START`, the query can be rewritten without changing its semantics:

```
      CP1.DATE_START >= '2015-10-16 00:00:00.0' AND CP1.DATE_START <= '2015-10-16 23:59:59.999999'
   AND CP1.DATE_END <= '2015-10-16 23:59:59.999999' AND CP1.DATE_END >= '2015-10-16 00:00:00.0'
```
The access path is now an index range scan on one index with both upper and lower bounds. The time will be proportional to the number of rows falling within the given date range.

**Comment by kmbarton423** [comment]
related to #1624

**Comment by michaelwschroeder** [comment]
NOTES:
1. work for this issue is being done under PR https://github.com/IBM/FHIR/pull/2562
2. This is implemented only in the new query builder

**Comment by michaelwschroeder** [comment]
This optimization can be done for date searches which generate a query of the form `start_date > <value> AND end_date < <value>`. This happens in two cases:
1. A date search with an explicit or implicit `eq` prefix, i.e. `.../Patient?birthdate=2021-06-01`
2. An explicit date range search using the `sa` and `eb` prefixes, i.e. `.../Patient?birthdate=sa1980-01-01&birthdate=eb2001-01-01` 

In the first case, the new query will look like the following:
```
      SELECT R.RESOURCE_ID, R.LOGICAL_RESOURCE_ID, R.VERSION_ID, R.LAST_UPDATED, R.IS_DELETED, R.DATA, LR.LOGICAL_ID 
        FROM (
      SELECT LR0.LOGICAL_RESOURCE_ID, LR0.LOGICAL_ID, LR0.CURRENT_RESOURCE_ID 
        FROM Patient_LOGICAL_RESOURCES AS LR0
       WHERE LR0.IS_DELETED = 'N'
         AND EXISTS (
      SELECT 1 
        FROM Patient_LOGICAL_RESOURCES AS LR1 
  INNER JOIN Patient_DATE_VALUES AS P2 ON P2.LOGICAL_RESOURCE_ID = LR1.LOGICAL_RESOURCE_ID
         AND P2.PARAMETER_NAME_ID = 1054
         AND (P2.DATE_START >= ?
         AND P2.DATE_START <= ?
         AND P2.DATE_END <= ?
         AND P2.DATE_END >= ?)
       WHERE LR1.LOGICAL_RESOURCE_ID = LR0.LOGICAL_RESOURCE_ID)) AS LR 
  INNER JOIN Patient_RESOURCES AS R ON LR.CURRENT_RESOURCE_ID = R.RESOURCE_ID
    ORDER BY LR.LOGICAL_RESOURCE_ID
 FETCH FIRST 10 ROWS ONLY
```

And in the second case, the new query will look like the following:
```
      SELECT R.RESOURCE_ID, R.LOGICAL_RESOURCE_ID, R.VERSION_ID, R.LAST_UPDATED, R.IS_DELETED, R.DATA, LR.LOGICAL_ID 
        FROM (
      SELECT LR0.LOGICAL_RESOURCE_ID, LR0.LOGICAL_ID, LR0.CURRENT_RESOURCE_ID 
        FROM Patient_LOGICAL_RESOURCES AS LR0
       WHERE LR0.IS_DELETED = 'N'
         AND EXISTS (
      SELECT 1 
        FROM Patient_LOGICAL_RESOURCES AS LR1 
  INNER JOIN Patient_DATE_VALUES AS P2 ON P2.LOGICAL_RESOURCE_ID = LR1.LOGICAL_RESOURCE_ID
         AND P2.PARAMETER_NAME_ID = 1054
         AND (P2.DATE_START > ?
         AND P2.DATE_START < ?
         AND P2.DATE_END < ?
         AND P2.DATE_END > ?)
       WHERE LR1.LOGICAL_RESOURCE_ID = LR0.LOGICAL_RESOURCE_ID)) AS LR 
  INNER JOIN Patient_RESOURCES AS R ON LR.CURRENT_RESOURCE_ID = R.RESOURCE_ID
    ORDER BY LR.LOGICAL_RESOURCE_ID
 FETCH FIRST 10 ROWS ONLY
```

**Comment by lmsurpre** [comment]
> This optimization can be done for date searches which generate a query of the form start_date > <value> AND end_date < <value>

shouldn't it apply to `ap` prefix searches too?

**Comment by d0roppe** [comment]
Rand the suggested search on the large database and the result came back rather quickly and proportionate to the resource matched vs the millions of records in the DB.  Closing issue.
