### ISSUE TITLE
Would like an easy way to extend the IBM FHIR Server TransactionManager timeout interval

### ISSUE THREAD

**Issue by d0roppe** [IBM/FHIR#1660]
**Is your feature request related to a problem? Please describe.**
Some long running searches time out before they finish, it would be nice to see how long they actually take instead of timing out.

**Describe the solution you'd like**
Be able to extend or shorten the IBM FHIR Server TransactionManager timeout interval for testing purposes.

**Describe alternatives you've considered**
n/a

**Acceptance Criteria**
At least one acceptance criteria is included.
set the timeout interval to 1 second and make sure you can get the error reported to say it timed out.
set the timeout interval to 900 seconds to make sure no fhir api request times out.

**Additional context**
n/a

**Comment by prb112** [comment]
Got this one, I can raise the PR today/tomorrow to add

**Comment by prb112** [comment]
Raised PR
