### ISSUE TITLE
Adding a _include to a search drasticly added length of time for the search to finish.

### ISSUE THREAD

**Issue by d0roppe** [IBM/FHIR#1665]
**Describe the bug**
A search like this against the large postgres DB `[base]/Patient/[id]/ExplanationOfBenefit?claim:Claim.created=2015-10-16`  takes a while about 30 seconds.  and it returned 1 EoB.  but adding the &_include=ExplanationOfBenefit to the end of the search added 7 minutes of execution time. 

**Expected behavior**
Adding the &_include=ExplanationOfBenefit to a search should not add a noticable amount of time unless you have a lot of resources you need to execute the _include on.

**Additional context**

**Comment by lmsurpre** [comment]
This is the ticket that caused @punktilious to suggest a change to our datetime queries (using both the low and the high to avoid large scans due to an open end to the range--low or high)

**Comment by lmsurpre** [comment]
https://github.com/IBM/FHIR/issues/1624 is also related in that it is performance-related for date searches

**Comment by d0roppe** [comment]
Running this test now with the current IBM fhir-server 4.7.0  the initial search took 296 ms, and the addition of &_include=ExplanationOfBenefit:* finished in 1787 ms.  Including 4 additional resources.
This issue seems to have been fixed with issue #1158
