### ISSUE TITLE
Composite search query failing

### ISSUE THREAD

**Issue by michaelwschroeder** [IBM/FHIR#1669]
**Describe the bug**
The count query generated for composite search fails due to invalid column name. 

**To Reproduce**
Attempt to execute a composite search, such as `Observation?code-value-string=1234$test`. The following exception is returned: `Column 'COMP1_P1.ROW_ID' is either not in any table in the FROM list or appears within a join specification and is outside the scope of the join specification or appears in a HAVING clause and is not in the GROUP BY list. If this is a CREATE or ALTER TABLE  statement then 'COMP1_P1.ROW_ID' is not a column in the target table.`

This is the generated SQL:
```
SELECT 
  COUNT(DISTINCT R.RESOURCE_ID) 
FROM 
  Observation_LOGICAL_RESOURCES LR 
  JOIN Observation_RESOURCES R ON R.LOGICAL_RESOURCE_ID = LR.LOGICAL_RESOURCE_ID 
  AND R.RESOURCE_ID = LR.CURRENT_RESOURCE_ID 
  AND R.IS_DELETED <> 'Y' 
  JOIN (
    SELECT 
      comp1.LOGICAL_RESOURCE_ID 
    FROM 
      Observation_COMPOSITES comp1 
      JOIN Observation_TOKEN_VALUES_V comp1_p1 ON comp1.COMP1_TOKEN = comp1_p1.ROW_ID 
      JOIN Observation_STR_VALUES comp1_p2 ON comp1.COMP2_STR = comp1_p2.ROW_ID 
    WHERE 
      (
        comp1.PARAMETER_NAME_ID = 1077 
        AND (
          (
            comp1_p1.PARAMETER_NAME_ID = 1077 
            AND (
              (comp1_p1.TOKEN_VALUE = ?)
            )
          ) 
          AND (
            comp1_p2.PARAMETER_NAME_ID = 1077 
            AND (
              comp1_p2.STR_VALUE_LCASE LIKE ? ESCAPE '+'
            )
          )
        )
      )
  ) Observation0 ON Observation0.LOGICAL_RESOURCE_ID = R.LOGICAL_RESOURCE_ID
```

**Expected behavior**
A valid search query should be generated and executed.

**Additional context**

**Comment by d0roppe** [comment]
Added composite searches to my JMeter tests to help verify this fix.  Without the fix loaded my searches failed. and with the fix they all worked.
