### ISSUE TITLE
More accurate representaton of what was searched for in the search output link URL

### ISSUE THREAD

**Issue by d0roppe** [IBM/FHIR#1670]
**Is your feature request related to a problem? Please describe.**
When you issue a search to FHIR, it outputs a link url that has what it searched on.  Like adding the _count if one was not issued, or adding the _page=1.  but it also fills in information like expanding out the time if you searched on a date.  but that time is not really what was searched on.

**Describe the solution you'd like**
Would like the link url to accuratly show what was searched on especially for date/time
like a search on _lastUpdated=2020-04 is represented in the output link url as _lastUpdated=2020-04-01T00:00:00Z but that is not what the search was.

**Describe alternatives you've considered**

**Acceptance Criteria**

**Additional context**

**Comment by kmbarton423** [comment]
either of the following is acceptable:
- self url in response matches the partial datetime passed in the request
- specify the range actually used

**Comment by tbieste** [comment]
Dates in the link urls (self, prev, next) will match the partial dates passed in the request.  This will allow paging to work properly.

**Comment by d0roppe** [comment]
verified with multiple date searches.
