### ISSUE TITLE
Token search does not include CODE_SYSTEM_ID clause if system is not explicitly specified in search

### ISSUE THREAD

**Issue by michaelwschroeder** [IBM/FHIR#1681]
**Is your feature request related to a problem? Please describe.**
The SQL generated for a token type search does not include a CODE_SYSTEM_ID clause for the token being searched unless a system value is provided as part of the search query. For example, the following SQL is generated for this search which explicitly specifies a system value: `Observation?status=http://hl7.org/fhir/observation-status|final`:
```
SELECT 
  COUNT(DISTINCT R.RESOURCE_ID) 
FROM 
  Observation_LOGICAL_RESOURCES LR 
  JOIN Observation_RESOURCES R ON R.LOGICAL_RESOURCE_ID = LR.LOGICAL_RESOURCE_ID 
  AND R.RESOURCE_ID = LR.CURRENT_RESOURCE_ID 
  AND R.IS_DELETED <> 'Y' 
  JOIN Observation_TOKEN_VALUES_V AS param0 ON (
    param0.PARAMETER_NAME_ID = 2009 
    AND (
      (
        param0.TOKEN_VALUE = ? 
        AND param0.CODE_SYSTEM_ID = ?
      )
    )
  ) 
  AND LR.LOGICAL_RESOURCE_ID = param0.LOGICAL_RESOURCE_ID
```
However, if the system is not specified (`Observation?status=final`), the following SQL is generated, which is much less performant:
```
SELECT 
  COUNT(DISTINCT R.RESOURCE_ID) 
FROM 
  Observation_LOGICAL_RESOURCES LR 
  JOIN Observation_RESOURCES R ON R.LOGICAL_RESOURCE_ID = LR.LOGICAL_RESOURCE_ID 
  AND R.RESOURCE_ID = LR.CURRENT_RESOURCE_ID 
  AND R.IS_DELETED <> 'Y' 
  JOIN Observation_TOKEN_VALUES_V AS param0 ON (
    param0.PARAMETER_NAME_ID = 2009 
    AND (
      (param0.TOKEN_VALUE = ?)
    )
  ) 
  AND LR.LOGICAL_RESOURCE_ID = param0.LOGICAL_RESOURCE_ID
```

**Describe the solution you'd like**
Ideally, if a system value is not explicitly specified, it can be looked up, and if not found on lookup, a default code system value can be used. This would allow the use of a CODE_SYSTEM_ID clause in most cases.

**Describe alternatives you've considered**
None

**Acceptance Criteria**
At least one acceptance criteria is included.

1.  
  GIVEN a FHIR DB with a lot of resources of a given type (maybe tens of thousands)
    WHEN a search is executed against a token-type search parameter for that resource type (ex. Observation.status)
    THEN the search performance should ideally be sub-second, or at least better than query without CODE_SYSTEM_ID clause

**Additional context**

**Comment by lmsurpre** [comment]
We added a capability to configure a search parameter with an "implicit system" and we've documented that at https://ibm.github.io/FHIR/guides/FHIRPerformanceGuide#65-search-examples

In my opinion, this adequately addresses this issue.  If you disagree, please feel free to move it back to the backlog.

**Comment by michaelwschroeder** [comment]
Agreed. The work referenced above done under issue #1929 addresses this issue.
