### ISSUE TITLE
Make the static datasource option the default

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#1694]
**Is your feature request related to a problem? Please describe.**
In #916 we introduced a new static datasource option.  Now I'd like that to be the default.
This will enable us to follow OpenLiberty docker image recommendations (e.g. see #923), use the newer maven-based liberty dev mode support, and potentially even run on other application servers.

**Describe the solution you'd like**
The default IBM FHIR Server image should use a static datasource approach which leverages configDropins to easilly add an remove tenant-based datasource definitions.

**Describe alternatives you've considered**
Keep using our FHIRProxyDatasource as the default.

**Comment by kmbarton423** [comment]
Attempted scenarios where fhir-server-config.json was not properly migrated away from fhirProxyDatasource.
Result:  "FHIRPersistenceException: Unexpected exception while creating JDBC persistence layer: 'Failure acquiring datasource'"

Sample log messages:
[ERROR   ] Failure acquiring datasource: jdbc/fhirProxyDataSource
CWWKN0008E: An object could not be obtained for name jdbc/fhirProxyDataSource.
