### ISSUE TITLE
Search with reverse chaining performing slowly

### ISSUE THREAD

**Issue by d0roppe** [IBM/FHIR#1705]
**Describe the bug**
The following search with _has takes over 2 minutes to run in the large postgres DB.
[base]/Patient?_has:Observation:patient:code-value-quantity=http://loinc.org|2339-0$68.6

**To Reproduce**

**Expected behavior**
The search should return faster than 2 minutes.   in most deploys it would timeout.

**Additional context**

**Comment by lmsurpre** [comment]
I saw similar when we merged the initial PR for this feature:  https://github.com/IBM/FHIR/pull/1666#issuecomment-723742963
Will be great if we can speed it up.

**Comment by d0roppe** [comment]
Running this search today with the latest code loaded on my local FHIR server linked to the large postgres DB.  this is now taking about 3.6 seconds to complete.

**Comment by lmsurpre** [comment]
Closing based on Dag's comment.  Future enhancements can come as a result of #677 findings / fixes.
