### ISSUE TITLE
_has search with _lastUpdated not working correctly

### ISSUE THREAD

**Issue by d0roppe** [IBM/FHIR#1706]
**Describe the bug**
The following search returns 38 observations and one of the Diagnostic reports has an lastUpdated field of  "lastUpdated": "2020-10-20T19:39:25.247Z"
[base]/Observation?code-value-quantity=http://loinc.org|2339-0$68.6&_revinclude=DiagnosticReport:result
but this search finds no results
[base]/Observation?code-value-quantity=http://loinc.org|2339-0$68.6&_has:DiagnosticReport:result:_lastUpdated=gt2020-10-01
I feel this last search should find at least 1 Observation.

**To Reproduce**

**Expected behavior**
was expecting at least 1 result

**Additional context**

**Comment by michaelwschroeder** [comment]
This issue applies to both chained and reverse chained searches with _lastUpdated. Examples:
- Procedure?subject:Patient._lastUpdated=gt2020-01-01
- Patient?_has:Procedure:subject:_lastUpdated=gt2020-01-01

**Comment by d0roppe** [comment]
Verified the tests used to find the issue now work, as well as the Chained vs reverse chain of the search worked. 
[base]/Observation?code-value-quantity=http://loinc.org|2339-0$68.6&_has:DiagnosticReport:result:_lastUpdated=gt2020-10-01
and
[base]/Observation?code-value-quantity=http://loinc.org|2339-0$68.6&encounter:Encounter._lastUpdated=gt2020-10-01
Both return data now.
