### ISSUE TITLE
Docker image of version 4.5.0 contains conflicting datasource definition files under `configDropins/overrides`

### ISSUE THREAD

**Issue by holger-stenzhorn** [IBM/FHIR#1724]
**Describe the bug**
The Docker image of version 4.5.0 contains conflicting datasource definition files under `configDropins/overrides`. The `README.md` within that directory actually says...
> Just one of these datasource definition files should be copied into the target Liberty configDropins/overrides folder. If more than one of these is present at the same time it will break the Liberty configuration because the datasource ids and JNDI location are common among the files.

**To Reproduce**
n/a

**Expected behavior**
All datasource definition files now in `configDropins/overrides` should be located under `configDropins/disabled`.

**Additional context**
n/a

**Comment by prb112** [comment]
Thank you for the bug, we will fix this in the docker image.
