### ISSUE TITLE
FHIRValidationException on absolute ElementDefinition.contentReference

### ISSUE THREAD

**Issue by coxstuart** [IBM/FHIR#1727]
When validating against a profile, we're getting fatal exception. FHIRValidationException: An error occurred during validation.

FHIR team troubleshooting found the issue was with our profile snapshot.  FHIR server was expecting a relative reference, but our profile had an absolute reference instead. 

The constraint generator currently assumes: ElementDefinition.contentReference are in this form #<element definition id>. 
But ours looked more like this:  http://hl7.org/fhir/StructureDefinition/Observation#Observation.referenceRange.

FHIR team said the FHIR server ConstraintGenerator cannot currently handle this particular element definition.  The irony is that this particular ElementDefinition doesn’t even generate a FHIRPath constraint… its just that the ConstraintGenerator has an issue processing it looking for constraints.  We should handle this scenario more gracefully.

**Comment by d0roppe** [comment]
I contacted the person who reported the issue.  He verified that it is working fine now.  Closing the issue.
