### ISSUE TITLE
Support token modifier ':not'

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#1731]
from https://www.hl7.org/fhir/R4/search.html#token:
> Reverse the code matching described in the paragraph above: return all resources that do not have a matching item. Note that this includes resources that have no value for the parameter - e.g. ?gender:not=male includes all patients that do not have gender = male, including patients that do not have a gender at all

example:
> Search for any patient with a gender that does not have the code "male". Note that for :not, the search does not return any resources that have a gender
    ```
GET [base]/Patient?gender:not=male
    ```

**Comment by tbieste** [comment]
Checking on requirements, where I don't see guidance from the FHIR spec:
1)  Support on token searches:  Yes
2)  Support on chained searches?    ":missing" is not, so should this be?
3)  Support on whole-system searches?  ":missing" is not, so should this be?

**Comment by lmsurpre** [comment]
I think we want `:missing` supported on those other searches as well; just havn't gotten to that.
So I'd say we want `:not` support on all three.  However, if its easier to start with just number 1, that seems reasonable to me (and open future enhancement request for the other two).

**Comment by tbieste** [comment]
Opened issue #1926 to for additional enhancements for chained/whole-system search support.

**Comment by lmsurpre** [comment]
ran a query like the following against a reasonably sized database and confirmed that the total count and the results looked right:
```
get(base + '/Patient' + '?' + 'gender:not=female' + '&' + '_summary=count')
```

also confirmed the error looks reasonable when using not on other parameter types:
```
get(base + '/Patient' + '?' + 'family:not=Smith' + '&_elements=name')
```
```
Unsupported type/modifier combination: string/not
```
