### ISSUE TITLE
Support token modifier ':text'

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#1732]
from https://www.hl7.org/fhir/R4/search.html#token:
> The search parameter is processed as a string that searches text associated with the code/value - either CodeableConcept.text, Coding.display, or Identifier.type.text. In this case, the search functions as a normal string search

Note: by "normal string search" I assume they mean it should be a "starts-with" and "case-insensitive" match.

example:
> Search for any Condition with a code that has a text "headache" associated with it (either in the text, or a display)
    ```
GET [base]/Condition?code:text=headache | 
    ```

**Comment by lmsurpre** [comment]
I don't believe we even index these values today and it could be expensive (lots of new string values in our STR_VALUES tables).

There is a different issue for searching longer / more sophisticated text search:  https://github.com/IBM/FHIR/issues/481

**Comment by michaelwschroeder** [comment]
Running against my local server with the latest codebase, I have performed token searches using the :text modifier against multiple fields and resources and have verified:
- CodeableConcept.text and Coding.display fields have been indexed properly
- search against TOKEN search parameters referencing those fields is case-insensitive and correct results are returned.
