### ISSUE TITLE
Support token modifiers ':above' and ':below'

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#1733]
from https://www.hl7.org/fhir/R4/search.html#token
|modifier|description|
| -- | -- | 
:above | The search parameter is a concept with the form [system]\|[code], and the search parameter tests whether the coding in a resource subsumes the specified search code. For example, the search concept has an is-a relationship with the coding in the resource, and this includes the coding itself.
:below | the search parameter is a concept with the form [system]\|[code], and the search parameter tests whether the coding in a resource is subsumed by the specified search code. For example, the coding in the resource has an is-a relationship with the search concept, and this includes the coding itself.

example:
> Search for any condition in the SNOMED CT value set "http://snomed.info/sct?fhir_vs=isa/126851005" that includes all descendants of "Neoplasm of liver"
    ```
    GET [base]/Condition?code:below=126851005
    ```

Note: I don't think that sample is actually right.  I think they need to include the system in there.  Should be:
```
GET [base]/Condition?code:below=http://snomed.info/sct|126851005
```

Also note: If we can support the modifier `:in` (#1734) then I think this one becomes less important because searching for anything in a valueset could be used for the same use cases and more.

**Comment by lmsurpre** [comment]
To support, we'd need to create and maintain a closure table within the database and make that closure table part of the query mechanism.
Open questions on how to efficiently generate and maintain the table.

Getting it to work for a subset of scenarios with lots of assumptions/limitations might be a little easier...

**Comment by JohnTimm** [comment]
A "lightweight" version of this feature could work as follows:
1. ask the terminology service for the closure of a given concept (the selection of whether the concept is coming from the search parameter or whether it is coming from the instance determines which concept to take)
2. convert the closure of the specified to a SQL IN clause with a literal enumeration IN ('a', 'b', c')
