### ISSUE TITLE
ValueSet expansion does not contain ValueSet.expansion.contains.display element

### ISSUE THREAD

**Issue by JohnTimm** [IBM/FHIR#1736]
The current implementation of the ValueSet expand operation (`ValueSetSupport.expand(ValueSet)`) does not include the `ValueSet.expansion.contains.display` element even when it is available in the `ValueSet.compose.concept.display` element or the `CodeSystem.concept.display` element.

The display element is cases and since we are doing set operations (intersection, set difference, etc.) with `ValueSet.Expansion.Contains` instances we rely heavily on the `hashCode` and `equals` methods which includes use all sub elements (e.g. `system`, `code`, `display`, etc.).

In order to get this to work, we would either need to a) use `TreeSet` with a custom `Comparator` implementation (with the tradeoff being performance O(1) versus O(log(n))) or b) use a wrapper class that implements the `hashCode` and `equals` methods differently (i.e. on `system` and `code` sub elements only).

Option a) versus option b) is a space/time tradeoff.

**Comment by lmsurpre** [comment]
To verify, I deployed with the fhir-us-core jar and hit the following endpoint: `GET [base]/ValueSet/$expand?url=http://hl7.org/fhir/us/core/ValueSet/detailed-ethnicity`

I see display values in the expansion and so I think its working as expected:
```
        "contains": [
            {
                "system": "urn:oid:2.16.840.1.113883.6.238",
                "version": "3.1.1",
                "code": "2133-7",
                "display": "Ethnicity"
            },
```
