### ISSUE TITLE
SearchUtil#getFilteredBuiltinSearchParameters uses List#contains

### ISSUE THREAD

**Issue by punktilious** [IBM/FHIR#1743]
**Describe the bug**
List#contains performs a linear search, which could have performs implications if the list is large and called repeatedly.

**To Reproduce**
See code

**Expected behavior**
A performant implementation.

**Additional context**
Review usage to see if a HashSet would be more appropriate in this context.

**Comment by lmsurpre** [comment]
See https://github.com/IBM/FHIR/issues/1625 for some related thoughts on improving performance of getting the filtered set of search parameters.

**Comment by punktilious** [comment]
LGTM. Verified through inspection.
