### ISSUE TITLE
FHIR Coverage resource focussed search returning duplicate entries

### ISSUE THREAD

**Issue by dandalavinod** [IBM/FHIR#1766]
**Describe the bug**
Duplicate resources are returned for the Coverage include search operation
**To Reproduce**
While performing a GET Rest call - {contextroot}/Coverage?beneficiary={patientid}&_include=Coverage:payor
Reponse is as below: note redacted some solution specific data

{
    "resourceType" : "Bundle",
    "id" : "a4191f5a-fb41-4d5c-a9a3-f5db955db2f4",
    "type" : "searchset",
    "total" : 1,
    "link" : [ {
      "relation" : "self",
     } ],
    "entry" : [ {
      "fullUrl" : "{contexroot}/Coverage/e17b7b4f-9e46-4629-b45c-6b075f441082",
      "resource" : {
        "resourceType" : "Coverage",
        "id" : "e17b7b4f-9e46-4629-b45c-6b075f441082",
        "meta" : {
          "versionId" : "2",
          "lastUpdated" : "2020-11-26T19:40:33.526Z",
          "profile" : [ "http://hl7.org/fhir/us/carin-bb/StructureDefinition/C4BB-Coverage" ],
          "tag" : [ {
            "system" : "http://ibm.com/fhir/cdm/StructureDefinition/ingestion-batch-id",
            "code" : "2020-11-26T19:40:21Z_AwsSBnYBFDtuiDayJ82I"
          } ]
        },
		.......... {redacted part of the response}

    }, {
      "fullUrl" : "{contexroot}/Coverage/e17b7b4f-9e46-4629-b45c-6b075f441082",
      "resource" : {
        "resourceType" : "Coverage",
        "id" : "e17b7b4f-9e46-4629-b45c-6b075f441082",
        "meta" : {
          "versionId" : "2",
          "lastUpdated" : "2020-11-26T19:40:33.526Z",
          "profile" : [ "http://hl7.org/fhir/us/carin-bb/StructureDefinition/C4BB-Coverage" ],
          "tag" : [ {
            "system" : "http://ibm.com/fhir/cdm/StructureDefinition/ingestion-batch-id",
            "code" : "2020-11-26T19:40:21Z_AwsSBnYBFDtuiDayJ82I"
          } ]
        },
        		.......... {redacted part of the response}
    } ]
  }

**Expected behavior**
Expect only one entry to be returned (to match total count) instead of duplicate entries.
Note that totalcount is 1 while there are 2 entries.

**Additional context**

**Comment by dandalavinod** [comment]
Adding the whole rest response (now includes all redacted info)
{
    "resourceType" : "Bundle",
    "id" : "f28ae3d6-0959-4cb8-8096-8b82a58e0940",
    "type" : "searchset",
    "total" : 1,
    "link" : [ {
      "relation" : "self",
      "url" : "fhirserverurl/fhir-server/api/v4/Coverage?_count=10&beneficiary=interop-fvt-1111-patient-3&_include=Coverage:payor:Organization&_include=Coverage:payor:Patient&_include=Coverage:payor:RelatedPerson&_page=1"
    } ],
    "entry" : [ {
      "fullUrl" : "fhirserverurl/fhir-server/api/v4/Coverage/e17b7b4f-9e46-4629-b45c-6b075f441082",
      "resource" : {
        "resourceType" : "Coverage",
        "id" : "e17b7b4f-9e46-4629-b45c-6b075f441082",
        "meta" : {
          "versionId" : "4",
          "lastUpdated" : "2020-12-01T14:57:00.497Z",
          "profile" : [ "http://hl7.org/fhir/us/carin-bb/StructureDefinition/C4BB-Coverage" ],
          "tag" : [ {
            "system" : "http://ibm.com/fhir/cdm/StructureDefinition/ingestion-batch-id",
            "code" : "2020-12-01T14:56:50Z_tSLOHnYB6uEUlMnZX1Wt"
          } ]
        },
        "identifier" : [ {
          "type" : {
            "coding" : [ {
              "system" : "http://terminology.hl7.org/CodeSystem/v2-0203",
              "code" : "MB",
              "display" : "Member Number"
            } ]
          },
          "system" : "https://www.xxxhealthplan.com/fhir/memberidentifier",
          "value" : "3761-703-4129-11660715187"
        } ],
        "status" : "active",
        "type" : {
          "coding" : [ {
            "system" : "http://terminology.hl7.org/CodeSystem/v3-ActCode",
            "code" : "HIP"
          } ],
          "text" : "health insurance plan policy"
        },
        "subscriberId" : "11660715187",
        "beneficiary" : {
          "reference" : "Patient/interop-fvt-1111-patient-3"
        },
        "relationship" : {
          "coding" : [ {
            "system" : "http://terminology.hl7.org/CodeSystem/subscriber-relationship",
            "code" : "self"
          } ]
        },
        "payor" : [ {
          "reference" : "Organization/interop-fvt2tenant-4196",
          "display" : "Aetna"
        } ],
        "class" : [ {
          "type" : {
            "coding" : [ {
              "system" : "http://terminology.hl7.org/CodeSystem/coverage-class",
              "code" : "group"
            } ],
            "text" : "An employee group"
          },
          "value" : "021890",
          "name" : "Acme Corporation"
        }, {
          "type" : {
            "coding" : [ {
              "system" : "http://terminology.hl7.org/CodeSystem/coverage-class",
              "code" : "plan"
            } ],
            "text" : "Plan"
          },
          "value" : "XYZ123",
          "name" : "ABC123-UPMC CONSUMER ADVA"
        } ],
        "network" : "ABC123-UPMC CONSUMER ADVA"
      }
    }, {
      "fullUrl" : "fhirserverurl/fhir-server/api/v4/Coverage/e17b7b4f-9e46-4629-b45c-6b075f441082",
      "resource" : {
        "resourceType" : "Coverage",
        "id" : "e17b7b4f-9e46-4629-b45c-6b075f441082",
        "meta" : {
          "versionId" : "4",
          "lastUpdated" : "2020-12-01T14:57:00.497Z",
          "profile" : [ "http://hl7.org/fhir/us/carin-bb/StructureDefinition/C4BB-Coverage" ],
          "tag" : [ {
            "system" : "http://ibm.com/fhir/cdm/StructureDefinition/ingestion-batch-id",
            "code" : "2020-12-01T14:56:50Z_tSLOHnYB6uEUlMnZX1Wt"
          } ]
        },
        "identifier" : [ {
          "type" : {
            "coding" : [ {
              "system" : "http://terminology.hl7.org/CodeSystem/v2-0203",
              "code" : "MB",
              "display" : "Member Number"
            } ]
          },
          "system" : "https://www.xxxhealthplan.com/fhir/memberidentifier",
          "value" : "3761-703-4129-11660715187"
        } ],
        "status" : "active",
        "type" : {
          "coding" : [ {
            "system" : "http://terminology.hl7.org/CodeSystem/v3-ActCode",
            "code" : "HIP"
          } ],
          "text" : "health insurance plan policy"
        },
        "subscriberId" : "11660715187",
        "beneficiary" : {
          "reference" : "Patient/interop-fvt-1111-patient-3"
        },
        "relationship" : {
          "coding" : [ {
            "system" : "http://terminology.hl7.org/CodeSystem/subscriber-relationship",
            "code" : "self"
          } ]
        },
        "payor" : [ {
          "reference" : "Organization/interop-fvt2tenant-4196",
          "display" : "Aetna"
        } ],
        "class" : [ {
          "type" : {
            "coding" : [ {
              "system" : "http://terminology.hl7.org/CodeSystem/coverage-class",
              "code" : "group"
            } ],
            "text" : "An employee group"
          },
          "value" : "021890",
          "name" : "Acme Corporation"
        }, {
          "type" : {
            "coding" : [ {
              "system" : "http://terminology.hl7.org/CodeSystem/coverage-class",
              "code" : "plan"
            } ],
            "text" : "Plan"
          },
          "value" : "XYZ123",
          "name" : "ABC123-UPMC CONSUMER ADVA"
        } ],
        "network" : "ABC123-UPMC CONSUMER ADVA"
      }
    }, {
      "fullUrl" : "fhirserverurl/fhir-server/api/v4/Coverage/e17b7b4f-9e46-4629-b45c-6b075f441082",
      "resource" : {
        "resourceType" : "Coverage",
        "id" : "e17b7b4f-9e46-4629-b45c-6b075f441082",
        "meta" : {
          "versionId" : "4",
          "lastUpdated" : "2020-12-01T14:57:00.497Z",
          "profile" : [ "http://hl7.org/fhir/us/carin-bb/StructureDefinition/C4BB-Coverage" ],
          "tag" : [ {
            "system" : "http://ibm.com/fhir/cdm/StructureDefinition/ingestion-batch-id",
            "code" : "2020-12-01T14:56:50Z_tSLOHnYB6uEUlMnZX1Wt"
          } ]
        },
        "identifier" : [ {
          "type" : {
            "coding" : [ {
              "system" : "http://terminology.hl7.org/CodeSystem/v2-0203",
              "code" : "MB",
              "display" : "Member Number"
            } ]
          },
          "system" : "https://www.xxxhealthplan.com/fhir/memberidentifier",
          "value" : "3761-703-4129-11660715187"
        } ],
        "status" : "active",
        "type" : {
          "coding" : [ {
            "system" : "http://terminology.hl7.org/CodeSystem/v3-ActCode",
            "code" : "HIP"
          } ],
          "text" : "health insurance plan policy"
        },
        "subscriberId" : "11660715187",
        "beneficiary" : {
          "reference" : "Patient/interop-fvt-1111-patient-3"
        },
        "relationship" : {
          "coding" : [ {
            "system" : "http://terminology.hl7.org/CodeSystem/subscriber-relationship",
            "code" : "self"
          } ]
        },
        "payor" : [ {
          "reference" : "Organization/interop-fvt2tenant-4196",
          "display" : "Aetna"
        } ],
        "class" : [ {
          "type" : {
            "coding" : [ {
              "system" : "http://terminology.hl7.org/CodeSystem/coverage-class",
              "code" : "group"
            } ],
            "text" : "An employee group"
          },
          "value" : "021890",
          "name" : "Acme Corporation"
        }, {
          "type" : {
            "coding" : [ {
              "system" : "http://terminology.hl7.org/CodeSystem/coverage-class",
              "code" : "plan"
            } ],
            "text" : "Plan"
          },
          "value" : "XYZ123",
          "name" : "ABC123-UPMC CONSUMER ADVA"
        } ],
        "network" : "ABC123-UPMC CONSUMER ADVA"
      }
    }, {
      "fullUrl" : "fhirserverurl/fhir-server/api/v4/Coverage/e17b7b4f-9e46-4629-b45c-6b075f441082",
      "resource" : {
        "resourceType" : "Coverage",
        "id" : "e17b7b4f-9e46-4629-b45c-6b075f441082",
        "meta" : {
          "versionId" : "4",
          "lastUpdated" : "2020-12-01T14:57:00.497Z",
          "profile" : [ "http://hl7.org/fhir/us/carin-bb/StructureDefinition/C4BB-Coverage" ],
          "tag" : [ {
            "system" : "http://ibm.com/fhir/cdm/StructureDefinition/ingestion-batch-id",
            "code" : "2020-12-01T14:56:50Z_tSLOHnYB6uEUlMnZX1Wt"
          } ]
        },
        "identifier" : [ {
          "type" : {
            "coding" : [ {
              "system" : "http://terminology.hl7.org/CodeSystem/v2-0203",
              "code" : "MB",
              "display" : "Member Number"
            } ]
          },
          "system" : "https://www.xxxhealthplan.com/fhir/memberidentifier",
          "value" : "3761-703-4129-11660715187"
        } ],
        "status" : "active",
        "type" : {
          "coding" : [ {
            "system" : "http://terminology.hl7.org/CodeSystem/v3-ActCode",
            "code" : "HIP"
          } ],
          "text" : "health insurance plan policy"
        },
        "subscriberId" : "11660715187",
        "beneficiary" : {
          "reference" : "Patient/interop-fvt-1111-patient-3"
        },
        "relationship" : {
          "coding" : [ {
            "system" : "http://terminology.hl7.org/CodeSystem/subscriber-relationship",
            "code" : "self"
          } ]
        },
        "payor" : [ {
          "reference" : "Organization/interop-fvt2tenant-4196",
          "display" : "Aetna"
        } ],
        "class" : [ {
          "type" : {
            "coding" : [ {
              "system" : "http://terminology.hl7.org/CodeSystem/coverage-class",
              "code" : "group"
            } ],
            "text" : "An employee group"
          },
          "value" : "021890",
          "name" : "Acme Corporation"
        }, {
          "type" : {
            "coding" : [ {
              "system" : "http://terminology.hl7.org/CodeSystem/coverage-class",
              "code" : "plan"
            } ],
            "text" : "Plan"
          },
          "value" : "XYZ123",
          "name" : "ABC123-UPMC CONSUMER ADVA"
        } ],
        "network" : "ABC123-UPMC CONSUMER ADVA"
      }
    } ]
  }

**Comment by lmsurpre** [comment]
it feels very similar to https://github.com/IBM/FHIR/issues/1557 except that in this case, we have the same Coverage resources being returned twice.  This would make sense if we were including Coverage resources in the response, but I don't think any of the _include resources should be Coverages:
```
Coverage?_count=10&beneficiary=interop-fvt-1111-patient-3&_include=Coverage:payor:Organization&_include=Coverage:payor:Patient&_include=Coverage:payor:RelatedPerson&_page=1
```

**Comment by michaelwschroeder** [comment]
It appears that the following stored procedure hasn't been updated on the system:  https://github.com/IBM/FHIR/blob/master/fhir-persistence-schema/src/main/resources/postgres/add_any_resource.sql. Likely the version on the system is not doing the delete from the _resource_token_refs table, and it's the multiple records in that table that is causing the issue.

After updating the stored procedure on the system, the existing resources will need to be re-indexed, or new resources will need to be used for testing.

**Comment by lmsurpre** [comment]
We believe there is a workaround which is to explicitly invoke the `--update-proc` action from fhir-persistence-schema after running `--update-schema`.
