### ISSUE TITLE
search using reverse chaining "_has" returned "FHIRPersistenceDataAccessException: Failure retrieving string values"

### ISSUE THREAD

**Issue by gk-zhang** [IBM/FHIR#1773]
**Describe the bug**
Dear ibm fhirserver team, 
we got a "FHIRPersistenceDataAccessException: Failure retrieving string values" error when we tried to query fhir resources using reverse chaining (_has) option.

**To Reproduce**
1.  The fhirserver was deployed using a docker-compose file. A docker container of fhirserver (version:4.5.0) and a docker container of postgresql database (version:13.0) are running. 

Assume the fhirserver can be accessed through: https://localhost:9443/fhir-server/api/v4 where we put a few million of Patients fhir resources and about 20,000 Observations. These fhir data were freshly uploaded and they are not the existing data from the previous versions (<4.5.0.).

In the Observation, there are a reference to a Patient.
```
{
    "resourceType": "Observation",
	...
    "subject": {
        "reference": "Patient/xxxxxx"
    },
    ...
}
```

2. We want to query the patients who have the Observations with code: "111111". The query should return none zero results as we have already posted such data there.

So the following curl query was used:
```
curl -k -u'fhiruser:change-password' 'https://localhost:9443/fhir-server/api/v4/Patient?_pretty=true&_has:Observation:patient:code=111111&_summary=count'
```

3. It took quite long time and returned error message:
```
{
    "resourceType": "OperationOutcome",
    "id": "c0-a8-60-3-483a0167-daef-45d8-9dc1-a045ced61e7c",
    "issue": [
        {
            "severity": "fatal",
            "code": "exception",
            "details": {
                "text": "FHIRPersistenceDataAccessException: Server error: failure retrieving count"
            }
        }
    ]
}

```

4. in the docker-compose log, I saw:
```
ibm-fhir-server_1  | [ERROR   ] Failure retrieving count. SQL=SELECT COUNT(DISTINCT R.RESOURCE_ID)  FROM Patient_LOGICAL_RESOURCES LR  JOIN Patient_RESOURCES R ON R.LOGICAL_RESOURCE_ID = LR.LOGICAL_RESOURCE_ID   AND R.RESOURCE_ID = LR.CURRENT_RESOURCE_ID   AND R.IS_DELETED = 'N'  JOIN ( SELECT CLR0.LOGICAL_ID FROM Patient_LOGICAL_RESOURCES AS CLR0 JOIN Patient_RESOURCES AS CR0 ON CR0.RESOURCE_ID = CLR0.CURRENT_RESOURCE_ID AND CR0.IS_DELETED = 'N' WHERE  EXISTS (SELECT 1 FROM Observation_TOKEN_VALUES_V AS CP1 JOIN Observation_LOGICAL_RESOURCES AS CLR1 ON CLR1.LOGICAL_RESOURCE_ID = CP1.LOGICAL_RESOURCE_ID JOIN Observation_RESOURCES AS CR1 ON CR1.RESOURCE_ID = CLR1.CURRENT_RESOURCE_ID AND CR1.IS_DELETED = 'N' JOIN Observation_TOKEN_VALUES_V  AS CP2 ON CP2.LOGICAL_RESOURCE_ID = CLR1.LOGICAL_RESOURCE_ID AND (CP2.PARAMETER_NAME_ID = 1073 AND ((CP2.TOKEN_VALUE = ?))) WHERE CP1.TOKEN_VALUE = CLR0.LOGICAL_ID AND CP1.PARAMETER_NAME_ID = 1274 AND CP1.CODE_SYSTEM_ID = 21000)) AS param0 ON LR.LOGICAL_ID = param0.LOGICAL_ID
ibm-fhir-server_1  |   searchArgs=[111111] [probeId=c0-a8-60-3-0b1e163e-5b1c-4f5e-8fca-0345db7cf08a]
ibm-fhir-server_1  | An I/O error occurred while sending to the backend.
ibm-fhir-server_1  | [ERROR   ] Server error: failure retrieving count
ibm-fhir-server_1  | Server error: failure retrieving count

```

Executing manually this SQL query in psql ("?" replaced with search args) has been tried. It took very long time (more than 30 Minutes) without end, then was cancelled by us. 

**Expected behavior**
This curl query should return the bundle with the number of patients who have the observations with the observation code "111111". Ths same query running on the hapi fhir jpaserver did work.

**Additional context**
This issue is similar to the one we reported in October: https://github.com/IBM/FHIR/issues/1623

**Comment by lmsurpre** [comment]
We just released 4.5.1 which includes a SQL change that sped up a similarly slow query on our side:  https://github.com/IBM/FHIR/issues/1705

Not positive it will help in your case, but maybe you can give it a try and let us know?

**Comment by gk-zhang** [comment]
I tested 4.5.1 and 4.5.2. Both are working with `_has` query, at least with relatively small dataset (about 780,000 Patients and 20,000 Observations). Thanks for the support!

**Comment by gk-zhang** [comment]
However, we also noticed that posting fhir transaction bundles through Rest Api to both `4.5.1` and `4.5.2` is running much slower than the previous version (<=`4.5.0`) . We did some benchmark. Digesting fhir bundles is now about 4 times slower.

**Comment by lmsurpre** [comment]
> I tested 4.5.1 and 4.5.2. Both are working with `_has` query, at least with relatively small dataset (about 780,000 Patients and 20,000 Observations). Thanks for the support!

Closing this issue based on this comment.
If you continue to have issues with the transaction bundle please open a separate issue with information / steps for reproducing
