### ISSUE TITLE
Schema case changes cause DuplicateNameException with Schema Tool

### ISSUE THREAD

**Issue by kathipavan** [IBM/FHIR#1783]
When we run --update-schema command with schema name in different case , when compared to the name provided during schema provision it is throwing exception. Detailed logs are attached below..
2020-12-03 19:33:49.601 0000001f  SEVERE .fhir.task.core.impl.TaskGroup SEQUENCE:sch_29pr.REFERENCES_SEQUENCE:1

com.ibm.db2.jcc.am.SqlSyntaxErrorException: DB2 SQL Error: SQLCODE=-601, SQLSTATE=42710, SQLERRMC=REFERENCES_SEQUENCE;SEQUENCE, DRIVER=4.26.14
com.ibm.fhir.database.utils.api.DuplicateNameException: com.ibm.db2.jcc.am.SqlSyntaxErrorException: DB2 SQL Error: SQLCODE=-601, SQLSTATE=42710, SQLERRMC=REFERENCES_SEQUENCE;SEQUENCE, DRIVER=4.26.14
        at com.ibm.fhir.database.utils.db2.Db2Translator.translate(Db2Translator.java:109) 

Thank you..

**Comment by prb112** [comment]
Thanks @kathipavan
