### ISSUE TITLE
Docker image `ibmcom/ibm-fhir-schematool:4.5.1` contains `fhir-persistence-schema-4.5.1-cli.jar` and `fhir-persistence-schema-4.5.0-SNAPSHOT-cli.jar`

### ISSUE THREAD

**Issue by holger-stenzhorn** [IBM/FHIR#1784]
**Describe the bug**
The Docker image `ibmcom/ibm-fhir-schematool:4.5.1` contains both `fhir-persistence-schema-4.5.1-cli.jar` as well as `fhir-persistence-schema-4.5.0-SNAPSHOT-cli.jar`.

**To Reproduce**
Simply run the Docker image in debug mode:
```sh
holger@homer:~$ docker run ibmcom/ibm-fhir-schematool:4.5.1 --tool.behavior=debug
jq: error: Could not open file /opt/schematool/workarea/persistence.json: No such file or directory
The tool behavior being executed is debug
run.sh - [INFO]: 2020-12-03_15:24:39 - The files included with the tool are:
total 78M
drwxr-xr-x 1 fhirschemaadmin fhirschemaadmin 4.0K Dec  2 13:33 .
drwxr-xr-x 1 root            root            4.0K Dec  2 13:33 ..
-rwxr-xr-x 1 fhirschemaadmin fhirschemaadmin  37M Dec  2 13:29 fhir-persistence-schema-4.5.0-SNAPSHOT-cli.jar
-rwxr-xr-x 1 fhirschemaadmin fhirschemaadmin  37M Dec  2 13:33 fhir-persistence-schema-4.5.1-cli.jar
drwxr-xr-x 2 fhirschemaadmin fhirschemaadmin 4.0K Dec  2 13:33 home
-rwxr-xr-x 1 fhirschemaadmin fhirschemaadmin 3.8M Dec  2 13:33 jq
-rwxr-xr-x 1 fhirschemaadmin fhirschemaadmin  20K Nov 23 20:01 run.sh
drwxr-xr-x 1 fhirschemaadmin fhirschemaadmin 4.0K Dec  2 13:29 workarea
The OpenSSL version is:
OpenSSL 1.1.1g FIPS  21 Apr 2020
```

**Expected behavior**
The Docker image should contain `fhir-persistence-schema-4.5.1-cli.jar` but *not* `fhir-persistence-schema-4.5.0-SNAPSHOT-cli.jar`.

**Additional context**
n/a

**Comment by prb112** [comment]
it's already fixed, thanks, please pull the latest

**Comment by prb112** [comment]
P.S. Thank you for opening, we hit this last night.

**Comment by prb112** [comment]
https://hub.docker.com/layers/ibmcom/ibm-fhir-schematool/latest/images/sha256-dfd89c37805d8738280112e4e4ed726b075a03bc214fe6bca741aeaa202f723b?context=explore

**Comment by prb112** [comment]
sorry - I'll leave in review/qa for you to confirm

**Comment by holger-stenzhorn** [comment]
Yes, now it is correct. Thanks!

Just one tiny question: In the `Dockerfile` it says `ARG FHIR_VERSION=4.5.0`. Is that correct or shouldn't it read `ARG FHIR_VERSION=4.5.1`?

**Comment by prb112** [comment]
Great - question - I noticed that too, but that's the default value, it's actually 4.5.1 as you can see in the label.  Arg is only a build time input, and I set a default.  When we do the build we set the current release number.
