### ISSUE TITLE
fhir-audit: Ensure HOSTNAME is obtained correctly and consistently

### ISSUE THREAD

**Issue by punktilious** [IBM/FHIR#1805]
I know it's not part of the change, but is this the best way to get the name of the host? Do we ensure that HOSTNAME is part of the environment?  On Windows, COMPUTERNAME might be more appropriate. 

_Originally posted by @punktilious in https://github.com/IBM/FHIR/pull/1804#r537621534_

This calls for a utility function which then should be used everywhere we need the hostname.

Needs to work correctly in containers as well as on Mac, Linux and Windows.

**Comment by lmsurpre** [comment]
Is this hostname expected to be the hostname of the node running this particular instance of the fhir server, or is it the hostname that the requestors use to address the fhir server?
If the former, there might not be anywhere else we actually need this.
If the latter, we should get this from the FHIRRequestContext which has logic for setting this value from a trusted header.

**Comment by prb112** [comment]
This was reference to audit, and is for the server serving the request.
