### ISSUE TITLE
FHIR primitive static factory helpers should be more resilient to nulls

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#1814]
**Is your feature request related to a problem? Please describe.**
When populating an object from a different source, its convenient to use the static factory methods like Code.of() like the following
```
Coding.builder()
    .code(Code.of(myObj.getMyCode()))
    .display(string("Pregnant"))
    .build()
```

However, if that source data can contain nulls, then today this breaks on the `Code.of(null)` with the following:
```
java.lang.IllegalStateException: ele-1: All FHIR elements must have a @value or children
```

This despite the following code working with no issue:
```
Coding.builder()
    .code(null)
    .display(string("Pregnant"))
    .build()
```

**Describe the solution you'd like**
`Code.of(null)` and similar convience functions should return null if null is passed in.  Instead of trying to create a privitive FHIR object with no value which is guaranteed to fail with `ele-1`.

**Describe alternatives you've considered**
Add javadoc to explain it will throw if you pass a null.

**Comment by lmsurpre** [comment]
Team decision:
1. update javadoc to say that the arguments to the factory methods must be non-null
2. add Object.requireNonNull to all the generated factory methods (with the name of the argument so we know what was null)

**Comment by michaelwschroeder** [comment]
I have validated the javadoc and the addition of Object.requireNotNull() method calls via visual inspection of classes in the fhir-model project and have validated that when attempting to pass a null value to these factory methods a NullPointerException is thrown indicating the name of the argument containing the null value.
