### ISSUE TITLE
Batch bundle request should lead to one audit event per entry

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#1816]
**Is your feature request related to a problem? Please describe.**
In https://github.com/IBM/FHIR/pull/1813, we introduce a change to start logging batch/transaction bundle requests via an audit event with action "E".
During review, I recommended that we handle batch bundles differently from transaction bundles.

For batch bundles, because some entries can succeed while others fail, I think we should create an audit event for each individual entry within the request.

**Describe the solution you'd like**
Each entry from within the batch should result in its own audit event.

For performance reasons, we must either:
A. fire those off asyncronously as we process the entries; or
B. track them as we process the bundle and then send them all at the end

**Additional context**
I think we probably still want to create an audit event with action "E" for the bundle request itself.
If so, then maybe it would make sense to have the multiple audit events for transaction bundles too...we could just wait to set the success/failure status of them until the very end. 

Also note that https://github.com/IBM/FHIR/issues/1627 could affect the way we process batch bundles that contain only reads (reads, vreads, history, or search).

**Comment by lmsurpre** [comment]
could be done at same time as #1746

**Comment by lmsurpre** [comment]
I tested this by submitting a bundle with 4 entries...each one a PUT.

In one case, I submitted 4 PUTs of the same resource at once.  This resulted in 1 successful entry and 3 entries that failed with "Encountered version id mismatch while inserting Resource" with a status of 409 (Conflict) which is expected.

In the audit log, I saw one event for each of the four entries (and none for the actual bundle request).
Unfortunately, all 4 event seemed to be nearly identical:
The had an action code of "E" and outcome of "0" (success).

Additionally, they each have a detail field with a base64Binary "FHIR Context" object with content like the following (after decoding):
```
{
    "request_unique_id": "aef1bb89-b7fb-49c8-826e-593be4480675",
    "action": "U",
    "start_time": "2022-03-02 21:40:00.541",
    "end_time": "2022-03-02 21:40:01.702",
    "api_parameters": {
        "request": "/fhir-server/api/v4/",
        "request_status": 200
    },
    "batch": {
        "resources_read": 0,
        "resources_created": 0,
        "resources_updated": 1,
        "resources_deleted": 0,
        "resources_executed": 0
    },
    "event_type": "fhir-bundle",
    "description": "FHIR Bundle Batch request",
    "location": "172.17.163.19/172-17-163-19.public-crc35r7h2w0gu06tdqghl0.kube-system.svc.cluster.local"
}
```

I would have liked to see some info about the specific bundle entry in here somewhere.
But more importantly, I think we need to indicate the success or failure of each entry separately (which is kind of the point of having an audit event for each entry).

**Comment by lmsurpre** [comment]
Dag opened a related issue for the fact that batched PUT entries don't align with what we're doing for standalone PUTs:  #3454

**Comment by d0roppe** [comment]
this now has more information, and information with errors example
```
{
    "request_unique_id": "691763fd-7467-452e-a334-6e9faaa2a355",
    "action": "U",
    "start_time": "2022-03-22 19:13:04.605",
    "end_time": "2022-03-22 19:13:04.970",
    "api_parameters": {
        "request": "/fhir-server/api/v4/Patient/a-sniff-test-check-P1",
        "request_status": 409
    },
    "data": {
        "resource_type": "OperationOutcome",
        "id": "c0-a8-1-d7-94d8dff5-4657-457f-96e9-822bf9a5bad8"
    },
    "batch": {
        "resources_read": 0,
        "resources_created": 0,
        "resources_updated": 1,
        "resources_deleted": 0,
        "resources_executed": 0
    },
    "event_type": "fhir-bundle",
    "description": "FHIR Bundle Batch request",
    "location": "127.0.0.1/localhost"
}
```
Closing issue
