### ISSUE TITLE
Set more specific batch bundle action in audit event when possible

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#1817]
**Is your feature request related to a problem? Please describe.**
In #1813, we introduce a change to start logging batch/transaction bundle requests via an audit event with action "E".
However, for bundles which are all reads, all creates, all updates, or all deletes, we should be able to be a little more specific.

**Describe the solution you'd like**
If the bundle is all reads, set "R".
If the bundle is all creates, set "C".
If the bundles is all updates, set "U".
If the bundle is all deletes, set "D".
Else, set "E".

**Describe alternatives you've considered**
If we decided to log each individual entry for both batch *and* transaction bundles (see #1816), then this task becomes a lot less important, because we would already have the info from each individual entry from within the bundle.

**Additional context**
Currently, we track how many reads, creates, and updates we have for each bundle.  But for some reason we don't track how many deletes.  That should be added under this work item so that we can set the action to "D" when appropriate.

**Comment by lmsurpre** [comment]
Could be done together with #1816

**Comment by d0roppe** [comment]
Verified the different "action" tags of "R", "C", "U". "D", and "E" are in the audit record.  Noting that a PUT no matter the return code (201, or 200) is marked as an Update.  Will create a new issue for this in case we want to address that.
