### ISSUE TITLE
Search parameter filtering fails for search parameter which has multiple base resource types

### ISSUE THREAD

**Issue by michaelwschroeder** [IBM/FHIR#1831]
**Describe the bug**
When filtering search parameters, we filter based on resource type. However, rather than using the resource type specified on the search, we're grabbing the first element in the SearchParameter.base field. So if a search parameter has more than one base and the first base element does not match the resource type specified in the search, then we filter on the wrong resource type and can possibly fail. 

**To Reproduce**
1. In fhir-server-config.json, configure a search parameter that has multiple base resource types (for example the `medication` search parameter) to be valid on only one of those resource types (for example, `MedicationRequest`).
2. Execute a search request using the configured search parameter against the configured resource type: `MedicationRequest?medication=xxx`

**Expected behavior**
The search should run successfully.

**Additional context**

**Comment by michaelwschroeder** [comment]
This issue is related to JIRA issue https://jsw.ibm.com/browse/WHCMSINTOP-238

**Comment by lmsurpre** [comment]
I submitted a MedicationRequest example from US Core that has the following:
```
  "medicationReference" : {
    "reference" : "#med2",
    "display" : "Nizatidine 15 MG/ML Oral Solution [Axid]"
  },
```

Then I submitted a request for `[base]/MedicationRequest?medication=%23med2` and it successfully returned the resource.
