### ISSUE TITLE
Support --schema-name option for --refresh-tenants

### ISSUE THREAD

**Issue by punktilious** [IBM/FHIR#1847]
When running the --refresh-tenants schema update command:

```
java -jar ./fhir-persistence-schema-4.5.3-cli.jar --prop-file db2.prop --refresh-tenants 
```

the current implementation will iterate over all the tenants. If there are multiple schemas and one of the schemas has not yet been upgraded, this command will fail.

```
No partition information found for table: FHIRDATA.COMMON_TOKEN_VALUES
com.ibm.fhir.database.utils.api.DataAccessException: No partition information found for table: FHIRDATA.COMMON_TOKEN_VALUES
        at com.ibm.fhir.database.utils.db2.Db2Adapter.addNewTenantPartitions(Db2Adapter.java:223)
        at com.ibm.fhir.database.utils.db2.Db2Adapter.addNewTenantPartitions(Db2Adapter.java:196)
        at com.ibm.fhir.database.utils.model.PhysicalDataModel.addNewTenantPartitions(PhysicalDataModel.java:276)
        at com.ibm.fhir.schema.app.Main.refreshTenants(Main.java:809)
        at com.ibm.fhir.schema.app.Main.process(Main.java:1505)
        at com.ibm.fhir.schema.app.Main.main(Main.java:1572)
```

The command currently ignores any --schema-name value.

Desired behavior:

If a --schema-name value is given, then limit the list of tenants being processed to just that schema.

**Comment by lmsurpre** [comment]
If we update `--refresh-tenants` to work with --schema-name, then I think we should just combine this action with `--update-schema` which already works that way.

`--refresh-tenants` should already be idempotent and combining it with `update-schema` should be one less thing for the end users to worry about during update / schema migration.

**Comment by tbieste** [comment]
Will attempt these steps to recreate:

1. 4.4.2:  Create/update schema A and B
2. 4.4.2:  Allocate tenant A to schema A, and tenant B to schema B
3. 4.5.3:  Update schema A
4. 4.5.3:  Refresh schemas --schema-name A

With 4.6.0, the --schema-name A should limit refresh to just schema A.

**Comment by tbieste** [comment]
Verified that if a --schema-name value is given, then limit the list of tenants being processed by --refresh-tenants to just that schema.
