### ISSUE TITLE
Update AuthZ interceptor to validate search requests and to convert non-compartment searches to compartment searches

### ISSUE THREAD

**Issue by michaelwschroeder** [IBM/FHIR#1849]
**Is your feature request related to a problem? Please describe.**
Currently, the AuthZ interceptor does not fully validate search requests, leading to the possibility of inferring data about patient that caller does not have access to.

For example, a search request with specific parameters designed to look for "Observations for patient 1234 with a code of abc", then looking for whether the search result is empty vs receiving a 403.

**Describe the solution you'd like**
The AuthZ interceptor's `beforeSearch()` method should do the following validation/processing of search requests:

If compartment search:
1. if not a Patient compartment search: fail with 403 error
2. else if Patient compartment search, but compartment ID does not match patient ID from token: fail with 403 error
3. else if Patient compartment search, but resource type being searched is not member of Patient compartment: fail with 400 error
4. else valid Patient compartment search: do nothing, allow search to continue

If not compartment search:
1. if resource type being searched is Patient: fail with 403 error
2. else if resource type being searched is not member of Patient compartment: do nothing, allow search to continue
3. else if resource type being searched is a member of Patient compartment: convert the search to a Patient compartment search of the caller's current patient context by adding the necessary inclusionCriteria search parameters to the searchContext

**Describe alternatives you've considered**
1. Turn 410 response code into a 404 response code
2. For search, return 200 with an empty bundle instead of 403
3. Disable Patient search altogether
4. ?

**Acceptance Criteria**
At least one acceptance criteria is included.

1.  
    GIVEN a compartment search request that is not a Patient compartment search
    WHEN the search request is executed
    THEN return a 403 FORBIDDEN http response
2.  
    GIVEN a compartment search request that is a Patient compartment search AND compartment ID does not match patient ID that caller has access to
    WHEN the search request is executed
    THEN return a 403 FORBIDDEN http response
3.  
    GIVEN a compartment search request that is a Patient compartment search AND compartment ID matches patient ID the caller has access to, but resource type being searched is not a member of the Patient compartment
    WHEN the search request is executed
    THEN return a 400 BAD REQUEST http response
4.  
    GIVEN a compartment search request that is a Patient compartment search AND compartment ID matches patient ID that caller has access to AND resource type being searched is a member of the Patient compartment
    WHEN the search request is executed
    THEN return a 200 http response with search results
5.  
    GIVEN a non-compartment search request that is a Patient search
    WHEN the search request is executed
    THEN return a 403 FORBIDDEN http response
6.  
    GIVEN a non-compartment search request AND the resource type being searched is not a member of the Patient compartment
    WHEN the search request is executed
    THEN return a 200 http response with search results
7.  
    GIVEN a non-compartment search request AND the resource type being searched is a member of the Patient compartment
    WHEN the search request is executed
    THEN return a 200 http response with search results for a Patient compartment search of the requested search type where the compartment ID is the patient ID the caller has access to

**Additional context**
We also discussed whether or not there is an issue with leaking similar information when a user performs a read/vread/history/delete operation against a given resource.
For example, when an already deleted resource is read, we return a 410, whereas a nonexistent resource read returns a 404. In this way, you could theoretically infer whether some given resource existed on the system or not.

We've already addressed this concern for the patient resource via https://github.com/IBM/FHIR/pull/1809 which should be treated like a patient identifier, but we don't believe other resource ids require the same degree of protection.

See https://chat.fhir.org/#narrow/stream/179166-implementers/topic/Patient.20Resource.20ID.20and.20HIPAA/near/219427535 for a related community discussion.

**Comment by lmsurpre** [comment]
I verified the issue by first attempting a broad search like `GET [host]/Observation` on a server configured with the previous fhir-smart jar.  This resulted in a 403 as expected, indicating that the user didn't have access to one or more resources in the result set.

Then I updated the deployment with a `fhir-smart` jar that has these changes and ran the same search.  This time it returned an empty result set.  I double-checked the logs and confirmed that the search was now including a parameter that scopes the search to this patient.

Note:  I also added the following to my fhir-server-config.json so that the deployment can take advantage of a the storedCompartmentParam added in [IBM FHIR Server 4.5.1](https://github.com/IBM/FHIR/releases/4.5.1):
```
"search": {
          "useStoredCompartmentParam": true
        },
```
and confirmed that the search now uses a single compartment parameter even for resources that have multiple inclusion criteria like Observation.
