### ISSUE TITLE
Use or remove requestProperties from the FHIRRestHelper doX methods

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#1852]
The requestProperties argument to our various FHIRRestHelper methods has some interesting history. Back in the old days we didn't have this anywhere. Then, for a specific solution, they wanted a way to pass different HTTP header values to different entries within the same batch/transaction bundle request. We were sort of forced to accommodate that and we did so by:

1. introducing this requestProperties parameter all over
2. defining an extension that clients could set at the batch/transaction bundle entry level for setting/overriding specific "header" values
3. adding logic to set the requestProperties in the calls to the various doX methods from the value of these extensions when we process the batch/transaction

When we went to open source, I think we lost parts 2 and 3 of this since it was deemed specific to that one solution. But the requestProperties lingers in our FHIRRestHelper methods.
I don't think they ever get set at all at this point. Assuming that right, we should either
A. bring back that bundle-entry HTTP headers feature; or
B. remove requestProperties from all over

I do think it was a nice feature, but my concern with A is that we are doing some header processing in the FHIRRestServletFilter and putting that information into the FHIRRequestContext.  That means that, unless we alter the FHIRRequestContext for each entry within the bundle, there will be some headers that cannot be overridden in this way.
Therefore, I'm leaning toward option B.

**Comment by JohnTimm** [comment]
Discussed this with Lee. Although we are currently not using this feature we could considering bringing it back in the future if we find a new use case that requires it.
