### ISSUE TITLE
Create Schema to track Performance run data per test.

### ISSUE THREAD

**Issue by d0roppe** [IBM/FHIR#1861]
**Is your feature request related to a problem? Please describe.**
Need to create a Schema that can be used to store test based performance run data and allow for easy comparison between different runs and also tracking over time.
**Describe the solution you'd like**
Create a schema with table and proper columns to hold the data. 
**Describe alternatives you've considered**

**Acceptance Criteria**
At least one acceptance criteria is included.

1.  
Be able to search the schema for a test case or test run and get the data pulled out. 

**Additional context**

**Comment by prb112** [comment]
I think @d0roppe mentioned this is in progress.

**Comment by d0roppe** [comment]
Created Schema in Postgres DB
Created table in the schema for a sample on what to store

**Comment by d0roppe** [comment]
Schema created and data added

**Comment by d0roppe** [comment]
Here is the DDL used:
CREATE SCHEMA schema;

CREATE TABLE schema.table
(
    name text NOT NULL,
    rundate time without time zone NOT NULL,
    count bigint NOT NULL,
    average double precision NOT NULL,
    environment text NOT NULL,
    PRIMARY KEY (name, rundate, environment)
);
