### ISSUE TITLE
Document validation of resource types in fhir-server-config.json with whole-system search

### ISSUE THREAD

**Issue by michaelwschroeder** [IBM/FHIR#1874]
**Is your feature request related to a problem? Please describe.**
We need to document what must be specified in fhir-server-config.json in order for whole-system search to be allowed.

**Describe the solution you'd like**
Documentation should include an explanation of what is checked and example configurations.

**Describe alternatives you've considered**

**Acceptance Criteria**
At least one acceptance criteria is included.

1.  
  GIVEN [a precondition]
    AND [another precondition] WHEN [test step]
    AND [test step]
    THEN [verification step]
    AND [verification step]

**Additional context**

**Comment by lmsurpre** [comment]
doc-only change; docs were reviewed
