### ISSUE TITLE
SMART AuthzPolicyEnforcement should allow read access to Provenance resources that target Patient-compartment resources

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#1881]
The current AuthzPolicyEnforcement implementation in `fhir-smart` is fairly generic / naive.  It uses whether a resource belongs to the Patient compartment of the "in-context" patient to control access.

This works well for most resource types, but not for the Provenance resource.
Provenance is a patient-compartment resource that only belongs to the patient compartment when its target is a Patient.
However, the target is supposed to be whichever resource the Provenance is for, and so the Provenance of a Patient's Observations/Conditions/Encounters/etc will actually *not* be in that Patient's compartment.

However, both the US Core and DaVinci PDEX implementation Guides understandably define Provenance as an allowed revInclude parameter for most of the other resources types and they both offer guidance that indicates it should be available to members/patients:
* https://hl7.org/fhir/us/core/basic-provenance.html
* http://hl7.org/fhir/us/davinci-pdex/STU1/HandlingDataProvenance.html

To accomplish this, I propose that we augment the AuthzPolicyEnforcementPersistenceInterceptor `enforce` method such that:
* if the resource in question is a Provenance resource;
* and that provenance resource targets a resource type that is a Patient-compartment resource type;
* then that Provenance resource type will be treated as if it were in that Patient's compartment;
* and access will be granted/denied accordingly

Open question:  should we allow read access to Provenance information about resources that are NOT patient compartment resources (like Practitioners, Organizations, etc?)

**Comment by lmsurpre** [comment]
neither US Core nor DaVinci PDEX specify Provenance:target as a valid revInclude target for Practitioner or Organization, so I’m gonna take that as a cue to not allow access to Provenance resources which target non-patient-compartment resources

**Comment by kmbarton423** [comment]
Tested in fhir-devtest environment using latest code level.
patient access api is getting a 403 forbidden attempting the following:
   Observation?subject=Patient/KMB-1881-Patient&_revinclude=Provenance:target
expected two Observations and one associated Provenance to be returned

log shows:
2021-02-12 16:38:18.693 wh-cmsiop-fhir1-patient-access-0000-64699bc7f5-47rhc fhir FINE read permission for 'Observation/KMB-1881a-Observation' is granted via scope [patient/*.read] with patient context 'KMB-1881-Patient'
2021-02-12 16:38:18.695 wh-cmsiop-fhir1-patient-access-0000-64699bc7f5-47rhc fhir FINE read permission for 'Observation/KMB-1881b-Observation' is granted via scope [patient/*.read] with patient context 'KMB-1881-Patient'
2021-02-12 16:38:18.706 wh-cmsiop-fhir1-patient-access-0000-64699bc7f5-47rhc fhir FINE read permission for 'Provenance/Observation1881b' is not granted by any of the provided scopes: [patient/*.read] with context id(s): [KMB-1881-Patient]

**Comment by lmsurpre** [comment]
I checked the test environment and found that it wasn't running the latest version for the `fhir-smart` module...please check again.

**Comment by kmbarton423** [comment]
Re-tested in fhir-devtest environment now running the latest version for the fhir-smart module.
Confirmed a variety of patient compartment resources and their associated Provenance were accessible via the patient access api.
Also confirmed that the non-patient compartment resources were accessible but their associated Provenance was not.
