### ISSUE TITLE
Docker image - server fails to initialise correctly

### ISSUE THREAD

**Issue by searjeant** [IBM/FHIR#1888]
The Docker image pulled from ibmcom/ibm-fhir-server fails to start correctly. 

**To Reproduce**
1. Pull the Docker image from https://hub.docker.com/r/ibmcom/ibm-fhir-server
2. Ensure Docker Desktop is running (I am using Windows 10)
2. In a bash shell in WSL2, start an instance of the image using `docker run -p9443:9443 ibmcom/ibm-fhir-server`
4. Once the server appears to have started, use the recommended health-check: `curl -k -i -u 'fhiruser:change-password' 'https://localhost:9443/fhir-server/api/v4/$healthcheck'`
5. Observe the console output.

**Expected behavior**
FHIR server startup, followed by a successful health check.

**Observations**
The console output suggests an issue with the embedded Derby database:

```
[ERROR   ] Encountered an exception while bootstrapping the FHIR database
java.sql.SQLNonTransientConnectionException: No current connection.
```
And the servlet context fails to initialise:

```
[ERROR   ] SRVE0283E: Exception caught while initializing context: java.lang.RuntimeException: Encountered an exception while initializing the servlet context.
        at com.ibm.fhir.server.listener.FHIRServletContextListener.contextInitialized(FHIRServletContextListener.java:208)
        at com.ibm.ws.webcontainer.webapp.WebApp.notifyServletContextCreated(WebApp.java:2433)
```

**Additional context**
My environment:
Windows 10 Professional Edition
Version	10.0.18363 Build 18363
Docker Desktop: v3.1.0
Docker Engine: v20.10.2
Using the WSL2 integration.

I have saved a complete copy of the console output in a public gist: https://gist.github.com/searjeant/1ba53621abe92cc783eec0a9a3969574

I did read (and re-read) the configuration documentation on the Docker Hub page, but I wanted to ensure I could start the default container first, before making any of the changes described on that page.  

Apologies if I have missed something obvious - I'd appreciate a hint.

**Comment by lmsurpre** [comment]
Can you please try setting the following environment variable?  `FHIR_TRANSACTION_MANAGER=120s`

What we've seen from some folks is that the derby bootstrapping is timing out.
We really should move that bootstrapping step to the image startup so that its not bound to the same transaction timeout as normal requests are, but we havn't gotten to that yet.

If this doesn't help, then let us know and we can look at the logs.

**Comment by prb112** [comment]
@searjeant did Lee's comment address your issue?

**Comment by danarteaga** [comment]
I am getting the exact same issue on Windows 10. Setting FHIR_TRANSACTION_MANAGER=240s did not fix the issue.

**Comment by lmsurpre** [comment]
My apologies.  The variable name is `FHIR_TRANSACTION_MANAGER_TIMEOUT` and not `FHIR_TRANSACTION_MANAGER`.
I can force a very similar stack trace on my MacBook by launching like this:
`docker run -p 9443:9443 -e FHIR_TRANSACTION_MANAGER_TIMEOUT=10s ibmcom/ibm-fhir-server:4.5.4`
and so I really think this is the issue.

**Comment by danarteaga** [comment]
Thanks for the quick response - unfortunately I am still receiving the same error when FHIR_TRANSACTION_MANAGER_TIMEOUT is set to 240s.

**Comment by prb112** [comment]
@danarteaga can you post an updated log? the reference in gist is without running with the FHIR_TRANSACTION_MANAGER_TIMEOUT=240s (as shown in the commandline)

**Comment by danarteaga** [comment]
Ahh, setting FHIR_TRANSACTION_MANAGER_TIMEOUT=600s did the trick. Just for your information, here is my hardware setup:

Processor	Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, 2112 Mhz, 4 Cores
RAM         	16.0 GB

Thank you for your help with this.

**Comment by prb112** [comment]
Right, it's the allocated resources in your Docker setup.  You can cap the total cores and available memory.

**Comment by prb112** [comment]
@danarteaga @searjeant I hope all is well.  If there is any followup, we're happy to re-open. 

Keep asking questions/opening bugs, we'll work on it.
