### ISSUE TITLE
Move db bootstrapping out of server startup

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#1897]
**Is your feature request related to a problem? Please describe.**
We've had a few issues where users report that the default docker container is failing to start due to a timeout that occurs during bootstrapping of the derby databases. See https://github.com/IBM/FHIR/issues/1554 and https://github.com/IBM/FHIR/issues/1888

The problem is that the bootstrapping code inherits the global transaction timeout (120s by default) that we use for serving user requests.  At the very least, the bootstrapping should have a different transaction timeout.

We've made it easy(ish) to get past the issue by setting the default transaction timeout via an env var (#1666).
However, the only reason we have the bootstrapping code to begin with is to make it dead simple to get our server up and running, so this kind of defeats the purpose.

**Describe the solution you'd like**
1. Database bootstrapping should be moved to a bash script
2. Package this bootstrapping script in our zip installer (and thus our docker image as well)
3. Write a custom entrypoint for the docker image to make it simple to:
  * control whether or not bootstrapping happens
  * specify which dbs are bootstrapped, as per #1408

Initially we can just focus on derby, but I think it would make sense to extend that behavior to Db2 and PostgreSQL as well.

**Describe alternatives you've considered**
Either:
A. never perform bootstrapping during image startup; or
B. keep bootstrapping scoped to derby and force the use of the schema-tool cli and/or image for the 'real' dbs.

**Acceptance Criteria**
At least one acceptance criteria is included.

1.  
  GIVEN a global transaction timeout of 60s
    AND derby bootstrapping enabled
    WHEN a user runs `docker run -p9443:9443 ibmcom/ibm-fhir-server`
    THEN the server starts successfully
    AND has a functional embedded derby database

To confirm it:
1. build the project:  `mvn clean install -f fhir-parent -DskipTests`
2. build the docker image `docker build fhir-install -t ibmcom/ibm-fhir-server`
3. run the docker image, ask it to use the bootstrap DB, and set a lower transaction timeout

`docker run -e BOOTSTRAP_DB=true -e FHIR_TRANSACTION_MANAGER_TIMEOUT=60s ibmcom/ibm-fhir-server`

**Additional context**

**Comment by tbieste** [comment]
Could this be simplified to just bootstrap an embedded derby database? (With just minimal ENVVARs to enable it.)  Then all other database bootstrapping is done via the schema-tool cli.  That lets the user give it a quick try via just docker run, but any "real" usage must use the schema tool to set up the DB first.

**Comment by kmbarton423** [comment]
Did the following on my Mac machine:
1. mvn clean install -f fhir-parent -DskipTests
2. docker build fhir-install -t ibmcom/ibm-fhir-server
3. docker run -p 9443:9443 -e BOOTSTRAP_DB=true -e FHIR_TRANSACTION_MANAGER_TIMEOUT=60s ibmcom/ibm-fhir-server

Once fhir server was up and running, confirmed derby database usage:
1. $healthcheck
2. PUT to create a Patient
3. GET to search on Patients
