### ISSUE TITLE
Migrate from Bintray

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#1904]
JFrog is sunsetting their bintray offering. 
A replacement is needed

Consider migration to Artifactory or GitHub Packages.

Must complete by May 2021.

**Comment by lmsurpre** [comment]
They have some "brown-outs" coming in April to help remind folks.  We should try to be off bintray by April 1.

**Comment by lmsurpre** [comment]
Currently, we're leaning toward moving shop over to maven central.


Question:  Do we migrate our historical artifacts as well?  It would be nice...

Proposal A:
* Write a script to copy the release artifacts from bintray and upload them to the corresponding Release page in github

Proposal B:
* Announce that bintray is going away and we will NOT be migrating any of the resources

**Comment by rubberduck203** [comment]
I saw in the PR @prb112 mentioned releasing 4.7.0 to Maven Central.
I was curious if you think we'll see that before JFrog shuts down Bintray.

**Comment by prb112** [comment]
> I saw in the PR @prb112 mentioned releasing 4.7.0 to Maven Central.
> I was curious if you think we'll see that before JFrog shuts down Bintray.

Yes - hold while we got through a QA/release process.

**Comment by rubberduck203** [comment]
Excellent news! Thank you very much for the quick response and all the work that goes into this project.

**Comment by prb112** [comment]
Our pleasure... the files are actually on Sonatype OSSRH now.  We're just waiting on the sync to Maven Central to be configured.

**Comment by prb112** [comment]
All Deployed.
