### ISSUE TITLE
PostgreSQL poor search performance with multiple search parameters on a Compartment Search

### ISSUE THREAD

**Issue by punktilious** [IBM/FHIR#1911]
**Describe the bug**
For PostgreSQL: A FHIR search query with multiple parameters can perform poorly if the number of tables involved exceeds the from_collapse_limit/join_collapse_limit defaults (8). 

**To Reproduce**

Consider the following compartment query:
```
<base>/Patient/test-patient-555/DiagnosticReport?status=final&category=LAB&code=57698-3
```

After bind-variable substitution, the resulting count query looks something like this:

```
SELECT COUNT(DISTINCT R.LOGICAL_RESOURCE_ID)
  FROM FHIRDATA.DiagnosticReport_LOGICAL_RESOURCES LR
  JOIN FHIRDATA.DiagnosticReport_RESOURCES R
    ON R.RESOURCE_ID = LR.CURRENT_RESOURCE_ID
   AND R.IS_DELETED = 'N'
  JOIN FHIRDATA.DiagnosticReport_TOKEN_VALUES_V  AS param0
    ON (param0.PARAMETER_NAME_ID = 2009
   AND ((param0.TOKEN_VALUE = 'final')))
   AND LR.LOGICAL_RESOURCE_ID = param0.LOGICAL_RESOURCE_ID
  JOIN FHIRDATA.DiagnosticReport_TOKEN_VALUES_V  AS param1
    ON (param1.PARAMETER_NAME_ID = 6001
   AND ((param1.TOKEN_VALUE = 'LAB')))
   AND LR.LOGICAL_RESOURCE_ID = param1.LOGICAL_RESOURCE_ID
  JOIN FHIRDATA.DiagnosticReport_TOKEN_VALUES_V  AS param2
    ON (param2.PARAMETER_NAME_ID = 6005
   AND ((param2.TOKEN_VALUE = '57698-3')))
   AND LR.LOGICAL_RESOURCE_ID = param2.LOGICAL_RESOURCE_ID
  JOIN FHIRDATA.DiagnosticReport_TOKEN_VALUES_V  AS param3
    ON ((param3.PARAMETER_NAME_ID = 2582160
   AND param3.TOKEN_VALUE = 'test-patient-555'
   AND param3.CODE_SYSTEM_ID = 341713292))
   AND LR.LOGICAL_RESOURCE_ID = param3.LOGICAL_RESOURCE_ID;
```

Each <resourceType>_TOKEN_VALUES_V is actually a view of a join between two tables, so the overall table count exceeds 8. In this case the predicate to filter on the patient compartment (for 'test-patient-555') is the most selective and should be first in the execution plan. However, because there are more than 8 tables coming before it in the query, the optimizer doesn't get a chance to reorder this. The resulting (bad) plan takes over 500 seconds.

To address this, the following values will be made configurable for search queries, for example:

```
SET from_collapse_limit=12;
SET join_collapse_limit=12;
```

A separate issue #1912 will write the query to ensure that the compartment param is added toward the start of the query to ensure it is always considered by the optimizer.

**Expected behavior**
Better performance for compartment-based searches.

**Comment by punktilious** [comment]
The from_collapse_limit and join_collapse_limit are now set to 16 before executing search queries. The values can be tuned if necessary. See updates to the user and performance guides.

The resulting performance is much better. An example query previously taking over 2 minutes now takes under 400ms.

**Comment by d0roppe** [comment]
verified the 2 options set in the fhir-server-config.json.  did not see any issues with the setting. closing issue
