### ISSUE TITLE
For compartment search, order inclusion criteria search parameters first in search parameter list

### ISSUE THREAD

**Issue by michaelwschroeder** [IBM/FHIR#1912]
**Describe the bug**
Inclusion criteria search parameters generated for a compartment search are placed at the end of the list of search parameters for a compartment search request. For best performance, they should be placed first in the list.

**To Reproduce**

**Expected behavior**

**Additional context**
What is actually happening is that the query optimizer is not generating the best plan for the query that is generated when the compartment search parameters are placed at the end of the search parameter list. Moving them to the front of the list produces a query that the optimizer can better optimize.

**Comment by kmbarton423** [comment]
Ran several queries in fhir-devtest environment which is at the latest pre-4.6.0 code level.
Used the CMS Interop Patient Access API which utilizes Patient compartment search.
Queries returned expected data.  
Log entries (using FINE tracing) showed SQL generated with compartment parameters at the front of the list.
