### ISSUE TITLE
whole-system-search: populate global search parameter tables

### ISSUE THREAD

**Issue by punktilious** [IBM/FHIR#1921]
To address #264 new global-level tables were introduced to the schema but are currently not populated.

Update the search parameter extraction and persistence to populate these parameter tables.

Migration will require a reindex...consider a reindex which can be parameterized to only update these tables, which should be much faster than a full reindex.

Part of epic #264.

**Comment by d0roppe** [comment]
verified new tables have values added on ingestion. Also reindexed a schema and the values were then populated. Closing issue.
