### ISSUE TITLE
whole-system-search: add last_updated to LOGICAL_RESOURCES

### ISSUE THREAD

**Issue by punktilious** [IBM/FHIR#1923]
To optimize whole-system-search, the last_updated field needs to be added to the system-level `LOGICAL_RESOURCES` table. This allows all system-level searches to be evaluated without having to join against the resource-specific `<resourceType>_LOGICAL_RESOURCES`.

In addition, a unique index should be defined as (last_updated, logical_resource_id). This will support simple scanning of changes which have occurred from a known point.

Consider also including the current IS_DELETED status.

NOTE: we updated LAST_UPDATED and IS_DELETED columns to the resource-specific xx_LOGICAL_RESOURCES tables for 4.6.0.  This task is different in that its about the whole-system search and the global LOGICAL_RESOURCES table.

Also VERSION?!

**Comment by lmsurpre** [comment]
stretch goal for 4.6.0

**Comment by lmsurpre** [comment]
Related issue #2011 was fixed by https://github.com/IBM/FHIR/pull/2013/files but I don't think we've added that column to the cross-resource LOGICAL_RESOURCES table yet.  Does it make sense to try to squeeze it in for 4.6.0, or we feel good about adding this later?

**Comment by punktilious** [comment]
Work can start on this now that the new query builder #1385 is done.

**Comment by d0roppe** [comment]
last_updated field in logical_resource table is not populated on ingestion. Closing issue
