### ISSUE TITLE
Automated e2e integration tests for the fhir-notification module

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#1936]
While reviewing https://github.com/IBM/FHIR/pull/1932 I noted that we really don't have any coverage of our fhir-notification module in our CI pipeline.

Way back when we added NATS.io support for notifications, we did the work to spin up the NATS cluster as part of our docker-compose env (with db2), but we never did circle back around to adding automated tests for it:

From build/README-DB2.md:
>    Note: If you are testing NATS notifications, invoke the NATS subscriber via `node fhir-server-test/src/test/nodejs/nats-subscriber`.  If this is your first time, install the dependencies first by installing [Node.js](https://nodejs.org/en/download) (if not already installed) and running `(cd fhir-server-test/src/test/nodejs && npm install)`.

I'm hoping we can expand on that and add automated tests that cover the create, update (and patch), and delete notification events within our existing CI.
We should probably upgrade the NATS dependency to 2.0 while we're at it...

**Comment by prb112** [comment]
I added Kafka (as it's the easiest to add, if we want to add nats, I can add that too)
