### ISSUE TITLE
fhir-notification: Limit handling for 1M

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#1948]
**Is your feature request related to a problem? Please describe.**

fhir-notification for Kafka and Nats default to 1M sized message payloads. These messages are included in the Notification Event sent from the IBM FHIR Server to the Nats/Kafka endpoints. 

If the messages exceed the limit, the Notification is never sent, where as it should be sent and handled appropriately. 

**Describe the solution you'd like**

The Notification Service should support sending a stub message where the receiver can retrieve the large message payload. 
This should be signaled to the user using a flag. 

**Describe alternatives you've considered**
1 - Splitting the Messages (however the messages may be received out of order)
2 - Not sending a message (however the user never knows the data exists)

**Acceptance Criteria**
At least one acceptance criteria is included.

1. Verify Kafka or Nats has a Message
  GIVEN Kafka OR Nats is configured as a Notification Service
    AND the Notification Service is Enabled 
   WHEN A resource of 10M is created (such as a Binary Resource)
    AND success (201)
    THEN The resource is retrieved from the Location
    AND the Topic contains a message without the 10M resource. 

**Additional context**
Refer to #1758 where the Nats issue was fixed by increasing the max payload size.

**Comment by lmsurpre** [comment]
The notification message size should be configurable (default to 1MB).  When message size is above that, send the stub instead.  Needs clear documentation for consumers of the notification events so they know they might not get the payload.  
They need to know that they should look for this flag before assuming there is a resource payload. 

We should also provide an option to omit the resource payload on all notifications...the code already supports this but its not exposed via config.

**Comment by kmbarton423** [comment]
New configuration properties:
fhirServer/notifications/common/maxNotificationSizeBytes => (default) 1000000
fhirServer/notifications/common/maxNotificationSizeBehavior => (default) "subset" or "omit"

Confirmed behavior of the above configuration properties via Kafka messages.
Tested a variety of settings as well as the defaults.
