### ISSUE TITLE
Refactor REST layer into multiple classes

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#195]
FHIRResource implements the entire HTTP API surface area of the FHIR server and weighs in at over 4000 lines of code.
Although it hasn't shown up on the Profiler yet, my understanding is that the JAX-RS framework instantiates this class for each request, which may limit our scalability.
It should be possible to give each Rest endpoint its own JAX-RS class, while keeping the doX methods (doCreate, doUpdate, etc), which perform the heavy lifting, in some static/stateless layer.
Alternatively, John mentioned we could use a Registry approach where the rest layer is able to look up interactions dynamically. This might simplify the design of the Operations framework as well which currently accepts a FHIRResourceHelper, which is actually backed by the full FHIRResource instance, on each invocation.
Can we make better use of IBM CDI (context and dependency injection)?

**Comment by prb112** [comment]
@lmsurpre let's talk about this.  It's not actually accurate to say it's instantiated on every request.

**Comment by lmsurpre** [comment]
I think I actually did this already as part of issue #17

**Comment by prb112** [comment]
Reviewed as part of the merged code which splits into REST Helper and corresponding classes.  This reduced the cognitive load for the FHIRResource Class.
