### ISSUE TITLE
AuthzPolicyEnforcement interceptor returns 500 for select client errors

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#1951]
**Describe the bug**
For most requests, if the AuthzPolicyEnforcementPeristenceInterceptor blocks the request, then it returns an HTTP 403 error to signify the request is Forbidden for the current user.

However, in select cases, the interceptor is throwing an IllegalArgumentException which bubbles up into an HTTP 500 error instead.

**To Reproduce**
1. Create a valid access token for a user that has no patient_id claim
2. Issue a request for a resource that belongs to a given patient compartment

Note that the response error code is a 500 Server Error.

**Expected behavior**
The HTTP status code should be either a 400 (invalid request) or, even better, a 403.

**Additional context**
n/a

**Comment by kmbarton423** [comment]
Confirmed "before" behavior in CMS Interop environment (500 internal server error).
Ran in fhir-devtest environment with fix and confirmed "after" behavior (403 forbidden):
{
    "resourceType": "OperationOutcome",
    "id": "ac-1e-3a-b0-6beb9e8c-f1fd-4926-80da-e73a84fa56fa",
    "issue": [
        {
            "severity": "fatal",
            "code": "forbidden",
            "details": {
                "text": "Authorization token is missing 'patient_id' claim"
            },
            "expression": [
                "<empty>"
            ]
        }
    ]
}
