### ISSUE TITLE
request to provide OperationOutcome when search parameters are ignored

### ISSUE THREAD

**Issue by kmbarton423** [IBM/FHIR#1952]
Ran into a situation today where it would have been nice to have an indicator that one of my search parameters was ignored.
Running with a lenient server where Organization does not support searchRevInclude for Provenance:target.

Attempted the following query:
   Organization?_revinclude=Provenance:target

The search results contained Organizations only.
I was expecting the associated Provenance resources too.

On closer inspection, the "link" in the search results does not show the revinclude parm:
    "link": [
        {
            "relation": "self",
            "url": "https://fhir-devtest.wh-cmsiop.dev.watson-health.ibm.com/fhir-server/api/v4/Organization?_count=10&_page=1"
        }
    ],

Looking at the log, I can see the revinclude parm was considered invalid:
Feb 16 16:07:34 wh-cmsiop-fhir1-patient-access-0000-674dc57966-vxlj6 fhir FINE 'Provenance:target' is not a valid _revinclude parameter value for resource type 'Organization'

It would have been very easy to assume that no associated Provenance resources existed.  The only reason I caught this is because I know my data.

This is an enhancement request to provide information in the search results in any situation where the original search parameters are ignored or altered. Based on the search info in the FHIR spec (RESTful API - https://www.hl7.org/fhir/http.html#ops), OperationOutcome could be used to relay this information.  

**QA recommendations:**

1. Test invalid/misspelled search parameters.
2. Test unsupported combinations of search parameters.
3. Test invalid values for _include, _revinclude, _elements, _sort
4. Test specifying same singleton search parameter, such as _type, multiple times.

**Comment by lmsurpre** [comment]
I think we should limit this behavior to when the user opts into it by passing the following header: `Prefer: return=OperationOutcome`

The OperationOutcome would come back as a search bundle response entry with search.mode set to "outcome".

**Comment by tbieste** [comment]
I was thinking of just putting all the issues in a single OperationOutcome, so they will look like this:

fhir-server/api/v4/Organization?invalid=value
```
        {
            "resource": {
                "resourceType": "OperationOutcome",
                "issue": [
                    {
                        "severity": "warning",
                        "code": "invalid",
                        "details": {
                            "text": "Search parameter 'invalid' for resource type 'Organization' was not found."
                        },
                        "expression": [
                            "<no expression>"
                        ]
                    },
                    {
                        "severity": "warning",
                        "code": "invalid",
                        "details": {
                            "text": "Search parameter 'invalid' for resource type 'Organization' ignored"
                        },
                        "expression": [
                            "<no expression>"
                        ]
                    }
                ]
            },
```

**Comment by tbieste** [comment]
Since these issues will only be returned in lenient mode, I don't think the "Prefer: return=..." header should control this.  Based on https://www.hl7.org/fhir/r4/http.html#ops, that header seems more for when POST, PUT, PATCH are used and determines how much info about the created/updated resource is returned, instead of how many issues to return in the OperationOutcome. I think would be best to return these warnings whenever lenient mode is used instead of requiring "Prefer: return=OperationOutcome" or "Prefer: return=representation" to opt-in.

**Comment by kmbarton423** [comment]
Looks good.  Now get the following for the sample search noted in the original problem description:

        {
            "resource": {
                "resourceType": "OperationOutcome",
                "issue": [
                    {
                        "severity": "warning",
                        "code": "invalid",
                        "details": {
                            "text": "'Provenance:target' is not a valid _revinclude parameter value for resource type 'Organization'"
                        },
                        "expression": [
                            "<no expression>"
                        ]
                    },
                    {
                        "severity": "warning",
                        "code": "invalid",
                        "details": {
                            "text": "Inclusion parameter '_revinclude' with value 'Provenance:target' ignored"
                        },
                        "expression": [
                            "<no expression>"
                        ]
                    }
                ]
            },
            "search": {
                "mode": "outcome"
            }
        }
