### ISSUE TITLE
Support resource change tracking with custom operation to fetch list of changes since a known point

### ISSUE THREAD

**Issue by punktilious** [IBM/FHIR#1955]
**Is your feature request related to a problem? Please describe.**
Systems need a way to reliably and efficiently track changes made to resources in the IBM FHIR Server.

**Describe the solution you'd like**
Add a change tracking table to the schema and insert records to the table each time a resource is changed. Record the Create/Update/Delete status and order the data with a timestamp and change sequence number. The change sequence number can be derived from the RESOURCE_ID because this comes from FHIR_SEQUENCE and will be unique across all resource types.

```
CREATE TABLE <fhir-data-schema>.RESOURCE_CHANGE_LOG (
  change_tstamp    TIMESTAMP NOT NULL,
  resource_id          BIGINT NOT NULL,
  change_type       CHAR(1) NOT NULL,
  resource_type_id INT NOT NULL,
  logical_id            VARCHAR(255) NOT NULL,
  version_id           INT NOT NULL,
  CONSTRAINT pk_resource_change_log PRIMARY KEY (change_tstamp, resource_id)
);

-- add FK to resource-types
```

The change-type is encoded as:

```
C - Resource CREATE
U - Resource UPDATE
D - Resource DELETE
```

The persistence stored procedure can be used to insert the change log record. This avoids another database round-trip. For Derby, the DAO will need to be updated.

A new custom operation `$changes` will be added to fetch the change log records from a known point. The custom operation supports the following parameters:

```
  limit - the number of changes to return in one call (default 1000)
  tstamp -  if given, return changes that have occurred on or after this time
  change_id - return changes with a change_id value greater than the given value
```

If no parameters are provided or the values are null, the scan starts from the first recorded change.

Take note of the inequality semantics relating to tstamp and change_id. These semantics allow a consumer of the API to efficiently retrieve changes that have occurred from a known point in time, but also to avoid receiving duplicates by providing a change_id if it is known. A consumer would implement the following loop (pseudo-code):

```
Date timestamp = chooseStartFrom();
Long changeId = null; // unless this is known already from an earlier checkpoint
do {
  // make the call the $changes custom operation
  List<ChangeRecord> changes = getChanges(timestamp, changeId);
  if (changes.size() > 0) {
    process(changes);

    // update the parameters so the next $changes call starts after the last record
    ChangeRecord last = changes.get(changes.size()-1);
    timestamp = last.getTimestamp();
    changeId = last.getChangeId();
} while (changeId != null);
```

**Describe alternatives you've considered**
Bulk export - not intended to be run frequently, making it difficult to stream incremental changes. Also bulk export currently does not support delete markers.

Notification - There are some edge cases related to transaction failures which could cause sync issues with a downstream system.

**Acceptance Criteria**
At least one acceptance criteria is included.

1.  
  GIVEN a sequence of Create/Update/Delete operations on FHIR resources
   THEN the `$changes` custom operation returns the list of changes in matching order.

**Comment by prb112** [comment]
Refer to https://github.com/IBM/FHIR/issues/850 where 850 will have to write to it

**Comment by punktilious** [comment]
The query portion of this is being implemented as the FHIR system history API.

```
  [base]/_history
  [base]/_history?_count=10
  [base]/_history?_count=10&_since=2021-02-21T03:00:53.878052Z"
  [base]/_history?_count=10&_since=2021-02-21T03:00:53.878052Z&_afterHistoryId=4"
  [base]/_history?_count=10&_afterHistoryId=4"
```

The _afterHistoryId parameter is an extension supported by the IBM FHIR Server which allows a client to make a sequence of such calls without having to worry about duplicates. The client can follow the `next` link in the bundle to continue fetching.

**Comment by lmsurpre** [comment]
Questions:
* is it worth adding a `self` link?
* would it be possible to support `total` in the future?
  * maybe controllable by the client once we support it in search (#1353)

The spec points to https://tools.ietf.org/html/rfc5005 and that has this language:
```
   The feed documents in a paged feed are tied together with the
   following link relations:

   o  "first" - A URI that refers to the furthest preceding document in
      a series of documents.

   o  "last" - A URI that refers to the furthest following document in a
      series of documents.

   o  "previous" - A URI that refers to the immediately preceding
      document in a series of documents.

   o  "next" - A URI that refers to the immediately following document
      in a series of documents.

   Paged feed documents MUST have at least one of these link relations
   present, and should contain as many as practical and applicable.
```

**Comment by lmsurpre** [comment]
Looks like we went with a default page size of 100.  That seems quite reasonable to me, but does differ from the value given in the description of this issue (1000).

**Comment by lmsurpre** [comment]
The spec points to https://tools.ietf.org/html/rfc5005 and that has this language:
```
   The feed documents in a paged feed are tied together with the
   following link relations:

   o  "first" - A URI that refers to the furthest preceding document in
      a series of documents.

   o  "last" - A URI that refers to the furthest following document in a
      series of documents.

   o  "previous" - A URI that refers to the immediately preceding
      document in a series of documents.

   o  "next" - A URI that refers to the immediately following document
      in a series of documents.

   Paged feed documents MUST have at least one of these link relations
   present, and should contain as many as practical and applicable.
```

However, when we get to the last entry in our implementation, following the `next` link returns this:
```
{
    "resourceType": "Bundle",
    "type": "history"
}
```

I'm not sure if its an issue or not, but maybe we should have "previous" links as well?  maybe a new `_beforeHistoryId` parameter?

**Comment by lmsurpre** [comment]
I confirmed that I'm seeing history entries for create, update, and delete actions.  One thing I noticed is that we always say that the method was "POST" even when it was "PUT" (irregardless of whether it was a create or an update).  I think it would be a little better if we could reflect the actual request better, so that an entry of a true `update` comes back like this:
```
        {
            "fullUrl": "Patient/Patient1/_history/4",
            "request": {
                "method": "PUT",
                "url": "Patient/Patient1"
            },
            "response": {
                "status": "200 OK",
                "lastModified": "2021-03-04T17:35:22.375Z"
            }
        },
```

**Comment by lmsurpre** [comment]
I was able to cause a 500 server error by passing a negative count.  Instead, it should reject that with as a 400 (bad request).

**Comment by punktilious** [comment]
Regarding _count in the next link, I left this as the original request on purpose because it allows us (in the future) to modulate the max number we actually process. Also, it's the client telling us that's the max that they can handle, so I don't think we should manipulate it.

**Comment by lmsurpre** [comment]
> Regarding _count in the next link, I left this as the original request on purpose because it allows us (in the future) to modulate the max number we actually process. Also, it's the client telling us that's the max that they can handle, so I don't think we should manipulate it.

After explaining that we return the "chomped" count in our search implementation of paging, robin agreed to update it.  This update looks to be working as expected.

**Comment by lmsurpre** [comment]
Looks good!
