### ISSUE TITLE
Enforce StorageType source and destination for BulkData using FHIR_BULKDATA_ALLOWED_TYPES

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#1982]
**Is your feature request related to a problem? Please describe.**
Enforce StorageType source and destination for BulkData using FHIR_BULKDATA_ALLOWED_TYPES

**Describe the solution you'd like**
Enforce StorageType source and destination for BulkData using FHIR_BULKDATA_ALLOWED_TYPES

**Describe alternatives you've considered**
Allow all

**Acceptance Criteria**
At least one acceptance criteria is included.

1.  Export
  GIVEN Env FHIR_BULKDATA_ALLOWED_TYPES=ibm-cos,aws-s3
    AND bulkdata is configured WHEN an export with file is executed
    THEN the export fails.

1.  Import
  GIVEN Env FHIR_BULKDATA_ALLOWED_TYPES=ibm-cos,aws-s3
    AND bulkdata is configured WHEN an import with file is executed
    THEN the import fails.

**Additional context**
n/a

**Comment by kmbarton423** [comment]
Set environment variable FHIR_BULKDATA_ALLOWED_TYPES=ibm-cos,aws-s3
Configured FHIR server bulkdata:storageProviders:default:type=file
Attempted both $import and $export.
Received the following in response:

{
    "resourceType": "OperationOutcome",
    "id": "ac-11-0-2-6b5b11da-3c01-487f-b0c9-8753360c2e48",
    "issue": [
        {
            "severity": "fatal",
            "code": "not-supported",
            "details": {
                "text": "storageType is disallowed"
            },
            "expression": [
                "<empty>"
            ]
        }
    ]
}
