### ISSUE TITLE
Default for PostgreSQL from/join_collapse_limit values are too high

### ISSUE THREAD

**Issue by punktilious** [IBM/FHIR#1993]
**Describe the bug**
If the following is not specified:
```
                    "searchOptimizerOptions": {
                        "from_collapse_limit": 12,
                        "join_collapse_limit": 12
                    }
```

in the PostgreSQL datasource, the default values are 16 which is too high and could result in worse performance.

Consider changing the default to 8, which is likely to be a better initial value now that the patient compartment predicate is always included first in queries. In other FHIR search queries, we also advise to include the most selective predicate first in the query parameters. This ensures that the PostgreSQL will consider this earlier in the join and produce a better execution plan.

**Comment by punktilious** [comment]
Based on testing it looks now like 7 is the best value, although additional tests are being run with more complex searches to see if this holds.

**Comment by prb112** [comment]
Moved to review based on PR. https://github.com/IBM/FHIR/pull/1996/files#

**Comment by d0roppe** [comment]
Recommending 12 to be the default.

**Comment by d0roppe** [comment]
recommendation based on this comparison.
[Limit compare on 12 and 7.xlsx](https://github.com/IBM/FHIR/files/6070303/Limit.compare.on.12.and.7.xlsx)

**Comment by punktilious** [comment]
Based on the additional testing (thanks @d0roppe!) we will use 12 as the new default (if not provided in a fair-server-config.json). As a reminder, to use the database default value (8), set the join_collapse_limit and from_collapse_limit values to `null` in the fhir-server-config.json file.

**Comment by punktilious** [comment]
Moving to QA. This code is now in main.

**Comment by d0roppe** [comment]
Verified the setting of 12 is now in main.  Closing issue.
