### ISSUE TITLE
Patient Export without Type results in a failed export

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#2012]
**Describe the bug**
Patient Export without Type results in a failed export

**To Reproduce**
1. Setup BulkData 
2. Execute a Patient Export
   curl -k -u "fhiruser:${PASS}" -H "Content-Type: application/fhir+json" -X GET \
    'https://localhost:9443/fhir-server/api/v4/Patient/$export?_outputFormat=application/fhir%2Bndjson' \
    -v --header "X-FHIR-TENANT-ID: ${TENANT_ID}"

Results in 
{"resourceType":"OperationOutcome","id":"c0-a8-56-16-2cba4727-e321-431b-95da-c09785ea7583","issue":[{"severity":"error","code":"invalid","diagnostics":"Resource Type outside of the Patient Compartment in Export"}]}

This is a subtle issue in the processing of the Parameters object where the _type is not specified, and we stop the processing.

**Expected behavior**
Pickup the Resources in the compartment only.

**Additional context**
n/a

**Comment by d0roppe** [comment]
more testing needed see issue #2059

**Comment by d0roppe** [comment]
Verified this is now working as expected. and no error as described in the issue
