### ISSUE TITLE
Use IS_DELETED and LAST_UPDATED from xxx_LOGICAL_RESOURCES

### ISSUE THREAD

**Issue by punktilious** [IBM/FHIR#2014]
From schema version V0011, LAST_UPDATED and IS_DELETED values can be used from xxx_LOGICAL_RESOURCES, allowing joins to xxx_RESOURCES to be eliminated except for the outermost layer where the data field is used. This simplifies queries and should make it easier for the optimizer to select the best plan.

**Comment by punktilious** [comment]
Closing because this is a duplicate of #1385 which has additional context and discussion related to this topic.

**Comment by lmsurpre** [comment]
OK, I updated the title on #1385 to reflect that it should cover us of LAST_UPDATED as well.
