### ISSUE TITLE
fhirSharedLib is defined multiple times and conflicts.

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#2035]
**Describe the bug**
fhirSharedLib is defined multiple times and conflicts.

```
    <library id="fhirSharedLib">
        <fileset dir="${shared.resource.dir}/lib/postgresql" includes="*.jar"/>
    </library>
```

**To Reproduce**
View disabled/overrides in bulkdata and datasource.xml

**Expected behavior**
There server.xml should define the libraries and reference in the datasource.xmls

**Additional context**
Team discussion

**Comment by lmsurpre** [comment]
while we're in there, please nix this line in the postgres datasource config:
![image](https://user-images.githubusercontent.com/5478798/110351640-0d389000-8003-11eb-982c-159de8f392b8.png)

**Comment by tbieste** [comment]
Some of the liberty-config/configDropins/disabled/…/bulkdata.xml still reference “fhirSharedLib”. Those should be updated.

**Comment by tbieste** [comment]
Verified that fhirSharedLib has been removed, and that derby, db2, and postgresql shared lib references work.
