### ISSUE TITLE
Whole system history - support protection from concurrency issues

### ISSUE THREAD

**Issue by punktilious** [IBM/FHIR#2039]
**Describe the bug**
The current documentation states:

> To guarantee no data is skipped, clients should not process resources with a `lastModified` timestamp which is after `{current_time} - {transaction_timeout} - {max_cluster_clock_drift}`. By waiting for this time window to close, the client can be sure the data being returned is complete and in order, and new data will not appear. The default value for transaction timeout is 120s but this is configurable. A value of 2 seconds is a reasonable default to consider for `max_cluster_clock_drift` in lieu of specific information. Implementers should check with server administrators on the appropriate values to use.

This is complicated and it would be better to implement a feature on the server side to prevent data from being returned which falls within the described time window. However, this may not be always the desired behavior. Consider two options:

1. Support an additional query parameter to enable/disable this behavior
2. Make the behavior configurable in fhir-server-config.

Option 1 is the most flexible, because it puts control in the hands of the client. In this case, the fhir-server-config parameter could also be used to determine the default behavior for option 1 - what do to if the parameter isn't passed by the client.

Once updated, the documentation must be updated accordingly.

**Comment by lmsurpre** [comment]
stretch for the current sprint

**Comment by lmsurpre** [comment]
the hard part of this one is to obtain the system's transaction timeout

currently, its just up to the clients to stop reading pages (or re-read pages) near the end.

**Comment by lmsurpre** [comment]
plan:  ALWAYS set an environment variable for the transaction timeout. 

its not foolproof because users could add a server.xml override that sets the value different than the variable.  but we think this is acceptable.

**Comment by lmsurpre** [comment]
we should do some tests to ensure timezone doesn't affect the impl

**Comment by d0roppe** [comment]
Closing this issue.  This generally works, there were a couple of nuances, and separate issues were created for that.
