### ISSUE TITLE
make quantity values searchable even without unit or code

### ISSUE THREAD

**Issue by d0roppe** [IBM/FHIR#2041]
**Is your feature request related to a problem? Please describe.**
Adding observation data component with valueQuantity, but only adding a value, fhir should index and allow searches on the value.
**Describe the solution you'd like**
When adding Observation data like this (mock data)
      "component": [{
        "code": {
          "coding": [{
            "system": "http://loinc.org",
            "code": "2339-0"
          }]
        },
        "valueQuantity": {
          "value": 58.7
        }
      }]
Should be able to search on this Observation with searches like:
[base]/Observation?component-code-value-quantity=http://loinc.org|2339-0$58.7

**Describe alternatives you've considered**
Continue to require valueQuantity units or code allong with value to index the data and allow searches.

**Acceptance Criteria**
At least one acceptance criteria is included.

1.  
  GIVEN [a precondition]
    AND [another precondition] WHEN [test step]
    AND [test step]
    THEN [verification step]
    AND [verification step]

**Additional context**

**Comment by lmsurpre** [comment]
The system+code columns are nullable, so we could either store without one or with some kind of placeholder values.

**Comment by lmsurpre** [comment]
Hopefully it just requires changes to extraction and no corresponding query changes.  Estimated accordingly.

**Comment by d0roppe** [comment]
Verified that this search capability now works.
