### ISSUE TITLE
nothing returned for curl on fhir server with invalid config

### ISSUE THREAD

**Issue by kmbarton423** [IBM/FHIR#2047]
nothing returned for curl on fhir server with invalid config

Testing with IBM FHIR Server and DB2 in a Red Hat Openshift cluster.

1 - Setup create a fhir-server-config.json with an empty json.
2 - Start the ibm-fhir-server
3 - Attempted the following curl but got no response from the server:

curl -k --location --request GET 'https://localhost:9443/fhir-server/api/v4/$healthcheck' \
--header 'X-FHIR-TENANT-ID: default' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic <pwd>'

Not sure what to expect from a server started with an invalid config.  
A warning of some sort is desirable.

**Comment by prb112** [comment]
```
