### ISSUE TITLE
Ensure all OperationDefinition resources are pulled from FHIRRegistry for specification-defined operations (e.g. $everything)

### ISSUE THREAD

**Issue by JohnTimm** [IBM/FHIR#2057]
Previously, we would include a copy of the OperationDefinition resource in the implementation of that operation. The FHIRRegistry provides access to all spec artifacts and, as a best practice, should be used to access definitions for specification-defined operations.

**Comment by lmsurpre** [comment]
Maybe we can tackle this one together with https://github.com/IBM/FHIR/issues/2057

**Comment by prb112** [comment]
I tried with the $everything operation and $convert and $document and $validate.
All looks good
