### ISSUE TITLE
confusing response when attempting GET vs POST with $import

### ISSUE THREAD

**Issue by kmbarton423** [IBM/FHIR#2062]
Working with FHIR 4.6.0 bulk data.
Received a confusing response when attempting $import with the wrong method (GET vs POST):

{
    "resourceType": "OperationOutcome",
    "id": "ac-11-0-2-6b5b11da-3c01-487f-b0c9-8753360c2e48",
    "issue": [
        {
            "severity": "fatal",
            "code": "not-supported",
            "details": {
                "text": "storageType is disallowed"
            },
            "expression": [
                "<empty>"
            ]
        }
    ]
}

**To Reproduce**
Attempt GET $import with an empty json body or a valid POST $import json body.

**Comment by prb112** [comment]
Moved to QA
