### ISSUE TITLE
Load historical artifacts to GitHub Releases

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#2064]
Bintray is going away.  We have #1904 for migrating to Maven Central.  But we don't want to lose our historical artifacts either.

Proposal:
* Write a script to copy the release artifacts from bintray and upload them to the corresponding Release page in github

_Originally posted by @lmsurpre in https://github.com/IBM/FHIR/issues/1904#issuecomment-796979586_

**Comment by prb112** [comment]
Please note as of 2021-MAY-01, JCenter is [shutting down BinTray](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/). The libraries, as of that date, are no longer available on BinTray.  Please download the [release-repo-4.3.3.zip](https://github.com/IBM/FHIR/releases/download/4.3.3/release-repository-4.3.3.zip) to cache your repository locally.

**Comment by prb112** [comment]
I added 4.6.1 to the release. 
I'll have the bintray switched to maven central by next release
