### ISSUE TITLE
Audit log entry for bulk data export should have a resource type associated with the total read in the log entry

### ISSUE THREAD

**Issue by d0roppe** [IBM/FHIR#2072]
**Is your feature request related to a problem? Please describe.**
When doing a bulk data export with multiple resource types, the Read record entries should have a resource type specified for the count given in the content entry.

**Describe the solution you'd like**
If you export _type=Patient,Observation. the Read audit log entries currently show a count for a type in the list of types, but we should also state what type it is associated with. 

**Describe alternatives you've considered**

**Acceptance Criteria**
1.  
   GIVEN [a precondition]
    AND [another precondition]
   WHEN [test step]
    AND [test step]
   THEN [verification step]
    AND [verification step]

**Additional context**

**Comment by prb112** [comment]
It'll output this... 
{
    "request_unique_id": "58429626-5637-4b91-8023-98a9053c2800",
    "action": "R",
    "start_time": "2021-03-12 01:56:49.439",
    "end_time": "2021-03-12 01:56:49.894",
    "api_parameters": {
        "request": "https://localhost:9443/fhir-server/api/v4/$export?_outputFormat=application/fhir%2Bndjson&_type=Patient",
        "request_status": 200
    },
    "query": "{_lastUpdated=[ge2019-01-01T08:21:26.94-04:00], _sort=[_lastUpdated]}",
    "batch": {
        "resources_read": 256
    },
    "event_type": "fhir-search",
    "description": "FHIR BulkData Search request",
    "location": "@source:default",
    "resource_name": "Patient"
}

**Comment by d0roppe** [comment]
verified the audit record now has the resource type listed with the count read when there are multiple resources in the _type parm. or there are multiple resources exported from the export call.
