### ISSUE TITLE
Add VERSION to the xx_LOGICAL_RESOURCES

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#2109]
**Is your feature request related to a problem? Please describe.**
For 4.6.0 we introduced IS_DELETED and LAST_UPDATED columns to the xx_LOGICAL_RESOURCES tables.
But when we went to use these in #1385 we realized that we'd also like the LATEST_VERSION in this table as well.

This could prevent some joins in the case of include/revinclude queries.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Acceptance Criteria**
1.  
   GIVEN [a precondition]
    AND [another precondition]
   WHEN [test step]
    AND [test step]
   THEN [verification step]
    AND [verification step]

**Additional context**

**Comment by kmbarton423** [comment]
stretch goal for 4.6.1

**Comment by prb112** [comment]
I can confirm the version_id is in the db2 describe of the logical_resources table, and has been populated properly.

**Comment by lmsurpre** [comment]
I also confirmed the same on a postgresql database with ~10M resources.
