### ISSUE TITLE
Make useStoredCompartmentParam the default

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#2111]
**Is your feature request related to a problem? Please describe.**
I’d like to make useStoredCompartmentParam default to true.  We added this in 4.5.1 and left it behind a flag since, if you’re migrating from before 4.5.1, it requires a reindex to work.  Now that we're on 4.6.x, its time to make this the default.

**Describe the solution you'd like**
Flip the default from false to true, and add "useStoredCompartmentParam": true to our default config

**Describe alternatives you've considered**
* Keep the default as false but add "useStoredCompartmentParam": true to our default config; or
* Flip the default from false to true, but add "useStoredCompartmentParam": false to our default config; or
* Flip the default from false to true, keep the parameter out of our default config, and mark the parameter as deprecated

**Additional context**
Now that we're using inclusionCriteria queries from bulk data (patient/group export) and fhir-smart (policy enforcement interceptor), this can have even more benefit.

**Comment by prb112** [comment]
I've tested compartment searches with GroupExport, Patient Export, regular rest calls with false, default, true. 
It's working as outlined in the issue.
