### ISSUE TITLE
bulk data export of a group the patient resource is not exported when asked for. 

### ISSUE THREAD

**Issue by d0roppe** [IBM/FHIR#2114]
**Describe the bug**
when you have a group created with a specified patient.  And you export based on a group, the patient related resources are exported, but not the patient resource. 
**To Reproduce**
Create a group with a patient.
Export based on group
**Expected behavior**

**Additional context**

**Comment by prb112** [comment]
```

**Comment by d0roppe** [comment]
Verified now the patient resource is also exported. in general and when asked for.  and when not asked for it is not exported.  Closing issue.
