### ISSUE TITLE
File-based export writes empty files

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#2121]
**Describe the bug**
We added a check that prevents our S3-based export from writing empty files.
However, for file-based export, we still write the file even when there are no resources to write.

**To Reproduce**
1. invoke a file-based $export on a fresh db (no resources)
2. check the output directory

**Expected behavior**
Only resource types with one or more resource will have files in the export.

**Additional context**
N/A

**Comment by d0roppe** [comment]
Verified that only export files with 1 or more resources are created for all 3 types of exports. Closing issue.
