### ISSUE TITLE
Support for deleting rows from FHIR_ADMIN.VERSION_HISTORY during drop-schema

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#2136]
**Is your feature request related to a problem? Please describe.**
While verifying #1631 I noted that the `--drop-schema` action doesn't actually delete the corresponding rows from `FHIR_ADMIN.VERSION_HISTORY`.  That prevents users from re-using this schema-name after the drop.

**Describe the solution you'd like**
For non-multitenant-schemas (i.e. everything other than db2 ones at the moment) `--drop-schema` should delete the correspondinig rows in `FHIR_ADMIN.VERSION_HISTORY`.

For multi-tenant schemas, it should continue to work the way it does today.

**Describe alternatives you've considered**
Create a separate action for deleting these rows on non-tenant-aware dbs.

**Acceptance Criteria**
1.  
   GIVEN you create a schema on a non-tenant-aware db schema (like postgresql or derby)
   WHEN you follow the documentation to drop a schema
   THEN all corresponding schema objects are gone
    AND you are able to re-create and re-deploy the schema (via --update-schema)

**Additional context**
We already have `--drop-tenant-meta` which fits the bill for our multi-tenant Db2 schema.  What we need is an approach for doing it on the non-tenant-aware schemas like postgresql.

**Comment by lmsurpre** [comment]
Possibly a duplicate of #1176.  If not, we should probably consolidate them anyway.

**Comment by lmsurpre** [comment]
We have a bit of a gap in our fhir_admin tables that makes this harder.
Therefor, as part of this issue, we should also add tenant schema information to fhir_admin.

**Comment by d0roppe** [comment]
Verified that table version history information is removed form fhir_admin when a drop-schema is issued for the schemas that is not fhir_admin.  Also verified that dropping all schemas cleans up everything.   Closing issue
