### ISSUE TITLE
Reading null from xx_RESOURCES.DATA causes NullPointerException

### ISSUE THREAD

**Issue by punktilious** [IBM/FHIR#2140]
**Describe the bug**
Certain databases used for development or testing may contain a null data column in the xx_RESOURCES tables. Trying to read a resource in this state will cause a NullPointerException to be thrown.

This causes issues with reindex because it prevents the reindex from continuing past the broken resource record.

This is extremely unlikely to occur in user databases. Although the data column is nullable, it is always set to a value by the persistence layer. The data column can only be null if it has been updated outside of the IBM FHIR Server, or as part of some feature development activity.

**To Reproduce**
Attempt to run reindex on a database which contains null values for the xx_RESOURCES data column.

**Expected behavior**
For reindex, the record should be skipped, because there's no resource payload to process.

For other read operations, generate an appropriate operational outcome.

**Comment by lmsurpre** [comment]
Hit while working on experiment "off-loading of resource payload to external storage"

**Comment by tbieste** [comment]
Here's the updated behavior:
1) Read/vRead:  Resource xxxxxxxxxxxx not found.'
2) Reindex: No search parameters are extracted.
3) Search: IllegalStateException: Returned resources must have an id.  (currently does this if resource.id == null, so just expanded it to also cover resource == null).

**Comment by tbieste** [comment]
I added a 2nd commit with the following update:
Instead of failing the whole search, return the bundle and include an OperationOutcome with "A resource with no data was found." or "A resource with no id was found".  So the whole search doesn't just fail if there's one nulled-out resource in the DB.
I can backout that commit if just failing the whole search is better.

**Comment by d0roppe** [comment]
Ran local tests with search and $reindex. now seems to be working as expected. Closing issue.
