### ISSUE TITLE
Transaction not rolled back after parameter insertion failure

### ISSUE THREAD

**Issue by punktilious** [IBM/FHIR#2164]
**Describe the bug**
If an error occurs during ingestion in some cases the transaction is still committed but should be rolled back.

**To Reproduce**
Ingest the following synthetic Patient resource which contains an invalid code-system:

```
{"resourceType":"Patient","id":"1761a4c3245-9d3576d6-723d-49b2-954e-906dac14df02","meta":{"versionId":"1","lastUpdated":"2020-11-30T17:56:09.925Z"},"text":{"status":"generated","div":"<div xmlns=\"http://www.w3.org/1999/xhtml\">\n\t\t\t<table>\n\t\t\t\t<tbody>\n\t\t\t\t\t<tr>\n\t\t\t\t\t\t<td>Name</td>\n\t\t\t\t\t\t<td>Peter James \n              <b>Chalmers</b> (&quot;Jim&quot;)\n            </td>\n\t\t\t\t\t</tr>\n\t\t\t\t\t<tr>\n\t\t\t\t\t\t<td>Address</td>\n\t\t\t\t\t\t<td>534 Erewhon, Pleasantville, Vic, 3999</td>\n\t\t\t\t\t</tr>\n\t\t\t\t\t<tr>\n\t\t\t\t\t\t<td>Contacts</td>\n\t\t\t\t\t\t<td>Home: unknown. Work: (03) 5555 6473</td>\n\t\t\t\t\t</tr>\n\t\t\t\t\t<tr>\n\t\t\t\t\t\t<td>Id</td>\n\t\t\t\t\t\t<td>MRN: 12345 (Acme Healthcare)</td>\n\t\t\t\t\t</tr>\n\t\t\t\t</tbody>\n\t\t\t</table>\n\t\t</div>"},"identifier":[{"use":"usual","type":{"coding":[{"system":"\u0000","code":"MR"}]},"system":"urn:oid:1.2.36.146.595.217.0.1","value":"12345","period":{"start":"2001-05-06"},"assigner":{"display":"Acme Healthcare"}}],"active":true,"name":[{"use":"official","family":"Chalmers","given":["Peter","James"]},{"use":"usual","given":["Jim"]},{"use":"maiden","family":"Windsor","given":["Peter","James"],"period":{"end":"2002"}}],"telecom":[{"use":"home"},{"system":"phone","value":"(03) 5555 6473","use":"work","rank":1},{"system":"phone","value":"(03) 3410 5613","use":"mobile","rank":2},{"system":"phone","value":"(03) 5555 8834","use":"old","period":{"end":"2014"}}],"gender":"male","birthDate":"1974-12-25","_birthDate":{"extension":[{"url":"http://hl7.org/fhir/StructureDefinition/patient-birthTime","valueDateTime":"1974-12-25T14:35:45-05:00"}]},"deceasedBoolean":false,"address":[{"use":"home","type":"both","text":"534 Erewhon St PeasantVille, Rainbow, Vic  3999","line":["534 Erewhon St"],"city":"PleasantVille","district":"Rainbow","state":"Vic","postalCode":"3999","period":{"start":"1974-12-25"}}],"contact":[{"relationship":[{"coding":[{"system":"http://terminology.hl7.org/CodeSystem/v2-0131","code":"N"}]}],"name":{"family":"du Marché","_family":{"extension":[{"url":"http://hl7.org/fhir/StructureDefinition/humanname-own-prefix","valueString":"VV"}]},"given":["Bénédicte"]},"telecom":[{"system":"phone","value":"+33 (237) 998327"}],"address":{"use":"home","type":"both","line":["534 Erewhon St"],"city":"PleasantVille","district":"Rainbow","state":"Vic","postalCode":"3999","period":{"start":"1974-12-25"}},"gender":"female","period":{"start":"2012"}}],"managingOrganization":{"reference":"Organization/1"}}
```

The parameter insertion will fail because `u0000` is not a valid UTF-8 byte sequence.

However, the exception stack trace in messages.log shows that a commit was still attempted:

```
	at com.ibm.tx.jta.impl.UserTransactionImpl.commit(UserTransactionImpl.java:162)
	at com.ibm.tx.jta.embeddable.impl.EmbeddableUserTransactionImpl.commit(EmbeddableUserTransactionImpl.java:101)
	at com.ibm.ws.transaction.services.UserTransactionService.commit(UserTransactionService.java:72)
	at com.ibm.fhir.persistence.jdbc.connection.FHIRUserTransactionAdapter.end(FHIRUserTransactionAdapter.java:128)
	at com.ibm.fhir.persistence.helper.FHIRTransactionHelper.commit(FHIRTransactionHelper.java:43)
	at com.ibm.fhir.server.util.FHIRRestHelper.doCreate(FHIRRestHelper.java:282)
	at com.ibm.fhir.server.operation.spi.FHIRResourceHelpers.doCreate(FHIRResourceHelpers.java:43)
	at com.ibm.fhir.server.resources.Create.create(Create.java:83)
```

**Expected behavior**
The transaction should be rolled back, not committed.

**Additional context**
The final behavior could be different depending on database type. PostgreSQL will fail the entire transaction, but Db2 could end up storing partial data.

**Comment by tbieste** [comment]
Doing some digging into how the flow goes.

1) For extracted TokenValue parameters, they are added to a list in a ParameterTransactionDataImpl.  These records are not inserted at the same time as other parameters.
2) Instead there is a beforeCompletion() method in CacheTransactionSync, that is "called just before the commit process starts, so we can use this to persist any data we've been holding onto. This makes it really easy to collect parameters during bundle processing and then insert them efficiently using a series of batches. The big benefit here is that it greatly reduces the amount of time we could be locking rows in common_token_values which helps with throughput."  This method calls ParameterTransactionDataImpl.persist().
3) The ParameterTransactionDataImpl.persist() catches any throwable and sets userTransaction.setRollbackOnly() to cause a rollback.

Based on that, it appears this working as expected.  Unless there's a reason to not wait until beforeCompletion() and persist TokenValue records at the same time as other parameters.  But it sounds like that was done for performance reasons.

**Comment by tbieste** [comment]
Here was the complete call stack from a recreate:

> [2021-04-06T19:15:46.459+0000] 0000009d ParameterTran E  Failed persisting parameter transaction data. Marking transaction for rollback
>                  com.ibm.fhir.persistence.exception.FHIRPersistenceException: Unexpected error while processing token value records. [probeId=c0-a8-63-1-9d5d296c-696e-46c7-bd43-57b9a0c9a2bb]
> 	at com.ibm.fhir.persistence.jdbc.impl.FHIRPersistenceJDBCImpl.persistResourceTokenValueRecords(FHIRPersistenceJDBCImpl.java:2265)
> 	at com.ibm.fhir.persistence.jdbc.impl.ParameterTransactionDataImpl.persist(ParameterTransactionDataImpl.java:55)
> 	at com.ibm.fhir.persistence.jdbc.dao.impl.TransactionDataImpl.lambda$persist$0(TransactionDataImpl.java:46)
> 	at java.util.HashMap$Values.forEach(HashMap.java:981)
> 	at com.ibm.fhir.persistence.jdbc.dao.impl.TransactionDataImpl.persist(TransactionDataImpl.java:46)
> 	at com.ibm.fhir.persistence.jdbc.impl.CacheTransactionSync.beforeCompletion(CacheTransactionSync.java:57)
> 	at com.ibm.tx.jta.impl.RegisteredSyncs.coreDistributeBefore(RegisteredSyncs.java:247)
> 	at com.ibm.tx.jta.impl.RegisteredSyncs.distributeBefore(RegisteredSyncs.java:148)
> 	at com.ibm.tx.jta.impl.TransactionImpl.prePrepare(TransactionImpl.java:1402)
> 	at com.ibm.tx.jta.impl.TransactionImpl.stage1CommitProcessing(TransactionImpl.java:793)
> 	at com.ibm.tx.jta.impl.TransactionImpl.processCommit(TransactionImpl.java:768)
> 	at com.ibm.tx.jta.impl.TransactionImpl.commit(TransactionImpl.java:711)
> 	at com.ibm.tx.jta.impl.TranManagerImpl.commit(TranManagerImpl.java:165)
> 	at com.ibm.tx.jta.impl.TranManagerSet.commit(TranManagerSet.java:113)
> 	at com.ibm.tx.jta.impl.UserTransactionImpl.commit(UserTransactionImpl.java:162)
> 	at com.ibm.tx.jta.embeddable.impl.EmbeddableUserTransactionImpl.commit(EmbeddableUserTransactionImpl.java:101)
> 	at com.ibm.ws.transaction.services.UserTransactionService.commit(UserTransactionService.java:72)
> 	at com.ibm.fhir.persistence.jdbc.connection.FHIRUserTransactionAdapter.end(FHIRUserTransactionAdapter.java:128)
> 	at com.ibm.fhir.persistence.helper.FHIRTransactionHelper.commit(FHIRTransactionHelper.java:43)
> 	at com.ibm.fhir.server.util.FHIRRestHelper.doCreate(FHIRRestHelper.java:282)
> 	at com.ibm.fhir.server.operation.spi.FHIRResourceHelpers.doCreate(FHIRResourceHelpers.java:43)
> 	at com.ibm.fhir.server.resources.Create.create(Create.java:83)

The bottom 8 levels of the stack do match what is in the original issue, and we see the transaction does get marked for rollback.

Since this appears to be working as expected, marking as closed.

**Comment by prb112** [comment]
@tbieste nothing gets persisted in the db2 db?

**Comment by tbieste** [comment]
If there's more I should do with this one, I'll reopen it.

**Comment by tbieste** [comment]
> @tbieste nothing gets persisted in the db2 db? Can we add a test case?

For DB2, the \u0000 character is stored in the DB successfully, so the commit is successful.  I can add a testcase if there's a good place for one.

**Comment by prb112** [comment]
`fhir-server-test` it can run on db2, derby, postgres and should have a consistent response.

**Comment by tbieste** [comment]
> `fhir-server-test` it can run on db2, derby, postgres and should have a consistent response.

Hmm... with Db2 the store will succeed, but PostgreSQL the store will fail.

**Comment by tbieste** [comment]
Also, an explanation for why this was detected recently.  In the original description, the `\u0000` character is in the Identifier.type.system field. That field only recently has become an extracted parameter in order to support the ":of-type" search modifier.  If the `\u0000` character would have been on other field, such as Identifier.system, it would have been happening prior to just recently.

**Comment by prb112** [comment]
Right - it shouldn't succeed

**Comment by tbieste** [comment]
I chatted with @punktilious:

> Db2 can handle the null byte sequences (which are valid UTF-8). From what I read, PostgreSQL uses null-terminated strings internally so can't support this. As there's no error with Db2, the transaction should commit as usual.

I'm going to go ahead and close this.
