### ISSUE TITLE
FHIRTerminologyGuide contains link to non-existent fhir-operation-term module

### ISSUE THREAD

**Issue by csandersdev** [IBM/FHIR#2174]
**Describe the bug**
The [FHIR Server Terminology Extended Operations section](https://ibm.github.io/FHIR/guides/FHIRTerminologyGuide#fhir-server-terminology-extended-operations) of the FHIRTerminologyGuide mentions and links to a project fhir-operation-term that does not/no longer exists.

**To Reproduce**
1. Navigate to [the link](https://ibm.github.io/FHIR/guides/FHIRTerminologyGuide#fhir-server-terminology-extended-operations)
2. Click on 'fhir-operation-term'
3. See Resource Not Found (404) error

**Expected behavior**
Documentation mentions the correct project and has valid links.

**Comment by prb112** [comment]
> **Describe the bug**
> The [FHIR Server Terminology Extended Operations section](https://ibm.github.io/FHIR/guides/FHIRTerminologyGuide#fhir-server-terminology-extended-operations) of the FHIRTerminologyGuide mentions and links to a project fhir-operation-term that does not/no longer exists.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
>     1. Navigate to [the link](https://ibm.github.io/FHIR/guides/FHIRTerminologyGuide#fhir-server-terminology-extended-operations)
> 
>     2. Click on 'fhir-operation-term'
> 
>     3. See Resource Not Found (404) error
> 
> 
> **Expected behavior**
> Documentation mentions the correct project and has valid links.

https://github.com/IBM/FHIR/pull/2175 <-- fixed here (it's missing the directory)

**Comment by prb112** [comment]
PS. Thank you for the bug

**Comment by prb112** [comment]
Website will update within 1 hr from this post
