### ISSUE TITLE
Provide the ability to retrieve a set of COMMON_TOKEN_VALUE_IDs in one request

### ISSUE THREAD

**Issue by michaelwschroeder** [IBM/FHIR#2184]
**Is your feature request related to a problem? Please describe.**
We have cases when building queries (processing inclusion criteria, processing :in, :not-in, :above, :below modifiers) where we want to attempt to retrieve COMMON_TOKEN_VALUE_IDs for a list of system+code pairs. It could be prohibitive performance-wise to go to the DB one-at-a-time for each cache miss.

**Describe the solution you'd like**
Provide a way to retrieve the COMMON_TOKEN_VALUE_IDs for a list of system+code pairs in a single request.

**Describe alternatives you've considered**
1. Using existing interface, risking going out to the DB for every cache miss
2. Don't use the COMMON_TOKEN_VALUE_IDs

**Acceptance Criteria**
1.  
   GIVEN [a precondition]
    AND [another precondition]
   WHEN [test step]
    AND [test step]
   THEN [verification step]
    AND [verification step]

**Additional context**

**Comment by lmsurpre** [comment]
the new QueryBuilder has support for handling an "in list" of common token values, so it will already handle conversion between `= 'a'` and `in (a,b,c)`, so just a matter of ensuring we get the values before that efficiently (even in face of cache misses)

**Comment by michaelwschroeder** [comment]
This issue has been verified. 

I started with a clean schema and performed a search using an :in modifier:
- verified via log that, as expected, for the values in the specified value set, all were cache misses
- verified that a DB query was executed to retrieve the common token value IDs for the cache misses
- verified that since none were found in the DB, a count query for the search was generated with only a -1 for the COMMON_TOKEN_VALUE_ID value

I then ingested resources which caused some of the values in the value set to be indexed and added to the DB and cache. I reran the search:
- verified via log that, as expected, for the values in the specified value set, all were cache misses except the ones that were indexed for the ingested resources
- verified a DB query was executed to retrieve the common token value IDs for the cache misses
- verified that since none of the misses were in the DB, a count query for the search was generated with only the cache hits specified for the COMMON_TOKEN_VALUE_ID values

I then stopped and restarted the server to clear the cache. I reran the search:
- verified via log that, as expected, for the values in the specified value set, all were cache misses
- verified a DB query was executed to retrieve the common token value IDs for the cache misses, and the ones that were indexed for the ingested resources were returned and added to the cache
- verified that a count query for the search was generated with only the DB hits specified for the COMMON_TOKEN_VALUE_ID values
