### ISSUE TITLE
Support compartment search via POST

### ISSUE THREAD

**Issue by tbieste** [IBM/FHIR#2187]
**Describe the solution you'd like**
Would like to be able perform compartment search via POST:

POST [base]/[Compartment]/[id]/[type]/_search{?[parameters]{&_format=[mime-type]}}

**Describe alternatives you've considered**
N/A

**Acceptance Criteria**
1.  
   GIVEN Resources exist in compartment on FHIR Server
   WHEN Compartment search via POST is performed
   THEN Search successful returns matching resources

**Additional context**
Compartment search is supported.
Search via POST is supported.
But compartment search via POST is not supported.

Note: don't forget to add it to the generated swagger/openapi too (a la #1846 )

**Comment by michaelwschroeder** [comment]
Running against my local server with the latest codebase, I have performed equivalent compartment searches using GET and POST methods via Postman and have verified the results returned are equivalent.
