### ISSUE TITLE
Patch Replaces Can Save Invalid Types

### ISSUE THREAD

**Issue by ssnowski** [IBM/FHIR#2207]
**Describe the bug**
When saving with patch, it seems like it can corrupt existing resources, preventing them from being retrieved properly.  This seems to be possible by making a request to save an element as a different type than it was previously (EG: save a valueString in the Patient.extension field (type: Extension).

**Environment**
IBM FHIR Server 4.6.1 via docker image.   presumably 4.6.0 as well, but untested

**To Reproduce**
1. Setup:
```
POST to fhir-server/api/v4:
{
        "resourceType": "Bundle",
        "type": "transaction",
        "entry": [
        {
                "resource": {
                        "id": "1234",
                        "resourceType": "Patient",
                        "identifier": [{
                                "system": "ibm.com/mrn",
                                "value": "1234"
                        }],
                        "extension": [
                          {
                            "url": "https://ibm.com/ext1",
                            "valueString": "testExtension"
                          }
                        ]
                },
                "request": {
                        "url": "Patient/1234",
                        "method": "PUT"
                }
        }
        ]
}
```

2. Corrupt the data:
```
POST to fhir-server/api/v4:
{
  "resourceType": "Bundle",
  "type": "transaction",
  "entry": [
    {
      "request": {
        "url": "Patient/1234",
        "method": "PATCH"
      },
      "resource": {
        "resourceType": "Parameters",
        "parameter": [
          {
            "name": "operation",
            "part": [
              {
                "name": "type",
                "valueCode": "replace"
              },
              {
                "name": "value",
                "valueString": "this isn't an extension"
              },
              {
                "name": "path",
                "valueString": "Patient.extension[0]"
              }
            ]
          }
        ]
      }
    }
  ]
}
```
3. See the error:
```
GET to fhir-server/api/v4/Patient/1234
```

**Expected behavior**
I would have expected step 2 to fail, returning a 4xx error with some text about a type mismatch.

**Additional context**

**Comment by tbieste** [comment]
@lmsurpre Attempted the steps to reproduce and it returns with a 500 Internal Server Error with the following response:

{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "fatal",
            "code": "exception",
            "details": {
                "text": "FHIRPatchException: An error occurred while replacing the value"
            }
        }
    ]
}

Instead of getting some type of 4xx error, is this the expected behavior?

**Comment by tbieste** [comment]
It now returns a 400 Bad Request Error, which matches the expected behavior.

> "issue": [
>         {
>             "severity": "error",
>             "code": "invalid",
>             "details": {
>                 "text": "Invalid patch: An error occurred while replacing the value"
>             },
>             "expression": [
>                 "Patient.extension[0]"
>             ]
>         }
>     ]

Closing.
