### ISSUE TITLE
Intermittent build failures due to a Spark driver issue

### ISSUE THREAD

**Issue by JohnTimm** [IBM/FHIR#2218]
The Spark driver used by bulkdata webapp causes the build to intermittently fail due to the following error:

```
java.net.BindException: Cannot assign requested address: Service ‘sparkDriver’ failed after 16 retries (starting from 38000)! Consider explicitly setting the appropriate port for the service ‘sparkDriver’ (for example spark.ui.port for SparkUI) to an available port or increasing spark.port.maxRetries
```

We originally thought that there was a port conflict between the Sparq driver and Berkeley DB Java Edition (used by Janusgraph). This prompted the following change:

```java
        spark = SparkSession.builder()
            .appName("parquetWriter")
            .master("local[*]")
            .config("spark.ui.enabled", false)
            .config("spark.driver.port", "38000")
            .getOrCreate();
```

setting the (starting) port to 38000 thinking this would avoid the conflict. Unfortunately the problem persists. @prb112 suggested that we change the maxRetries value to 1000.

**Comment by lmsurpre** [comment]
We've done quite a few builds since this was merged and I havn't seen that issue again yet...lets consider it fixed and we can reopen if it pops up again.
