### ISSUE TITLE
Add support for POST of empty objects

### ISSUE THREAD

**Issue by csandersdev** [IBM/FHIR#2222]
I encountered an issue where the CQL engine we are using tried to do a POST to ``/ValueSet/<someid>/$expand`` with an empty parameters object (e.g. ``{"resourceType": "Parameters"}``) and the IBM FHIR server failed to process the request because of the empty object. For example...

```
$ curl -X POST -H 'Content-Type: application/json' -d '{"resourceType":"Parameters"}' 'https://localhost:9443/fhir-server/api/v4/ValueSet/2.16.840.1.113883.3.464.1003.108.12.1001/$expand'

{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "fatal",
            "code": "invalid",
            "details": {
                "text": "FHIRProvider: global-1: All FHIR elements must have a @value or children"
            },
            "expression": [
                "<no expression>"
            ]
        }
    ]
}
```

**Describe the solution you'd like**
Parsing of empty objects was discussed in Zuplip [here](https://chat.fhir.org/#narrow/stream/179202-terminology/topic/CodeSystem.20.24lookup/near/190328714) and turned into an issue that was voted on and approved for FHIR R4B [here](https://jira.hl7.org/browse/FHIR-26565). I propose that we add support for empty objects to IBM FHIR in support of this vote.

**Describe alternatives you've considered**
As a workaround, clients can generally convert a request with an empty parameters body from POST to GET, but the spec allows this only when operations have the "affectsState" property set to false. The affectsState property does not seem to be widely used, so it is difficult to use this to determine behavior at runtime.

**Acceptance Criteria**
1.  
   WHEN the user does a POST to an operation with an empty parameters object
   THEN the FHIR server will successfully parse the parameters and pass the object along to the operation

**Comment by prb112** [comment]
```
curl --location --request POST 'https://localhost:9443/fhir-server/api/v4/$reindex?resourceCount=1' \
--header 'X-FHIR-TENANT-ID: default' \
--header 'Content-Type: application/fhir+json' \
--header 'Authorization: Basic ....' \
--data-raw '{"resourceType":"Parameters"}'
```

Received 200 back and the correct response.

proceeding to negative tests

**Comment by prb112** [comment]
```

**Comment by prb112** [comment]
That is actually valid.  So we're all set.
