### ISSUE TITLE
Remove fhir-cli

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#2226]
**Is your feature request related to a problem? Please describe.**
Deprecate and remove fhir-cli

**Describe the solution you'd like**
The feature is not used much, and surface area we should probably update if we want to support, else remove it.

**Describe alternatives you've considered**
n/a

**Acceptance Criteria**
The module should not be there.

**Additional context**

**Comment by lmsurpre** [comment]
Probably no need for a deprecation period since it is its own separate standalone-module.
Anyone wishing to continue using it can use the last published version.

**Comment by lmsurpre** [comment]
I found one last reference to the module and opened https://github.com/IBM/FHIR/pull/2537/files to clear that out.

**Comment by lmsurpre** [comment]
done
