### ISSUE TITLE
Add server configuration option to control the default page size for search

### ISSUE THREAD

**Issue by csandersdev** [IBM/FHIR#2229]
**Is your feature request related to a problem? Please describe.**
When the client does not specify a page count for search the server defaults to a page size of 10 and there is no way to change it.

**Describe the solution you'd like**
I would like the ability to control the default page size on the server so that it is increased for each request without specifying it in each client request.

**Describe alternatives you've considered**
If the client wants a different page size, it can provide the _count parameter on each request. We may not always have control of the client code and it would be nice to be able to control default behavior on the server side.

**Acceptance Criteria**
1.  
   GIVEN [a configuration property exists in the server config file]
    AND [the user has configured the server with a different value than the default]
   WHEN [the user searches for any resource without specifying the _count parameter]
   THEN [the server uses the page size configured in the server config file]
2.  
   GIVEN [no page size configuration is specified in the server config file]
   WHEN [the user searches for any resource without specifying the _count parameter]
   THEN [the server uses the default page size (10)]
3.
   GIVEN [a configuration property exists in the server config file]
    AND [the user has configured the server with a value larger than the maximum allowed size]
   WHEN [the user searches for any resource without specifying the _count parameter]
   THEN [the server logs a warning and uses the maximum allowed page size]

**Comment by tbieste** [comment]
I verified the acceptance criteria using a local server, and all 3 criteria work as expected. Closing.
