### ISSUE TITLE
update-05-version-aware tests failed

### ISSUE THREAD

**Issue by albertwang-ibm** [IBM/FHIR#224]
There were 14 test errors due to the setup failure of the testscript, per discussion with touchstone, this should be a touchstone testscript defect, touchstone team already added this defect to their queue, we will need to re-run the test to find out if there if any other issue when the touchstone fix is ready.

https://touchstone.aegis.net/touchstone/scriptexecution?exec=201910090957018398892466&qn=/FHIR4-0-0-Advanced/Patient/04-update/fhir-api-r4-patient-update-05-version-aware#WAITING_OPER

**Comment by senthilbak** [comment]
problem is in test suite. waiting for fix from Touchstone.

**Comment by senthilbak** [comment]
Touchstone fixed the test. Albert verified.
