### ISSUE TITLE
ServerRegistryResourceProvider cache invalidation is problematic in multi-server environments

### ISSUE THREAD

**Issue by JohnTimm** [IBM/FHIR#2255]
The `ServerRegistryResourceProvider` class implements both `FHIRRegistryResourceProvider` and `FHIRPersistenceInterceptor`. Registry resources read from the persistence layer are cached in a tenant/datastore specific cache that gets invalidated on `afterCreate`, `afterUpdate`, and `afterDelete` events. Unfortunately this only works if the Create/update/delete was performed through the same server where the cache resides. In multi-server environments some of the nodes may end up with stale data. The caching feature should be removed from the `FHIRRegistryResourceProvider` or it should be cache with a time-based eviction policy.

**Comment by kmbarton423** [comment]
created a CodeSystem resource containing code=icecream
GET  https://localhost:9443/fhir-server/api/v4/CodeSystem/hungrycaterpillar/$validate-code?code=icecream
immediately updated the CodeSystem removing code=icecream
repeated $validate multiple times to confirm that the cached code was evicted within a minute
