### ISSUE TITLE
trustDefaultCerts=true by default in liberty configuration (server.xml)

### ISSUE THREAD

**Issue by JohnTimm** [IBM/FHIR#2271]
Per OpenLiberty documentation (https://openliberty.io/docs/21.0.0.3/reference/config/ssl.html):

```
Specifies whether the trust manager can establish trust by using the  default certificates. If set to true, then the default certificates are  used in addition to the configured truststore file to establish trust.  The attribute is set to false by default.
```

**Comment by prb112** [comment]
Already added - moved to QA 
https://github.com/IBM/FHIR/blob/d4a7538816320c473178631abfadc6520f632703/fhir-server/liberty-config/configDropins/defaults/trustDefault.xml

**Comment by kmbarton423** [comment]
Built/ran Docker container with default FHIR server configuration. 
Added SNOMED to the FHIR server configuration (remoteTermServiceProviders).
Confirmed successful code lookup to SNOMED when variable SEC_TLS_TRUSTDEFAULTCERTS defaults true.

Below are the contents of trustDefault.xml:

<server description="fhir-server">
    <ssl id="defaultSSLConfig" trustDefaultCerts="${SEC_TLS_TRUSTDEFAULTCERTS}"/>
    <variable name="SEC_TLS_TRUSTDEFAULTCERTS" defaultValue="true"/>
</server>
