### ISSUE TITLE
Avoid redundant reads during update interaction

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#2283]
**Is your feature request related to a problem? Please describe.**
Doing a single read before the update makes sense, because we need to pull the current version out of the db to set the new version.
However, presently, we do this read multiple times.

Firstly, around line 432 in my local version, we do this:
```
        ior.setPrevResource(doRead(type, id, (patch != null), true, newResource, null, false));
```

Then, a little lower (around line 460 in FHIRRestHelper), we do it again:
```
                try {
                    doRead(type, id, (patch != null), false, newResource, null, false);
                } catch (FHIRPersistenceResourceDeletedException e) {
                    isDeleted = true;
                }
```

The second read is just to see if its deleted or not.
Is there a better way?

**Describe the solution you'd like**
Determine whether the resource is deleted or not the first time we read it.  Probably needs design.

**Describe alternatives you've considered**
Push more of this into the persistence layer

**Acceptance Criteria**

**Additional context**

**Comment by punktilious** [comment]
There is a better way...

```
    SingleResourceResult<? extends Resource> doRead(String type, String id, boolean throwExcOnNull, boolean includeDeleted,
            Resource contextResource, MultivaluedMap<String, String> queryParameters) throws Exception;
```

The doRead functions now return a SingleResourceResult which has been augmented with the deleted status flag. The read is now only performed once.

**Comment by lmsurpre** [comment]
I found another case where we are performing a redundant read:  https://github.com/IBM/FHIR/issues/2478

**Comment by lmsurpre** [comment]
I ran the server in debug mode and confirmed we only perform a single update now (in the case of a "true" update).
