### ISSUE TITLE
Expand support of X-FHIR-UPDATE-IF-MODIFIED to batch/transaction entries

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#2284]
**Is your feature request related to a problem? Please describe.**
In https://github.com/IBM/FHIR/issues/2263 we added support for a server-side update optimization.
However, this optmization was only implemented for PUT requests.
Now I'd like to expand that to apply to batch/transaction interactions that contain PUTs as well.

**Describe the solution you'd like**
When users set X-FHIR-UPDATE-IF-MODIFIED to true, each PUT request within the bundle will be processed according to the "skippableUpdate" processing.

**Describe alternatives you've considered**

**Acceptance Criteria**
1.  
   GIVEN an existing resource in the server
   WHEN we get an update request as part of a batch request
    AND the X-FHIR-UPDATE-IF-MODIFIED header is set to true
   THEN avoid performing the update
    AND return the existing resource as appropriate (per the `Prefer: return` request)

**Additional context**

**Comment by kmbarton423** [comment]
Ran a variety of bundles with PUT requests (both type=batch and type=transaction) with a mix of resources that were and were not equivalent to what already persisted.  Confirmed the following OperationOutcome was received for those resources where equivalency was true and X-FHIR-UPDATE-IF-MODIFIED was test to true:

'''        {
            "resource": {
                "resourceType": "OperationOutcome",
                "issue": [
                    {
                        "severity": "information",
                        "code": "informational",
                        "details": {
                            "text": "Update resource matches the existing resource; skipping the update"
                        }
                    }
                ]
            },
'''
