### ISSUE TITLE
Add support for generating constraints from slices with the "profile" discriminator type

### ISSUE THREAD

**Issue by JohnTimm** [IBM/FHIR#2290]
We currently don't support the "profile" discriminator type when generating constraints from slices and therefore we end up with FHIRPath constraints that are syntactically valid but lead to an IllegalArgumentException. For example:

```
contained.exists() implies (contained.exists() and contained.conformsTo('http://hl7.org/fhir/us/spl/StructureDefinition/USAgentAffiliation'))
```

The constraint is syntactically correct but the `conformsTo` function will generate an `IllegalArgumentException` because it checks `isResource` and `isElement` which both check `isSingleton`.

**Comment by lmsurpre** [comment]
See #2288 for the IG that causes this issue

**Comment by prb112** [comment]
Moved to QA

**Comment by prb112** [comment]
Reviewed and discussed with John - closing the issue.
