### ISSUE TITLE
appears a subset of tests are being run twice in FHIRServerIntegrationTests

### ISSUE THREAD

**Issue by kmbarton423** [IBM/FHIR#2291]
Found a problem today with one of the profile specific tests included in the fhir server integration test bucket.  Interestingly, the failure for that single test showed up twice in the results of the test run.  

Working in Eclipse with IBM FHIR Server 4.7.0+ ... latest version of main

Did the following:
 1. configured fhir-server-config with snomed remote term service provider 
          "term": {
             "remoteTermServiceProviders": [{
                "__comment": "Configuration for public SNOMED-CT endpoint",
                "enabled": true,
                "base": "https://snowstorm-fhir.snomedtools.org/fhir",
                "supports": [{
                    "system": "http://snomed.info/sct"
                }]
            }]
        },
2.  ran integration test
     fhir-server-test->src/test/java->testng.xml   (Run as TestNG Suite)

Expected all tests to pass but found one test failed twice (see attachment):
"com.ibm.fhir.server.test.profiles.USCoreObservationSmokingStatusTest" failed "loadResources"
    once as part of "Server Tests" and once as part of "Profile Tests"

Why was this profile test run more than once?

**Comment by kmbarton423** [comment]
![profileFailure](https://user-images.githubusercontent.com/69682345/116156937-28965200-a6ba-11eb-9325-455fcb856bc6.png)

**Comment by prb112** [comment]
I looked into this issue in more detail. - per testng `If the package name ends with .* then subpackages are included too.` in this case we are not using package-names. I think this is an artifact only in Eclipse with the testng plugin, and it's not actually running twice.  phew...
