### ISSUE TITLE
BYOP and DB2OnCloudSetup has out of date instructions for datasource configuration

### ISSUE THREAD

**Issue by csandersdev** [IBM/FHIR#2303]
**Describe the bug**
The documentation at [DB2OnCloudSetup](https://ibm.github.io/FHIR/guides/DB2OnCloudSetup/#configuring-an-ibm-fhir-server-datasource) documentation shows the pre-4.6.0 way of doing datasource configuration. It should be updated to reflect the new style of configuration.

There is also a reference to ``jndi/fhirProxyDataSource`` in [BringYourOwnPersistence#config](https://ibm.github.io/FHIR/guides/BringYourOwnPersistence/#config) that I believe should be updated or removed. In [FHIRServerUsersGuide 3.3.1 The JDBC Persistence Layer](https://ibm.github.io/FHIR/guides/FHIRServerUsersGuide/#331-the-jdbc-persistence-layer), it says that the default JNDI name is now jdbc/fhir_tenantId_dsId, so I feel like BYOP is out of date.

**Environment**
4.7.1

**To Reproduce**
1. Go to the Configuring an IBM FHIR Server datasource section of the DB2OnCloudSetup documentation and note that it still uses connectionProperties.
2. Got to the Config section of BringYourOwnPersistence and note the reference to jndi/fhirProxyDataSource as the default.

**Expected behavior**
Documentation is updated to be correct for the latest release.

**Comment by lmsurpre** [comment]
Separate, but Corery also mentioned to me that `fhirServer/persistence/datasources/<datasourceId>/jndiName` is missing from the tables in section 5 of the user's guide.

**Comment by lmsurpre** [comment]
@csandersdev the guides are now updated and so I'm marking this closed.  please have a look and re-open / contact us if you have further questions/concerns.
