### ISSUE TITLE
Search with both '_total=none' and '_include' or '_revinclude' parameter fails with FHIRPersistenceDataAccessException

### ISSUE THREAD

**Issue by michaelwschroeder** [IBM/FHIR#2305]
**Describe the bug**
When performing a search that includes both a `_total=none` search parameter and an `_include` or `_revinclude` search parameter, and for which no 'match' resources are returned, we fail with a `FHIRPersistenceDataAccessException: Failure retrieving FHIR objects` exception.

**Environment**
4.7.1

**To Reproduce**
1. run the following search query: `.../Patient?_id=bad-id&_total=none&_include=Patient:organization`

**Expected behavior**
The search returns with 0 search results and no error.

**Additional context**

**Comment by kmbarton423** [comment]
Confirmed behavior of _total=none when combined with _include and _revinclude for which no 'match' resources are returned as well as when 'match' resources are returned.  Fix looks good.
