### ISSUE TITLE
Add support for the TerminologyCapabilities resource via the capabilities interaction

### ISSUE THREAD

**Issue by JohnTimm** [IBM/FHIR#2342]
There is an optional "mode" parameter on the capabilities interaction than can be used to expose a `TerminologyCapabilities` resource:

`<base>/fhir-server/api/v4/metadata?mode=terminology`

`TerminologyCapabilities` resource:
http://hl7.org/fhir/terminologycapabilities.html

Capabilities interaction:
http://hl7.org/fhir/http.html#capabilities

**Comment by lmsurpre** [comment]
I confirmed that a request to `GET [base]/metadata?mode=terminology` now returns a valid TerminologyCapabilities resource.

Additiionally, I started up a server with the `serverRegistryResourceProvider` enabled, posted a new codesystem, and confirmed that this codesystem appears in in the TerminologyCapabilities (after the cached copy times out).
