### ISSUE TITLE
Update Capabilities.java to use fhir-cache

### ISSUE THREAD

**Issue by JohnTimm** [IBM/FHIR#2344]
Capabilities.java currently uses a `ConcurrentMap` to manage a tenant-specific cache for the capabilities statement. This could be updated to use a `fhir-cache` managed cache with a time-based eviction policy.

**Comment by lmsurpre** [comment]
After setting the `fhirServer/core/capabilityStatementCacheTimeout` property to 1 (minute), I ran the following two tests.

1. GET [base]/metadata
2. get it again right away and confirm that its cached (by noting response time and CapabilityStatement.date)
3. wait a minute, then try again.

1. GET [base]/metadata?mode=terminology
2. get it again right away and confirm that its cached (by noting response time and TerminologyCapabilities.date)
3. wait a minute, then try again

In each case, the resource was server cached in step 2 and served fresh on step 3.
