### ISSUE TITLE
Allocate Tenant without TenantKey Fails in the ibm-fhir-schematool on db2

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#2349]
**Describe the bug**
Allocate Tenant without TenantKey Fails in the ibm-fhir-schematool on db2

**Environment**
Which version of IBM FHIR Server?
4.7.1

**To Reproduce**
1. Run 
```
docker run ibm-fhir-schematool:latest-debug --tool.behavior=onboard --db.host=localhost \
    --db.port=50000 --user=db2inst1 --password=change-password --db.database=fhirdb \
    --sslConnection=false --db.type=db2 --schema.name.fhir=CLINIC3 --grant.to=testuser \
    --tenant.name=ic3
```
2. Check the exit code `$?` and it returns 1 which is unexpected. 

**Expected behavior**
Allocation should complete with exit code 0 and then proceed to test-tenant

**Additional context**
Reported by Client

**Comment by prb112** [comment]
PR https://github.com/IBM/FHIR/pull/2351

**Comment by kmbarton423** [comment]
Verified behavior via docker run of ibm-fhir-schematool with db2 on ibmcloud

(output at run conclusion)
2021-05-14 18:28:55.098 00000001  INFO  com.ibm.fhir.schema.app.Main SCHEMA CHANGE: OK
+ echo 0
+ set +x
Successful Setup of: 
TENANT_NAME: KMB
TENANT_KEY: rzpTU7STgHWdiAIBKLplKb++W+apo4k7yAmGysxwnsc=
