### ISSUE TITLE
Add support for default version of registry resources

### ISSUE THREAD

**Issue by JohnTimm** [IBM/FHIR#2356]
`FHIRRegistryResource.getResource(String url)` currently parses the url parameter as a canonical url (`<url>|<version>`). If the version is not present, then it will look for all versions with the given url across all registry resource providers. It will then dedup/sort this list and return the "latest version". In addition to "latest version" there is a notion of "default version". The "default version" may be designated by an implementation (see `TerminologyCapabilities.codeSystem.version.isDefault` for an example of this).

We should make the following changes to support the idea of a "default version".
- Add a `defaultVersion` field to the `FHIRRegistryResource` class along with constructor(s) that include `defaultVersion` as a parameter and an `isDefaultVersion` method
- Add factory methods that create `FHIRRegistryResource` instances and allow for a `defaultVersion` to be specified
- Add unit tests to test "default version" and "latest version" behavior
- Update `FHIRRegistry`, `PackageRegistryResourceProvider` and `ServerRegistryResourceProvider` to use "default version" when a version is not specified

If no version is designated as the "default version", then the logic falls back to "latest version" based on sort order. If multiple versions are designated as the "default version" then the first one encountered will be used.

We also discussed the potential for supporting a `defaultVersion` field in the `.index.json` NPM package format we use to load resources for a `PackageRegistryResourceProvider` but decided it was lower priority.

We may want to consider an extension that allows a client to specify that a particular definitional resource (e.g `CodeSystem`, `StructureDefinition`, etc.) has a business `version` that is intended to be the `default` version. We could then update `FHIRRegistryResource.from` method to use that extension (if it exists).

**Comment by tbieste** [comment]
I verified in my dev workspace that if the `FHIRRegistryResource.from` method sets `default` to true for a CodeSystem version, then the `<base>/metadata?mode=terminology` API shows `isDefault: true` for that CodeSystem version. More complete QA of the functionality can be done when there is a way for a client to indicate the default version of definitional resource via an extension is implemented in the future.
