### ISSUE TITLE
Document serverRegistryResourceProviderEnabled and missing extension-search-parameters.json in performance guide

### ISSUE THREAD

**Issue by punktilious** [IBM/FHIR#2364]
**Description**
When serverRegistryResourceProviderEnabled is true, StructureDefinition resources are searched in DB during ingestion. Update the performance guide to recommend setting this to false to improve ingestion performance.

If extension-search-parameters.json is missing, search param extraction tries to open it for every resource. This is a file-system operation which results in a context switch and will impact performance. Update the performance guide to recommend that this file is included for every tenant, even if empty.

**Environment**
4.8.0

**Comment by lmsurpre** [comment]
here is a minimal extensiono-search-parameters.json that i've used with success
```
{
  "resourceType": "Bundle",
  "type": "collection",
  "entry": []
}
```

**Comment by prb112** [comment]
PR https://github.com/IBM/FHIR/pull/2446

**Comment by punktilious** [comment]
Changes in PR are OK.
