### ISSUE TITLE
Support for Azure Blob

### ISSUE THREAD

**Issue by d0roppe** [IBM/FHIR#2374]
**Is your feature request related to a problem? Please describe.**
Investigate the setup and use of S3Proxy to access Azure Blob but with existing S3 API access.

This is a potential alternative to MinIO for S3 support into 

**Describe the solution you'd like**
Have a 3rd party addition in the Azure env to allow S3 access into Azure Blob without any code changes. 

**Describe alternatives you've considered**

**Acceptance Criteria**
1.  
   GIVEN [a precondition]
    AND [another precondition]
   WHEN [test step]
    AND [test step]
   THEN [verification step]
    AND [verification step]

**Additional context**

**Comment by prb112** [comment]
Clarification: We do not use S3 as a proxy.  We use it as an IntegrationTest environment.

**Comment by prb112** [comment]
I've implemented  Azure Blob support

**Comment by d0roppe** [comment]
Moved this back to in-progress as a couple of exports are not fully working correctly.

**Comment by d0roppe** [comment]
Ran the test with the latest code and it was working as expected. Closing the issue.
