### ISSUE TITLE
Add Support for Pattern Value Constraint with $this in the Path

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#2377]
**Is your feature request related to a problem? Please describe.**
Add Support for Pattern Value Constraint with $this in the Path

support canonical pattern value constraints

We generate a constraint =  "generated-C4BB-Organization-1: Constraint violation: meta.where(lastUpdated.exists() and profile = 'http://hl7.org/fhir/us/carin-bb/StructureDefinition/C4BB-Organization%7C1.0.0').exists()"
should this be = or an in http://hl7.org/fhirpath/#in-membership
Currently, we say the following is an error, however profile is an array...
```json
{
  "resourceType" : "Organization",
  "id" : "OrganizationProvider1",
  "meta" : {
    "lastUpdated" : "2019-12-12T09:14:11+00:00",
    "profile" : [
      "http://hl7.org/fhir/us/carin-bb/StructureDefinition/C4BB-Organization",
      "http://hl7.org/fhir/us/carin-bb/StructureDefinition/C4BB-Organization|1.0.0"
    ]
  }
}
```
https://build.fhir.org/ig/HL7/carin-bb/Organization-OrganizationProvider1.html

they had a constraint on the number of profiles, I'm opening a JIRA issue for it

**Comment by lmsurpre** [comment]
> they had a constraint on the number of profiles, I'm opening a JIRA issue for it

![image](https://user-images.githubusercontent.com/5478798/118639612-1897fc80-b7a6-11eb-81a1-e10567b6eb10.png)

What they're trying to say here is that at least one of the profiles should be `http://hl7.org/fhir/us/carin-bb/StructureDefinition/C4BB-Organization%7C1.0.0`.
The profile element itself is `1..*`, its just the slice with this pattern that is `1..1`.

Net:  I think this is solely our issue and I think the IG is just fine.

**Comment by prb112** [comment]
hum... I thought this asserted that the canonical pattern has to be...

**Comment by prb112** [comment]
@JohnTimm I think you've already implemented this?

**Comment by prb112** [comment]
I've already tried this out. 
QA done
