### ISSUE TITLE
Make schema drop idempotent

### ISSUE THREAD

**Issue by punktilious** [IBM/FHIR#2401]
If a procedure doesn't exist, this may cause the drop to fail.

For PostgreSQL use:
```
DROP PROCEDURE foo IF EXISTS;
```

For other databases, the catalog may need to be queried first to see if the procedure exists. This gets complicated because of parameter overloading.

**Comment by prb112** [comment]
FYI - we do query the catalog on db2 for the unique ids, and wipe them.
