### ISSUE TITLE
Erase operation is repeated many times in the CapabilityStatement

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#2406]
**Describe the bug**
I’m seeing this in our /metadata response:
```
                    ],
                    "operation": [
                        {
                            "name": "erase",
                            "definition": "http://ibm.com/fhir/OperationDefinition/erase",
                            "documentation": "The erase operation remove an instance of a resource, or a version of an instance of a resource."
                        },
                        {
                            "name": "erase",
                            "definition": "http://ibm.com/fhir/OperationDefinition/erase",
                            "documentation": "The erase operation remove an instance of a resource, or a version of an instance of a resource."
                        },
                        {
                            "name": "erase",
                            "definition": "http://ibm.com/fhir/OperationDefinition/erase",
                            "documentation": "The erase operation remove an instance of a resource, or a version of an instance of a resource."
                        },
                        {
                        ...
```

**Environment**
4.8.1

**To Reproduce**
1. start the server
2. retrieve the CapabilityStatement from [base]/metadata

Note that it contains thousands of operation entries for the `erase` operation

**Expected behavior**
The `erase` operation is only listed once per resource type.

**Additional context**

**Comment by prb112** [comment]
We had a ArrayList and converted to LinkedHashSet so it dedupes naturally. Otherwise we're kind of susceptible to duplicates.

**Comment by lmsurpre** [comment]
I confirm that with these changes, our default CapabilityStatement is back down from 1.9MB to just over 1MB.
I searched the output for `http://ibm.com/fhir/OperationDefinition/erase` and found 146 entries which is about what we'd expect. LGTM.
