### ISSUE TITLE
Enable Spec Driver using Dynamic Test Factory

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#241]
The current tests use a single test to wrap many spec driver executions.  This approach belies the total testing that is done. 

** Steps ** 
1 - Implement TestNg Dynamic Test Factory 
2 - Apply to fhir-model 
3 - Apply to fhir-server-tests
4 - Apply to fhir-search 
5 - Check for other locations

**Comment by lmsurpre** [comment]
not sure i totally agree with the motivations behind this one; number of tests is not a great metric and making a change just to inflate that number seems a bit odd

**Comment by prb112** [comment]
I understand where you are coming from, I think there is some logic to breaking out into a separate series of tests. 

If it's something worked on, we can convert to lower case for the testType.
