### ISSUE TITLE
Vanity URLs with AWS result in bucket NOT_FOUND on $import

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#2411]
**Describe the bug**
Vanity URLs with AWS result in bucket NOT_FOUND on $import

**Environment**
Which version of IBM FHIR Server? 4.8.1

**To Reproduce**
1. On AWS, create a bucket such as my-bucket
2. Configure bulkdata with a external and internal endpoint with the bucketized url https://my-bucket.s3.notmyhost.host.com
Note: the api endpoint works fine.
3. Execute an $import with a file that exist

**Expected behavior**
The File should be imported

**Additional context**
@d0roppe found this while testing.

**Comment by prb112** [comment]
PR  https://github.com/IBM/FHIR/pull/2465/files

**Comment by d0roppe** [comment]
with the documented change of only allowing the vanity URL on the endpointExternal URL it is working
            "endpointInternal": "https://s3.region.host-name.com",
            "endpointExternal": "https://bucket-name.s3.region.host-name.com",
