### ISSUE TITLE
Add operations for clearing terminology caches

### ISSUE THREAD

**Issue by csandersdev** [IBM/FHIR#2421]
**Is your feature request related to a problem? Please describe.**
The terminology subsystem caches terminology resources (e.g. CodeSystems and ValueSets) such that when a resource change is made to the same URL and version, the resource changes are not immediately reflected in all operation results (e.g. validate-code).

**Describe the solution you'd like**
I would like for the server to either clear the cache automatically on resource update (difficult to do right now because the cache is not shared between clustered nodes) or provide mechanism through which a client application can clear the cache on demand.

**Describe alternatives you've considered**
This isn't an issue if the client application does not try to reuse the same URL and version, but that is common at dev time. There is a server flag ``fhirServer/term/disableCaching`` that was introduced that will disable caching in the terminology subsystem, but is not desirable for a production application. We have a production use case that wants caching, but also wants to be able to clear the cache after updating a single resource url + version.

**Acceptance Criteria**

1.  
   GIVEN a valueset resource exists
    AND the valueset cache has been populated (e.g. $validate-code operation called)
   WHEN the valueset resource is updated
    AND the clear-cache operation is called on that resource
   THEN the next valueset operation returns the correct result for the new resource.

2.  
   GIVEN a codesystem resource exists
    AND the codesystem cache has been populated (e.g. $validate-code operation called)
   WHEN the codesystem resource is updated
    AND the clear-cache operation is called on that resource
   THEN the next codesystem operation returns the correct result for the new resource.

3.  
   GIVEN an intensional valueset resource exists
    AND the codesystem cache has been populated (e.g. ValueSet/xxx/$expand operation called)
   WHEN the codesystem resource is updated
    AND the clear-cache operation is called on that resource
   THEN the next valuset expand operation returns the correct result for the new resource.

**Additional Context**
It is a known constraint that the FHIR server caches are JVM-local. In the event that a clear-cache operation is needed, the client application will need to call clear-cache on each FHIR server in a cluster.

**Comment by lmsurpre** [comment]
A potential workaround for this is to do a rolling restart of the fhir-server pods if you really need to clear the caches.

**Comment by JohnTimm** [comment]
> A potential workaround for this is to do a rolling restart of the fhir-server pods if you really need to clear the caches.

@lmsurpre the other option we discussed is using the `fhirServer/term/disableCaching` configuration option during `CodeSystem` and `ValueSet` development. The clear cache operations give finer grained control over what gets invalidated down to specific value sets.

**Comment by prb112** [comment]
Corey implemented this feature, I've marked as QA

**Comment by prb112** [comment]
No further references/Updates, I am closing it as complete.
