### ISSUE TITLE
Missing identifier modifier in FHIRParameters.Modifier enum

### ISSUE THREAD

**Issue by csandersdev** [IBM/FHIR#2427]
**Describe the bug**
The conformance guide says that we support the Reference :identifier modifier, but it is not declared in the fhir-client module FHIRParameters.Modifier enum.

**Environment**
4.8.1

**To Reproduce**
1. View the code for the FHIRParameters.Modifier enum and note that identifier is missing.

**Expected behavior**
All supported modifiers are declared in the enum.

**Comment by csandersdev** [comment]
Something else to consider here is the value/utility of the TYPE member of the FHIRParameters.Modifier enum. If I'm writing client code and I want to filter on a specific type (e.g. `new FHIRParameters().searchParam( "subject", Modifier.TYPE, "23" )`) isn't going to spit out what I want. It would be more useful to the client to have the ResourceTypes available as modifiers or specifiable in the searchParam method signature.

**Comment by csandersdev** [comment]
One more thought on FHIRParameters is that [reference chaining](https://www.hl7.org/fhir/search.html#chaining) is not well supported in the FHIRParameters class right now. If I wanted to do `/Observation?subject:Patient.name=peter`, I would have to construct that myself in the name of the query parameter vs. having the client construct it for me.

**Comment by csandersdev** [comment]
Looks like we are also missing the "of-type" modifier for token.

**Comment by csandersdev** [comment]
This covers most of what I mentioned above, but do we want to do anything in this PR around my [third comment](https://github.com/IBM/FHIR/issues/2427#issuecomment-848055935) above regarding reference chaining? I'd be happy to split that into a separate issue if the team wants to handle that separately.

**Comment by tbieste** [comment]
> This covers most of what I mentioned above, but do we want to do anything in this PR around my [third comment](https://github.com/IBM/FHIR/issues/2427#issuecomment-848055935) above regarding reference chaining? I'd be happy to split that into a separate issue if the team wants to handle that separately.

Yeah, I prefer to keep things close to the original bug; to avoid feature creep in work items.  If this satisfies the original bug, then opening a separate issue for the item in your [third comment] sounds good to me.

**Comment by lmsurpre** [comment]
Confirmed that the new prefixes were added to the enums and that the new `:[type]` modifier methods have unit test coverage.
