### ISSUE TITLE
Deprecate extended codeable concept validation configuration parameter in favor of a more accurate name (e.g. extended coded element validation)

### ISSUE THREAD

**Issue by JohnTimm** [IBM/FHIR#2429]
We currently have a configuration parameter named `extendedCodeableConceptValidation` however it extends the validation of more than codeable concepts. Per the documentation:
```
Used to determine:
1. whether CodeableConcepts that don't contain both system and code are checked during object construction
2. whether syntax-based validation of UCUM and language codes is done during object construction
```
I suggest that we either a) rename it to `extendedCodedElementValidation` or b) create a separate configuration parameter called `syntaxBasedValidation` or similar.

**Comment by lmsurpre** [comment]
Agree "codedElement" is a bit more accurate since it now applies beyond just CodeableConcept types, but we don't want to force users to deal with the name change / migration headache.
