### ISSUE TITLE
CXF LoggingFeature is deprecated, and it'd be nice to move the fhir-client to the latest approach

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#2453]
**Is your feature request related to a problem? Please describe.**
CXF LoggingFeature is deprecated, and it'd be nice to move the fhir-client to the latest approach

https://stackoverflow.com/questions/54989929/apache-cxf-loggingininterceptor-is-deprecated-what-to-use-instead

**Describe the solution you'd like**
Upgrade the LoggingFeature to the latest

**Describe alternatives you've considered**
Do Nothing or Move to RestEasy

*Please do NOT implement until a team review*

**Acceptance Criteria**

1.  
   GIVEN [a precondition]
    AND [another precondition]
   WHEN [test step]
    AND [test step]
   THEN [verification step]
    AND [verification step]

**Additional context**

**Comment by lmsurpre** [comment]
I think we should consider moving the whole thing over to RestEasy...

**Comment by lmsurpre** [comment]
We should also look at removing the `provided` dependency on CXF from `fhir-term-remote`.  We think its just using JAX-RS / isn't actually tied to CXF or the fhir-client.

To use the non-deprecated approach for CXF: probably a couple points

To switch over to RestEasy wholesale, upwards of 5 points.
