### ISSUE TITLE
Potential race condition when create overlaps with erase (hard-delete)

### ISSUE THREAD

**Issue by punktilious** [IBM/FHIR#2454]
**Describe the bug**
The persistence layer contains logic to handle race conditions when two threads attempt to create a new resource at the same time. The current implementation handles the locking/create/update sequence correctly with the proviso that a logical_resource could never be deleted.

This is no longer true now that the IBM FHIR Server supports `$erase` hard-delete. Although the chance of create/erase conflicting is low, for completeness the locking/create/update logic should be enhanced to handle the possibility of a row being deleted between the (failed) create and update steps. This needs to be implemented as a loop.

**Environment**
4.8.2

**To Reproduce**
Run concurrent create/update/erase operations

**Expected behavior**
Data consistency at all times.

**Comment by lmsurpre** [comment]
Probably should start with the test.  Maybe a fork of our ConcurrentUpdateTest.

**Comment by prb112** [comment]
I found no concurrency issues - opened PR with the test cases which mixes the workload.
PR https://github.com/IBM/FHIR/pull/2792
