### ISSUE TITLE
Update FHIRPath "as" operation implementation to be consistent with FHIRPath "as" function implementation

### ISSUE THREAD

**Issue by JohnTimm** [IBM/FHIR#2455]
Our current implementation of the FHIRPath "as" operation implementation includes the following logic:
```java
for (FHIRPathNode node : nodes) {
    if (type.isAssignableFrom(node.type())) {
        result.add(node);
    }
 }
```

whereas our current implementation of the FHIRPath "as" function is:
```java
for (FHIRPathNode node : getCurrentContext()) {
    FHIRPathType nodeType = node.type();
    if (SYSTEM_NAMESPACE.equals(type.namespace()) && node.hasValue()) {
        nodeType = node.getValue().type();
    }
    if (type.isAssignableFrom(nodeType)) {
        result.add(node);
    }
}
```
The FHIRPath section of the FHIR specification mentions only the "as" function (not the "as" operation) and our implementation is consistent with that. The FHIRPath specification mentions both the "as" operation and "as" function but mentions the "as" function exists for backwards compatibility and will be deprecated in a future release. That said, it makes sense, IMO to follow our implementation of the "as" function for the "as" operation so that they are effectively interchangeable.

**Comment by lmsurpre** [comment]
Unit tests provide sufficient coverage
