### ISSUE TITLE
CARIN BB service-date doesn't search on ExplanationOfBenefit.item.servicedDate

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#2460]
**Describe the bug**
With the CARIN IG loaded, a search for ExplanationOfBenefit by service-date is not working as expected.

**Environment**
4.8.2

**To Reproduce**
1. ensure the fhir-ig-carin-bb jar is in userlib and start the server
2. upload an ExplanationOfBenefit resource with a ExplanationOfBenefit.item.servicedDate
3. perform a search with `[base]/ExplanationOfBenefit?service-date=YOURDATE`

note it comes back empty

**Expected behavior**
It find the resource

**Additional context**
There is a corresponding upstream issue at https://jira.hl7.org/browse/FHIR-30443

**Comment by prb112** [comment]
I loaded the spec examples, and executed a test against https://localhost:9443/fhir-server/api/v4/ExplanationOfBenefit?service-date=ge2019

I confirmed the example was found using the search-parameter that is updated.
