### ISSUE TITLE
Trouble with the Liberty OpenAPI feature

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#2461]
**Describe the bug**
During startup of the docker image, I'm seeing the following:

> CWWKO1661E: An error occurred when processing application fhir-server-webapp and an OpenAPI document was not produced. The error was: java.lang.IllegalStateException: SROAP00001: Model already initialized.

**Environment**
main

**To Reproduce**
1. checkout main, build the project, build the docker image
2. docker run

**Expected behavior**
No errors during startup

**Additional context**
It doesn't prevent the server from starting but does seem to prevent the OpenAPI feature from working

**Comment by prb112** [comment]
Might be related... https://github.com/OpenLiberty/open-liberty/issues/16764

**Comment by lmsurpre** [comment]
Yep, I think thats it.  I upgraded to Liberty 21.0.0.5 and the issue seems to have gone away.

**Comment by lmsurpre** [comment]
This log message is no longer in the output and I confirmed that the openapi/ui endpoint is operational after startup, no further QA needed on this one.
