### ISSUE TITLE
CARIN BB Institutional EOB 'adjudication-has-amount-type-slice' constraints are not specified correctly

### ISSUE THREAD

**Issue by JohnTimm** [IBM/FHIR#2462]
See: https://jira.hl7.org/browse/FHIR-32337

**Comment by JohnTimm** [comment]
This is a bug in the IG not in our implementation.

**Comment by kmbarton423** [comment]
Starting with C4BB examples:
   EOB Inpatient Institutional - Example 1
   EOB Outpatient Institutional - Example 1

Added the following:
{
    "category": {
        "coding": [
            {
			    "system": "http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBAdjudicationDiscriminator",
				 "code": "allowedunits"
			 }
		 ]
    },
	"value": 1
}

Confirmed failing behavior:
        {
            "severity": "error",
            "code": "invariant",
            "details": {
                "text": "adjudication-has-amount-type-slice: If Adjudication is present, it must have at least one adjudicationamounttype slice"
            },
            "expression": [
                "ExplanationOfBenefit.adjudication[1]"
            ]
        }

With fix, verified that both cases (inpatient and outpatient EOB) no longer hit this error.
