### ISSUE TITLE
Upgrade source compatibility to Java 11 and drop Java 8 tests in CI

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#2477]
**Is your feature request related to a problem? Please describe.**
The Latest Java introduces new features and functions for security, xml processing. 

Investigate updating to latest Java/OpenLiberty supported JVMs. 

#2251 may be related.

**Comment by prb112** [comment]
Somewhat related https://github.com/IBM/FHIR/issues/2491

**Comment by lmsurpre** [comment]
We will add java 17 to our test matrix in the future, not as part of this issue.

**Comment by lmsurpre** [comment]
on the install.sh we might want to check for java 11

**Comment by lmsurpre** [comment]
we should update the getting started for dev wiki and other places that say our minimum version is java 8

**Comment by prb112** [comment]
QA: I can confirm this is working as expected
