### ISSUE TITLE
Incorporate and Improve test coverage in the build/site

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#248]
Incorporate and Improve test coverage in the build/site

**STEPS**
- Investigate Sonar Cloud 
- Investigate CodeCov.io
- Determine how to report effectively for the FHIR build 
- Review with team
- Add to build

**Comment by lmsurpre** [comment]
I tried enabling SonarCloud, but it doesn't seem to be enabled for the IBM organization.

However, `Codecov` is already listed as an `Installed GitHub App` so that might be an easier option.

**Comment by prb112** [comment]
I added this to the release process.  I'll explain how to retrieve and document on Monday.

**Comment by prb112** [comment]
PR https://github.com/IBM/FHIR/pull/606

**Comment by prb112** [comment]
PR https://github.com/IBM/FHIR/pull/629 - improves test coverage to 80%
adding conditional activation
