### ISSUE TITLE
Reindex Returns 500 when the Client sends a bad timestamp

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#2493]
**Describe the bug**
Reindex Returns 500 when the Client sends a bad timestamp

[INFO    ] Completed request[0.855 secs]: tenantId:[default] dsId:[default] user:[fhiruser] method:[POST] uri:[https://localhost:9443/fhir-server/api/v4/$reindex] status:[200]
[INFO    ] Received request: tenantId:[default] dsId:[default] user:[fhiruser] method:[POST] uri:[https://localhost:9443/fhir-server/api/v4/$reindex]
[ERROR   ] Unexpected error occurred while processing request for operation 'reindex': java.time.format.DateTimeParseException: Text 'BAD_STRING' could not be parsed at index 0
Unexpected error occurred while processing request for operation 'reindex': java.time.format.DateTimeParseException: Text 'BAD_STRING' could not be parsed at index 0

**Environment**
Which version of IBM FHIR Server?

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by prb112** [comment]
Also reindex needs to return 400 when using GET
```
---------------------------
ID: 1
Address: https://localhost:9443/fhir-server/api/v4/$reindex
Http-Method: GET
Content-Type: 
Headers: {Accept=[application/fhir+json], X-FHIR-TENANT-ID=[default], X-FHIR-DSID=[default]}
--------------------------------------
Jun 10, 2021 9:05:32 AM org.apache.cxf.interceptor.LoggingInInterceptor
INFO: Inbound Message
----------------------------
ID: 1
Response-Code: 400
Encoding: ISO-8859-1
Content-Type: application/fhir+json
Headers: {connection=[Close], Content-Language=[en-US], Content-Length=[222], content-type=[application/fhir+json], Date=[Thu, 10 Jun 2021 13:05:32 GMT]}
Payload: {"resourceType":"OperationOutcome","id":"c0-a8-56-14-819e9faa-5677-464c-aba6-5f8e6c35a623","issue":[{"severity":"fatal","code":"not-supported","details":{"text":"HTTP method not supported: GET"},"expression":["<empty>"]}]}```

**Comment by tbieste** [comment]
Verified that using GET and passing an invalid formatted `tstamp` each result in HTTP 400 status code.

- `Invalid format for 'tstamp' value, only 'yyyy-MM-dd' or ISO 8601 dateTime format is valid`
- `HTTP method not supported: GET`
