### ISSUE TITLE
Add history-system and history-type endpoints to the openapi / swagger

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#2496]
**Is your feature request related to a problem? Please describe.**
The swagger / openapi definitions generated by `fhir-swagger-generator` are missing the whole-system interactions (both search and history).

Update:  we added support for the type-level history interaction now as well, so that make sense to add to the swagger at the same time.

**Describe the solution you'd like**
Include some flag that indicates whether or not to include these.  Maybe an entry in the list with a type of `Resource`?
If so, we need to make it clear that you can't have create/update/read/vread interactioons for this type.

In the swagger-per-type mode, generate a separate swagger definition for these whole-system interactions.

**Describe alternatives you've considered**
Always include the whole-system endpoints.

**Acceptance Criteria**

**Additional context**
Whole-system history could be added with #2026

**Comment by lmsurpre** [comment]
Splitting `search-system` into a separate task.

**Comment by lmsurpre** [comment]
QA plan:
* open our openapi/ui view
* look for the new endpoints
* ensure they list proper query parameters
* exercise the endpoints

**Comment by tbieste** [comment]
Closed after trying out the OpenAPI UI for whole system history and type history with various parameter combinations.
