### ISSUE TITLE
fhir-bucket ignores --schema-name when running scan and load

### ISSUE THREAD

**Issue by punktilious** [IBM/FHIR#2499]
**Describe the bug**
The --schema-name argument should direct fhir-bucket to use a specific schema instead of the default FHIRBUCKET (for Db2 and PostgreSQL) or APP (for Derby).

**Environment**
4.8.3

**To Reproduce**
Try to use fhir-bucket main directed to another schema.

**Expected behavior**
It should be possible to direct fhir-bucket to use a specific schema with the --schema-name argument.

**Additional context**
N/A

**Comment by tbieste** [comment]
Verified that --create-schema (for both derby and postgresql), as well as scanAndLoad, use the --schema-name parameter, when specified; otherwise they use the default schema name.
