### ISSUE TITLE
Consolidate delete params code which currently is implemented multiple times

### ISSUE THREAD

**Issue by punktilious** [IBM/FHIR#2500]
**Is your feature request related to a problem? Please describe.**
The code to delete the current parameters for a logical resource is implemented multiple times, and this risks difficult to detect defects if the implementations ever get out of sync.

* Primary ingestion (Db2 and PostgreSQL stored procedures, Derby DAO)
* Reindex
* Erase
* PostgreSQL no-proc DAO

**Describe the solution you'd like**
Refactor the delete parameters block of statements so that there is a single Java DAO implementation and a corresponding pair of (new) stored procedures for Db2 and PostgreSQL. The procedures can be invoked directly from the existing procedures.

**Describe alternatives you've considered**
Do nothing and risk a future regression defect.

**Acceptance Criteria**
Unit and system tests pass.

**Additional context**
N/A

**Comment by prb112** [comment]
FYI https://github.com/IBM/FHIR/issues/2348

**Comment by lmsurpre** [comment]
Duplicates #2348
