### ISSUE TITLE
Support $reindex operation supports `resourceLogicalId` on Type and Instance

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#2503]
**Is your feature request related to a problem? Please describe.**
The $reindex operation supports `resourceLogicalId`. 

|`resourceLogicalId`|string|The ResourceType or the ResourceType/Logical id for targetted reindexing|

```
POST [base]/$reindex would reindex resources of any type
POST [base]/Patient/$reindex would reindex Patient resources
POST [base]/Patient/123/$reindex would reindex just Patient/123
```

It'd be nice to support reindex on the specific Resource and Type.

**Describe the solution you'd like**
Update the Reindex Operation to support the Input Parameter.

**Describe alternatives you've considered**

**Acceptance Criteria**

1.  
   GIVEN [a precondition]
    AND [another precondition]
   WHEN [test step]
    AND [test step]
   THEN [verification step]
    AND [verification step]

**Additional context**

**Comment by tbieste** [comment]
Verified:

- POST [base]/$reindex would reindex resources of any type **[Success]**
- POST [base]/Patient/$reindex would reindex Patient resources **[Success]**
- POST [base]/Patient/123/$reindex would reindex just Patient/123 **[Success]**
- Using both Type/Instance and the`resourceLogicalId` parameter results in the following error: `resourceLogicalId` already specified using call to Operation on Type or Instance` **Success**
- Specifying `resourceLogicalId` with ResourceType of `Resource` or `DomainResource` results in the following error: `ResourceType is not valid` **Success**
- Specifying `[base]/Resource/$reindex` or `[base]/DomainResource/$reindex` results in the following error: `ResourceType is not valid` **Results in no error, but for consistency, probably should**

**Comment by tbieste** [comment]
Verified:

- Specifying [base]/Resource/$reindex or [base]/DomainResource/$reindex results in the following error:`Resource Type 'Resource' is not valid`
