### ISSUE TITLE
OperationDefinition.name and OperationDefinition.code inconsistent between FHIRRestHelpers and FHIROperationRegistry

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#2505]
**Describe the bug**
OperationDefinition.name and OperationDefinition.code inconsistent between FHIRRestHelpers and FHIROperationRegistry

**Environment**
Which version of IBM FHIR Server? 4.8.3

**To Reproduce**
1. Create an OperationDefintion with a mismatch between code and name. 
2. Add an instance type support = true, with resource: [Resource]
3. Execute a call
4. Check the Logs

```[6/14/21, 13:22:55:244 UTC] 00000067 FHIRResource  1   Operation with name: 'reindex:Patient' was not found
                                 com.ibm.fhir.exception.FHIROperationException: Operation with name: 'reindex:Patient' was not found  [probeId=c0-a8-56-14-00683e0c-88e3-460a-982e-80308d9507b9]
	at com.ibm.fhir.server.operation.FHIROperationRegistry.getOperation(FHIROperationRegistry.java:131)
	at com.ibm.fhir.server.util.FHIRRestHelper.doInvoke(FHIRRestHelper.java:1139)
```

**Expected behavior**
This should work since it has the same code.

**Additional context**
Discovered in $reindex support
Asked John/Lee to confirm this behavior is expected or not.

**Update**
Note, core problem was System-Type-Instance handling in FHIROperationRegistry
Changed the lines to reflect use of code

**Comment by lmsurpre** [comment]
Mostly a code cleanup thing, no QA outside of the unit tests and #1751
