### ISSUE TITLE
Bundle-level constraints are not being checked against the Bundle

### ISSUE THREAD

**Issue by jduteau** [IBM/FHIR#2513]
There are a number of Bundle constraints that are not being checked against the Bundle.  After discussion with Lee and John, it was discovered that the validator is not invoked against the outer bundle but just on the entries within the bundle.

The validator should check constraints against the outer Bundle (checks such as bdl-3, bdl-5, bdl-7, and bdl-8).  

The following prose in the FHIR specification about Bundle would also be good to check:

Except for transactions and batches, each entry in a Bundle must have a fullUrl which is the identity of the resource in the entry. Note that this is not a versioned reference to the resource, but its identity. Where a resource is not assigned a persistent identity that can be used in the Bundle, a UUID should be used (urn:uuid:...).

**Acceptance Criteria**

1.  WHEN a Bundle is submitted that should fail the bdl-x constraints or that does not have a fullUrl for every entry
   THEN errors should be raised by the validator.

**Comment by lmsurpre** [comment]
Leaning toward just writing java logic for the handful of bundle-level constraints...probably as additional checks in FHIRRestHelper.validateBundle

**Comment by d0roppe** [comment]
Verified that the bundle constraints are now checked.  Closing issue.
