### ISSUE TITLE
NPE thrown in FHIRPathUtil.getResourceNodes(FHIRPathTree tree, FHIRPathNode node) when FHIRPathNode is not in FHIRPathTree 

### ISSUE THREAD

**Issue by JohnTimm** [IBM/FHIR#2518]
When the FHIRPath `ResolveFunction` resolves an internal fragment reference to a resource that is contained (or is a container) it creates a new `FHIRPathTree` of the resolved resource. This causes an NPE when `getResourceNodes` is called on a node that is in the new tree but not in the original tree.

https://github.com/IBM/FHIR/blob/cb16c9fcb7d91f1cfd5e1fbf6f9975f8de38e18e/fhir-path/src/main/java/com/ibm/fhir/path/util/FHIRPathUtil.java#L1184-L1188

**Comment by lmsurpre** [comment]
Associated unit test and integration tests are sufficient.
