### ISSUE TITLE
Deprecate the /Resource and /DomainResource endpoints

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#2526]
In our DSTU2 implementation, we allowed a user to search on `[base]/Resource` to invoke whole-system search.

In #261 we made it possible to search via GET on `[base]/` or by POST on `[base]/_search`.
However, we never actually removed the ability to interact with the /Resource and /DomainResource endpoints.

We should remove the /DomainResource and document the /Resource endpoint as deprecated.  Once complete, we should open a separate task for removing the Resource endpoint as well.

Potentially relates to https://github.com/IBM/FHIR/issues/2445

**Comment by lmsurpre** [comment]
I decided to deprecate these endpoints for 4.9.0 which basically just means:
1. logging a warning when we serve requests at these endpoints 
2. adding this to the release notes under the *deprecated* section

**Comment by michaelwschroeder** [comment]
Running with the latest code from the main branch on my local system, I executed the following search requests:
`GET [base]/Resource?_id=test`
`GET [base]/DomainResource?_id=test`
`POST [base]/Resource/_search?_id=test`
`POST [base]/DomainResource/_search?_id=test`

In all cases, I verified that one of the following two WARNING messages was issued as appropriate:
`[WARNING ] Use of abstract resource types like 'Resource' in FHIR URLs is deprecated and will be removed in a future release`
`[WARNING ] Use of abstract resource types like 'DomainResource' in FHIR URLs is deprecated and will be removed in a future release`

Issue verified and closed.
