### ISSUE TITLE
Regular expression constraint fires incorrectly

### ISSUE THREAD

**Issue by jduteau** [IBM/FHIR#2530]
**Describe the bug**
I have a constraint that uses a regular expression:

Expression: 
```
(system = 'phone' or system = 'fax') implies value.matches('^\\\\+[0-9]{1,3}-[0-9]{1,3}-[0-9]{3,4}-[0-9]{4}(;ext=[0-9]+)?$')
```

When I submit a contactPoint with a phone number that should match the constraint, it produces an error:
```xml
        <contact>
          <name>
            <text value="Charles Yaghmour"/>
          </name>
          <telecom>
            <system value="phone"/>
            <value value="+1-703-362-1280"/>
          </telecom>
          <telecom>
            <system value="email"/>
            <value value="cyaghmour@samvit-solutions.com"/>
          </telecom>
          <address>
            <line value="11654 Plaza America Dr."/>
            <city value="Reston"/>
            <state value="VA"/>
            <postalCode value="20190"/>
            <country value="USA"/>
          </address>
        </contact>
```
```
Error Type: invariantError Details: generated-LabelerOrganization-9: Constraint violation: 
contact.exists() and 
contact.all(name.exists() and 
telecom.exists() and 
telecom.where(conformsTo('http://hl7.org/fhir/us/spl/StructureDefinition/SPLContactPoint')).count() = 1 and 
telecom.exists() and 
telecom.where(conformsTo('http://hl7.org/fhir/us/spl/StructureDefinition/SPLContactPoint')).count() = 1 and 
address.exists() and 
address.conformsTo('http://hl7.org/fhir/us/spl/StructureDefinition/SPLAddress'))
```

When we change the phone number to be +1-703-3621280, then the constraint does not error out.

**Environment**
4.8.3

**To Reproduce**
1. Create a profile that includes the constraint above
2. Validate an instance that has a correct contactPoint
3. Receive the above error.

**Expected behavior**
The constraint should not error against that phone number.

**Additional context**
[StructureDefinition-EstablishmentOrganization.txt](https://github.com/IBM/FHIR/files/6678294/StructureDefinition-EstablishmentOrganization.txt)
[StructureDefinition-SPLContactPoint.txt](https://github.com/IBM/FHIR/files/6678296/StructureDefinition-SPLContactPoint.txt)

**Comment by jduteau** [comment]
Here is a file that *SHOULD* pass validation but doesn't.
[LabelerCodeRequest20210614-F1.1Take3.txt](https://github.com/IBM/FHIR/files/6678512/LabelerCodeRequest20210614-F1.1Take3.txt)

**Comment by prb112** [comment]
HI @jduteau  this issue has an associated PR that should address this issue. We've tested it in our environments, and are closing the issue. Should this not be satisfactory please let us know, and we can work with you on resolving any remaining elements to your issue.  This code is in release 4.9.0 (pending build and release) thank you, Paul
