### ISSUE TITLE
FHIROperationException indicated when $expand for loinc code returns 0 

### ISSUE THREAD

**Issue by kmbarton423** [IBM/FHIR#2532]
**Describe the bug**
Have term:remoteTermServiceProviders configured for http://loinc.org
Attempted to $expand a valid code (https://localhost:9443/fhir-server/api/v4/ValueSet/$expand)
Received fatal exception "FHIROperationException: An error occurred during the ValueSet expand operation"
Retried $expand request directed at loinc endpoint and found the expansion results in 0 returned.

**Environment**
Running on current FHIR main branch.

**To Reproduce**
1. Configure term:remoteTermServiceProviders for http://loinc.org
2. Create CodeSystem/loinc if needed
3. Attempt $expand
POST https://localhost:9443/fhir-server/api/v4/ValueSet/$expand
`{
    "resourceType": "ValueSet",
    "id": "loinc-valueset",
    "url": "http://ibm.com/fhir/ValueSet/loinc-valueset",
    "version": "1",
    "name": "LOINC ValueSet",
    "status": "active",
    "compose": {
        "include": [
            {
                "system": "http://loinc.org",
                "filter": [
                    {
                        "property": "concept",
                        "op": "is-a",
                        "value" : "85354-9"
                    }
                ]
            }
        ]
    }
}`

**Expected behavior**
Should be told that the $expand returns nothing vs receiving a FHIROperationException.

**Comment by prb112** [comment]
Confirmed using the steps above. Results in 
```
