### ISSUE TITLE
Discriminator incorrectly generated for profile constraints

### ISSUE THREAD

**Issue by JohnTimm** [IBM/FHIR#2541]
A recent change has introduced a bug that incorrectly generates the discriminator when the element definition has a profile constraint:

```
contained.where(conformsTo('http://hl7.org/fhir/us/spl/StructureDefinition/USAgentAffiliation')) and contained.count() = 1.exists()
```

the `and contained.count() = 1` was recently added to address another issue but when generating the discriminator this clause causes issues

**Comment by prb112** [comment]
QA and review completed with the spl ig.
