### ISSUE TITLE
_sort not working correctly with id value

### ISSUE THREAD

**Issue by d0roppe** [IBM/FHIR#2560]
**Describe the bug**
When doing a search and adding a sort like &_sort=_id  the resource ID are not sorted. 

**Environment**
4.8.3

**To Reproduce**
Issue a search on all patients like /Patient?_sort=_id or /Patient?_sort=-_id this will return the same list in the same order, and they should be ascending and descending sorted on the id of the resource. 

**Expected behavior**

**Additional context**

**Comment by prb112** [comment]
Discussed with team - work only New Query Builder only

**Comment by d0roppe** [comment]
Verified the sort of ID is now honored. Closing issue.
