### ISSUE TITLE
Support Invoking Local Reference Resolution in Operations

### ISSUE THREAD

**Issue by ssnowski** [IBM/FHIR#2563]
**Is your feature request related to a problem? Please describe.**
* I'm trying to implement an operation that determines the appropriate ID to insert data in and then inserts data at that id (to get deduplicating and patching logic with an interface that mostly just takes a resource in).  I've found that, when I do that, I lose the ability to use local ids, which are even more important as I am delaying the decision on which ID to alter, and my links fall apart.

**Describe the solution you'd like**
An ability to hook in to local reference resolution logic in the FHIRRestHelper (and possibly additional logic there) from a custom operation.  It would probably need to be opt-in, as not all operations would want this.
It seems like this might require changing the FHIROperation and/or AbstractOperation to allow a two-step process, as the decision on which IDs to use needs to happen for all operation calls prior to the local references being replaced.

**Describe alternatives you've considered**
* I've considered duplicating local-reference parts of the rest helper in a custom operation that takes bundles as input.
* I've considered giving up and doing all the id-checking and processing outside of the fhir server, but I think that will make a lot of rest requests and slow it down substantially.

**Acceptance Criteria**

1.  
   GIVEN [a precondition]
    AND [another precondition]
   WHEN [test step]
    AND [test step]
   THEN [verification step]
    AND [verification step]

**Additional context**

**Comment by ssnowski** [comment]
Note: the solution given to this problem was:
```
1. Operation: Post Bundle(type='collection') directly to the system-level operation
    - or Parameters object that includes Search Criteria and the Resource
2. Operation: Figure out if the resource is an UPDATE using Search Criteria ($merge logic) -> Merged
    - Produce the custom Merged Resource
    - Assembling the Transaction Bundle
3. FHIR Rest Helpers: use doBundle to pass into the framework.
NF: Your audit trail will audit the Operation call only.
```

**Comment by prb112** [comment]
@ssnowski if you are OK with that solution, we ask that you close the issue. Thanks. Paul

**Comment by prb112** [comment]
Closing as there is an alternative as proposed
