### ISSUE TITLE
Create a fhir-bucket docker image

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#2570]
**Is your feature request related to a problem? Please describe.**
Include the fhir-bucket in the docker image

**Describe the solution you'd like**
Wrap fhir-bucket in its own docker image (similar to the schema tool).

The new image should be peer to ibm-fhir-server on DockerHub.

The user experience of the image should be focused on making reindex as simple as possible, however it should not preclude the usage of loading.

**Describe alternatives you've considered**
Include it in our ibm-fhir-server image directly.

**Acceptance Criteria**

1.  
   GIVEN [a precondition]
    AND [another precondition]
   WHEN [test step]
    AND [test step]
   THEN [verification step]
    AND [verification step]

**Additional context**

**Comment by lmsurpre** [comment]
I added an alternative option under the "Describe alternatives" section which is to give fhir-bucket its own image.

**Comment by prb112** [comment]
requested the repository on DockerHub

**Comment by prb112** [comment]
agreed on ibm-fhir-bucket-tool

**Comment by prb112** [comment]
Updated https://hub.docker.com/r/ibmcom/ibm-fhir-bucket-tool - let me know if you want more.

**Comment by prb112** [comment]
Chat on the Side agreed it is a good start, will update going forward
