### ISSUE TITLE
Add support for a configurable "fail fast" validation feature

### ISSUE THREAD

**Issue by JohnTimm** [IBM/FHIR#2582]
In production, it makes sense to fail fast when the `FHIRValidator` encounters an issue with an ERROR severity. A configurable "fail fast" validation feature would allow for development with standard behavior and production with a more performant option.

**Comment by prb112** [comment]
Created an Observation without issues
Created an Observation (same starting point without a validQuantity) and FailFast as false
Two Errors present
Created an Observation with same starting point and failFast as true 
One Error Present (as expected)
```
    "resourceType": "OperationOutcome",
    "id": "c0-a8-56-14-d7cf56ff-323d-4b1b-881c-130604e5548f",
    "issue": [
        {
            "severity": "error",
            "code": "invariant",
            "details": {
                "text": "vs-3: If there is no a value a data absent reason must be present"
            },
            "expression": [
                "Observation.component[0]"
            ]
        },
        {
            "severity": "warning",
```
