### ISSUE TITLE
Add support for extending the FHIRValidator with custom validation logic

### ISSUE THREAD

**Issue by JohnTimm** [IBM/FHIR#2583]
The `FHIRValidator` is relatively fixed in terms of how it handles the validation of resource instances. There are circumstances where a user may want to configure custom validation logic or override some of the base model or profile constraints used in the validation process.

**Comment by lmsurpre** [comment]
Confirmed by:
1. posting the following to Patient/$validate
```
{
  "resourceType": "Patient",
  "name": [{
      "given": [ "John" ]
  }]
}
```
2. building fhir-validation-4.9.0-SNAPSHOT-test.jar and adding it to the userlib of my test server, and
3. posting it again

This second time it yields a validation error like 
> "patient-name-1: If Patient.name exists, then Patient.name.family SHOULD exist"

This shows that the java-based constraint has been successfully found and invoked.
