### ISSUE TITLE
Support "special" search param Location-near

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#259]
In DSTU2 we did our own "special" Location search behavior and I think our schema still includes a Location search parameters table.

In STU3 or R4, they defined the "special" search parameter Location-near:
Search for locations where the location.position is near to, or within a specified distance of, the provided coordinates expressed as [latitude]\|[longitude]\|[distance]\|[units] (using the WGS84 datum, see notes). If the units are omitted, then kms should be assumed. If the distance is omitted, then the server can use its own discretion as to what distances should be considered near (and units are irrelevant) Servers may search using various techniques that might have differing accuracies, depending on implementation efficiency. Requires the near-distance parameter to be provided also | Location.position

We should either:
A. map this new search parameter onto the current functionality (and test test test); or
B. remove the current functionality if its broken / in disrepair

**Comment by prb112** [comment]
Put in Review QA

**Comment by prb112** [comment]
PR https://github.com/IBM/FHIR/pull/497/files
