### ISSUE TITLE
Unify approach for creating operation outcome issues across the codebase

### ISSUE THREAD

**Issue by JohnTimm** [IBM/FHIR#2596]
There are a number of different components across that codebase that generate operation outcome issues for a variety of reasons. I'd like to create a single set of utility methods for creating operation outcome issues (and operation outcome resources) and ensure that all components are using the same set of utilities. We have generally moved in this direction but things are still a bit scattered. These utility methods could took a flag that indicates whether user input is included in the message so that we could selectively encode before returning them to the client. It is a compromise between completely ad hoc approach and an "encode everything" approach.

**Comment by lmsurpre** [comment]
Team decision:  use Encoder.encode() in all the places where we're reflecting user input back in OperationOutcome issue messages.  No separate utility.
