### ISSUE TITLE
When using _total=none, a "next" link is generated when there isn't a "next" page

### ISSUE THREAD

**Issue by csandersdev** [IBM/FHIR#2607]
**Describe the bug**
When using _total=none, a "next" link is generated when there isn't a "next" page

**Environment**
Main (4.9.0-SNAPSHOT)

**To Reproduce**

`$ curl -k -u 'fhiruser:change-password' 'https://localhost:9443/fhir-server/api/v4/Encounter?_count=1000&type:in=http://ibm.com/health/ValueSet/wh-cohorting-synthea-encounters&subject:Patient=17a5e657590-cfaa4225-b98a-4f84-9a67-a3aff9da8ca3'`

```json
{
    "resourceType": "Bundle",
    "id": "03f1a0f6-ce90-46c2-8d5c-5808913c5a95",
    "type": "searchset",
    "total": 61,
    "link": [
        {
            "relation": "self",
            "url": "https://localhost:9443/fhir-server/api/v4/Encounter?_count=1000&type:in=http://ibm.com/health/ValueSet/wh-cohorting-synthea-encounters&subject:Patient=17a5e657590-cfaa4225-b98a-4f84-9a67-a3aff9da8ca3&_page=1"
        }
    ]
}
```
-----
`$ curl -k -u 'fhiruser:change-password' 'https://localhost:9443/fhir-server/api/v4/Encounter?_count=1000&type:in=http://ibm.com/health/ValueSet/wh-cohorting-synthea-encounters&subject:Patient=17a5e657590-cfaa4225-b98a-4f84-9a67-a3aff9da8ca3&_total=none'`

```json
{
    "resourceType": "Bundle",
    "id": "10dcec7a-d6d7-4ec3-a47b-23bab7b5024a",
    "type": "searchset",
    "link": [
        {
            "relation": "self",
            "url": "https://localhost:9443/fhir-server/api/v4/Encounter?_count=1000&type:in=http://ibm.com/health/ValueSet/wh-cohorting-synthea-encounters&subject:Patient=17a5e657590-cfaa4225-b98a-4f84-9a67-a3aff9da8ca3&_total=none&_page=1"
        },
        {
            "relation": "next",
            "url": "https://localhost:9443/fhir-server/api/v4/Encounter?_count=1000&type:in=http://ibm.com/health/ValueSet/wh-cohorting-synthea-encounters&subject:Patient=17a5e657590-cfaa4225-b98a-4f84-9a67-a3aff9da8ca3&_total=none&_page=2"
        }
    ]
}
```

**Expected behavior**
When there isn't a next page, no next link should be generated. As-is, my implementation saves some CPU cycles by using _total=none, but then loses some CPU cycles by making an additional, unnecessary web request because it doesn't know we are done after the first call.

**Comment by lmsurpre** [comment]
Proposal:  in cases where total was passed, only include the next link when we have a full page of results.  Otherwise, omit it.

**Comment by tbieste** [comment]
Updated to only include the next link when we have a full page of results.

**Comment by JohnTimm** [comment]
I verified this locally using the following search URL:
```
https://localhost:9443/fhir-server/api/v4/Patient?_count=1000&_total=none
```
