### ISSUE TITLE
Previously-working search queries should continue to work after migration before a complete reindex

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#2609]
**Is your feature request related to a problem? Please describe.**
For #1922 we introduced dedicated tables for the `_profile`, `_security`, and `_tag` parameters.
* during ingestion / indexing, we write the parameter to these values instead of to the corresponding search parameter tables
* during search, the query builder looks for them in these new tables instead of the search parameter tables
* data for existing resources is only copied over via reindexing

The consequence is that previously working queries (anything involving these 3 parameters) will now return empty until a complete reindexing is performed.

Instead, what we'd like is for the previous queries to continue using the data from the old location until the reindex is performed...at which point it is safe to look only in the new tables for this data.

**Describe the solution you'd like**
Introduce `fhirServer/search/enableLegacyWholeSystemSearchParams` param with a default of false.

During ingestion / reindex:
* if legacyWholeSystemSearchParams is true then put the _profile, _tag, and _security params in both their new tables AND in their old location (search param tables)
* else only in the new tables 

During query
* if legacyWholeSystemSearchParams is true then look only in the old spot (this is the biggest piece of new work)
* else only look in the new tables (the existing code)

The migration procedure could then look something like this:
1. Stop ingestion
2. Copy/duplicate db
3. Migrate the standby db
4. Set up the new code against the standby db and set `legacyWholeSystemSearchParams = true`
5. Cut over to the new code and the new db (queries involving `_tag`, `_profile`, and `_security` will continue to look in the old search param tables due to enableLegacyWholeSystemSearchParams)
6. Re-enable ingestion (new `_tag`, `_profile`, and `_security` params will be added to both the old search param tables and the new tables)
7. Kick off reindex (existing `_tag`, `_profile`, and `_security` params will be added to both the old search param tables and the new tables)
8. Once reindex completes, set `legacyWholeSystemSearchParams = false`
9. On the next reindex, the uneccessary _profile, _tag, and _security data in the param tables will get removed

**Describe alternatives you've considered**
Perform reindexing on the standby and only cut over to it when this is complete.  The downside here is that either ingestion needs to be off the whole time or we need to flush out our replication strategy so that any new data ingested to the old system after the copy/duplicate db step can be carried over to the new system.

**Acceptance Criteria**

1.  
   GIVEN a resource with a tag, a profile, and security label
    AND the resource is saved to the db under ibm fhir server 4.8.3
   WHEN the db is migrated to ibm fhir server 4.9.0
    AND ibm fhir server 4.9.0 is configured with `legacyWholeSystemSearchParams = true`
   THEN searches with the tag, profile, and security label continue to retrieve the resource

**Additional context**
After some period of time after iplementing this feature, it would be nice to deprecate and remove this config parameter and the associated code (so that we don't need to continue supporting this extra code path for these queries.
Maybe deprecate `fhirServer/search/enableLegacyWholeSystemSearchParams` in 4.11 and plan to remove it in 4.12?

**Comment by lmsurpre** [comment]
For #2524 we skip the reindexing if all the search parameter code+value pairs are the same, so if legacyWholeSystemSearchParams is changed and $reindex is run then its possible that we'll fail to do the reindex.
We should consider adding the value of the legacyWholeSystemSearchParams config param to the hash (or something similar) if we think its important for the reindex to run when none of the parameter values have changed.

**Comment by michaelwschroeder** [comment]
Summary of SQL differences based on settings of `fhirServer/search/enableOptQueryBuilder` and `fhirServer/search/enableLegacyWholeSystemSearchParams`:

1. `enableOptQueryBuilder = false` AND `enableLegacyWholeSystemSearchParams = false`:
    In this case, we're using the old query builder, but the new search parameter tables for the `_profile`, `_tag`, and `_security` search parameters. Any query involving one of these search parameters (whole-system or not) will use these new tables:
    - `<resourceType>_profiles` for the `_profile` search parameter
    - `<resourceType>_tags` for the `_tag` search parameter
    - `<resourceType>_security` for the `_security` search parameter
2. `enableOptQueryBuilder = false` AND `enableLegacyWholeSystemSearchParams = true`:
    In this case, we're using the old query builder, and the old search parameter tables for the `_profile`, `_tag`, and `_security` search parameters. Any query involving one of these search parameters (whole-system or not) will use these existing tables:
    - `<resourceType>_str_values` for the `_profile` search parameter
    - `<resourceType>_token_values_v` for the `_tag` search parameter
    - `<resourceType>_token_values_v` for the `_security` search parameter
3. `enableOptQueryBuilder = true` AND `enableLegacyWholeSystemSearchParams = false`:
    In this case, we're using the new query builder, and the new search parameter tables for the `_profile`, `_tag`, and `_security` search parameters. Any query involving one of these search parameters will use these new tables:
    - `logical_resource_profiles` (whole-system search) and `<resourceType>_profiles` (resource-specific search) for the `_profile` search parameter
    - `logical_resource_tags` (whole-system search) and `<resourceType>_tags` (resource-specific search) for the `_tag` search parameter
    - `logical_resource_security` (whole-system search) and `<resourceType>_security` (resource-specific search) for the `_security` search parameter
4. `enableOptQueryBuilder = true` AND `enableLegacyWholeSystemSearchParams = true`:
    In this case, we're using the new query builder, but the old search parameter tables for the `_profile`, `_tag`, and `_security` search parameters. Any whole-system search query will default to use the old query builder, so will use the tables described in list item 2 above). Any resource-specific query involving one of these search parameters will use these existing tables:
    - `<resourceType>_str_values` for the `_profile` search parameter
    - `<resourceType>_token_values_v` for the `_tag` search parameter
    - `<resourceType>_token_values_v` for the `_security` search parameter

**Comment by tbieste** [comment]
> From #2524 we skip the reindexing if all the search parameter code+value pairs are the same, so if legacyWholeSystemSearchParams is changed and $reindex is run then its possible that we'll fail to do the reindex.
> We should consider adding the value of the legacyWholeSystemSearchParams config param to the hash (or something similar) if we think its important for the reindex to run when none of the parameter values have changed.

I just noticed this still needed to be done, so I opened https://github.com/IBM/FHIR/pull/2622 as a quick solution.

**Comment by prb112** [comment]
QA: I ran positive and negative tests using existing data. It's working as expected
