### ISSUE TITLE
whole-system search(search all and search across multiple resource types)  on the base endpoint

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#261]
We currently implement whole-system search by handling GET requests to `[base]/_search` in `FHIRResource.searchAll()`.  However, that conflicts with the following from the [specification](https://www.hl7.org/fhir/http.html#vsearch):
```
...
It is also possible to search across multiple resource types:

  GET [base]?_type=Condition,Observation&[parameters]{&_format=[mime-type]}

This is a request to search on both Condition and Observation. In this case, the only parameters that can be used are those defined for both Condition and Observation (using SearchParameter.base - see Cross-resource Search Parameters), or the parameters defined for all resources. If a search lists types not listed in SearchParameter.base for any of the parameters, this is an error, and a server SHOULD return a 400 status. It is also possible to search on all types at once:

  GET [base]?[parameters]{&_format=[mime-type]}
```

Maybe we were confused by this paragraph at the [top of the page](https://www.hl7.org/fhir/http.html#styleguide):
```
This specification uses the underscore as a prefix to disambiguate reserved names from other names in 3 cases:

    To differentiate system wide history and search interactions from interactions on Resource Types
    To differentiate search, history and similar interactions from instances of a resource type
    To differentiate search parameters defined for all resources from those defined for specific resource types
```

Specifically, I think the first part there (To differentiate system wide history and search interactions) is misleading.

NOTE:  rather than removing support for the `[base]/_search` endpoint, we should support POST method searches on that endpoint.

**Comment by albertwang-ibm** [comment]
After studying Fhir r4 search spec, I think we need to add:
(1) Multiple resource types search with GET using base url with _type parameter
(2) Multiple resource types search with POST using base url+_search with _type parameter.
(3) All resource types search with GET using base url.
(4) All resource types search with POST using base url+_search

**Comment by prb112** [comment]
Closed as the PR is accepted
