### ISSUE TITLE
Provide overloaded setters that take native Java objects

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#2621]
**Is your feature request related to a problem? Please describe.**
fhir-model provides static factory helpers like String.of, Code.of, etc.  However, due to the decision to use the fhir names verbatim, some of the class names conflict with built-in java types (or heavily used types) which means you have to fully quality their usage.

For just this reason, we introduced static factory methods String.string, Boolean.bool, etc.
However, its annoying to explain to new users that they have to statically import those in each class they want to work with the model.

**Describe the solution you'd like**
Start by overriding all the setters in all the fhir-model builders where the argument type conflicts with a common java class name in the jre:
* String
* Integer
* Boolean
* Date
* Instant
* others?

The implementation of these setters would simply call our existing factory methods (at least for any non-null input).

**Describe alternatives you've considered**
Some kind of simplified java facade that is layered on top of the existing model but present a more java-friendly view (e.g. no primitive extensions, but the ability to drill down in the "real" model if/when needed).

**Acceptance Criteria**

1.  
   GIVEN [a precondition]
    AND [another precondition]
   WHEN [test step]
    AND [test step]
   THEN [verification step]
    AND [verification step]

**Additional context**
The Collection<> flavor of the setter cannot be overridden due to type erasure, but I think that is OK since this is really just a convenience mechanism anyway.

**Comment by lmsurpre** [comment]
One unforseen consequence of adding the overloaded methods is that it can break client code that is calling an effected builder setter with null:

![image](https://user-images.githubusercontent.com/5478798/130004865-1dd7d47a-ace2-4830-8e42-c647340ed3dc.png)

Is it a deal-breaker?

**Comment by lmsurpre** [comment]
Another interesting tidbit:  there seems to be a bug in Eclipse where it lists the overloaded method but presents the javadoc of the latter method for *both* instances:

![image](https://user-images.githubusercontent.com/5478798/130009383-e2a4b78f-1c47-402a-8d89-3bb4f1c0b8f3.png)

![image](https://user-images.githubusercontent.com/5478798/130009420-79b34aa3-76b1-4758-8b92-ef484025b8df.png)

Whichever one was declared last is the one the eclipse uses, so I think I'll put the new java-friendly overload setters *before* the existing ones.
This affects String, Boolean, and Integer overrides, but not Date and Instant ones (because those ones have Java equivalents that have different simple names).

**Comment by prb112** [comment]
I ran through the mapping above with various FHIR Resources, it feels very natural as I built up an object.  I'll mark this as closed.
