### ISSUE TITLE
Whole-system search using _id parameter performs poorly

### ISSUE THREAD

**Issue by michaelwschroeder** [IBM/FHIR#2629]
**Describe the bug**
Whole-system search using the `_id` search parameter performs poorly. The generated SQL contains a clause to check against the logical_resources.logical_id column, but no corresponding clause to check against the logical_resources.resource_type_id column, so a table scan is done rather than using an index.

**Environment**
4.8.3

**To Reproduce**
1. Run the following query against a DB with a large number of resources: `.../v4?_id=xxx`

**Expected behavior**
This query should run in less than a second.

**Additional context**

**Comment by d0roppe** [comment]
Verified this is a lot faster with this fix. closing issue.
