### ISSUE TITLE
Under certain conditions, FHIR search returns the same resource multiple times

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#265]
1.  Create a resource with a repeated searchable field (e.g. multiple tags with the same value)
2.  Search on this value

Actual results:
The search result includes the indexed resource multiple times

Expected result:
Per http://hl7.org/fhir/dstu2/bundle.html#bundle-unique the resulting bundle/searchset should have no duplicates.

This has come up on our slack channel a couple times:

1. https://ibm-watsonhealth.slack.com/archives/C14JTTR6C/p1497284931413446
2. https://ibm-watsonhealth.slack.com/archives/C14JTTR6C/p1540834247005400

For further background, please see https://nsjazz.raleigh.ibm.com:8050/ccm/web/projects/Watson%20Health%20Cloud%20%28Development%29#action=com.ibm.team.workitem.viewWorkItem&id=212546
I'm not sure whether `comment 18` is still relevant or not since we've switch to the "normalized" schema since then.

**Comment by lmsurpre** [comment]
John:  This should probably happen during extraction by deduping extracted values for a given search parameter path. Since all model objects implement equals/hashCode. It may be as easy as using Sets instead of Lists.

Lee:  Regarding de-dup during extraction, that may be smart but I'm not sure its sufficient.
For example, there could be two different values with the same "starts with" substring. Our queries need to be smart enough not to return same resource twice in those cases.
However, agree that *most* cases of this (in the wild) are from repeating values that get indexed multiple times, so maybe we carve off just the "de-dup during extraction" piecer and target that fro 4.0.0.

**Comment by lmsurpre** [comment]
Step 1 is to create some tests that replicate the issue / better define under which condititions we see this.

**Comment by albertwang-ibm** [comment]
the duplicated resource issue was caused by the joins (of the value tables) in our older selectClause builder, and it caused the same resource showed up exactly the same time as the matched conditions, and with my performance fix for 262, this was also fixed.

I'm adding test cases to cover this.
