### ISSUE TITLE
Validate extension-search-parameters config file for invalid types

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#266]
Search parameters have a type that may differ from the datatype of the element.

In the current implementation, search parameters of any type can be defined on any field (of any type). 

This can result in runtime errors when you actually create a resource instance with the given field.
For example, it is possible to declare a search parameter of type `quantity` on a field of type `integer` or `decimal`.  However, at runtime, creating a resource with this field will result in an error like:
```
'java.sql.SQLIntegrityConstraintViolationException: Column 'CODE'  cannot accept a NULL value.' was thrown while evaluating an expression.
```
Where possible, I think we should check the extension-search-parameters file against the resource definitions to look for mismatches.
For true extensions, we can't know what data type the field has (unless we are told via a StructureDefinition) and so we might only be able to enforce that at runtime.  However, we could perform this checking in AbstractProcessor (or earlier) in order to prevent this type of issue from surfacing at the database level.

For the list of valid combinations please see https://www.hl7.org/fhir/DSTU2/search.html#table

**Comment by lmsurpre** [comment]
Alternative:  just write up "best practice" inside the SearchParameter extensions guide.

**Comment by prb112** [comment]
Lee / Paul - worked on the alternative which includes documentation. in #280
