### ISSUE TITLE
$bulkdata-status needs to indicate when no data was exported

### ISSUE THREAD

**Issue by kmbarton423** [IBM/FHIR#2676]
**Is your feature request related to a problem? Please describe.**
Ran an $export using _type and _typeFilter that I did not match any data so nothing was exported.
Ran $bulkdata-status to for the associated jobId.

`{
    "transactionTime": "2021-08-10T21:14:53.311Z",
    "request": "https://localhost:9443/fhir-server/api/v4/Patient/$export?_type=Encounter&_typeFilter=Encounter?status=active",
    "requiresAccessToken": false
}`

The status above left me guessing.

**Describe the solution you'd like**
I would like to see some indication returned by $bulkdata-status that the job finished successfully and no data was exported.

**Describe alternatives you've considered**
Maybe a return code would be better but I don't see this as a failure.

**Comment by lmsurpre** [comment]
Options:
A. empty array
B. a separate field with an OperationOutcome to explain that everything worked but there was nothing to export 

The response body is defined at https://hl7.org/fhir/uv/bulkdata/export/index.html#response---complete-status
Proposal:  include an empty array *and* an extension that has an OperationOutcome with the detaiils

**Comment by kmbarton423** [comment]
Confirmed empty array and extension now returned:

`{
    "transactionTime": "2021-08-24T15:13:02.866Z",
    "request": "https://localhost:9443/fhir-server/api/v4/Patient/$export?_type=Encounter&_typeFilter=Encounter?status=active",
    "requiresAccessToken": false,
    "output": [],
    "extension": {
        "outcome": {
            "resourceType": "OperationOutcome",
            "issue": [
                {
                    "severity": "information",
                    "code": "informational",
                    "details": {
                        "text": "No Data Exported"
                    }
                }
            ]
        }
    }
}`
