### ISSUE TITLE
Is this a public private key?

### ISSUE THREAD

**Issue by 25077667** [IBM/FHIR#2685]
https://github.com/IBM/FHIR/blob/6d0a060e03419afa5c5abca878c68ef4537cb28c/build/docker/minio/private.key#L1

**Comment by prb112** [comment]
> https://github.com/IBM/FHIR/blob/6d0a060e03419afa5c5abca878c68ef4537cb28c/build/docker/minio/private.key#L1

Yes, it is. It's only used for testing in a CI/CD pipeline contained within GitHub Acionts.

**Comment by prb112** [comment]
> > https://github.com/IBM/FHIR/blob/6d0a060e03419afa5c5abca878c68ef4537cb28c/build/docker/minio/private.key#L1
> 
> Yes, it is. It's only used for testing in a CI/CD pipeline contained within GitHub Acionts.

I also wanted to say thank you @25077667 for asking - I think it's a great question and a good public service to check.   More details are at https://github.com/IBM/FHIR/tree/main/build/certificates
