### ISSUE TITLE
Support _pretty query parameter

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#269]
From https://www.hl7.org/fhir/http.html#parameters:

```
_pretty

Clients that wish to request for pretty-printed resources (either in JSON or XML) can use the _pretty parameter:

GET [base]/Patient/example?_pretty=true

Value values are true and false. Since pretty printed or not makes no difference to the content, this is only of interest for development tools, and servers MAY choose to support this parameter. 
```

**Comment by lmsurpre** [comment]
we already support it from a Header

one option would be to use the query parameter to set the corresponding header (similar to _format)

**Comment by prb112** [comment]
`<hint>`
To add to Lee's comments, FHIRHttpServletRequestWrapper is where the change should be made.  Along with updated / new tests in fhir-server-tests.

**Comment by prb112** [comment]
PR https://github.com/IBM/FHIR/pull/444
