### ISSUE TITLE
FHIRNotificationService should emit event for patch update

### ISSUE THREAD

**Issue by fsa1803** [IBM/FHIR#2692]
**Describe the bug**
When  patch a Patient resource no websocket event is triggered.

**Environment**
IBM FHIR Server :  4.9
Windows:              10
JVM:                      JRE 1.8.0_251

**To Reproduce**
1. Enable websocket notification
2. Open ws channel, I use Chrome Extension: "Web Socket Client"
3. Insert Patient resource 
4. WS console show me the event: 
{"lastUpdated":"2021-08-17T11:01:15.307Z","location":"Patient/MPI0000000017/_history/1","operationType":"create","resourceId":"MPI0000000017","datasourceId":"default","tenantId":"default"}
5. Update gender:
curl -s -H "Content-Type: application/json-patch+json;charset=UTF-8" -XPATCH https://localhost:9443/fhir-server/api/v4/Patient/MPI0000000017 -u fhiruser:fhiruser --insecure -d '
[{ "op": "replace", "path": "/gender", "value": "male" }]
'

**Expected behavior**
A notification for Patient update

**Comment by prb112** [comment]
Thank you for opening this @fsa1803 

The default behavior is to do nothing with this notification. 

```
    /**
     * This method is called during the processing of an 'patch' REST API invocation, immediately after the updated
     * resource has been stored by the persistence layer.
     * 
     * @param event
     *            information about the 'patch' event
     * @throws FHIRPersistenceInterceptorException
     */
    default void afterPatch(FHIRPersistenceEvent event) throws FHIRPersistenceInterceptorException {
    }
```

If this helps your use case, we'll implement these in the corresponding classes as outlined below.

![image](https://user-images.githubusercontent.com/3016328/129729738-254fd6c6-4b70-44ea-a70a-d69309623cc8.png)

**Comment by fsa1803** [comment]
Fine, this help my use case. 

Thanks

**Comment by prb112** [comment]
> Fine, this help my use case.
> 
> Thanks

OK, thanks, just testing the change now and will review with Lee

**Comment by d0roppe** [comment]
Tested this fully with the FHIRPath Patch path and seems to be issuing the correct notifications.
