### ISSUE TITLE
Update schema diagram/description in documentation

### ISSUE THREAD

**Issue by punktilious** [IBM/FHIR#2694]
The schema documentation has fallen behind the current implementation. Update the diagram and document the new tables.

**Comment by lmsurpre** [comment]
For QA:

1. try following the sample commands in the tl;dr version at https://github.com/IBM/FHIR/tree/main/fhir-persistence-schema#tldr

2. follow links and confirm any expected information is present / arranged reasonably at https://github.com/IBM/FHIR/blob/main/fhir-persistence-schema/docs/SchemaToolUsageGuide.md

**Comment by d0roppe** [comment]
read through the documentation and checked the links.  Working as expected.  Closing issue.
