### ISSUE TITLE
Upgrade Dependencies in 4.9.0

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#2698]
**Describe the bug**
Upgrade Dependencies in 4.9.0

**Environment**
Which version of IBM FHIR Server?
4.9.0

**To Reproduce**
mvn dependency:list -f fhir-parent -Dscope=compile | grep ":.*:.*:*" | sed "s|\[INFO\]    ||g" | sort -u  | grep compile > sorted.log

**Additional context**

Upgrade
com.ibm.cos:ibm-cos-java-sdk-core:jar:2.9.0:compile
com.ibm.cos:ibm-cos-java-sdk-kms:jar:2.9.0:compile
com.ibm.cos:ibm-cos-java-sdk-s3:jar:2.9.0:compile
com.ibm.cos:ibm-cos-java-sdk:jar:2.9.0:compile
upgrade to 2.10.1
            <dependency>
                <groupId>com.ibm.cos</groupId>
                <artifactId>ibm-cos-java-sdk</artifactId>
                <version>2.10.1</version>
            </dependency>

                        <dependency>
                <groupId>ch.qos.logback</groupId>
                <artifactId>logback-classic</artifactId>
                <version>1.2.5</version>
            </dependency>
            <dependency>
                <groupId>ch.qos.logback</groupId>
                <artifactId>logback-core</artifactId>
                <version>1.2.5</version>
            </dependency>

                        <dependency>
                
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-annotations</artifactId>
                <version>2.12.3</version>
            </dependency>

**Comment by lmsurpre** [comment]
security scans are now passing...no remaining warnings on open source dependencies.

if we find any issues as part of ongoing testing, keep in mind these dependency updates.
