### ISSUE TITLE
Document the schema migration process on the project wiki

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#270]
We used to use liquibase.  Now we use custom database-util logic.  I need to learn this part of our code and I'll create some documentation as I do it.

**Comment by lmsurpre** [comment]
I also left a TODO in the FHIRServerUserGuide for this content as well.

**Comment by prb112** [comment]
Dockerfile used to test this is merged in this PR https://github.com/IBM/FHIR/pull/413/files/fc3635fd3e250dada4ff3979f517e3944bf9ff71#diff-b0ee41879dbc3cde079556c7613ea929

**Comment by prb112** [comment]
PR https://github.com/IBM/FHIR/pull/452  cleans up documentation related to the docker, which is used to test this issue/migration

**Comment by prb112** [comment]
PR https://github.com/IBM/FHIR/pull/782
