### ISSUE TITLE
bulkdata preflight checks should verify output provider config

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#2709]
**Is your feature request related to a problem? Please describe.**
I submitted a bulk export job against a configure s3 storageProvider.  It accepted the job but then failed with this:
```
StepChunkListener: job[bulkexportfastjob/1/1] --- com.ibm.cloud.objectstorage.services.s3.model.AmazonS3Exception: The specified bucket does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchBucket; Request ID: 50967bf1-b6f6-4ae3-acf2-78598f2f4d36), S3 Extended Request ID: null
com.ibm.jbatch.container.exception.BatchContainerRuntimeException: com.ibm.cloud.objectstorage.services.s3.model.AmazonS3Exception: The specified bucket does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchBucket; Request ID: 50967bf1-b6f6-4ae3-acf2-78598f2f4d36), S3 Extended Request ID: null
	at com.ibm.jbatch.container.controller.impl.ChunkStepControllerImpl.readItem(ChunkStepControllerImpl.java:360)
	at com.ibm.jbatch.container.controller.impl.ChunkStepControllerImpl.readAndProcess(ChunkStepControllerImpl.java:245)
	at com.ibm.jbatch.container.controller.impl.ChunkStepControllerImpl.invokeChunk(ChunkStepControllerImpl.java:626)
	at com.ibm.jbatch.container.controller.impl.ChunkStepControllerImpl.invokeCoreStep(ChunkStepControllerImpl.java:795)
	at com.ibm.jbatch.container.controller.impl.BaseStepControllerImpl.execute(BaseStepControllerImpl.java:295)
	at com.ibm.jbatch.container.controller.impl.ExecutionTransitioner.doExecutionLoop(ExecutionTransitioner.java:118)
	at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl.executeCoreTransitionLoop(WorkUnitThreadControllerImpl.java:96)
	at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl.executeWorkUnit(WorkUnitThreadControllerImpl.java:178)
	at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl$AbstractControllerHelper.runExecutionOnThread(WorkUnitThreadControllerImpl.java:503)
	at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl.runExecutionOnThread(WorkUnitThreadControllerImpl.java:92)
	at com.ibm.jbatch.container.util.BatchWorkUnit.run(BatchWorkUnit.java:113)
	at com.ibm.ws.context.service.serializable.ContextualRunnable.run(ContextualRunnable.java:79)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:836)
Caused by: com.ibm.cloud.objectstorage.services.s3.model.AmazonS3Exception: The specified bucket does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchBucket; Request ID: 50967bf1-b6f6-4ae3-acf2-78598f2f4d36), S3 Extended Request ID: null
```

In this particular case, I think I accidentally had the bucketName set to "".

**Describe the solution you'd like**
The bulkdata preflight checks should check for whether or not the configured bucket exists.

**Describe alternatives you've considered**
One alternative would be to auto-create the bucket if it doesn't exist, but that doesn't seem like a great idea because it might be hard to know the desired ACL / access policies for the bucket.

**Acceptance Criteria**

1.  
   GIVEN [a precondition]
    AND [another precondition]
   WHEN [test step]
    AND [test step]
   THEN [verification step]
    AND [verification step]

**Additional context**
Similar idea to https://github.com/IBM/FHIR/issues/2083#issuecomment-805766005

**Comment by prb112** [comment]
> **Is your feature request related to a problem? Please describe.**
> I submitted a bulk export job against a configure s3 storageProvider. It accepted the job but then failed with this:
> 
> ```
> StepChunkListener: job[bulkexportfastjob/1/1] --- com.ibm.cloud.objectstorage.services.s3.model.AmazonS3Exception: The specified bucket does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchBucket; Request ID: 50967bf1-b6f6-4ae3-acf2-78598f2f4d36), S3 Extended Request ID: null
> com.ibm.jbatch.container.exception.BatchContainerRuntimeException: com.ibm.cloud.objectstorage.services.s3.model.AmazonS3Exception: The specified bucket does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchBucket; Request ID: 50967bf1-b6f6-4ae3-acf2-78598f2f4d36), S3 Extended Request ID: null
> 	at com.ibm.jbatch.container.controller.impl.ChunkStepControllerImpl.readItem(ChunkStepControllerImpl.java:360)
> 	at com.ibm.jbatch.container.controller.impl.ChunkStepControllerImpl.readAndProcess(ChunkStepControllerImpl.java:245)
> 	at com.ibm.jbatch.container.controller.impl.ChunkStepControllerImpl.invokeChunk(ChunkStepControllerImpl.java:626)
> 	at com.ibm.jbatch.container.controller.impl.ChunkStepControllerImpl.invokeCoreStep(ChunkStepControllerImpl.java:795)
> 	at com.ibm.jbatch.container.controller.impl.BaseStepControllerImpl.execute(BaseStepControllerImpl.java:295)
> 	at com.ibm.jbatch.container.controller.impl.ExecutionTransitioner.doExecutionLoop(ExecutionTransitioner.java:118)
> 	at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl.executeCoreTransitionLoop(WorkUnitThreadControllerImpl.java:96)
> 	at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl.executeWorkUnit(WorkUnitThreadControllerImpl.java:178)
> 	at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl$AbstractControllerHelper.runExecutionOnThread(WorkUnitThreadControllerImpl.java:503)
> 	at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl.runExecutionOnThread(WorkUnitThreadControllerImpl.java:92)
> 	at com.ibm.jbatch.container.util.BatchWorkUnit.run(BatchWorkUnit.java:113)
> 	at com.ibm.ws.context.service.serializable.ContextualRunnable.run(ContextualRunnable.java:79)
> 	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:238)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at java.base/java.lang.Thread.run(Thread.java:836)
> Caused by: com.ibm.cloud.objectstorage.services.s3.model.AmazonS3Exception: The specified bucket does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchBucket; Request ID: 50967bf1-b6f6-4ae3-acf2-78598f2f4d36), S3 Extended Request ID: null
> ```
> 
> In this particular case, I think I accidentally had the bucketName set to "".
> 
> **Describe the solution you'd like**
> The bulkdata preflight checks should check for whether or not the configured bucket exists.
> 
> **Describe alternatives you've considered**
> One alternative would be to auto-create the bucket if it doesn't exist, but that doesn't seem like a great idea because it might be hard to know the desired ACL / access policies for the bucket.
> 
> **Acceptance Criteria**
> 
>     1. GIVEN [a precondition]
>        AND [another precondition]
>        WHEN [test step]
>        AND [test step]
>        THEN [verification step]
>        AND [verification step]
> 
> 
> **Additional context**
> Similar idea to [#2083 (comment)](https://github.com/IBM/FHIR/issues/2083#issuecomment-805766005)

This should have generated a warning. The reason it is a warning in this case is that we want it to work with virtualhost versus api URL endpoints. 

You should see a warning in the locks that it doesn't exist. 

What we can do is have an explicit exception returned back to the client when it fails, rather than a generic 500.

Also We have the "create" option in the configs. 
1/ the create option we have 
2/ fewer jars in the fhir-server-webapp by not having the s3 jars in the app

**Comment by lmsurpre** [comment]
> This should have generated a warning. The reason it is a warning in this case is that we want it to work with virtualhost versus api URL endpoints.

Yeah, this sounds vaguely familiar to me now.  It still seems surprising that there is no reliable way to detect if a bucket exists or not in preflight.  I don't think the better error message addresses the root concern on this one, but its definitely not a high-priority issue either...I just wanted to capture the fact we don't catch this error condition in preflight and that ideally we would.

**Comment by prb112** [comment]
It has to do with how the s3 api treats virtualhosts... you don't find out it is bad until the very time you begin to write.

**Comment by lmsurpre** [comment]
I still think preFlight should detect this condition, but I understand that its either not possible or not worth it given current S3 client limitations.  How about we ice-box this one?

**Comment by prb112** [comment]
I do think I addressed this.  I don't think it's possible to do it otherwise.  Happy to discuss in more detail

**Comment by prb112** [comment]
QA: have an invalid COS setting

**Comment by d0roppe** [comment]
This works for $export, but not for $import.  it accepts the $import, and the bulkdata-status of the import job gets the 500 error, but no indication as to why.
The export is not started, and gets the 500 error with the message: `"text": "The location for the bulkdata operation is not found"`

**Comment by prb112** [comment]
Chatting with Dag on this one:

**Comment by d0roppe** [comment]
Verified, that incorrect info for file, ibm-cos, and aws-s3 all stop the request if there are issues with the configuration.  Closing issue.
