### ISSUE TITLE
Bulk Export Status Report

### ISSUE THREAD

**Issue by dabimahesh** [IBM/FHIR#2714]
Regarding one more scenario for bulk export

A scenario while testing in Inferno

Request URL:
https://***:9443/fhir-server/api/v4/$bulkdata-status?job=HRheZqFY_KT5TXhdXFuY7g

Response Body:
{
"transactionTime": "2021-08-18T10:21:53.82Z",
"request": "https://***:9443/fhir-server/api/v4/Group/17b58c31108-77f6763e-008b-4010-b428-c42ee061aa57/$export",
"requiresAccessToken": false,
"output": [{
"type": "AllergyIntolerance",
"url": "_jVMAj-5zOenYBhcTN5pa5b6DvR2rsx2Cpv4l9wuXOY/AllergyIntolerance_1.ndjson",
"count": 10
},
{
"type": "CarePlan",
"url": "_jVMAj-5zOenYBhcTN5pa5b6DvR2rsx2Cpv4l9wuXOY/CarePlan_1.ndjson",
"count": 2
}
]
}

This test case is a pass, except that it needs few extra things in the response as mentioned below:

 "requiresAccessToken": false. This parameter in the response is false, we need to return this in response as true. We have done all the required changes but are not able to get this. Seems that it is fixed value.
Could you please let us know how to achieve this?

https://chat.fhir.org/#narrow/stream/212434-ibm/topic/releases/near/250499231

**Comment by prb112** [comment]
Marked this as an enhancement.

**Comment by prb112** [comment]
Adding an entry to the storageProvider`fhirServer/bulkdata/storageProviders/" + provider + "/requiresAccessToken`

**Comment by lmsurpre** [comment]
I confirmed that the `"requiresAccessToken"` in the output now takes it value from this new config property and that the default is still `false`.
