### ISSUE TITLE
Bulk Export Status

### ISSUE THREAD

**Issue by dabimahesh** [IBM/FHIR#2715]
While doing bulkdata status request  "error":[], should be a part of the response, even if there is no error in this request. Please help us in this. This is required for ONC MU Inferno testing tool.

https://chat.fhir.org/#narrow/stream/212434-ibm/topic/releases/near/250080961

Thanks
Mahesh

**Comment by prb112** [comment]
Thanks, this is an enhancement.

**Comment by lmsurpre** [comment]
Confirmed that, upon successful export, the bulkdata-status endpoint response now contains `"error": []`
