### ISSUE TITLE
CodeSystem/$validate-code causes and NPE when display is not present in the data

### ISSUE THREAD

**Issue by JohnTimm** [IBM/FHIR#2716]
There are scenarios where a `$validate-code` operation causes a `500 Internal Server Error` due to a `NullPointerException` on line `1042` of `FHIRTermService`. This is because, when the code system is case-sensitive, we must normalize the display name before we compare:

```java
result = caseSensitive ? outcome.getDisplay().equals(coding.getDisplay()) : normalize(outcome.getDisplay().getValue()).equals(normalize(coding.getDisplay().getValue()));
```

We must add an additional null check on `outcome.getDisplay.getValue()` and `coding.getDisplay().getValue()` to protect against this.

**Comment by prb112** [comment]
QA - Tested for NPE, and found it returns properly
![image](https://user-images.githubusercontent.com/3016328/131525835-8943eead-7c54-45c8-86a0-b1cd4eb94250.png)
