### ISSUE TITLE
URI should default to complete match (not starts-with)

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#273]
**Describe the bug**
https://localhost:9443/fhir-server/api/v4/Patient?favorite-uri=http://www.ibm.com results in SQL like:
```sql
... P5.LOGICAL_RESOURCE_ID = R.LOGICAL_RESOURCE_ID AND 
(P5.PARAMETER_NAME_ID=3000 AND (P5.STR_VALUE LIKE ? ESCAPE '+'))

bindVariables=[http://www.ibm.com%]
```

**To Reproduce**
perform a search on a search parameter of type uri (e.g. `favorite-uri` in the tenant1 test config) and check the results

**Expected behavior**
From https://www.hl7.org/fhir/search.html#uri
> By default, matches are precise (e.g. case, accent, and escape) sensitive, and the entire URI must match.

**Comment by lmsurpre** [comment]
Start by adding a test for this to AbstractSearchURITest

**Comment by lmsurpre** [comment]
Also, don't forget to update Conformance.md if needed

**Comment by prb112** [comment]
PR https://github.com/IBM/FHIR/pull/447
