### ISSUE TITLE
Using fhir-persistence-schema CLI tool to drop schema gives an error

### ISSUE THREAD

**Issue by d0roppe** [IBM/FHIR#2758]
**Describe the bug**
using the fhir-persistance-schema CLI command to drop fhir schemas hits a bug
com.ibm.fhir.database.utils.api.DataAccessException: org.postgresql.util.PSQLException: ERROR: cannot drop table fhirdata.logical_resources because other objects depend on it
  Detail: constraint fk_logical_resource_tags_lr on table fhirdata.logical_resource_tags depends on table fhirdata.logical_resources
constraint fk_logical_resource_security_lr on table fhirdata.logical_resource_security depends on table fhirdata.logical_resources
  Hint: Use DROP ... CASCADE to drop the dependent objects too.
	at com.ibm.fhir.database.utils.postgres.PostgresTranslator.translate(PostgresTranslator.java:104)
	at com.ibm.fhir.database.utils.common.JdbcTarget.runStatement(JdbcTarget.java:48)
	at com.ibm.fhir.database.utils.common.CommonDatabaseAdapter.runStatement(CommonDatabaseAdapter.java:243)
	at com.ibm.fhir.database.utils.common.CommonDatabaseAdapter.dropTable(CommonDatabaseAdapter.java:282)
	at com.ibm.fhir.database.utils.model.Table.drop(Table.java:176)
	at com.ibm.fhir.database.utils.model.PhysicalDataModel.drop(PhysicalDataModel.java:185)
	at com.ibm.fhir.schema.app.Main.dropSchema(Main.java:502)
	at com.ibm.fhir.schema.app.Main.process(Main.java:2117)
	at com.ibm.fhir.schema.app.Main.main(Main.java:2218)
Caused by: org.postgresql.util.PSQLException: ERROR: cannot drop table fhirdata.logical_resources because other objects depend on it
  Detail: constraint fk_logical_resource_tags_lr on table fhirdata.logical_resource_tags depends on table fhirdata.logical_resources
**Environment**
Latest main and postgreSQL

**To Reproduce**

**Expected behavior**

**Additional context**
The issue highlights a testing gap in our CI/CD.  We should add a drop schema step that runs against each db...probably by extending the current migration tests with an extra step at the end.

**Comment by lmsurpre** [comment]
Also relates to #2136

**Comment by prb112** [comment]
test commands 
```
--prop db.host=hostname  --prop db.port=5432 --prop db.database=dropschemadb --prop user=fhiradmin --prop password=passw0rd     --db-type postgresql --create-schemas

--prop db.host=hostname  --prop db.port=5432 --prop db.database=dropschemadb --prop user=fhiradmin --prop password=passw0rd     --db-type postgresql --update-schema

--prop db.host=hostname  --prop db.port=5432 --prop db.database=dropschemadb --prop user=fhiradmin --prop password=passw0rd     --db-type postgresql --drop-schema-fhir --schema-name fhirdata --confirm-drop

--prop db.host=hostname  --prop db.port=5432 --prop db.database=dropschemadb --prop user=fhiradmin --prop password=passw0rd     --db-type postgresql --drop-schema-oauth --confirm-drop

--prop db.host=hostname  --prop db.port=5432 --prop db.database=dropschemadb --prop user=fhiradmin --prop password=passw0rd     --db-type postgresql --drop-schema-batch --confirm-drop --schema-name fhir_jbatch
```

**Comment by d0roppe** [comment]
First attempt at verification did not work, moving issue back to in progress.

**Comment by prb112** [comment]
PR https://github.com/IBM/FHIR/pull/2784/files

**Comment by d0roppe** [comment]
Closed the issue to quickly.  Still has a issue.

**Comment by d0roppe** [comment]
User error on the reopen.  if not using the fhir_jbatch or fhir-oauth schemas, but a different name the name of the schema needs to be stated after the --drop-schema-batch and the --drop-schema-oauth options.
