### ISSUE TITLE
Update searchParameterFilter change from 2.x

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#277]
Previously, when you configured a searchParamterFilter for a resource type, that filter implicitly included search paramters defined on the `Resource` type.

For example, an entry like
```
		"searchParameterFilter": {
			"Device": [
				"patient",
				"organization"
			],
```
would only allow you to search on patient and organization search parameters, not _id and _lastUpdated.

In the new implementation, to exclude _id and _lastUpdated search params, you'd need to create an entry with a key of "Resource":
```
		"searchParameterFilter": {
			"Resource": [
			],
```
and there is no way to exclude them from a specific resource type.

We need to fix the documentation to reflect this change.

**Comment by prb112** [comment]
PR https://github.com/IBM/FHIR/pull/295
