### ISSUE TITLE
Automate Term Graph Loader build

### ISSUE THREAD

**Issue by ibmatc** [IBM/FHIR#2798]
Term Graph loading was added as a Docker container in the fhir-install module via #2795.  The process requires a build script to automate the build of the image

I believe the pattern used by ibm-fhir-schematool can be followed here to script the build and add it to the release process. 
 The nuances of this pattern are complex so I excluded it from the initial release of the Term Graph loader code.

Without this update, the Term Graph Loader container will not remain up-to-date and may result in out-of-date images being used in future releases.

**Acceptance Criteria**
1.  
   GIVEN a new release of FHIR
   WHEN a build is initiated
   THEN a new version of the term-graph-loader image will be built and pushed to the docker repository

This approach was discussed with @prb112 and agreed to be a reasonable direction.

**Comment by prb112** [comment]
Docker repository such as ibm-fhir-term-loader 
Automation would follow similar to ibm-fhir-schematool

**Comment by prb112** [comment]
Fixed issue in https://github.com/IBM/FHIR/issues/2930
QA Complete - Adam was able to load data using the container
