### ISSUE TITLE
'migration' workflow fails to upload server logs

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#2803]
I am trying to debug a failed migration pipeline run, but it is hard to do that when we are missing the server logs in the artifacts section:  https://github.com/IBM/FHIR/actions/runs/1266952122

In our other workflows (e.g. `integration.yaml`) we have a `post-integration-test-docker.sh` script that runs after the integration tests and gathers to docker console output to a directory named `integration-test-results`.  Then it uploads all that as part of the `Upload logs` step.

The migration.yaml workflow seems to be doing something similar because it has an `Upload logs` step that uploads the content from `fhir/build/migration/integration-test-results`.  However, I don't think thats working because when I download the artifacts I see only these two files:
* current-integration-tests.log
* prev-integration-tests.log

-----

Note: the run linked above also lists some test failures like the following:
```
migration (db2, last)
expected:<201> but was:<500>
```
However, when I view the current-integration-tests.log from the attached artifact, it says that all of the tests were successful.  I'm hoping that the extra log output could possibly help untangle this.

**Comment by lmsurpre** [comment]
I noticed the following comment in build/migration/bin/7_current-integration-test.sh`:
> # Add || docker container logs "$(docker container ls --format {{.Names}} | grep -i ${migration} | grep -i fhir)"

Not sure if thats just for debug or some kind of TODO related to this.

**Comment by lmsurpre** [comment]
In our other pipelines, we gather the logs in two different spots:
* on success:  post-integration-test-docker.sh (at the end of the test step)
* on failure:  the Gather error logs step

I don't see a post-integration-test equivalent on the migration workflow, so I think we need to either:
A. add a step for that; or
B. *always* run the "Gather error logs" step

To be honest, I'm not totally sure why we don't do B in our other workflows...maybe just because this step was added later and we didn't want to mess with the existing (working) post-integration-test script/

**Comment by prb112** [comment]
> I noticed the following comment in build/migration/bin/7_current-integration-test.sh`:
> 
> ```
> # Add || docker container logs "$(docker container ls --format {{.Names}} | grep -i ${migration} | grep -i fhir)"
> ```
> 
> Not sure if thats just for debug or some kind of TODO related to this.

We can talk about it. You are looking at it a bit out of step, I'll explain when we chat.

**Comment by prb112** [comment]
I checked the latest PRs and can confirm they are present.
