### ISSUE TITLE
AdoptOpenJDK Images are deprecated and we need to convert to Eclipse builds

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#2814]
**Describe the bug**
AdoptOpenJDK Images are deprecated and we need to convert to Eclipse builds

**Environment**
Which version of IBM FHIR Server? 4.9.1 and below

IBM Semeru https://github.com/docker-library/official-images/pull/10666
eclipse-temurin:<version>-alpine
https://hub.docker.com/_/eclipse-temurin/?tab=description

**Expected behavior**
n/a

**Additional context**
n/a

**Comment by prb112** [comment]
We have to use UBI.  
Pick up the Adoptium one if Semeru is not available.

**Comment by prb112** [comment]
PR https://github.com/IBM/FHIR/pull/2815

**Comment by lmsurpre** [comment]
This one caused our 4.9.2 release automation to hiccup and so our schematool image wasn't published at first.  Paul manually addressed the missing image on dockerhub.  Moving forward, we just need to monitor this docker repo as its location may change.

**Comment by punktilious** [comment]
Tested on RHEL8:
```
ibm-fhir-schematool$ docker run  --add-host=host.docker.internal:127.0.0.1 --env ENV_TOOL_INPUT=$(cat persistence.json | base64 -w 0) localhost/ibm-fhir-schematool:4.10.0
...
2021-10-07 07:51:10.568 00000001    INFO   com.ibm.fhir.schema.app.Main Processing took:   7.063 s
2021-10-07 07:51:10.572 00000001    INFO   com.ibm.fhir.schema.app.Main SCHEMA CHANGE: OK
+ set +x
Skipping refresh-tenants as it's not needed on 'postgresql'
```

Verified.
