### ISSUE TITLE
SearchParameter processing should be version-aware

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#2843]
**Is your feature request related to a problem? Please describe.**
During startup, we build a ParametersMap from the search parameters in the registry:
https://github.com/IBM/FHIR/blob/main/fhir-search/src/main/java/com/ibm/fhir/search/parameters/ParametersUtil.java#L136-L138

Currently, this map is keyed by "code" and "url"...it does not even look at version.

Then, when we get a request in, we read the relevant searchParameter config and filter the list of all search parameters down to the list of applicable ones.

Once we are packaging multiple versions of an IG (#2551), we might hit a case where there is some subtle change in the registered SearchParameter from one version to the next.

Does `FHIRRegistry.getInstance().getSearchParameters(searchParamType.value())` return all the versions, or just the "latest" one for each url? 
If it returns multiple versions, we will currently get some warnings as we add the duplicate versions to our ParametersMap (and only the one that "wins" will end up being used).

It would be nice to allow the operator to specify which versions of the search parameters they'd like to use as part of the searchParameter filtering config (`fhirServer/resources/[resource]/searchParameters/[code]`).

**Describe the solution you'd like**
1. ensure that `FHIRRegistry.getInstance().getSearchParameters(searchParamType.value())` returns all versions of all search parameters
2. update ParametersMap to be search parameter version aware
3. update our search parameter filtering logic to support users that specify a `|version` at the end of the search parameter urls from our config (`fhirServer/resources/[resource]/searchParameters/[code]`)

**Describe alternatives you've considered**
Support only the latest version of each search parameter

**Acceptance Criteria**

1.  
   GIVEN [a precondition]
    AND [another precondition]
   WHEN [test step]
    AND [test step]
   THEN [verification step]
    AND [verification step]

**Additional context**

**Comment by prb112** [comment]
QA Complete
1 - Tested without Version (0..1) https://www.hl7.org/fhir/searchparameter.html
2 - Tested with Version 

Worked as expected with the canonical and versions.
