### ISSUE TITLE
Remove (or restore) user-defined schematron feature

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#285]
In DSTU2, we supported a way for admins to configure the server with "user-defined schematron" that would fire under certain conditions (e.g. whenever we get an Observation resource).

In R4, we're trying to do away with the reliance on XML serialization for validation (primarilly for performance reasons) and I think we already removed the XSLT libraries needed for this feature.

I think we should "finish the job" and totally remove all traces of this feature before we have our initial R4 release.

**Comment by lmsurpre** [comment]
similar to https://github.com/IBM/FHIR/issues/153

**Comment by prb112** [comment]
worked for me
