### ISSUE TITLE
What is the username and password for openapi ?

### ISSUE THREAD

**Issue by darmawan01** [IBM/FHIR#2888]
Hi, need help.

How can i use the openapi to test the fhir-server. it's ask for username and passsword

![image](https://user-images.githubusercontent.com/23370707/138395536-840947f9-1592-4ae4-bd4d-df89a2d42cfb.png)

the server is live if check the metadata

![image](https://user-images.githubusercontent.com/23370707/138395675-175c54e9-45aa-4cde-abaf-2eb33a941c06.png)

i use the demo/example for run the fhir-server

**Comment by darmawan01** [comment]
Thanks @lmsurpre @punktilious , close this issues now 🙏🏻

**Comment by darmawan01** [comment]
is there any sample to add new user account that can access resources sir @lmsurpre @punktilious ?

**Comment by prb112** [comment]
```

**Comment by darmawan01** [comment]
thanks sir, so we need to added manually. so if i need something like RBAC to control access to the resources i should implement it outside of the fhir right ? 

i have plan to create some client app to communicate with fhir server

**Comment by lmsurpre** [comment]
you've got a couple different main options at this point:
1. use OpenLiberty.  the snippet paul shared above is just one example of how to configure users in a registry in Liberty.  see https://openliberty.io/docs/latest/user-registries-application-security.html for a lot more info.  today we don't expose fine-grained RBAC for such users...there's really only one security role and that is "FHIRUsers".  That means you'd need to either modify the server or add your RBAC in front of it.
2. use OAuth.  via our `fhir-smart` module, we can enforce "SMART" authorization scopes.  so if you can stand up a "SMART Authorization Server", you could use that to control who is able to get which scopes.  see https://ibm.github.io/FHIR/guides/FHIRServerUsersGuide#53-openid-connect-and-oauth-20 for a little more detail, although most of the work here is in the auth server.

**Comment by darmawan01** [comment]
got it, thanks for the clear answer. and now i am trying to implement [openid](https://ibm.github.io/FHIR/guides/FHIRServerUsersGuide#53-openid-connect-and-oauth-20 )
