### ISSUE TITLE
Move kafka-clients from 2.8.1 to 3.0.0

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#2923]
Move kafka-clients from 2.8.1 to 3.0.0

Failing PR https://github.com/IBM/FHIR/pull/2895

**Comment by lmsurpre** [comment]
I ran `mvn dependency:tree -f fhir-parent` and confirmed all instances were now at 3.0.0.

Intersetingly, I found `com.amazonaws:aws-java-sdk-kafka:jar:1.11.596:provided` in with the aws stuff, but that is marked as provided and so should be ok.
