### ISSUE TITLE
$everything operation fails when certain resources / search parameters are filtering out in fhir-server-config

### ISSUE THREAD

**Issue by sroorda** [IBM/FHIR#2963]
**Describe the bug**
We are using resource / search parameter filtering and tried to invoke $everything and it fails

**Environment**
4.9.2

**To Reproduce**
1. Setup our FHIR server to use resource/search parameter filtering.  The set of resources and parameters is different from what is in the Patient Compartment
2. Attempt to invoke the $everything operation on a patient (after retrieving a bearer token)
3. Operation Fails with a 500 internal server error
4. See the errors below, Appointment is not one of the resources in our config.

Returned from the REST call with the 500 code:
```
{
  "resourceType": "OperationOutcome",
  "id": "ac-11-29-36-b09cd017-b254-4943-bd97-da2a71ba82ae",
  "issue": [
    {
      "severity": "fatal",
      "code": "exception",
      "details": {
        "text": "Error retrieving $everything resources of type 'Appointment' for patient patient-1"
      },
      "expression": [
        "<empty>"
      ]
    }
  ]
}
```

Dug into the source code, it was swallowing the exception, we updated it to dump the exception and got this
```
Caused by: com.ibm.fhir.exception.FHIROperationException: The requested resource type 'Appointment' is not found  [probeId=ac-11-29-36-8116c0ba-9327-47d3-8e90-381226c5b1ef]
	at com.ibm.fhir.server.util.FHIRRestHelper.buildRestException(FHIRRestHelper.java:1758)
	at com.ibm.fhir.server.util.FHIRRestHelper.validateInteraction(FHIRRestHelper.java:2855)
	at com.ibm.fhir.server.util.FHIRRestHelper.doSearch(FHIRRestHelper.java:1284)
	at com.ibm.fhir.server.util.FHIRRestHelper.doSearch(FHIRRestHelper.java:1273)
	at com.ibm.fhir.operation.everything.EverythingOperation.doInvoke(EverythingOperation.java:210)
	... 62 more
```

**Expected behavior**
It appears from the code that the $everything operation is invoking search using the Patient Compartment definition.
```
try {
                results = resourceHelper.doSearch(compartmentType, PATIENT, logicalId, searchParameters, null, null);
```

I think a reasonable solution would be 1 of the following:

A. documentation on the proper set of resources/search params to enable $everything to work 
B. a way for me to override the default set with my own "custom" set
C. apply the same filtering logic to this set of resources / search parameter that are applied on search

**Additional context**
None

**Comment by prb112** [comment]
Worth noting the $everything operation is able to establish a whitelist of Resources to return. 

```
_type | 0..* | code |   |   | One  or more parameters, each containing one or more comma-delimited FHIR  resource types to include in the return resources. In the absence of any  specified types, the server returns all resource types
-- | -- | -- | -- | -- | --
```

**Comment by lmsurpre** [comment]
decision:  lets implement option C on this one and leave any future enhancements to other issues:

> C. apply the same filtering logic to this set of resources / search parameter that are applied on search

instead of scoping it to just the `$everything` impl, we could do the config-based filtering of the Compartment definition.  this way, compartment search could benefit from the same type of checking.

Potential problem scenario:
1. config:  no search on Appointment resources (create is allowed)
2. ingest an Appointment (behavior here depends on https://github.com/IBM/FHIR/issues/1777)
3. config update:  now we can search Appointment
4. Compartment search comes in.  miss the previously ingested Appointment
REINDEX REQUIRED TO FIX

We'd need to decide if the compartment membership should be extracted during ingestion if search is not enabled for that resource type / inclusion parameter.  That is related to https://github.com/IBM/FHIR/issues/1777

**Comment by sfc42** [comment]
My FHIR pull request for this issue is:  https://github.com/IBM/FHIR/pull/3164

**Comment by prb112** [comment]
Created a docker image 
setup `fhirServer/resources/open = true`
Created a Dummy User - curl -k --location --request POST 'https://localhost:9443/fhir-server/api/v4' --header 'Content-Type: application/fhir+json' --user "fhiruser:${DUMMY_PASSWORD}" --data-binary  "@Marco_Antonio298_Hurtado459_d171d808-1f31-4ad3-aba5-e03a2fa921c7.json" -o response.json
setup `fhirServer/resources/open = false`
Confirmed configuration shows only two resources - https://localhost:9443/fhir-server/api/v4/metadata?_format=application/fhir+json
Check https://localhost:9443/fhir-server/api/v4/Patient?_format=application/fhir+json for the uuid 17e4f762755-28066b72-a4e2-4592-b220-a86aec92dfa5
Ran $everything

*Unsupported Resource*

curl -k --location --request GET 'https://localhost:9443/fhir-server/api/v4/Patient/17e4f762755-28066b72-a4e2-4592-b220-a86aec92dfa5/$everything?_type=CarePlan,CareTeam&_since=2021-01-01T00:00:00Z&_count=1'     --header 'Content-Type: application/fhir+json'     --user "fhiruser:${DUMMY_PASSWORD}" -o care.json

{"resourceType":"OperationOutcome","id":"ac-11-0-2-9e54f765-e981-4af8-ae0d-a64e897be939","issue":[{"severity":"fatal","code":"invalid","details":{"text":"The following resource types are not supported by this operation: CarePlan,CareTeam"},"expression":["<empty>"]}]}

*Supported Resource*
curl -k --location --request GET 'https://localhost:9443/fhir-server/api/v4/Patient/17e4f762755-28066b72-a4e2-4592-b220-a86aec92dfa5/$everything?_type=Observation&_since=2021-01-01T00:00:00Z&_count=1'     --header 'Content-Type: application/fhir+json'     --user "fhiruser:${DUMMY_PASSWORD}" -o care.json

Returns expected bundle

*No _type* 
curl -k --location --request GET 'https://localhost:9443/fhir-server/api/v4/Patient/17e4f762755-28066b72-a4e2-4592-b220-a86aec92dfa5/$everything?_since=2021-01-01T00:00:00Z&_count=1'     --header 'Content-Type: application/fhir+json'     --user "fhiruser:${DUMMY_PASSWORD}"

Returns the expected Bundle

*Bad fhirServer/resources entry*

Tried with a bad xObservation and the code paths still protect/work.
