### ISSUE TITLE
Location URI is wrong when resource id begins with resource type name

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#2965]
**Describe the bug**

**Environment**
main

**To Reproduce**
1. issue a PUT to `{{base}}/Patient/{{id}}` with an id like "Patient1"
2. note the location header in the response

The resource is created successfully, but the location header in the response has an extra `/Patient`:
`https://localhost:9443/fhir-server/api/v4/Patient/Patient/Patient1/_history/1`

**Expected behavior**
The location header should point to the proper absolute url of the created resource

**Additional context**
When we try to construct the baseUrl from the request, we mistake the `/Patient1` for the `/Patient` segment of the path.

**Comment by d0roppe** [comment]
Verified this no longer happens.  Verified with 3 different resource types.
