### ISSUE TITLE
Stored procedure changes should update whole-schema-version

### ISSUE THREAD

**Issue by punktilious** [IBM/FHIR#2979]
**Describe the bug**
Stored procedures do not use the standard schema object versioning as they have always been applied after any schema changes are made. If only the stored procedures are updated, the whole-schema-version still needs to be updated otherwise the procedure update will be skipped unless the CLI tool is run using the --update-procedure option exclusively.

Also in testing this it was observed that a prior change for MigrateV0021AbstractTypeRemoval was removing required rows from the VERSION_HISTORY table by mistake. This is caused by:

```
                "DELETE FROM FHIR_ADMIN.VERSION_HISTORY"
                + " WHERE (OBJECT_NAME LIKE 'DOMAINRESOURCE_%'"
                + "   OR OBJECT_NAME LIKE 'RESOURCE_%')"
                + "   AND SCHEMA_NAME = ?";
```

which isn't selective enough, and ends up removing rows for RESOURCE_TYPES, RESOURCE_CHANGE_LOG and RESOURCE_TOKEN_REFS. This breaks future updates.

Quick fix is to filter out these tables in the above where clause:

```
                "DELETE FROM FHIR_ADMIN.VERSION_HISTORY"
                + "    WHERE (OBJECT_NAME LIKE 'DOMAINRESOURCE_%'"
                + "       OR OBJECT_NAME LIKE 'RESOURCE_%')"
                + "      AND SCHEMA_NAME = ? "
                + "      AND OBJECT_NAME NOT IN ('RESOURCE_TYPES', 'RESOURCE_CHANGE_LOG', 'RESOURCE_TOKEN_REFS')";
```

Although in general it's a bit risky using pattern match clauses like this to remove stuff.

**Comment by prb112** [comment]
I'm pretty sure this is merged

**Comment by d0roppe** [comment]
Verified that with this change the tables in question are not removed. closing issue
