### ISSUE TITLE
Intermittent unit test failure RevChainParameterParseTest.testValidReverseChainWithDateSearchParameter

### ISSUE THREAD

**Issue by punktilious** [IBM/FHIR#2981]
**Describe the bug**
Build threw the following failure:

```
[ERROR]   RevChainParameterParseTest.testValidReverseChainWithDateSearchParameter:617 expected [2021-11-12T11:43:49.999999Z] but found [2021-11-12T11:43:49Z]
```

**Environment**
Which version of IBM FHIR Server? 4.10.0-SNAPSHOT

**To Reproduce**
1. git clone
2. mvn clean install -f fhir-parent

**Expected behavior**
Unit test should pass.

**Additional context**
Happened only once, but indicates a rounding issue in the code or unit test that should be investigated.

**Comment by tbieste** [comment]
The issue occurs when the value of Instant.now() has a milliseconds value of exactly 0 (so roughly a 1 in 1000 chance).  In which case, the generated date string in the query will not include milliseconds. Therefore, the search upper-bound will be that second plus 999999 nano seconds.  As long as Instant.now() has a non-0 milliseconds value, the test as written will succeed.

**Comment by tbieste** [comment]
Same issue can happen with:
ChainParameterParseTest.testValidChainWithDateSearchParameter()

**Comment by prb112** [comment]
Since this is a Unit test we can skip QA as it is hit on CICD.

@punktilious I'll leave you to close
