### ISSUE TITLE
Update the server.xml to reflect the OpenSource pacakage name in the trace specification.

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#3]
Update the server.xml to reflect the OpenSource pacakage name in the trace specification. 

```
<logging traceSpecification="=info:com.ibm.watsonhealth.fhir.=finer" traceFormat="BASIC"/>
```

```
<logging traceSpecification="=info:com.ibm.watson.health.fhir.=finer" traceFormat="BASIC"/>
```

**Comment by lmsurpre** [comment]
https://github.com/IBM/FHIR/blob/master/fhir-server/liberty-config/server.xml#L98 <- looks right to me.  please re-open if you disagree
