### ISSUE TITLE
Set serverRegistryResourceProviderEnabled to false in the default fhir-server-config

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#3001]
**Is your feature request related to a problem? Please describe.**
Our performance guide recommends disabling this for performance reasons, and our default (if its not specified) is to have it off I think.  But our default fhir-server-config.json that gets installed has it on (presumably for CI testing reasons).

**Describe the solution you'd like**
Set this to false in our default fhir-server-config.json (the one that gets used by default after installing a new server / executing `docker run`).

**Describe alternatives you've considered**
keep it set to true in this default config file

**Acceptance Criteria**

1.  
   GIVEN [a precondition]
    AND [another precondition]
   WHEN [test step]
    AND [test step]
   THEN [verification step]
    AND [verification step]

**Additional context**

**Comment by prb112** [comment]
I thought about this a bit... perhaps this should be part of an epic to identify what we want our default to really be...

**Comment by lmsurpre** [comment]
QA plan:
1. build the docker image with our default config
2. confirm the default/fhir-server-config.json has serverRegistryResourceProviderEnabled set to false

Separately:  remove the value from the config and confirm the value still defaults to false.

**Comment by punktilious** [comment]
Started container as described in fhir-install/README.md.
Run
```
podman exec -ti fhir-server bash
vi config/default/fhir-server-config.json
```
Confirmed that
```
"serverRegistryResourceProviderEnabled": false,
```

Also, after enabling trace for FINE, we can see the search query executed when serverRegistryResourceProviderEnabled=true but not when it is set to false. Similarly, it is confirmed that the search query is not executed when the parameter is removed, thus confirming the default behavior is serverRegistryResourceProviderEnabled=false.
