### ISSUE TITLE
NPE at JaxRsFactoryImplicitBeanCDICustomizer.afterServiceInvoke

### ISSUE THREAD

**Issue by punktilious** [IBM/FHIR#3009]
**Describe the bug**
Some requests fail reporting NPE at JaxRsFactoryImplicitBeanCDICustomizer.afterServiceInvoke

**Environment**
4.10.0

**To Reproduce**
1. Run 4.10.0
2. Execute a high volume of concurrent bundle GET requests
3. See intermittent errors

**Expected behavior**
Requests should succeed.

**Additional context**
Bug in Open Liberty 21.0.0.9: https://github.com/OpenLiberty/open-liberty/issues/18663

Fixed in Open Liberty 21.0.0.11

**Comment by prb112** [comment]
JAXRS fix is in place.

**Comment by punktilious** [comment]
Ran a high volume interop workload test for 24 hours and confirmed the error is no longer seen.
