### ISSUE TITLE
download url is improperly constructed for ndjson exports where storageProvider is parquet-enabled

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#3053]
**Describe the bug**
The bulkdata property group in fhir-server-config has a storageProviders section and each one can have the following setting:
```
"enableParquet": true
```

When parquet is enabled, we allow requests to specify an `_outputFormat` parameter value of `application/fhir+parquet`.
However, we still default to an output format of ndjson.

Unfortunately, when we go to construct the download url for export jobs with parquet-enabled, we always assume the export is a parquet file.

**Environment**
main

**To Reproduce**
1. enable parquet export by packaging the libs / marking the dependencies as runtime (instead of `provided`)
2. configure an ibm-cos/aws-s3 storageProvider for parquet export:  `"enableParquet": true`
3. issue an export for this storageProvider (with no explicit _outputFormat value / defaults to ndjson)
4. once complete, hit the status endpoint

note that the download url uses `.parquet` even though the actual file that was written is .s3

**Expected behavior**
The download url should be right for ndjson exports even when the storageProvider is enabled for parquet 

**Additional context**

**Comment by prb112** [comment]
No longer applicable as we've removed Parquet.
