### ISSUE TITLE
`ibm-fhir-server` outputs JSON to the console except for a set of two lines.

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#3069]
**Describe the bug**
The `ibm-fhir-server` outputs JSON to the console except for a set of two lines.

```
bootstrap.sh - [INFO]: 2021-12-02_19:35:45 - Current directory: /opt/ibm-fhir-server
bootstrap.sh - [INFO]: 2021-12-02_19:35:45 - Skipping Derby database bootstrapping
```

**Environment**
Which version of IBM FHIR Server? main

**To Reproduce**
1. start the docker image 

**Expected behavior**
If not bootstrapping, maybe we can skip the message and let the formatting state consistent when not bootstrapping.

**Additional context**

**Comment by lmsurpre** [comment]
Default container output for the ibm-fhir-server is BASIC, not JSON>
So for this to be most helpful, I think we'd want to match whatever is configured for that.  Maybe just use the `TRACE_FORMAT` env var?  But there's a liberty message one as well.

Then there's also the fact the persistence schema tool doesn't log in json format.

We're thinking this one would be more trouble than it's worth.
