### ISSUE TITLE
Bulk Data 2.0.0 Export Response needs updates to PollingLocationResponse

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#3087]
**Is your feature request related to a problem? Please describe.**

http://hl7.org/fhir/uv/bulkdata/export.html#response---complete-status

Missing: 
```
deleted | optional | JSON array
```

This is split out from #1927 as it may be used by conformance tools to check that this array exists.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Acceptance Criteria**

1.  
   GIVEN [a precondition]
    AND [another precondition]
   WHEN [test step]
    AND [test step]
   THEN [verification step]
    AND [verification step]

**Additional context**

**Comment by prb112** [comment]
3087 should show a new empty array called deleted. This is so conformance tools (as they are updated pass). We don't actually populate the field. 

```
    Update polling response to match http://hl7.org/fhir/uv/bulkdata/export.html#response---complete-status
    Ensure conformance with anticipated deleted array.
```

**Comment by d0roppe** [comment]
verified the empty array is part of the $bulkdata-status of a completed $export.  Closing the issue
