### ISSUE TITLE
Combine fhir-task-api and fhir-task-core into fhir-database-utils

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#309]
We have an awful lot of projects and these are good candidates for consolidation.  `fhir-task-api` just defines the interfaces and `fhir-task-core` is extremely generic.  I get why we made these independent, but I can't imagine someone outside our team re-using these things at the moment.  We can always consider splitting them back out of fhir-database-utils in the future if we find the need.

**Comment by prb112** [comment]
Moved to closed, as it's passed e2e and review
