### ISSUE TITLE
Can't start the docker container when Docker Resource/Memory is less than 3.25 GB

### ISSUE THREAD

**Issue by bruneves** [IBM/FHIR#3111]
I am not exactly sure what the minimum memory requirement is for running the FHIR Server container image (tag 4.10.2), however by testing with diff configurations I was able to start the container as soon as the Docker Resource/Memory is set to 3.25 GB. Just bringing this to your attention in the case the server was supposed to run with less than that.

## Error Message

```
JVMJ9GC020E -Xms too large for heap
JVMJ9VM015W Initialization error for library j9gc29(2): Failed to initialize
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

Reference https://www.eclipse.org/openj9/docs/xxusecontainersupport/

**Comment by prb112** [comment]
@lmsurpre suggestion is to update docs or add a jvm.options file for minimal environments.

**Comment by prb112** [comment]
Raised a proposal for development specific examples/docs

**Comment by lmsurpre** [comment]
Thanks Paul.  Personally, I'd still like to use a smaller fixed initial heap (or remove it and go with the jvm-default if we can prove that resizing the heap has minimal impact).  However, I'm OK with the documentation-focused PR and have added my approval.

**Comment by lmsurpre** [comment]
ended up with a doc-only change...no further QA needed
