### ISSUE TITLE
Deprecate resource types removed in FHIR R4B

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#3114]
**Is your feature request related to a problem? Please describe.**
Per #2065 our current thinking is to move to R4B wholesale via a 5.x series (and stop maintaining the 4.x series).
Its *mostly* backwards compatible, but there are major changes to Medication Definition resources as described at https://build.fhir.org/branches/R4B/ballot-intro.html#meddef

This includes removal (or renaming) of all the following resource types:
```
MedicinalProduct
MedicinalProductAuthorization
MedicinalProductContraindication
MedicinalProductIndication
MedicinalProductInteraction
MedicinalProductUndesireableEffect
MedicinalProductIngredient
MedicinalProductManufactured
MedicinalProductPackaged
MedicinalProductPharmaceutical
SubstanceNucleicAcid
SubstancePolymer
SubstanceProtein
SubstanceReferenceInformation
SubstanceSourceMaterial
SubstanceSpecification
```

as well as breaking changes to the Substance resource.

**Describe the solution you'd like**
To help warn users about the future removal of these immature R4 resource types, we'd like to:
1. Mark the classes as deprecated in our next 4.x release; and
2. Clearly indicate our plan to remove these resource types in the release; and
3. Include a warning in the fhir-persistence-schema tool's output to indicate that the corresponding tables might go away at some point in the future (similar to what we did for the Resource and DomainResource tables); and

Optionally, we might also want to mark the corresponding values as deprecated in the corresponding code subtype classes:
* FHIRAllTypes
* FHIRDefinedType
* FHIRResourceType
* ResourceType

**Describe alternatives you've considered**

**Acceptance Criteria**

1.  
   GIVEN a 5.0.0-SNAPSHOT flavor of our schema tool
   WHEN you run `--update-schema`
   THEN the output warns you about the resource types that have been removed

**Additional context**

**Comment by d0roppe** [comment]
Verified that this does warn you about the use of the tables
example
```
2022-05-28 09:09:41.951 00000001 WARNING   com.ibm.fhir.schema.app.Main SubstanceSpecification tables [SubstanceSpecification_DATE_VALUES, SubstanceSpecification_LATLNG_VALUES, SubstanceSpecification_LOGICAL_RESOURCES, SubstanceSpecification_NUMBER_VALUES, SubstanceSpecification_QUANTITY_VALUES, SubstanceSpecification_RESOURCE_TOKEN_REFS, SubstanceSpecification_RESOURCES, SubstanceSpecification_STR_VALUES] will be dropped in a future release. No data should be written to these tables. If any data exists in these tables, that data should be exported (if desired) and deleted from these tables.
```
Closing issue
