### ISSUE TITLE
Error when canceling request to metadata endpoint 

### ISSUE THREAD

**Issue by daniel-eichinger-bl** [IBM/FHIR#3131]
**Describe the bug**
The IBM FHIR server throws an `FHIRGeneratorException` when a request to the metadata endpoint is cancelled.

**Environment**
4.10.2 (Linux Container, Windows Installation)

**To Reproduce**
1. Run the IBM FHIR server
2. Download [cancel.html](https://gist.github.com/Daniel091/bf130425436016b2d56ce37fd548a2bc)
3. Modify `urlToFetch` variable in cancel.html to point to your IBM FHIR Server
4. Open cancel.html in your browser
5. Press the "Fetch & Cancel" button 
6. See `FHIRGeneratorException` in IBM FHIR Server logs

> As this is somewhat of a timing issue you might need to try-out different values for the `setTimeout()` function that cancels the request

**Expected behavior**
No `FHIRGeneratorException` should be thrown by IBM FHIR server if a request to the metadata endpoint is cancelled. 

**Additional context**
I found this issue while launching a SMART on FHIR application with [fhirclient.js](https://github.com/smart-on-fhir/client-js).
The library sends requests to the smart-configuration and metadata endpoints.
Usually the smart-configuration request is faster, as a result the metadata endpoint request is cancelled.

For the full exception, please refer to: [ibm_fhir.log](https://github.com/IBM/FHIR/files/7743974/ibm_fhir.log)

**Comment by lmsurpre** [comment]
Please see https://github.com/IBM/FHIR/issues/2165 and in particular https://github.com/IBM/FHIR/issues/2165#issuecomment-810222741

We could set that by default if we want to, but I stopped short of that in the past because its sometimes useful to know if the clients are hanging up early.

**Comment by Daniel091** [comment]
Thank you for the quick response 👍🏼 
It's great to see there is already a configuration for this.

**Comment by lmsurpre** [comment]
discussed as a team and we're thinking to set this to false in our server.xml

   ```
    <!-- Specify whether the HTTP channel creates an I/O exception when an inbound connection is closed 
        while still in use by the servlet. -->
    <httpOptions id="defaultHttpOptions" ThrowIOEForInboundConnections="false"/>
    ```

if users need to know when the client has hung up before response was delivered, they can override it


idea for QA:  maybe configure a kubernetes healthcheck that will fail... our kubernetes http readiness probe is where we were seeing this one a lot prior to our change in #2165

idea 2 for QA:  take the large payload test and modify it to have the client hang up

if one works, probably no need to do the other

**Comment by punktilious** [comment]
Confirmed by interrupting a fhir-bucket ingestion run which loads several large bundles in parallel. When fhir-bucket is terminated early, this usually results in many IOException errors in the fhir-server log:

```
Caused by: jakarta.json.JsonException: I/O error while flushing generated JSON
        at org.eclipse.parsson.JsonGeneratorImpl.flush(JsonGeneratorImpl.java:114)
        at com.ibm.fhir.model.generator.FHIRJsonGenerator.generate(FHIRJsonGenerator.java:56)
        ... 60 more
Caused by: java.io.IOException: Broken pipe
        at java.base/sun.nio.ch.FileDispatcherImpl.write0(Native Method)
        at java.base/sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
        at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113)
        at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:58)
        at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:50)
```

When the httpOptions is configured per this issue, no such errors appear.
