### ISSUE TITLE
Implement reconciliation service to keep azure-blob container in sync with RDBMS

### ISSUE THREAD

**Issue by punktilious** [IBM/FHIR#3143]
**Is your feature request related to a problem? Please describe.**
With payload-offloading, the call to store the payload is made before the RDBMS transaction commits. If the transaction is rolled back, an attempt is made to delete any payloads which were stored as part of the transaction. However, it is possible that the delete call could fail (a network partition, maybe) in which case resource records will exist in the offload store, but not the RDBMS.

**Describe the solution you'd like**

We need a reconciliation process which runs in the background on a periodic basis. The process can scan the offload data store and check that the RDBMS contains a matching record. Records which exist in the offload data store but not the RDBMS can be removed.

**Describe alternatives you've considered**
None.

**Acceptance Criteria**

1.  
   GIVEN a resource exists in the offload data store
    AND the same resource does not exist in the RDBMS
   WHEN the reconciliation process has completed a pass over the data
   THEN the resource should no longer exist in the offload data store

**Additional context**
Discussion to be had on the best runtime option for this process. Options:
1. A thread running in the background when the IBM FHIR Server starts.
2. A custom operation which can be invoked by a simple job
3. A standalone Java program which can be packaged as a container application

My preference is 2, with a possible extension to fhir-bucket which would support it being called in a loop until all the work was done.

**Comment by punktilious** [comment]
Each payload persistence implementation will need to implement this feature separately. For the Cassandra payload persistence implementation, a prototype reconciliation implementation is provided in fhir-persistence-cassandra-app CLI.

**Comment by lmsurpre** [comment]
Lets make this one specific to the Azure blob implementation.  Will create separate ticket for the S3 / minio flavor of this.

**Comment by d0roppe** [comment]
The reconciliation  service seems to be working fine, closing issue
