### ISSUE TITLE
Build fails in 2022 due to test data violating current year constraint 

### ISSUE THREAD

**Issue by punktilious** [IBM/FHIR#3147]
**Describe the bug**
spl-X.1.1.2: The effective time year is equal to the current

**Environment**
Which version of IBM FHIR Server? main

**To Reproduce**
1. Build from main in 2022

**Expected behavior**
Successful build.

**Additional context**

The test resource Bundles in `conformance/fhir-ig-spl/src/test/resources/json/` contain a timestamp field with a 2021 value. This violates the above constraint. This can be avoided by updating the timestamp to `now` before the test validates the resource (in com.ibm.fhir.ig.us.spl.ExamplesValidationTest).

**Comment by lmsurpre** [comment]
tests are passing now
