### ISSUE TITLE
Dockerfile doesn't update yum on build

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#3159]
**Describe the bug**

Dockerfile doesn't update yum on build. In release 4.7.0, we removed the yum update. Need to understand the reasons and if this is intended. 

https://github.com/IBM/FHIR/commit/6b5e844b39abe0d17c0a0cd86d99a67989341d06#diff-bb21e41aa1608e829c45be2d17d3831a0e77f0c602fc8e0213753f2ee7298ded

```USER root
RUN yum update -y && \
    yum clean all && \
    rm -rf /var/cache/yum

USER 1001
```

**Environment**
Which version of IBM FHIR Server?

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by prb112** [comment]
PR #3302

**Comment by lmsurpre** [comment]
the dockerfile is updated
