### ISSUE TITLE
NullPointerException in LibraryHelper when no system is specified for type coding of Library resource

### ISSUE THREAD

**Issue by csandersdev** [IBM/FHIR#3161]
**Describe the bug**
In the [LibraryHelper](https://github.com/IBM/FHIR/blob/b8f2134e9631ff45ea1f2e99c75fff80e38aecc5/cql/fhir-cql/src/main/java/com/ibm/fhir/cql/helpers/LibraryHelper.java#L181), when we check to see whether a given Library resource is a logic-library based on the `type` attribute, we expect that the coding will have both a system and a code. If the system is null, then it will cause a NullPointerException.

**Environment**
4.10.2

**To Reproduce**
1. Create a Library resource with a type attribute as follows...
```json
      "type": {
        "coding": [ {
          "code": "logic-library"
        } ]
      }
```
2. Try to use that Library from inside a Library/$evaluate call

**Expected behavior**
I checked [reference implementation](https://github.com/hapifhir/hapi-fhir/blob/737409955a64aab41c372b34b84f0746670da693/hapi-fhir-jpaserver-cql/src/main/java/ca/uhn/fhir/cql/r4/helper/LibraryHelper.java#L190) and their check requires a system to be present to be considered pass this check. They are just smarter with null checking. We should add an isNotNull check to both the system and code attributes prior to checking their values.

**Additional context**
A valid example to pass this check is as follows...
```
 "type": {
    "coding": [ {
      "system": "http://terminology.hl7.org/CodeSystem/library-type",
      "code": "logic-library"
    } ]
  },
```

**Comment by kmbarton423** [comment]
Using EXM104-8.2.000 bundle, confirmed no longer receiving NPE for the situation where a depends-on library does not have the type properly coded with "system": "http://terminology.hl7.org/CodeSystem/library-type","code": "logic-library".

GET .../Library/library-EXM104-8.2.000/$evaluate?subject=Patient/Patient-Bones
Status 404
{
	"resourceType": "OperationOutcome",
	"id": "ac-11-0-3-9c0f56aa-98bf-466c-96c7-28eebcbd573c",
	"issue": [
		{
			"severity": "error",
			"code": "invalid",
			"details": {
				"text": "Library MATGlobalCommonFunctions not found."
			}
		}
	]
}
