### ISSUE TITLE
_history with _excludeTransactionTimeoutWindow=true can cause issue with "self" link

### ISSUE THREAD

**Issue by d0roppe** [IBM/FHIR#3174]
**Describe the bug**
with the _history?_excludeTransactionTimeoutWindow=true if you add a &_before=<timestamp>
in the self link in the results the &_before=<timestamp> has been removed.
**Environment**
main branch

**Expected behavior**
The "self" link should contain all the info passed in on the original _history lookup.

Related item:
in the "next" link it usually includes the _changeIdMarker=<id>  and this is kind of mentioned in the documentation.  I think in the Documentation it should state that the _changeIdMarker should not be used by the user, and is only used on the "next" link to eliminate duplicating entries on different pages.

**Comment by punktilious** [comment]
Looks like we were never including `_before` in the returned self link. This parameter should be included in the self link whenever it is specified in the request, regardless of other query parameter values.

**Comment by d0roppe** [comment]
Verified that both _before and _since with or without _excludeTransactionTimeoutWindow=true is included in the self link.  And the documentation states that the _changeIdMarker is for system use in the next link to remove duplicates from pages.
