### ISSUE TITLE
when querying _history with _since we are not using fhir search parsing rules for the timestamp

### ISSUE THREAD

**Issue by d0roppe** [IBM/FHIR#3175]
**Describe the bug**
when adding _since or _before to the _history query you have to have a timezone and you have to have a full timestamp with or without miliseconds to have the query currently work.  We should be able to follow fhir search parsing for the timestamp that defaults to the utz timezone and allows partial timestamps. 

**Environment**
fhir main.

**Expected behavior**
defaults to the utz timezone and allows partial timestamps.

**Comment by lmsurpre** [comment]
The spec isn't very clear on this, but in the table of parameters for _history, they document that the type of the `_since` parameter is an "instant" and they link instant to https://www.hl7.org/fhir/search.html#date

**Comment by d0roppe** [comment]
A documentation change was added to state the the _before and _since are treated as instant data types and linked to the definition of instant data type in the spec.  This clarifies what you need to provide in the timestamp to use _before and _since. Closing issue
