### ISSUE TITLE
$import allows adding Resources of multiple types in the same ndjson which could include unsupported resources.

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#3180]
**Describe the bug**
$import allows adding Resources of multiple types in the same ndjson which could include unsupported resources.

**Environment**
Which version of IBM FHIR Server? 4.10.2

**To Reproduce**
1. Create an NDJSON with a Condition resource
2. Create a fhir-server-config.json which doesn't have Condition
3. Condition should not be loaded but is.... 

**Expected behavior**

I expect a filtering of the unsupported resources.

**Additional context**

**Comment by d0roppe** [comment]
Verified that $import did not import the resource if it was not known.
