### ISSUE TITLE
Advertise system and type-level history in CapabilityStatement

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#3184]
**Is your feature request related to a problem? Please describe.**
In https://github.com/IBM/FHIR/issues/2972 we added support for type-level history.
However, we forgot to advertise this new capability in our CapabilityStatement

**Describe the solution you'd like**
Add `history-type` to the list of supported interactions for each resource type on the server:  https://www.hl7.org/fhir/capabilitystatement-definitions.html#CapabilityStatement.rest.resource.interaction.code

**Describe alternatives you've considered**

**Acceptance Criteria**

1.  
   GIVEN fhirServer/resources/Resource/interactions is present and doesn't list 'seach' or 'history' (i.e. whole-system search and history are disabled)
   WHEN /metadata is invoked
   THEN the response does *not* list `search-system` and `history-system` as supported interactions

1.  
   GIVEN whole-system search and history are enabled 
   WHEN /metadata is invoked
   THEN the response *does* list `search-system` and `history-system` as supported interactions

1.  
   GIVEN search and history are disabled for the Patient resource
   WHEN /metadata is invoked
   THEN the response does *not* list `search-type`, `history-type`, and `history-instance` as supported interactions for this resource type

1.  
   GIVEN search and history are enabled for the Patient resource
   WHEN /metadata is invoked
   THEN the response *does* list `search-type`, `history-type`, and `history-instance` as supported interactions for this resource type

I didn’t list every possible thing, but hopefully the intent is clear. It should be for all resource types, not just Patient.
And you can configure search and history independently

**Additional context**
While at it, we should also start setting https://www.hl7.org/fhir/capabilitystatement-definitions.html#CapabilityStatement.rest.resource.readHistory to true to indicate that we can "return past versions as part of the vRead operation".  I thought was kind of a given with vread, but apparently not.

**Comment by d0roppe** [comment]
Verified the acceptance criteria, new code is working as expected.
