### ISSUE TITLE
Capabilities Statement uses duplicate logic from FHIRConfigHelper

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#3186]
**Describe the Tech Debt**

1. Go to Capabilities Statement uses duplicate logic from FHIRConfigHelper. 
2. It's be great to have one common piece of logic

https://github.com/IBM/FHIR/blob/main/fhir-server/src/main/java/com/ibm/fhir/server/resources/Capabilities.java#L605-L630

#2963 contains the QA details

**Comment by d0roppe** [comment]
Tested many uses of Metadata and it is working so closing this issue.
