### ISSUE TITLE
AccessTokens should not be set with Presigned URLs

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#3188]
**Describe the bug**

AccessTokens should not be set with Presigned URLs

Per discussion with the spec authors, presigned URLs imply there is NO accessToken to use. 
Which we do not account for

**Environment**
Which version of IBM FHIR Server? main

**To Reproduce**
1. set `fhirServer/bulkdata/storageProviders/<source>/requiresAccessToken` to true for your export storageProvider
2. set `fhirServer/bulkdata/storageProviders/<source>/presigned` to true for the same storageProvider
3. perform an export and check the $bulkdata-status response

note that it has requiresAccessToken set to true, despite offering presigned urls

**Expected behavior**
presigned urls don't really make sense together with requireAccessToken=true
so maybe just ignore the requiresAccessToken value with presigned=true? 

**Additional context**
Our `requiresAccessToken` config property is really dumb...we basically just take whatever value you set for that and include it in the bulkdata-status response.

**Comment by d0roppe** [comment]
Verified that now if presigned=true, the requiresAccessToken will be set to false in the bulkdata-status output even if requiresAccessToken=true was set to true in the fhir-server-config.json file for the bulk data storage provider.  Closing issue.
