### ISSUE TITLE
add --help option for fhir-persistence-schema cli jar

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#3209]
**Is your feature request related to a problem? Please describe.**
from [#3072](https://github.com/ibm/fhir/issues/3072#issuecomment-1016537310)

**Describe the solution you'd like**
add an official `--help` flag that prints the menu without the 
```
Invalid argument: '--help'
java.lang.IllegalArgumentException: Invalid argument: '--help'
	at com.ibm.fhir.schema.app.Main.parseArgs(Main.java:2085)
	at com.ibm.fhir.schema.app.Main.main(Main.java:2703)
```
and 
```
2022-01-19 09:41:37.027 00000001  SEVERE   com.ibm.fhir.schema.app.Main SCHEMA CHANGE: BAD ARGS
```

**Describe alternatives you've considered**
`-h` or `--usage` or keep as-is

**Acceptance Criteria**

1.  
   GIVEN [a precondition]
    AND [another precondition]
   WHEN [test step]
    AND [test step]
   THEN [verification step]
    AND [verification step]

**Additional context**
`--help` is already listed as a valid flag in the usage info

**Comment by d0roppe** [comment]
Ran the latest command with the --help flag and no error and the usage menu was provided:
fhir-persistence-schema-4.11.0-SNAPSHOT-cli.jar --help
