### ISSUE TITLE
Bundle Change impacted the member-match behavior.

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#3212]
**Describe the bug**

Bundle Change impacted the member-match behavior.

**Environment**
Which version of IBM FHIR Server? main

**To Reproduce**

**Expected behavior**

**Additional context**
The original change that uncovered this one was for #3058

**Comment by kmbarton423** [comment]
Created multiple resourceTypes with the same resource.id (Patient, Coverage, etc).  
Confirmed $member-match works as expected when processing these resources.
