### ISSUE TITLE
Warning statement should be issued when an explicitly-configured search parameter doesn't exist

### ISSUE THREAD

**Issue by sfc42** [IBM/FHIR#3219]
**Describe the bug**
Warning statement should be issued when an explicitly-configured search parameter doesn't exist

**Environment**
4.11.0

**To Reproduce**
1. Add a search parameter to the server-config file that doesn't exist
2. The server starts, but doesn't warn the user the search parameter doesn't exist.

**Expected behavior**
A warning should end up in the log to tell the user the search parameter doesn't exist.

**Additional context**

**Comment by sfc42** [comment]
The pull request for this issue was merged:  https://github.com/IBM/FHIR/pull/3221

**Comment by kmbarton423** [comment]
Confirmed new warning message received on startup when a non-existent search parameter is specified in fhirServer/resources/<resourceType>/searchParameters:

ParametersUti W   Search parameter 'favorite-food' with the configured url 'http://ibm.com/fhir/SearchParameter/Patient-favorite-food' for resourceType 'Patient' could not be found.
