### ISSUE TITLE
MemberMatch improperly generates date formats which are spec invalid

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#3252]
**Describe the bug**

MemberMatch improperly generates date formats which are spec invalid. 
birthdate=[eq1970-2-2] instead of birthdate=[eq1970-02-02]

**Environment**
Which version of IBM FHIR Server? main 

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by kmbarton423** [comment]
Behavior confirmed by Michelle Schlicht
