### ISSUE TITLE
member-match definition has changed to now include a Consent resource and update Implementation Guide Da Vinci Health Record Exchange (HRex) 0.2.0 - STU R1 - 2nd ballot

### ISSUE THREAD

**Issue by sfc42** [IBM/FHIR#3253]
**Is your feature request related to a problem? Please describe.**
http://build.fhir.org/ig/HL7/davinci-ehrx/OperationDefinition-member-match.html has changed to now include a Consent resources in the input parameters

**Describe the solution you'd like**
The input parameters of member-match should be changed to include a Consent resource.

**Describe alternatives you've considered**

**Acceptance Criteria**

1.  
   GIVEN [a precondition]
    AND [another precondition]
   WHEN [test step]
    AND [test step]
   THEN [verification step]
    AND [verification step]

**Additional context**

**Comment by prb112** [comment]
Please update the IG first. 

Similar to Implementation Guide Da Vinci Health Record Exchange (HRex) 0.2.0 - STU R1 - 2nd ballot #1490 

This is probably 1 pt, and must be done first.
