### ISSUE TITLE
Remove any remaining support for requests to abstract endpoints like `[base]/Resource`

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#3265]
**Is your feature request related to a problem? Please describe.**
In https://github.com/IBM/FHIR/issues/2526 we added warnings for requests to "abstract" type endpoints like `[base]/Resource`.
Now I'd like to pull the trigger and remove that support altogether.

**Describe the solution you'd like**
have requests to `[base]/Resource` handled just like requests to `[base]/bogus`

**Describe alternatives you've considered**
keep supporting it in whatever way we do today

**Acceptance Criteria**

1.  
   GIVEN a 5.0 version of IBM FhIR Server
   WHEN a request is made to `[base]/bogus`
   THEN it results in a 404 not found

**Additional context**
one such place is FHIRResource.checkType(String):
```
if (!ModelSupport.isConcreteResourceType(type)) {
            log.warning("Use of abstract resource types like '" + type + "' in FHIR URLs is deprecated and will be removed in a future release");
}
```

**Comment by d0roppe** [comment]
Error 404 issued with the text the "unknow" text is not a valid resource  Closing issue.
The 404 is given for both 4.0 and 4.3 fhir versions
