### ISSUE TITLE
Avoid storing the resource contents in the case of a soft delete

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#3293]
**Is your feature request related to a problem? Please describe.**
In versioned FHIR servers (like ours), the DELETE action is a "soft delete"... its actually more like an update where we set the delete flag to Y.

Despite the resource content being logically deleted, for historical reasons we always write a new version of the entire resource payload in the db on this deleted version.

**Describe the solution you'd like**
Stop writing the resource payload on the deleted version of this record.

**Describe alternatives you've considered**

**Acceptance Criteria**

1.  
   GIVEN [a precondition]
    AND [another precondition]
   WHEN [test step]
    AND [test step]
   THEN [verification step]
    AND [verification step]

**Additional context**
In a previous iteration of the DB, I think we always needed non-null data for the x_Resources tables.
We may have a few places that still assume you can read it back out (maybe audit?), but we think we can manage those.

**Comment by lmsurpre** [comment]
I confirmed that the rows in the x_resources table that correspond to deleted versions now have a null data column:
![image](https://user-images.githubusercontent.com/5478798/156180748-f146f51c-5c3b-457f-ad85-75c577d53aab.png)

**Comment by lmsurpre** [comment]
I deployed this one to our cluster on IBM Cloud and ran the touchstone conformance tests against it.  100% successful.

**Comment by kmbarton423** [comment]
confirmed conditional delete is working as expected
did write up an enhancement issue #3419

**Comment by kmbarton423** [comment]
confirmed if-none-match and if-none-match within a bundle functionality

**Comment by kmbarton423** [comment]
confirmed $erase functionality
found issue 3439 during testing but it appears to be unrelated to these changes for soft delete

**Comment by lmsurpre** [comment]
issue #3439 has been addressed and this feature seems to be working
