### ISSUE TITLE
Unify handling of `_type` parameter across system-search, system-history, $everything and $export

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#3319]
**Is your feature request related to a problem? Please describe.**
Currently, our system-history implementations accepts multiple instances of the `_type` parameter and combine them into a single list.

Conversely, our system-search implementation takes just the first one.

In a recent version of the bulkdata spec, they relaxed the cardinality and so multiple instances of this parameter should be supported there as well.  We have a separate issue, https://github.com/IBM/FHIR/issues/3081, for that one.

**Describe the solution you'd like**
across these 4 endpoints, we should have common behavior for this parameter

**Describe alternatives you've considered**

**Acceptance Criteria**

1.  
   WHEN a search like `GET [base]?_type=Patient&_type=Condition`
   THEN the values of the _type parameters are combined
    AND the result matches `GET [base]?_type=Patient,Condition`

And verify this same behavior when:
1. system-history is invoked with multiple _type query params
2. $everything is invoked with multiple _type query params
3. $export is invoked via GET with multiple _type query params
4. $export is invoked via POST with multiple _type params in the Parameters body

And finally, verify that when $export is invoked via POST, none of the query parameters are used (only the Parameters from the body).

**Additional context**
We should probably document the behavior in Conformance.md as well, since this differs from how we handle other "return parameters" (#3318 )

**Comment by lmsurpre** [comment]
The $export operation has some special handling for the _types parameter where it checks in both the request url AND the Parameters object.  I'd like to try normalizing the two so that downstream code can look in a single spot for request parameters.  I think we already do something like that for extended operations that are invoked via GET.

**Comment by lmsurpre** [comment]
Based on the last comment, I added this line to the acceptance criteria:
> And finally, verify that when $export is invoked via POST, none of the query parameters are used (only the Parameters from the body).

**Comment by d0roppe** [comment]
Verified that specifying _type=<resourceType1>,<resourceType2> or _type=<resourceType1>&_type=<resourceType2> are handled the same for Search, History, $everything, and Bulk Data Export as requested in the Acceptance Criteria.
