### ISSUE TITLE
add warning info to $healthcheck OperationOutcome when deployment update required

### ISSUE THREAD

**Issue by kmbarton423** [IBM/FHIR#3336]
When the database schema is more up-to-date than the code, you receive the following log messages upon executing $healthcheck:

`[2/11/22, 17:57:14:821 UTC] 00000047 FHIRRestServl I   Received request: tenantId:[default] dsId:[default] user:[fhiruser] method:[GET] uri:[https://localhost:9443/fhir-server/api/v4/$healthcheck]
[2/11/22, 17:57:15:065 UTC] 00000047 FHIRPersisten W   Deployment update required: database schema version [25] is newer than code schema version [24]
[2/11/22, 17:57:15:083 UTC] 00000047 FHIRRestServl I   Completed request[0.262488459 secs]: tenantId:[default] dsId:[default] user:[fhiruser] method:[GET] uri:[https://localhost:9443/fhir-server/api/v4/$healthcheck] status:[200]`

The $healthcheck is still successful by design:

```json
{
	"resourceType": "OperationOutcome",
	"issue": [
		{
			"severity": "information",
			"code": "informational",
			"details": {
				"text": "All OK"
			}
		}
	]
}
```

This is an enhancement request to include the warning information for the above situation in the OperationOutcome of the $healthcheck as well as the log.

**QA guidance**

Verify HTTP 200 is still returned, but when "Prefer" HTTP Header is set to "return=OperationOutcome", the OperationOutcome contains a warning.
```json
{
	"resourceType": "OperationOutcome",
	"issue": [
		{
			"severity": "warning",
			"code": "informational",
			"details": {
				"text": "Deployment update required: database schema version [26] is newer than code schema version [25]"
			}
		}
	]
}
```

**Comment by lmsurpre** [comment]
might make sense to do this one together with #3031

**Comment by tbieste** [comment]
Since #3131 is currently in another PR, I went ahead and worked on this issue.

**Comment by tbieste** [comment]
Verified that when the schema version is higher than the code version, HTTP 200 is returned by $healthcheck with the following output:

```
{
	"resourceType": "OperationOutcome",
	"issue": [
		{
			"severity": "warning",
			"code": "informational",
			"details": {
				"text": "Deployment update required: database schema version [26] is newer than code schema version [25]"
			}
		}
	]
}
```
