### ISSUE TITLE
Whole system interactions should honor resources config when open=false

### ISSUE THREAD

**Issue by d0roppe** [IBM/FHIR#3390]
**Describe the bug**
with fhirServer/resource configurations in fhir-server-config.json with resources listed, and open=false.  Whole system search should only work on the resources listed

server log contains exception

**Environment**
FHIR main

**Comment by lmsurpre** [comment]
this work was already implemented in our `r4b-rebased` branch as part of #3242 ...what we need to do is backport that to our main branch

**Comment by d0roppe** [comment]
Now with `"open": = false` for the resources configuration, a whole system search now gets appended with `_type=` for the resource types noted in the configuratiopn.  So now the whole system search works as expected with the `"open": = false`
