### ISSUE TITLE
componentIp in AuditLogEntry null if fhirServer/audit/ip is not configured.

### ISSUE THREAD

**Issue by jornvanwier** [IBM/FHIR#3391]
**Describe the bug**
[com.ibm.fhir.server.util.RestAuditLogger.initLogEntry](https://github.com/IBM/FHIR/blob/main/fhir-server/src/main/java/com/ibm/fhir/server/util/RestAuditLogger.java#L832) is supposed to either get the IP from the configuration or determine it automatically. However, currently the condition is the opposite of what it should be, causing the ip be set to null if the overrideIp (from the configuration) is null, instead of falling back to automatically determining the ip. Additionally, if an ip is configured, it will use the automatically determined ip.

**Environment**
`main` and 4.10.2

**To Reproduce**
1. Set `fhirServer/audit/serviceProperties/mapper` to `auditevent` and do not set `fhirServer/audit/ip`.
2. Do something that creates an audit log (e.g., searching for an observation)
3. A NPE will be thrown because componentIp is null.

**Expected behavior**
The configured ip should be used if it is set, and `componentIpHandler.getIpAddresses` should be used if is not.

**Comment by d0roppe** [comment]
Verified no NPE with the specified configuration,  Audit record added. Closing issue
