### ISSUE TITLE
Prevent tenant payload configuration from falling back to default

### ISSUE THREAD

**Issue by punktilious** [IBM/FHIR#3416]
**Describe the bug**
For datasource configurations, we prevent tenant requests for the datasource config from falling back to using the default configuration if no tenant-specific configuration if provided. The same should be done for payload offload configuration elements.

**Environment**
Which version of IBM FHIR Server? main (pre-5.0.0)

**QA**
1. Configure payload offload for the default tenant.
2. Do not configure payload offload for a second tenant e.g. tenant1
3. FHIR interactions for the default tenant should use payload offload
4. FHIR interactions for tenant1 should not use payload offload - the content should be stored in the database. This can be verified by inspecting the trace.log with tracing enabled (there should be no mention of payload offload operations), or it can also be verified by inspecting the database and checking that the data column is populated with the resource payload value: for example `select data from tenant1_data.patient_resources`. If offloading is being used, the data column should be null.

**Comment by tbieste** [comment]
@punktilious I'd like to try to work on this one. I'm a bit unclear where in the code this type of checking can be added.  Can you point me in the right direction?

**Comment by punktilious** [comment]
Oh I just did it. In FHIRConfigHelper, I just did
```
                if (propertyName.startsWith(FHIRConfiguration.PROPERTY_DATASOURCES)
                        || propertyName.startsWith(FHIRConfiguration.PROPERTY_PERSISTENCE_PAYLOAD)) {

```
adding the second line.

**Comment by d0roppe** [comment]
Verified that this is working as described in the QA section above.
