### ISSUE TITLE
PostgreSQL create schema does not grant required permissions on schema itself

### ISSUE THREAD

**Issue by punktilious** [IBM/FHIR#3417]
**Describe the bug**
The schema tool CLI create schema option does not grant the necessary permissions on the schema object.

For example, when attempting to query the RESOURCE_TYPES table:
```
INFO: Opening connection to database: jdbc:postgresql://localhost:5432/fhirdb?currentSchema=cdpdev
Mar 02, 2022 10:02:08 AM com.ibm.fhir.persistence.blob.app.Main main
SEVERE: failed
com.ibm.fhir.database.utils.api.UndefinedNameException: org.postgresql.util.PSQLException: ERROR: relation "resource_types" does not exist
  Position: 47
	at com.ibm.fhir.database.utils.postgres.PostgresTranslator.translate(PostgresTranslator.java:101)
```

To work around this issue, execute the following grant:
```
GRANT USAGE on schema schema-name to fhirserver;
```

Where:
* schema-name is the name of the FHIR data schema
* fhirserver is the database user you have created for the FHIR server to connect with

**Environment**
Which version of IBM FHIR Server? main (4.11.0-prerelease)

**To Reproduce**
1. Use the schema tool CLI to create a new schema on a PostgreSQL database
2. Configure the FHIR server to connect using a non-admin user (e.g. `fhirserver`)
3. Attempt to read or create a resource

**Expected behavior**
For PostgreSQL, the CLI tool should apply the usage grant to the schema when applying grants to the other objects.

**Additional context**
N/A

**Comment by d0roppe** [comment]
This is now working, and also works with bulk data.   Closing issue
