### ISSUE TITLE
_history after $erase version returns FHIRPersistenceException: convertResourceDTO returned no resource 

### ISSUE THREAD

**Issue by kmbarton423** [IBM/FHIR#3439]
Executed an $erase of a specific version of a resource.  Received 500 Internal Server Error when attempted to review the resource history after the erase.

GET  .../Patient/[ID]/_history
{
	"resourceType": "OperationOutcome",
	"id": "ac-11-0-3-57354466-583e-4407-86e9-2679c80d6c31",
	"issue": [
		{
			"severity": "fatal",
			"code": "exception",
			"details": {
				"text": "FHIRPersistenceException: convertResourceDTO returned no resource for 'Patient/P0008'"
			}
		}
	]
}

Working with the latest level of main.  

1. Store three versions of a resource ... Patient/[ID]
2. Erase version 2 of Patient/[ID]
3. Attempt to review resource history ... Patient/[ID]/_history

**Comment by kmbarton423** [comment]
attachment contains stack trace

[historyError.txt](https://github.com/IBM/FHIR/files/8200803/historyError.txt)

**Comment by punktilious** [comment]
After erasing a specific version of a Patient using:

```
curl -k -i \
-H 'Content-Type: application/json' \
-H 'X-FHIR-TENANT-ID: a-tenant-name' \
-X POST \
-u 'some-credentials' '.../fhir-server/api/v4/Patient/patient1/$erase' -d '
{
  "resourceType": "Parameters",
  "parameter": [
    {
      "name": "patient",
      "valueString": "patient1"
    },
    {
      "name": "reason",
      "valueString": "My Reason for removing this resource"
    },
    {
      "name": "version",
      "valueInteger": 2
    }
  ]
}'

```

we get 
```
fhirdb=> select resource_id, version_id, is_deleted, length(data) from fhirdata.patient_resources where logical_resource_id = 6607002;
 resource_id | version_id | is_deleted | length 
-------------+------------+------------+--------
     6607001 |          1 | N          |    170
     6610001 |          2 | N          |       
     6611001 |          3 | Y          |       
     6614001 |          4 | N          |    170
     6617001 |          5 | N          |    170
```

showing that the data column is nulled out for version 2 (note that we have also done a soft-delete of version 3 in this case.
