### ISSUE TITLE
FHIR Resource extension support

### ISSUE THREAD

**Issue by proxsys** [IBM/FHIR#3472]
I'm trying to find how this server supports FHIR extensions.

I'm unable to find it in the documentation.

**Comment by lmsurpre** [comment]
The model supports extensions in the same way it supports every other element type:
https://github.com/IBM/FHIR/blob/main/fhir-model/src/test/java/com/ibm/fhir/model/test/ModelBuilderTest.java#L38-L41

The validator validates extensions by looking up the corresponding StructureDefinition in the internal registry.
If an extension is used which has no corresponding StructureDefinition, we issue a warning to indicate this fact.

More info on the model:  https://ibm.github.io/FHIR/guides/FHIRModelGuide
More info on the validator:  https://ibm.github.io/FHIR/guides/FHIRValidationGuide#profile-support

Hope that helps.
