### ISSUE TITLE
build pipeline fails ocassionally in server integration test

### ISSUE THREAD

**Issue by albertwang-ibm** [IBM/FHIR#350]
We found that timeout happens from time to time when processing complete-mock - ExplanationOfBenefit-1.json.

The [CI Workflow](https://github.com/IBM/FHIR/pull/332/checks?check_run_id=285174293) generated the following error on one of the `complete-mock` resources - `OK         ibm/complete-mock/ExplanationOfBenefit-1.json`.

```
 [ERROR] processExamples(com.ibm.fhir.server.test.R4ExampleServerTest)  Time elapsed: 130.08 s  <<< FAILURE!
javax.ws.rs.client.ResponseProcessingException: Problem with reading the data, class com.ibm.fhir.model.resource.ExplanationOfBenefit, ContentType: application/fhir+json.
```

The resource generates the following parameters:

```
Starting Test -> testExtractAll
0|care-team|=[eVOYEME6M8]
1|claim|=[ldKETF2ZcD]
2|coverage|=[QCuLLknY32]
Value DateTime: [2019-08-03T00:12:34.062-04:00]
3|created|=[2019-08-03T00:12:34.062-04:00]
4|detail-udi|=[WhMqzPWY0J]
5|disposition|=[CzARoc8inI]
6|encounter|=[FsfGHHCM4v]
7|enterer|=[FJTi3mIU49]
8|facility|=[819y6m8cV7]
9|identifier|=[null]
10|item-udi|=[XU7oL5ld4n]
11|patient|=[Jad8F8OL2Z]
12|payee|=[gnk1pVCcYx]
13|procedure-udi|=[ZA8nSONiyf]
14|provider|=[NvE9EamfCR]
15|status|=[cancelled]
16|subdetail-udi|=[JSHDCyCWuh]
17|_id|=[YSbxPVnN2s]
Value DateTime: [2019-08-03T00:12:34.152-04:00]
18|_lastUpdated|=[2019-08-03T00:12:34.152-04:00]
19|_profile|=[pjq89TOc13]
20|_security|=['true']
21|_source|=[aTBkgna3DR]
22|_tag|=['true',ibm/complete-mock]
End of Test -> testExtractAll
PASSED: testExtractAll
```

We've hit this issue with both openjdk11 and openjdk8, although it seems more common with openjdk11.

**Comment by prb112** [comment]
I did some rough math and lots of tests 1000 loops of the minimal spec test.  It resulted in 25 to 25 seconds to complete each loop. 

A few causes could be: 
- Row to Table Locking Switch (We could tune this) http://db.apache.org/derby/docs/10.12/tuning/ctunoptimz26019.html
- derby.stream.error.logSeverityLevel also the lock log severity 
http://db.apache.org/derby/docs/10.12/adminguide/cadminlockvti83889.html
> To see a thread's stack trace when a lock is requested, set derby.locks.deadlockTrace to true. This property is ignored if derby.locks.monitor is set to false.

**Comment by prb112** [comment]
Linked Failure on OpenJDK8 - https://github.com/IBM/FHIR/pull/357/checks?check_run_id=288198433

**Comment by albertwang-ibm** [comment]
I run into this issue locally with jdk8 and the same sample json. and there is not time out in server side at all, the processings of the sample json file are always within only 1 second. the timeout happens in the client side. and this should be a unsolved issue of apache cxf async http client just as mentioned there http://mail-archives.apache.org/mod_mbox/hc-dev/201909.mbox/%3CJIRA.13256372.1568301069000.62179.1568450580088@Atlassian.JIRA%3E

**Comment by prb112** [comment]
Per Albert's fix, I've marked this as closed
