### ISSUE TITLE
"Undelete" action is logged as an update in the changes table but a create in audit

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#3507]
**Describe the bug**
We're somewhat inconsistent in the way we handle the "undelete" case (an update after a delete).

Our server returns a 201 (Created) status and we now log this as a create in the audit log (as of https://github.com/IBM/FHIR/issues/2471).

This matches what the spec says (from https://www.hl7.org/fhir/http.html#delete)
> If the interaction is successful, the server SHALL return either a 200 OK HTTP status code if the resource was updated, or a 201 Created status code if the resource was created (or brought back to life/re-created)

Prior to https://github.com/IBM/FHIR/issues/3293 we were calling the `beforeUpdate` and `afterUpdate` methods for this case.
Therefor, the notification events we emitted also called this an `update`.
But now that the "prevResource" is null for this "undelete" case, we now call `beforeCreate` and `afterCreate` and therefor this interaction will lead to a `create` action code in the notification event going forward.
Furthermore, we also call FHIRPersistence.create (rather than FHIRPersistence.update).

However, when we insert into the RESOURCE_CHANGE_LOG table, we're still setting the changeType to U (and not C).
This leads to the _history api using the status code `200` for these requests, even though the actual status code was a 201.

**Environment**
main

**To Reproduce**
1. create a resource
2. delete it
3. update it (bringing it "back to life")
4. invoke system or type-level history

Note that the entry for step 3 indicates that the result was 200 OK even though the actual interaction resulted in a 201 Created

**Expected behavior**
The history api returns a status code that accurately reflects the actual status code for the "undelete" interaction.

**Additional context**
Originally identified at https://github.com/IBM/FHIR/issues/2988#issuecomment-1020241412

**Comment by lmsurpre** [comment]
I think it will require an update to the stored procedures (and to DerbyResourceDAO)

**Comment by lmsurpre** [comment]
For system and type-level history interactions, we can easily start writing those to the CHANGE_LOG table as creates ('C') rather than updates ('U').

However, for instance-level history its not so simple.  To do it properly (where the Bundle.entry.response element always reflects the proper HTTP method and response status of that specific interaction) I think we'd need to reimplement this instance-level history on top of the CHANGE_LOG table. For now, I'm thinking to just fix the system and type-level interactions... maybe we can open a separate issue for the instance-level history?

**Comment by d0roppe** [comment]
From testing this with the latest code, I am still seeing code 200 on a recreate for the _history

**Comment by lmsurpre** [comment]
> From testing this with the latest code, I am still seeing code 200 on a recreate for the _history

That is mentioned as a limitation of the current approach for instance-level history just above. 
 I've now opened https://github.com/IBM/FHIR/issues/3554 to track that.

**Comment by d0roppe** [comment]
With verifying this for whole system history and type history this is working as expected.
