### ISSUE TITLE
Use the published Da Vinci Health Record Exchange (HRex) (STU1)

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#3526]
**Is your feature request related to a problem? Please describe.**
In issue #3407 we used a snapshot version of HRex.  Now HRex 1.0 is published and we should use that:  http://hl7.org/fhir/us/davinci-hrex/STU1/

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Acceptance Criteria**

1.  
   GIVEN [a precondition]
    AND [another precondition]
   WHEN [test step]
    AND [test step]
   THEN [verification step]
    AND [verification step]

**Additional context**
we're expecting minimal changes

**Comment by lmsurpre** [comment]
there is no capability statement for this IG but I confirmed that, after adding the built jar to my userlib, /metadata shows all of the following profiles as supported:
```
                        "http://hl7.org/fhir/us/davinci-hrex/StructureDefinition/hrex-practitioner|1.0.0",
                        "http://hl7.org/fhir/us/davinci-hrex/StructureDefinition/hrex-organization|1.0.0",
                        "http://hl7.org/fhir/us/davinci-hrex/StructureDefinition/hrex-coverage|1.0.0"
                        "http://hl7.org/fhir/us/davinci-hrex/StructureDefinition/hrex-task-data-request|1.0.0"
                        "http://hl7.org/fhir/us/davinci-hrex/StructureDefinition/hrex-consent|1.0.0"
                        "http://hl7.org/fhir/us/davinci-hrex/StructureDefinition/hrex-claimresponse|1.0.0"
                        "http://hl7.org/fhir/us/davinci-hrex/StructureDefinition/hrex-parameters-member-match-out|1.0.0",
                        "http://hl7.org/fhir/us/davinci-hrex/StructureDefinition/hrex-parameters-member-match-in|1.0.0"
                        "http://hl7.org/fhir/us/davinci-hrex/StructureDefinition/hrex-patient-demographics|1.0.0",
                        "http://hl7.org/fhir/us/davinci-hrex/StructureDefinition/hrex-practitionerrole|1.0.0",
```

**Comment by d0roppe** [comment]
davinci-hrex now sowas version 1.0.0 in /metadata
