### ISSUE TITLE
liberty openapi ui is missing style / unusable

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#3587]
**Describe the bug**
the openapi ui loads without its stylesheet and cannot be used

**Environment**
4.11.0

**To Reproduce**
1. start a server and navigate to https://localhost:9443/openapi/ui

**Expected behavior**

**Additional context**
this is a known issue with liberty 22.0.0.3

**Comment by d0roppe** [comment]
Verified that with the new install the `https://localhost:9443/openapi/ui/` looks correct
