### ISSUE TITLE
Perform schema migration test workflows more selectively

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#3607]
**Is your feature request related to a problem? Please describe.**
The longest-running actions in our CI are the schema migration ones.

Even before we added those, I was thinking that we'd want to selectively run them.
What went in for issue #2245 was a comparison from the previous *minor* release and the previous *patch* release to whatever is at HEAD.

However, that doesn't seem to be working as expected because even just after our 4.11.1 release, the scripts seem to be comparing us against version 4.8.3 for some reason.  From the https://github.com/IBM/FHIR/runs/6200970041 "Determine parameters" step:
```
Run bash fhir/build/migration/bin/0_determine.sh previous
Changes to 'fhir-persistence-schema' between tags
HEAD..4.11.1|0
4.11.1..4.11.0|0
4.11.0..4.10.2|38
4.10.2..4.10.1|0
4.10.1..4.10.0|0
4.10.0..4.9.2|30
4.9.2..4.9.1|5
4.9.1..4.9.0|3
4.9.0..4.8.3|16
4.8.3..4.8.2|13
4.8.2..4.8.1|2
4.8.1..4.8.0|0
4.8.0..4.[7](https://github.com/IBM/FHIR/runs/6200970041?check_suite_focus=true#step:6:7).1|10
4.7.1..4.7.0|0
4.7.0..4.6.1|0
4.6.1..4.6.0|7
4.6.0..4.5.5|16
4.5.5..4.5.4|5
...
Changes to 'fhir-database-utils' and 'fhir-persistence-schema' between tags
HEAD..4.11.1|296|0
4.11.1..4.11.0|0|0
4.11.0..4.10.2|45|3[8](https://github.com/IBM/FHIR/runs/6200970041?check_suite_focus=true#step:6:8)
4.10.2..4.10.1|0|0
4.10.1..4.10.0|0|0
4.10.0..4.[9](https://github.com/IBM/FHIR/runs/6200970041?check_suite_focus=true#step:6:9).2|43|30
4.9.2..4.9.1|1|5
4.9.1..4.9.0|3|3
4.9.0..4.8.3|21|16
4.8.3..4.8.2|1|13
4.8.2..4.8.1|1|2
4.8.1..4.8.0|0|0
4.8.0..4.7.1|120|10
4.7.1..4.7.0|0|0
4.7.0..4.6.1|1|0
4.6.1..4.6.0|2|7
4.6.0..4.5.5|11|16
4.5.5..4.5.4|12|5
...
Changes to 'build/migration' between tags
HEAD..4.11.1|33
4.11.1..4.11.0|0
4.11.0..4.[10](https://github.com/IBM/FHIR/runs/6200970041?check_suite_focus=true#step:6:10).2|8
4.10.2..4.10.1|0
4.10.1..4.10.0|0
4.10.0..4.9.2|7
4.9.2..4.9.1|0
4.9.1..4.9.0|33
4.9.0..4.8.3|0
4.8.3..4.8.2|0
4.8.2..4.8.1|0
4.8.1..4.8.0|0
4.8.0..4.7.1|0
4.7.1..4.7.0|0
4.7.0..4.6.1|0
4.6.1..4.6.0|0
4.6.0..4.5.5|0
...
# fhir-persistence-schema = 0

# fhir-database-utils = 0

# build/migration = 0

env.migration_skip=true
env.migration_branch=4.8.3
```

**Describe the solution you'd like**
Instead of fixing the bug so that we compare against the right versions, lets adopt the pattern from our build workflow and only run the migration tests when the PR contains a change in one of the following paths:
* build/migration
* fhir-database-utils
* fhir-persistence-schema

**Describe alternatives you've considered**
Figure out why its comparing us against version 4.8.3 instead of the expected version: 4.10.2

**Acceptance Criteria**

1.  
   GIVEN a PR that modifies files under build/migration, fhir-database-utils, or fhir-persistence-schema
   THEN migration tests run to ensure we can cleanly migrate from a specified list of prior release versions

1.  
   GIVEN a PR that does *not* modify files under build/migration, fhir-database-utils, or fhir-persistence-schema
   THEN the migration tests are skipped

**Additional context**
See https://github.com/IBM/FHIR/issues/2245#issuecomment-912770504 for background.

**Comment by d0roppe** [comment]
Re-Opening this issue as the Migration tests fail when executed by themselves.

**Comment by d0roppe** [comment]
verified this only fires when the PR warrents, and allows a dedicated run be requested, and that also works.  Closing issue.
