### ISSUE TITLE
Make skippable updates the default

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#3614]
**Is your feature request related to a problem? Please describe.**
In #2263 we added opt-in support for skipping updates when the the resource content matches the existing resource content.
This seems to be working well, but most clients don't know to opt in for this.

**Describe the solution you'd like**
There seems to already be broad support for this idea in the community (e.g. https://chat.fhir.org/#narrow/stream/179166-implementers/topic/Handling.20of.20Updates/near/270802907 ) and so I think we could remove the client opt-in and just make this the normal behavior for 5.0.

I'm thinking that we retire the custom `X-FHIR-UPDATE-IF-MODIFIED` header (the name was confusing anyway) and always skip the update in this case, but I'd also be fine with renaming the header to something like `X-FHIR-FORCE-UPDATE` (with a default of false).

**Describe alternatives you've considered**
Make it configurable via a server config property instead.

**Acceptance Criteria**

1.  
   GIVEN a patch or update
    AND the updated resource matches the existing one (sans Resource.id, meta.versionId, and meta.lastUpdated)
   WHEN HTTP header `X-FHIR-FORCE-UPDATE` is absent or set to "false"
   THEN the update is skipped

1.  
   GIVEN a patch or update
    AND the updated resource matches the existing one (sans Resource.id, meta.versionId, and meta.lastUpdated)
   WHEN HTTP header `X-FHIR-FORCE-UPDATE` is set to "true"
   THEN the update is performed

**Additional context**

**Comment by d0roppe** [comment]
Verified this is now the new default, closing issue.
