### ISSUE TITLE
Name of the file that contains the reference to the persistence interceptor class.

### ISSUE THREAD

**Issue by fernanda62** [IBM/FHIR#3629]
Hello,
I am working on version 4.10.2 of the IBM FHIR server.
I have impemented an interceptor class by specifying the class name in the 
‘META-INF/services/com.ibm.fhir.persistence.interceptor.FHIRPersistenceInterceptor’ file as described in the user guide.
It does not work. In the trace file I found: No persistence interceptors found...

Now I have changed the file name in ‘com.ibm.fhir.server.spi.interceptor.FHIRPersistenceInterceptor’.
In this case everything seems work fine and in the trace file I found: 
Discovered the following persistence interceptors: >>> interceptor.csainterceptor@2af917e8

It’s right?

thank you

**Comment by d0roppe** [comment]
Verified the users guide is updated with the correction. closing issue.
