### ISSUE TITLE
Schema Migration issues related to Replication-API

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#364]
Schema Migration issues related to Replication-API removal. 

The Schema has fixed values. 
>      "TX_CORRELATION_ID" VARCHAR(36) NOT NULL,
>        "CHANGED_BY" VARCHAR(64) NOT NULL,
>        "CORRELATION_TOKEN" VARCHAR(36) NOT NULL,
>        "REASON" VARCHAR(255) NOT NULL,
>        "SERVICE_ID" VARCHAR(32) NOT NULL,

The NOT NULL constraints, while not used, are required to be set in PR #363 
we added the columns back in and passed an empty string into these fields. 

 **Files**  
- fhir-persistence-schema/src/main/resources/add_any_resource.sql
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/FhirResourceGroup.java

As such, the schema migration must be investigated and addressed. 
- increment version in the constants
- account for 'deprecating' columns
- run idempotently across versions

Currently, BaseObject.applyVersion is where it actually checks the old version in the VERSION_HISTORY table vs version in the PhysicalDataModel object

Related to PR https://github.com/IBM/FHIR/pull/363/files

**Comment by prb112** [comment]
**Proposal** 
- Make a Breaking Change with the Schema
- Remove the Constraints above and the PreparedStatement
- Wipe the Schema, Restart Fresh

Team feedback is to proceed with the proposal.

**Comment by lmsurpre** [comment]
+1 from me
