### ISSUE TITLE
Fix or disable erroring tests and enable FHIRPathSpecTest in the build

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#385]
In  #374 I introduced a new TestNG test class for invoking the spec-provided FHIRPath tests.

I added skips for the easy stuff (e.g. when we throw UnsupportedOperationException), but we still have about 166 test cases failing.

FHIR does not use all of FHIRPath and so getting to 100% passing is a non-goal for our 4.0.0 release.
However, there are definitely some things in here that need to get cleaned up.

[test-output.zip](https://github.com/IBM/FHIR/files/3825632/test-output.zip)

**Comment by lmsurpre** [comment]
Are #387 or #388 started yet?
I checked out master and I see that our results are looking pretty good:
`Tests run: 679, Failures: 0, Skips: 206`

However, there are a few test cases commented out in `tests-fhir-r4.xml`.
I assume `tests-fhir-r4-old.xml` was the original test file and we've updated it based on what we support.
I recommend removing `tests-fhir-r4-old.xml` altogether (git has the history) and adding comments to the commented out test cases to indicate why they are commented out.
For example, I see a few with comments like `<!-- testWrong(patient(), "Encounter.name.given"); -->`...does that mean if it doesn't have this comment then the test is likely valid?

What does it mean when we remove the "expected output" (output element) from the test xml?  Does that just cause us to skip the test?

**Comment by JohnTimm** [comment]
I didn't add `tests-fhir-r4-old.xml`. I don't know where that file came from but I'm happy to remove it.

**Comment by JohnTimm** [comment]
I don't know the meaning of Grahame's comments.

**Comment by senthilbak** [comment]
The skipped tests(skip=199, total=678) at this time are due to unsupported functionality that will come post R1.
