### ISSUE TITLE
broken CONTRIBUTING link on project home page

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#390]
The `CONTRIBUTING` link from the project home page at https://ibm.github.io/FHIR/ is broken.

Furthermore, CONTRIBUTING.md exists at both the project root and at `docs/src/pages`
The one at the root of the project is focused on just the contribution process, whereas the version under docs seems to be an amalgamation of the cary-gatsby-them contribution process, our base CONTRIBUTING content, and the project setup from the wiki.

IMHO, the one at the root of the project should be the source of truth wrt the contribution process and I don't think we need to copy "how to contribute" type information to the website.

**Comment by prb112** [comment]
Paul reviewed

**Comment by lmsurpre** [comment]
reopening this one until the change gets published.  link is still broken on the public site.

**Comment by prb112** [comment]
Agreed with Lee to close
