### ISSUE TITLE
Out of Date File in fhir-audit

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#4]
During a review of the codebase on August 30, 2019, we identified an out-of-date and unused file with `key` `iv` used for ondisk encryption of logs. The file is `fhir-audit/src/main/resources/config.properties`

There are no running instances which use the library that use this configuration file specific to audit. 
There is no compilable code which uses the config.properties. 

The team has opted to remove the unused file.

**Comment by prb112** [comment]
The file is removed in the latest commits to `master`

**Comment by JohnTimm** [comment]
The file removal has been verified.
