### ISSUE TITLE
Upgrade FHIR spec version to 4.0.1

### ISSUE THREAD

**Issue by JohnTimm** [IBM/FHIR#403]
HL7 recently released a technical correction to FHIR R4 v4.0.0. We need to download the latest artifacts (e.g. structure definitions, search parameters, etc.), regenerate the model code and run a regression to see what else needs to get updated.

- [x] Updated definitions in fhir-tools and fhir-registry
- [x] Regenerate fhir-model
- [x] Regenerate ibm examples
- [x] Overwrite spec examples in fhir-examples
- [x] Update FHIRPathEvaluator for %rootResource
- [x] other?

**Comment by lmsurpre** [comment]
Turns out there was quite a bit of "other"...mostly related to a spec change where Resource.id is no longer an Id but instead has a type code of `http://hl7.org/fhirpath/System.String`

**Comment by prb112** [comment]
Whole team reviewed this one
