### ISSUE TITLE
Add DB2 on Cloud setup/configuration docs

### ISSUE THREAD

**Issue by punktilious** [IBM/FHIR#41]
**Is your feature request related to a problem? Please describe.**
Document the setup and configuration of DB2 on Cloud as a persistence provider for FHIR R4.

**Describe the solution you'd like**
A markdown document

**Describe alternatives you've considered**
Is there anything better than markdown?

**Additional context**
N/A

**Comment by lmsurpre** [comment]
https://github.com/IBM/FHIR/blob/master/docs/DB2OnCloudSetup.md looks good to me
