### ISSUE TITLE
DateTime edge case cleanup

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#437]
1.  Add parameter type for all VALUES tables.  This way we'll always know the data type that we extracted the parameter from.
2.  Add boolean inclusive column flag to X_VALUE_DATE tables and update date search SQL queries to use it
2b.  add index to the table to include DATE_START + DATE_END + INCLUSIVE
2c.  drop DATE from X_VALUE_DATE tables
3.  Prefix handling with datetimes
`lt`, `gt`, `le`, `ge` would become implicitly instants (similar to numbers)
`sa` and `eb` stay implicit ranges (unless the search parameter value includes fractional seconds), the same as `eq`, `ne`, and `ap`

acceptance criteria:  when complete, all tests in AbstractSearchDateTest should be uncommented and passing, although the expected results might need to get updated in places based on our recent discussion wrt edge cases (number 3 above).

**Comment by prb112** [comment]
PR https://github.com/IBM/FHIR/pull/506
