### ISSUE TITLE
Introduce fhir-path and fhir-profile modules

### ISSUE THREAD

**Issue by JohnTimm** [IBM/FHIR#453]
In order to complete the initial implementation of FHIR profiling support, we need to introduce two new modules: `fhir-path` and `fhir-profile` and move classes from `fhir-model` and `fhir-validation` into them, respectively. This will enable a cleaner dependency graph that avoids cycles.

**Comment by prb112** [comment]
fhir-constraint does not exist.  It looks like this is all done.
