### ISSUE TITLE
 Quantity search does not consider the quantity comparator field 

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#493]
The FHIR Quantity datatype can contain a comparator field which modifies the meaning of the value of the quantity. However, this comparator is not written into the FHIR search tables and is never considered during search.

For example, we currently have 3 values in the quantity parameters table: Number, LowNumber, and HighNumber. To support implicit precision, LowNumber and HighNumber would always need to be filled out (where the LowNumber is inclusive and the HighNumber is exclusive).

To support comparators, we would need to null either the low or the high as appropriate. Additionally, we would need some kind of indicator to denote whether the high and low are inclusive or exclusive.

How do the comparators relate to the implicit precision range? For example, if a value is 3 with a > comparator, does that mean we should really handle that like >2.5?
No. Based on my reading of https://build.fhir.org/search.html#prefix, quantities with comparators should be handled with bounds which match the explicit value with infinite precision...there is implicit range in these cases.

[#245](https://github.ibm.com/watson-health-fhir-server/fhir/issues/245)

**Comment by lmsurpre** [comment]
Impl tips:
```on extraction, update JDBCParameterBuildingVisitor to either store the comparator or to infer the proper range values (visitQuantity AND visitRange)

on search, update JDBCNormalizedQueryBuilder to query the quantity value as either a Value or a Range

look at the tests in AbstractSearchQuantityTest```

**Comment by michaelwschroeder** [comment]
[issue493Design.docx](https://github.com/IBM/FHIR/files/6522524/issue493Design.docx)

**Comment by kmbarton423** [comment]
Tested new functionality with ResearchDefinition element "useContext" and search parm "context-quantity".
Confirmed search behavior using all prefixes for resources configured with each type of comparator.
