### ISSUE TITLE
Wrong self url when using chained search parameter

### ISSUE THREAD

**Issue by albertwang-ibm** [IBM/FHIR#494]
Query observation using chained search parameter as following:
     .../fhir-server/api/v4/Observation?subject:Patient.name=peter
The self url in the response bundle is as following:
     ...fhir-server/api/v4/Observation?_count=10&subject:Patientnamename=peter&_page=1
But the expected self url should be:
     /fhir-server/api/v4/Observation?_count=10&subject:Patient.name=peter&_page=1

**Comment by prb112** [comment]
Merged and Closed
