### ISSUE TITLE
Db2 deadlock while executing com.ibm.fhir.schema.app.Main --update-schema

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#508]
**Describe the bug**
```
DB2 SQL Error: SQLCODE=-911, SQLSTATE=40001, SQLERRMC=2, DRIVER=4.26.14) ALTER TABLE FHIRDATA2.TOKEN_VALUES ADD CONSTRAINT FK_TOKEN_VALUES_PN FOREIGN KEY(MT_ID,PARAMETER_NAME_ID) REFERENCES FHIRDATA2.PARAMETER_NAMES
2019-12-16 01:51:12.145 0000000e WARNING atabase.utils.model.BaseObject Deadlock detected processing: TABLE:FHIRDATA2.TOKEN_VALUES [remaining=0]
```

**To Reproduce**
Follow the steps at https://github.com/IBM/FHIR/blob/master/fhir-install/README-DB2.md to install and configure a db2 image.
Execute `com.ibm.fhir.schema.app.Main` with arguments like:
```
--prop-file fhir.properties
--schema-name FHIRDATA
--update-schema
```

**Expected behavior**
The schema should be deployed with no errors

**Additional context**
The issue can be worked around by reducing the level of concurrency (e.g. by passing `--pool-size 2`)

**Comment by lmsurpre** [comment]
Attempted to address this one in #499 by adding a dependency from the resource tables to the global parameter values tables like `FHIRDATA.TOKEN_VALUES`.  Now we should be able to run with high levels of parallelism again.

**Comment by prb112** [comment]
Moved from Reviewed / QA to Close
