### ISSUE TITLE
Add dependency graph image to docs

### ISSUE THREAD

**Issue by JohnTimm** [IBM/FHIR#523]
![image](https://user-images.githubusercontent.com/12091744/71182246-bdc24480-2243-11ea-8a5a-68f0e0bbff5a.png)

**Comment by prb112** [comment]
The image is now hosted at https://ibm.github.io/FHIR/images/fhir-dependency-graph.png

**Comment by lmsurpre** [comment]
Now we just need to decide where to reference it from :-)
README?
FHIRServerUserGuide?
ModelGuide?

**Comment by prb112** [comment]
> Now we just need to decide where to reference it from :-)
> README?
> FHIRServerUserGuide?
> ModelGuide?

right... If I know where, I can raise the PR

**Comment by prb112** [comment]
Loaded into the WIP PR John opened
