### ISSUE TITLE
SwaggerGenerator double-writes all search parameters

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#535]
**Describe the bug**
I tried running the SwaggerGenerator from the 4.0.0 release and, unfortunately, it produces invalid Swagger.  OpenApiGenerator has the same issue.
![image](https://user-images.githubusercontent.com/5478798/71373612-d0ab8080-2585-11ea-9fe7-44c9b74c34ae.png)

**To Reproduce**
Execute OpenApiGenerator and validate the result.

**Expected behavior**
Search parameters should only be listed once per type.

**Additional context**
There was a late change leading up to 4.0.0 in which I introduced a second entry in the search parameters map for each search parameter.  In the past we only needed to look up the applicable search parameters by "code" but for Composite search we needed to look them up by "url" as well.
Obviously, I didn't know that would cause this knock-on effect to the Swagger/OpenAPI.

**Comment by prb112** [comment]
interesting side effect.

**Comment by prb112** [comment]
Reviewed, and closing after discussions in PR are complete
