### ISSUE TITLE
Include examples in the generated Swagger/OpenAPI

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#536]
**Is your feature request related to a problem? Please describe.**
Tools like IBM API Connect attempt to generate examples, but this can be very difficult with a schema of this size/complexity.  For example, because all elements contain extensions and extensions contain extensions, the schema is infinite and the tools need to inteligently select when "enough is enough".

**Describe the solution you'd like**
We're sitting on a whole pile of example in the `fhir-examples` project, so can we include some of those in the schema?

**Additional context**
Tools like IBM API Connect attempt to generate examples, but this can be very difficult with a schema of this size/complexity.  If we provide our own examples, will they just use those?

**Comment by prb112** [comment]
Reviewed and QAd.  Closing.
