### ISSUE TITLE
Following directions to install ibm-fhir on windows ... install.bat fails

### ISSUE THREAD

**Issue by rojeff2303** [IBM/FHIR#557]
The install.bat has an issue with the line ... 

echo Error: JAVA_HOME not set; make sure JAVA_HOME points to a Java 8 JVM (or above) and then re-try.

On my system the parens around '(or above)' causes issues that causes the bat file to stop ... remove the parens on that line

**Comment by prb112** [comment]
PR https://github.com/IBM/FHIR/pull/561
Waiting on my virtual machine tests to complete

**Comment by prb112** [comment]
![image](https://user-images.githubusercontent.com/3016328/71849469-2280fa00-30a0-11ea-8b03-f844e58a39e1.png)

**Comment by prb112** [comment]
Merged

**Comment by prb112** [comment]
We're going to add e2e tests at some point.
