### ISSUE TITLE
Update fhirVersion in CapabilityStatement

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#617]
**Describe the bug**
The documentation says the server is for FHIR version 4.0.1 but the /metadata endpoint says its for 4.0.0

**To Reproduce**
`GET [base]/metadata`

**Expected behavior**
CapabilityStatement.fhirVersion should be "4.0.1"

**Comment by prb112** [comment]
I'm pretty sure Lee completed this work.  I moved to review/qa

**Comment by lmsurpre** [comment]
confirmed
