### ISSUE TITLE
Optional _typeFilter support for bulkdata export

### ISSUE THREAD

**Issue by albertwang-ibm** [IBM/FHIR#632]
**Spec:** https://hl7.org/Fhir/uv/bulkdata/export/index.html
In "Experimental Query Parameters" section of the spec,  _typeFilter is an experimental parameter to further limit the export results.

**Example:**
  $export?
  _type=
    MedicationRequest,
    Condition&
  _typeFilter=
    MedicationRequest%3Fstatus%3Dactive,
    MedicationRequest%3Fstatus%3Dcompleted%26date%3Dgt2018-07-01T00%3A00%3A00Z

**Comment by prb112** [comment]
in PR633 I pass this property `fhir.typeFilters` to the backend as a property

**Comment by albertwang-ibm** [comment]
Because one resource type could have multiple filters("or" together),  each with one or more conditions (& together); so we will have to run search on each filter separately. e.g, for the example mentioned in the description, there are 2 filters defined for MedicationRequest,  we need to get all the active MedicationRequests in the first search by using the first filter, process and export the found resources and at the mean time put the processed resource ids into a hashset, and then do the second search using the second filter, and process and export the resource if it's not already in the hashset, and put the id of the process resource into the hashset. repeat the process til there is no more filter defined for the resource type.

**Comment by lmsurpre** [comment]
Note:  this story includes end-of-sprint demo
