### ISSUE TITLE
Encrypt job instance id for polling location url of Bulkdata operations

### ISSUE THREAD

**Issue by albertwang-ibm** [IBM/FHIR#635]
**Problem**: We need a mechanism to protect the job instance id in the polling location url, otherwise, user will be able to poll and get the exported url of any other user, or delete the request submitted by others. 
**Solution**: Seems a simple solution is to encrypt the job instance Id, and because the javabatch job id is not reused(always increase if non in-memory db) in server side, so user will not be able to use his/her old job info to get or deleted other's export.
One approach is to use AES encryption and set the encryption key in server.xml

**Comment by prb112** [comment]
Albert. - This is not true.  I check the tenantId on each request

**Comment by prb112** [comment]
Let's sync up on Monday, I can explain my approach with verifyTenant. 
If we need more, I can turn it around quickly.

**Comment by albertwang-ibm** [comment]
yes, I know you check if the tenant itself is legal or not. The root cause of the problem is that we don't keep tenant - jobids mapping, that mean with a legal tenant id, user can access status of any job instance id(it's just a simple number). we don't really have the data to check if a job is started by a tenant or not at present. and I think encrypting job id is a little easier than storing the tenant--jobids mapping.

**Comment by prb112** [comment]
> yes, I know you check if the tenant itself is legal or not. The root cause of the problem is that we don't keep tenant - jobids mapping, that mean with a legal tenant id, user can access status of any job instance id(it's just a simple number). we don't really have the data to check if a job is started by a tenant or not at present. and I think encrypting job id is a little easier than storing the tenant--jobids mapping.

hum... but we keep them in unique tablespaces...

**Comment by albertwang-ibm** [comment]
Paul's enhancement to the operation does check if the tenant id of the status/delete request matches the tenant id in the job parameter of the export job, so this can already guarantee  that only user from the same tenant can check/delete the export job.  And in the discussion, we still think we should not expose the internal javabatch job id(simple numbers as 1,2 etc) to the end user, so, we agree that we still want to encrypt/decrypt the job instance id during the processing.

**Comment by albertwang-ibm** [comment]
and hopefully, this will also make it difficult for other users of the same tenant from deleting my export request by mistake.
