### ISSUE TITLE
Simplify javabatch client codes and configuration with JobOperator and BatchRuntime

### ISSUE THREAD

**Issue by albertwang-ibm** [IBM/FHIR#636]
**Task**: Instead of using REST API to start/monitor/stop the job, we can use **JobOperator** and **BatchRuntime**.
**Reference**: page 54 of http://www-03.ibm.com/support/techdocs/atsmastr.nsf/002573f7000ac64286256c71006d2e0a/f34b9c5a6e29bc7886257e7c004c93eb/$FILE/WP102544%20-%20WLB%20Step-by-Step%20Implementation%20Guide.002.pdf/WP102544%20-%20WLB%20Step-by-Step%20Implementation%20Guide.pdf

**Sample codes**:

import javax.batch.operations.JobOperator; 
import javax.batch.runtime.BatchRuntime; 
import javax.batch.runtime.JobExecution; 
import javax.batch.runtime.JobInstance;

Start a job:
JobOperator jobOperator = BatchRuntime.getJobOperator(); 
long execId = jobOperator.start("job-id", JobParameters); 
JobInstance jobInstance = jobOperator.getJobInstance(execId);
JobExecution jobExecution = jobOperator.getJobExecution(execId);

Status of a job:
JobOperator jobOperator = BatchRuntime.getJobOperator();
JobInstance jobInstance = jobOperator.getJobInstance(execId); 
List<JobExecution> jobExecutions = jobOperator.getJobExecutions(jobInstance);
...

Stop a job:
BatchRuntime.getJobOperator().stop(execId);
 
Restart a job:
newExecId = BatchRuntime.getJobOperator().restart(execId, JobParameters);

**Comment by prb112** [comment]
@albertwang-ibm I looked into this and tried this approach.  It does not work.  It automatically starts the job on the local operator.

**Comment by albertwang-ibm** [comment]
per Paul's experiments and discussed in the scrum, because if using these APIs, the job will be started inside fhir-server itself, this is not what we want to see, so we will not use these APIs.
