### ISSUE TITLE
Add and use utility for generating 'empty' narrative text for resources

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#646]
**Is your feature request related to a problem? Please describe.**
We get a lot of validation warnings due to our examples not having narrative text.

**Describe the solution you'd like**
Ideally we could generate narrative text from the structured data (#645), but until we get to that I think we could just add empty narrative like this:
```
  "text" : {
    "status": "empty",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Narrative text intensionally left empty</div>" 
  },
```

Some alternate placeholder text I considered was "This resource contains only structured data, no narrative text".  We could make it shorter, but I wanted to make it clear the text was empty and not necessarilly the resource.

**Comment by lmsurpre** [comment]
Actually, it looks like I already have something similar on the `complete-mock` examples:
```"text": {
        "status": "empty",
        "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"></div>"
    },
```

And it sort of goes against the spirit of the `minimal` and `complete-absent` ones.

I'm gonna reword this issue so that its about making it easier to add an empty narrative rather than making it about adding it to our generated examples

**Comment by lmsurpre** [comment]
team decision:  introduce a constant Narrative.EMPTY with the follow content:
```
  "text" : {
    "status": "empty",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Narrative text intensionally left empty</div>" 
  },
```

**Comment by tbieste** [comment]
I verified that the new constant exists in the main branch, so closing this.
