### ISSUE TITLE
Configure server to override "self" URIs with external path

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#66]
**Is your feature request related to a problem? Please describe.**
We're running the FHIR Server behind a proxy and that proxy modifies the request URLs.

Request come in to an endpoint like `https://[host]/wh-fhir-dev/api/v4` but the server is returning URIs like `https://[host]/fhir-server/api/v4/$export-status?job=9`.

Is there a way to use the origin request URL in the server URLs returned by the server?

I think it affects at least:
* search result `self` uri
* Bundle entry fullUrl values
* bulkimportexport polling URLs

**Describe the solution you'd like**
https://[host]/wh-fhir-dev/api/v4
Either:
* a setting the server will use as the "base" in all self uris; or
* a way to tell the server which HTTP header has the original request URI (so it can use that to construct self uris)

**Comment by albertwang-ibm** [comment]
if we have to set/change a new config, why don't we simply change the existing contextRoot in server.xml instead of adding another config? BTW, usually proxy server doesn't pass the original request url to the internal servers.

**Comment by prb112** [comment]
I think Lee is saying that we add a new configuration. 
The context root doesn't always have the Proxy origin.

**Comment by albertwang-ibm** [comment]
yeah, if we want to change hostname part also, then we may need a new configure. actually, can we configure proxy to do the translaction if the hostname is different?

**Comment by albertwang-ibm** [comment]
ideally, proxy can change the response also ...

**Comment by albertwang-ibm** [comment]
but I agree that adding a new config in fhir server side sounds like a simpler solution.

**Comment by prb112** [comment]
I'll try to fix as-soon-as-possible

**Comment by prb112** [comment]
PR https://github.com/IBM/FHIR/pull/659

**Comment by lmsurpre** [comment]
#659 removes the bulkdata-specific hostname/path properties that we invented, but I still think we need:
A. a way to infer the uri of the original request from headers; and/or
B. a fhir-server-config property to overwrite the request uri  (relates to #660)

**Comment by prb112** [comment]
```
{
    "__comment": "FHIR Server configuration",
    "fhirServer": {
        "core": {
            "truststoreLocation": "resources/security/fhirTruststore.jks",
            "truststorePassword": "change-password",
            "tenantIdHeaderName": "X-FHIR-TENANT-ID",
            "datastoreIdHeaderName": "X-FHIR-DSID",
            "originalRequestUriHeaderName" : "IBM-PROXY",
            "checkReferenceTypes": false
        },
```
Added this for testing... 

```
    @Test(groups = { "server-search-near" }, dependsOnMethods = { "testCreateLocation" })
    public void testSearchUsingLocationNear() throws Exception {
        FHIRParameters parameters = new FHIRParameters();
        parameters.searchParam("near", "42.256500|-83.694810|11.20|km");
        FHIRResponse response = client.search(Location.class.getSimpleName(), parameters, new FHIRRequestHeader("IBM-PROXY", "https://localhost:9090/ABC"));
        
        assertResponse(response.getResponse(), Response.Status.OK.getStatusCode());
        Bundle bundle = response.getResource(Bundle.class);
        SearchAllTest.generateOutput(bundle);
        assertNotNull(bundle);
        assertTrue(bundle.getEntry().size() >= 1);
    }
```

```
{
    "resourceType": "Bundle",
    "id": "297cb1f9-dfc7-4d50-a4f8-2bdb41ec98e1",
    "type": "searchset",
    "total": 4,
    "link": [
        {
            "relation": "self",
            "url": "https://localhost:9090/ABC?_count=10&near=42.256500%7C-83.694810%7C11.20%7Ckm&_page=1"
        }
    ],
```

**Comment by prb112** [comment]
Confirmed with my above test
