### ISSUE TITLE
Merge bulkdata config into fhir-server-config

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#660]
**Is your feature request related to a problem? Please describe.**
The IBM FHIR Server design is to have a single config file which has all the configuration for the server.  However, out of expedience, our current bulkdata operation support has its own separate config file.

**Describe the solution you'd like**
BulkData should get its own section within fhir-server-config.
Furthermore, the bulk data implementation should use the core settings of the FHIR Server such as:
* base url (the hostname to use for the base url in responses), #66 
* pretty-print config

**Comment by albertwang-ibm** [comment]
I have already added fhir-server/bulkdata section in PR647 for the batch job encryption key, so if need, we can put all the other configs there also.
