### ISSUE TITLE
Build pipeline failure due to maven timeout issue

### ISSUE THREAD

**Issue by albertwang-ibm** [IBM/FHIR#668]
**Problem:** Execution create-archive of goal org.apache.maven.plugins:maven-assembly-plugin:3.1.0:single failed: Plugin org.apache.maven.plugins:maven-assembly-plugin:3.1.0 or one of its dependencies could not be resolved: Failed to collect dependencies at org.apache.maven.plugins:maven-assembly-plugin:jar:3.1.0 -> org.apache.maven.shared:maven-artifact-transfer:jar:0.9.0: Failed to read artifact descriptor for org.apache.maven.shared:maven-artifact-transfer:jar:0.9.0: Could not transfer artifact org.apache.maven.shared:maven-artifact-transfer:pom:0.9.0 from/to central (https://repo.maven.apache.org/maven2): Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.101.184.215] failed: Connection timed out

**Possible solution:**
(1) add -Dmaven.wagon.http.pool=false` OR `-Dhttp.keepAlive=false` as flags to the maven tasks.
(2) upgrade to maven 3.2 or after.

**Reference:** 
https://developercommunity.visualstudio.com/content/problem/292284/maven-hosted-agent-connection-timeout.html

**Comment by albertwang-ibm** [comment]
per discussion, we'd like to try the the first solution of adding flag.

**Comment by lmsurpre** [comment]
The linked issues from https://developercommunity.visualstudio.com/content/problem/292284/maven-hosted-agent-connection-timeout.html are all marked as resolved (as of 3.3.x).

I double-checked our pipeline and we're already using the latest maven:
`Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)`

Something not right...

**Comment by lmsurpre** [comment]
I tried adding both `-Dmaven.wagon.http.pool=false` and `-Dhttp.keepAlive=false` but it broker the build.

I updated it to -Dmaven.wagon.httpconnectionManager.ttlSeconds=240` and it works, but its hard to confirm whether it addresses the issue or not.  If we hit the issue again, please reopen this one.

**Comment by albertwang-ibm** [comment]
seems it works so far with multiple builds of my PR have passed, so close this issue for now.

**Comment by lmsurpre** [comment]
I just hit this one:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.1.0:single (fhir-persistence-proxy) on project fhir-persistence-proxy: Execution fhir-persistence-proxy of goal org.apache.maven.plugins:maven-assembly-plugin:3.1.0:single failed: Plugin org.apache.maven.plugins:maven-assembly-plugin:3.1.0 or one of its dependencies could not be resolved: The following artifacts could not be resolved: org.apache.maven.shared:maven-shared-utils:jar:3.1.0, org.apache.maven.shared:maven-artifact-transfer:jar:0.9.0: Could not transfer artifact org.apache.maven.shared:maven-shared-utils:jar:3.1.0 from/to central (https://repo.maven.apache.org/maven2): Transfer failed for https://repo.maven.apache.org/maven2/org/apache/maven/shared/maven-shared-utils/3.1.0/maven-shared-utils-3.1.0.jar: Connection timed out (Read failed) -> [Help 1]
```

However, I'm not confident that the source branch had this change in it.

**Comment by lmsurpre** [comment]
Actually, that error was in the e2e tests this time and I had only added that ttlSeconds property to the normal build (build with tests).  With https://github.com/IBM/FHIR/pull/717 I've added it to the e2e tests too...so lets continue to keep an eye on this one to see whether its resolved or not.

**Comment by lmsurpre** [comment]
havn't seen it in 19 days, i think we nailed it
