### ISSUE TITLE
Connectathon Issues with Bulkdata

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#67]
Connectathon Issues with Bulkdata

**Comment by prb112** [comment]
resolving ds issue and tenant issue with Albert

**Comment by lmsurpre** [comment]
Once we finally started testing with a partner, we hit a few issues where we returned 400 error when it was actually a server error.  This was frustrating to user and made it harder for him to trust us when we rejected other requests with the same error (even those really were client issues).
We really need to default unexpected exceptions to 500.

**Comment by lmsurpre** [comment]
Separate thought...I don't think we need to be appending each chunk into a big string.  Can we buffer the objects instead?

**Comment by prb112** [comment]
> Once we finally started testing with a partner, we hit a few issues where we returned 400 error when it was actually a server error. This was frustrating to user and made it harder for him to trust us when we rejected other requests with the same error (even those really were client issues).
> We really need to default unexpected exceptions to 500.

Sure - I think we consider this part of refactoring.
