### ISSUE TITLE
Basic create and read performance comparison tests before and after the SyntheticMass data import

### ISSUE THREAD

**Issue by albertwang-ibm** [IBM/FHIR#674]
Measure the performance of the inserts and reads after the loading of the data and compare it with metrics from before the import

**Comment by albertwang-ibm** [comment]
**Test setup:** 
Run local fhir server with performance8 tenant configured to use the one created in bludb of CDT env.
**Test tool:**
The REST performance test tool in the fhir-server-test project with following settings
  --threads 5
  --max-inflight 5
  --tenant-id performance8

**Comment by albertwang-ibm** [comment]
Performance results before SyntheticMass data import:
INFO: Overall success rate = 3845/3845 = 100%. Took 634575 ms
     **REQS MAX(ms) AVG(ms) 95TH(ms) CALLS/s**
   PARSE  3845    2021       6       9     6.1
VALIDATE  3637    6409       4       9     5.7
  CREATE  3607    8918     692    1603     5.7
    READ  3607    2379     173     207     5.7
 PROCESS  3607    9128     868    1795     5.7
Feb 26, 2020 1:29:36 PM com.ibm.fhir.server.test.app.Main main
INFO: Took: 634.988 seconds

**Comment by albertwang-ibm** [comment]
`INFO: Overall success rate = 3845/3845 = 100%. Took 634575 ms
          REQS MAX(ms) AVG(ms) 95TH(ms) CALLS/s
   PARSE  3845    2021       6       9     6.1
VALIDATE  3637    6409       4       9     5.7
  CREATE  3607    8918     692    1603     5.7
    READ  3607    2379     173     207     5.7
 PROCESS  3607    9128     868    1795     5.7
Feb 26, 2020 1:29:36 PM com.ibm.fhir.server.test.app.Main main
INFO: Took: 634.988 seconds`

**Comment by albertwang-ibm** [comment]
**Performance results after data import:**
**First run:**
Overall success rate = 3819/3845 = 99%. Took 794155 ms
          REQS MAX(ms) AVG(ms) 95TH(ms) CALLS/s
   PARSE  3845    1893       6      11     4.8
VALIDATE  3637    6472       4       9     4.6
  CREATE  3581   12181     879    2239     4.5
    READ  3581    8122     207     266     4.5
 PROCESS  3607   12412    1089    2509     4.5
Mar 12, 2020 10:30:41 AM com.ibm.fhir.server.test.app.Main main

**Comment by albertwang-ibm** [comment]
We decided to run a second run using another DB2 cloud instance with an empty DB, a new schema and new tanent performance8.

**Comment by albertwang-ibm** [comment]
Performance` results before SyntheticMass data import(2nd run):
Mar 13, 2020 10:43:35 AM com.ibm.fhir.model.spec.test.R4ExamplesDriver processIndex
INFO: Overall success rate = 3845/3845 = 100%. Took 136387 ms
          REQS MAX(ms) AVG(ms) 95TH(ms) CALLS/s
   PARSE  3845    2840       8      17    28.2
VALIDATE  3637   22088      10      22    26.7
  CREATE  3607    8734     123     309    26.4
    READ  3607    3028      37      61    26.4
 PROCESS  3607    8891     167     379    26.4
Mar 13, 2020 10:43:35 AM com.ibm.fhir.server.test.app.Main main
INFO: Took: 136.840 seconds

**Comment by albertwang-ibm** [comment]
**Performance` results after SyntheticMass data import(2nd run):**
Mar 23, 2020 10:02:54 AM com.ibm.fhir.model.spec.test.R4ExamplesDriver processIndex
INFO: Overall success rate = 3845/3845 = 100%. Took 553904 ms
          REQS MAX(ms) AVG(ms) 95TH(ms) CALLS/s
   PARSE  3845    2149       5       9     6.9
VALIDATE  3637    6983       4       9     6.6
  CREATE  3607    4962     577     843     6.5
    READ  3607    2886     176     223     6.5
 PROCESS  3607    5087     756    1077     6.5
Mar 23, 2020 10:02:54 AM com.ibm.fhir.server.test.app.Main main

**Comment by senthilbak** [comment]
@albertwang-ibm please create a new issue to investigate the slowdown.
