### ISSUE TITLE
Build a search performance test harness

### ISSUE THREAD

**Issue by albertwang-ibm** [IBM/FHIR#676]
Build a search performance test harness to include reasonable variations of search, Leverage the [Windtunnel project](https://github.com/FirelyTeam/Wind.Tunnel) as appropriate

The goal is to help us find slow queries or queries which scale poorly with the amount of data, especially in advanced search features like:

- whole-system search
- chaining
- reverese chaining (_has) - #1218 
- includes
- reverse includes
- compartment search

Once, ready, we will use this framework to get a baseline for our search performance (#677).
Then, we need some way to track this over time (and spot regressions).

**Comment by kmbarton423** [comment]
Is the goal here to have something that execute these searches every time we each run a build?  or is it intended to be something that someone would run based on a time interval (maybe weekly)?  or just when new fhir code is committed?  My opinion is that there needs to be a consistent chunk of data found and returned when these searches are done in order to better understand performance ... that would require mock data designed with specific relationships and content ... not sure it makes sense to include in the build process to be run all the time

**Comment by lmsurpre** [comment]
> Is the goal here to have something that execute these searches every time we each run a build?  or is it intended to be something that someone would run based on a time interval (maybe weekly)? or just when new fhir code is committed?

Running it on pull requests (and being notified of slowdowns) would be great, but at this point I'd just be happy to have a baseline of the various search queries against a sizeable database.

> My opinion is that there needs to be a consistent chunk of data found and returned when these searches are done in order to better understand performance ... that would require mock data designed with specific relationships and content ... not sure it makes sense to include in the build process to be run all the time

I agree.  Perhaps we should just run this ourselves against one of our internal deployments (and probably not from the public CI).  Although hopefully we could still share the results in some publicly-available way.

**Comment by lmsurpre** [comment]
At connectathon, I became aware of a nice Postman collection of "complex but realistic" queries for Provider Directory (PDEX PlanNet):  https://github.com/Jammjammjamm/plan-net-postman-collection

These queries, or queries like them, but form a good basis for some queries to measure.
For convenience, I'll list some of the more advanced ones here:
* Scenario 3: Request data on an individual Organization 
```
{{url}}/Organization?name=GREATER LAWRENCE FAMILY HEALTH CENTER, INC.&_revinclude=Location:organization&_revinclude=HealthcareService:organization&_revinclude=Endpoint:organization
```
* Scenario 4: Request data on Organizations
```
{{url}}/Organization?name=BAY STATE COMMUNITY SERVICES, INC.&_revinclude=OrganizationAffiliation:participating-organization&_revinclude=Endpoint:organization&_revinclude=HealthcareService:organization
```
* Scenario 5a: Request Organization data for a specific Provider
```
{{url}}/Practitioner?identifier=1230782571&_revinclude=PractitionerRole:practitioner&_include:iterate=PractitionerRole:organization
```
* Scenario 5b: Request Locations, HealthcareServices, and Endpoints for Provider Organization
```
{{url}}/Organization?_id={{pract_assoc_orgs}}&_revinclude=Location:organization&_revinclude=HealthcareService:organization&_revinclude=Endpoint:organization
```
* Scenario 6a: Identify Organization and Practitioner data associated with a Network
```
{{url}}/Organization?name=State of Massachusetts Preferred Provider Network&_revinclude=OrganizationAffiliation:network&_revinclude=PractitionerRole:network
```
* Scenario 6b: Identify location and healthcare services data associated with an Organizational Provider Network 
Member
```
{{url}}/Organization?_id={{network_org_members}}&_revinclude=Location:organization&_revinclude=HealthcareService:organization
```
* Scenario 7a: Identify HealthcareServices in a state
```
{{url}}/HealthcareService?location.address-state=RI&_include=HealthcareService:organization
```
* Scenario 7b: Identify HealthcareServices in a city
```
{{url}}/HealthcareService?location.address-state=RI&location.address-city=Providence&_include=HealthcareService:organization
```
* Scenario 7c: Identify particular types of HealthcareServices in a state
```
{{url}}/HealthcareService?service-type=respiratory-therapy&location.address-state=RI&_include=HealthcareService:organization
```
* Scenario 7d: Identify particular types of HealthcareServices in an area
```
{{url}}/HealthcareService?service-type=respiratory-therapy&location.near=-71.4|41.8|100|mi_us
```
* Scenario 8: Find Practitioners whose license will expire in the next 90 days
```
{{url}}/Practitioner?qualification-period=eb2019-12-14
```
* Scenario 9a: Identify Organizations in a Network
```
{{url}}/OrganizationAffiliation?network=plannet-network-HPID110000&_include=OrganizationAffiliation:participating-organization
```
* Scenario 9b: Identify Practitioners in a Network
```
{{url}}/PractitionerRole?network=plannet-network-HPID110000&_include=PractitionerRole:practitioner
```

**Comment by d0roppe** [comment]
Mock Data Search example:
search sample that covers chaining and include
https://localhost:7000/fhir-server/api/v4/ExplanationOfBenefit?claim:Claim.created=2015-10-16&patient:Patient._id=17546b5cd4a-cae29bb0-d6d7-4a1a-a8df-505e2e3a975e&_include=ExplanationOfBenefit:*
Currently fails.
Sample with just chaining works
https://localhost:7000/fhir-server/api/v4/ExplanationOfBenefit?claim:Claim.created=2015-10-16&patient:Patient._id=17546b5cd4a-cae29bb0-d6d7-4a1a-a8df-505e2e3a975e

**Comment by d0roppe** [comment]
tests added and merged to performance/fhir-meter/searchTest.jmx JMeter tests in git
