### ISSUE TITLE
Search performance comparison tests - Using the test harness built in issue 676

### ISSUE THREAD

**Issue by albertwang-ibm** [IBM/FHIR#677]
Perform comprehensive search testing after loading all of Synthetic mass.

This will help us find any slow queries we might have lurking around, especially in advanced search features like:
1. whole-system search
2. chaining
3. reverese chaining (_has)
4. includes
5. reverse includes
6. compartment search
etc.

**Comment by d0roppe** [comment]
Created issue #1769 with searches created for issue 676 that take longer than 2 seconds on the large postgres DB.
