### ISSUE TITLE
Unexpected warning validating against us-core-condition

### ISSUE THREAD

**Issue by tbieste** [IBM/FHIR#684]
**Describe the bug**
FHIR Server 4.0.1.
Attempting to validate a Condition resource against us-core-condition with a valid category, but I get a warning:

**To Reproduce**
1. Validate with a valid Condition that contains:
 "category" : [ {
		"coding" : [ {
			  "system" : "http://terminology.hl7.org/CodeSystem/condition-category",
			  "code" : "encounter-diagnosis"
			} ]
	 } ]
2.  Get this back in output:
  "issue": [
        {
            "severity": "warning",
            "code": "invariant",
            "details": {
                "text": "us-core-1: A code in Condition.category SHOULD be from US Core Condition Category Codes value set."
            },
            "expression": [
                "Condition"
            ]
        }
    ]

**Expected behavior**
Expected no warnings from validation.

**Comment by JohnTimm** [comment]
This issue is related to a problem in the constraint definition itself. That is the `in` operator is being overloaded to with the expectation that it works like the `memberOf` function. However, nowhere does it say this in the FHIRPath documentation. This issue should be propagated into the HL7 GForge tracker so that it can get into the next build of the US Core R4 IG.

**Comment by JohnTimm** [comment]
I have posted the following topic on Zulip:
https://chat.fhir.org/#narrow/stream/179166-implementers/topic/Invalid.20FHIRPath.20constraint.20in.20the.20US.20Core.20Condition.20profile

Depending on the responses that we get from that, I will likely follow up by creating an issue in FHIR Jira tracker.

**Comment by JohnTimm** [comment]
Created an issue in the Jira tracker:
https://jira.hl7.org/projects/FHIR/issues/FHIR-26605

**Comment by JohnTimm** [comment]
I will implement backwards-compatible support in FHIREvaluator as a stop gap until the US Core IG gets updated.
