### ISSUE TITLE
e2e windows tests report success even when e2e tests fail

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#698]
**Describe the bug**
![image](https://user-images.githubusercontent.com/5478798/74277771-195dfb00-4ce6-11ea-9d77-03d65db02640.png)

**To Reproduce**
1. Introduce an e2e test failure and open a PR

**Expected behavior**
The e2e windows job should show a red X

**Additional context**
I was hoping it was as simple as adding `$ErrorActionPreference = "Stop"` to the github action, but it seems like that wasn't enough.

**Comment by prb112** [comment]
@lmsurpre if you need me to build local, let me know, and leave a message

**Comment by prb112** [comment]
tested in my fork... basically pushed Lee's fix into the script
