### ISSUE TITLE
Add cache support for the capabilites request

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#734]
**Is your feature request related to a problem? Please describe.**
Calls to the /metadata take a long time and it shouldn't change unless someone updates the config.  At the very least, we should make sure we're adding reasonable cache-control headers.

**Describe the solution you'd like**
I'd love to start caching this, maybe on a per-tenant basis....

**Describe alternatives you've considered**
Make it more static.  For example, IGs sometimes ship with their own CapabilityStatement resources.  How will we expose those?

**Comment by lmsurpre** [comment]
potentially related to #661

**Comment by JohnTimm** [comment]
One thing we need to consider on this one is how to dynamically support definitional resources that contribute to the capabilities statement (i.e. profiles that are POST or PUT through the endpoint). I think, per Lee's suggestion, we would need to go to a time-based cached.

**Comment by prb112** [comment]
PR https://github.com/IBM/FHIR/pull/1078

I went with a time based cache (since the date in the generated capabilities statement is using ZonedDateTime.now I check to see if the current ZonedDateTime.now is within 1 hr)

**Comment by JohnTimm** [comment]
https://guava.dev/releases/17.0/api/docs/com/google/common/cache/CacheBuilder.html
