### ISSUE TITLE
Configurable FHIR-based Terminology Service Integration

### ISSUE THREAD

**Issue by JohnTimm** [IBM/FHIR#745]
There are existing public FHIR servers that provide terminology service capabilities per the spec:
http://hl7.org/fhir/terminology-service.html

A component that integrates these capabilities with our FHIR server can address gaps in our terminology related validation functions (e.g. CodeSystem/$validate-code, ValueSet/$validate-Code).

LOINC FHIR server
https://loinc.org/fhir/

SNOMED-CT FHIR server
https://snowstorm-fhir.snomedtools.org/fhir/metadata

**Comment by jaykola** [comment]
Hi guys, I have been test the FHIR-Server and it works a treat. I am also conscious you have labelled various things as `experimental`.  However, on this issue I'd like to clarify if this is an issue in need of some more work. 

I have configured fhir-server to use a Remote Terminology Service Provider as advised in [docs](https://ibm.github.io/FHIR/guides/FHIRTerminologyGuide#remote-terminology-service-provider-implementation-experimental). When I do this, `CodeSystem/$lookup` operations work as expected. ValueSet operations `isa`  and `below` work as expected. 

FHIR Implicit Value Sets can be defined via [`ecl` for SNOMED CT](https://www.hl7.org/fhir/snomedct.html#implicit).  You already added some support for this in #2092. As you are aware SNOMED CT has this `Expression Constraint Language` (SQL equivalent of sorts for SNOMED CT) and is pretty powerful. But right now using  `ecl` for implicit valuesets does not work when accessing from the fhir-server, even though the remote server supports the operation.

Here are specific examples:
Query: 'http://localhost:9070/fhir-server/api/v4/ValuSet/$expand?url=http://snomed.info/sct?fhir_vs=ecl/<<27624003' produces response
```
{
    "resourceType": "OperationOutcome",
    "id": "ac-16-0-3-f827c8a2-6c77-490b-8485-805442338e45",
    "issue": [
        {
            "severity": "fatal",
            "code": "not-supported",
            "details": {
                "text": "ValueSet with url 'http://snomed.info/sct?fhir_vs=ecl/<<27624003' is not available"
            },
            "expression": [
                "<empty>"
            ]
        }
    ]
}
```
You can verify this query is supported by the remote terminology server - equivalent call: 

https://snowstorm-fhir.snomedtools.org/fhir/ValueSet/$expand?url=http://snomed.info/sct?fhir_vs=ecl/%3C%3C27624003

Now the semantic equivalents of that expansion using `isa` and `below` both work. So am I missing something, or is the `ecl` operator yet to be supported. 

Happy to help if that is useful. Again, happy to file a separate issue if that is better.

**Comment by lmsurpre** [comment]
Yes, we added.  @JohnTimm has been driving this terminology work and he's out today, but I'm thinking we should:
1. close this issue.  the remote term service provider was added under https://github.com/ibm/fhir/issues/2198 and I think it addresses this particular issue (at least whats written in the description).
2. open a separate enhancement request for adding support for ECL to the SNOMED CT implicit valuesets feature. I don't think its a high priority for us at the moment, but possibly John could give some pointers when he returns.

> happy to file a separate issue if that is better

Please do!

**Comment by JohnTimm** [comment]
The ECL operator is not currently supported.
