### ISSUE TITLE
Custom operation should support more types being passed from URI

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#75]
**Describe the bug**
While trying to invoke $export operation via GET, it complains that we can't process an input parameter of type instant.

**To Reproduce**
Invoke export with a request like this:  `{{http}}://{{host}}:{{port}}/{{basePath}}/$export?_outputFormat=application/fhir+ndjson&_since=2019-01-01T08:21:26.94-04:00&_type=Patient`

**Additional context**
Spec says we should support passing of "primitive" types via URL.

**Comment by prb112** [comment]
It's intentional :) there is a todo in the BulkDataClient to pass the joined list. 
defensively - I opted not to pass since only one type is supported at this time.

**Comment by lmsurpre** [comment]
I really think we should just expand the set of supported types that come in from the URL.  Its not a bulk issue; just a limitation of current operation framework impl.  Will have PR shortly.

**Comment by lmsurpre** [comment]
I don't think this is really blocked by #55.  We just need to add some tests and then I'll close it out.

**Comment by prb112** [comment]
was not the intent to block - rather link the two

**Comment by lmsurpre** [comment]
yeah, i wish they had a "related to".  all you can really do then is just mentioned the issue #s in comments.
