### ISSUE TITLE
Update "Setting up for development" instructions to fork before clone

### ISSUE THREAD

**Issue by philcoibm** [IBM/FHIR#750]
**Describe the bug**
In Setting up for development the instructions state to clone this FHIR repo, but it should be updated to say fork and clone the fork following the usual [GitHub Standard Fork & Pull Request Workflow](https://gist.github.com/Chaser324/ce0505fbed06b947d962). Also, a little more detail on setting up Eclipse would be useful, eg like that you won't find TestNG in Marketplace. 

**To Reproduce**
1. Go to https://github.com/IBM/FHIR/wiki/Setting-up-for-development
2. Follow the steps 
3. Note little things that could be improved
4. Open this ticket :)

**Expected behavior**
A clear and concise description of how to get going as a contributor.

**Additional context**
ok this is just an excuse to get my feet wet here :)

**Comment by philcoibm** [comment]
ok @prb112 changes made, over to you for review

**Comment by prb112** [comment]
Thank you kindly - all reviewed.
