### ISSUE TITLE
Bulk should accept _outputFormat requests with encoded "+"

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#76]
**Describe the bug**
When _outputFormat is submitted as a query parameter, the UriInfo injected in FHIRResource replaces the "+" char with a space.

This is the same issue we hit with the FHIR "_format" query parameter, but in a different part of the code.

**To Reproduce**
`{{http}}://{{host}}:{{port}}/{{basePath}}/$export?_outputFormat=application/fhir+ndjson&_since=2019-01-01T08:21:26.94-04:00&_type=Patient`

**Expected behavior**
Not sure if its liberty or JAX-RS or CXF at fault here, but we need to work around the issue for this to work.

**Comment by prb112** [comment]
It's coming from Liberty. I can take this one.
