### ISSUE TITLE
Implement Static Source Code Scanning

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#801]
Implement Static Source Code Scanning

- Investigate SonarCube, ASOC, AppScan 
- Implement as part of pipeline
- come up with a false positive strategy... [AppScan Java Annotation](https://help.hcltechsw.com/appscan/ASoC/src_java_annotations.html)

cc: @senthilbak

**Comment by smhdfdl** [comment]
HCL AppScan has flagged a couple of issues in the fhir-validation assembly, see attached.


[AppScan_Report.pdf](https://github.com/IBM/FHIR/files/4370506/AppScan_Report.pdf)

**Comment by prb112** [comment]
I'll let Lee respond.  I don't think this is the right issue to track the issues you mention @smhdfdl

**Comment by smhdfdl** [comment]
I agreed it with Lee

**Comment by lmsurpre** [comment]
Paul to schedule a deep dive to review this with rest of team.
