### ISSUE TITLE
DB2 docker file name incorrect

### ISSUE THREAD

**Issue by smhgit** [IBM/FHIR#824]
See here:

https://github.com/IBM/FHIR/blob/master/fhir-install/README-DB2.md

Should be: Dockerfile-db2

**Comment by prb112** [comment]
raised pr https://github.com/IBM/FHIR/pull/826

**Comment by prb112** [comment]
Fixed, Please confirm.  

cc: @lmsurpre

**Comment by prb112** [comment]
Lee confirmed. 

Fixed and merged an additional update from Lee
