### ISSUE TITLE
Toustone test regression for fhir-api-r4-patient-update-05-version-aware

### ISSUE THREAD

**Issue by albertwang-ibm** [IBM/FHIR#825]
**The problem:**
There are 2 test failures in
https://touchstone.aegis.net/touchstone/scriptexecution?exec=202003201323454328340136&qn=/FHIR4-0-1-Advanced/Patient/04-update/fhir-api-r4-patient-update-05-version-aware

Both of them were passed in the previous run of Advanced_all tests:
https://touchstone.aegis.net/touchstone/scriptexecution?exec=202003032154323137535807&qn=/FHIR4-0-1-Advanced/Patient/04-update/fhir-api-r4-patient-update-05-version-aware#WAITING_OPER

**The cause:**
The http error code was changed from 409 to 412.

**Comment by albertwang-ibm** [comment]
It's really interesting to find that in 4.0.1 spec, **412** is indeed the correct response code. checked the fhir spec version history, seems 409 is required in the 3.x versions, not sure if 409 is required in 4.0.0 version also(can not find 4.0.0 version anymore.) 

So, this should be a defect of touchstone instead of our fhir server, we have made the correct change, will notify TouchStone to make the change accordingly.

**Comment by lmsurpre** [comment]
Yes, this is why I made the change in the first place, and its consistent with the guidance on usage of HTTP from the ietf.  If the request contains a `If-X` precondition that fails, the response should be a 412.  Thanks for opening the ticket with AEGIS TouchStone support.

**Comment by lmsurpre** [comment]
TouchStone support has confirmed this is an issue on their side.  Lets move this to either under review or ice-box until that gets resolved.  Also, since no change is needed on our side, I'll remove this from the 4.1.0 release list.

**Comment by albertwang-ibm** [comment]
fixed by touchstone side.
