### ISSUE TITLE
Support dynamicity in the registry

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#832]
**Is your feature request related to a problem? Please describe.**
The FHIRRegistry is used for various validation-related tasks.  It currently uses ServiceLoader to find all the FHIRRegistryResourceProviders and then asks each one for the set of FHIRRegistryResources it can provide and stores those in a big map.

This works well for statically-configured servers (like how we support fhir-ig-us-core and other IGs), but in order to support a per-tenant "management" API where each tenant can store their own MetadataAritfacts, we need something more dynamic.

**Describe the solution you'd like**
Instead of keeping a map in the FHIRRegistry, just keep the list of providers.
Then, each time you need to look up a given resource by its url/version/whatever, the registry should ask each provider for it.
This way, the FHIRRegistryResourceProviders can dynamically change the list of resources that they are tracking.
Sometimes this is called the "whiteboard" pattern.

**Comment by lmsurpre** [comment]
In combination with the registry changes, we should implement a FHIRRegistryResourceProvider which uses FHIRPersistence to get the list of resources it can provide.

We might need to extend FHIRPersistence interface and impls to consult the X_VALUES search tables and return a set of fields necessary to instantiate the FHIRRegistryResource objects.

**Comment by mjdisc** [comment]
@JohnTimm Per our slack conversation, I'm adding a comment to this issue to change the FhirRegistry from lazy initialization to instead initialize at FHIR server startup time. This will cause any failures in loading a registry jar to be reported immediately upon server startup.

**Comment by lmsurpre** [comment]
The "Create FHIR server registry resource provider" part of this one was split into #889
