### ISSUE TITLE
Basic creation and read speed is impacted by the Ingested SyntheticMass data set a lot

### ISSUE THREAD

**Issue by albertwang-ibm** [IBM/FHIR#835]
**The problem:**
After ingesting tens millions resources into the test system, Basic create and read operations become much more slower than before SyntheticMass data was ingested.
     about 30/Second vs 7/Second.

**Test setup:**
The REST performance test tool in the fhir-server-test project with following settings
--threads 5
--max-inflight 5
--tenant-id performance9

**Expected Results**
There should be no huge difference of the processing rates

**Real Results**
After ingestion, the processing rates are 4 times slower.

**Comment by albertwang-ibm** [comment]
please refer to issue #674 for the detailed test results.

**Comment by prb112** [comment]
Given the changes to Composites, this may no longer be valid or current.

**Comment by prb112** [comment]
@punktilious and @d0roppe are looking at performance again, and will confirm
