### ISSUE TITLE
SearchAllTest timeout and slowdowns after BulkData Load

### ISSUE THREAD

**Issue by albertwang-ibm** [IBM/FHIR#836]
**Problem**
SearchAllTests using `_lastUpdated` are slow and timeout (> 60 seconds) after ingesting SyntheticMass. The tests that are slow are: 

| Tests | Timing |
|-----|-----|
| testSearchAllUrlReflexsivityUsingLastUpdated | **60s**|
| testSearchAll2UsingUniqueTag | |
| testSearchAllUsing2FullTags | |
| testSearchAllUsing2Tags | |
| testSearchAllUsing2TagsAndNoExistingTag | |
| testSearchAllUsingId | |
| testSearchAllUsingLastUpdated | **60s** |
| testSearchAllUsingOneTag | |
| testSearchAllUsingProfile | |
| testSearchAllUsingSecurity | |
| testSearchAllUsingTag | |

These queries use a global table for `LOGICAL_RESOURCES`. 

**Reference**
- [Search performance comparison tests - leverage existing server integration test #675](https://github.com/IBM/FHIR/issues/675)
- whole-system search performs poorly for queries with many results #264

**Comment by albertwang-ibm** [comment]
please refer to issue #675 for more detailed info if need.

**Comment by prb112** [comment]
![image](https://user-images.githubusercontent.com/3016328/87160851-a1463200-c291-11ea-88b2-efe5ffb195db.png)

| Tests | Prior to Change | After Refactor #1 | After Refactor #2 |
|-----|-----|-----|-----|
| testCreatePatient | 12.597 | 6.997 | 4.34 |
| testCreatePatientAndObservationWithUniqueTag | 7.513 | 5.15 | 3.323 | 0.55 |
| <mark>testSearchAllUrlReflexsivityUsingLastUpdated</mark> | 60.056 (timeout) | 22.098 | 1.327 |
| testCreateObservation | 2.41 | 1.686 | 0.137 |
| <mark>testSearchAll2UsingUniqueTag</mark> | 20.719 | 15.421 | 0.465 |
| testSearchAll2UsingUniqueTag_OneType | 0.458 | 0.587 |0.061 |
| testSearchAll2UsingUniqueTag_TwoTypes | 0.476 | 0.758 | 0.073 |
| testSearchAll2UsingUniqueTag_TwoTypes_Summary | 0.314 | 0.454 |0.075 |
| testSearchAll2UsingUniqueTag_TwoTypes_elements | 0.308 | 0.451 | 0.095 |
| testSearchAll2_TwoTypes_ChainedParameter | 0.599 | 0.758 | 0.083 |
| testSearchAll2_TwoTypes_InvalidChainedParameter | 0.033| 0.045 | 0.151 |
| testSearchAll2_TwoTypes_InvalidInclude | 0.032 | 0.038 | 0.063 |
| <mark>testSearchAllUsing2FullTags</mark> | 31.838 | 17.952 | 1.027 |
| <mark>testSearchAllUsing2Tags</mark> | 30.338 | 18.192 | 1.375 |
| <mark>testSearchAllUsing2TagsAndNoExistingTag</mark> | 29.994 | 18.505 | 1.213 |
| <mark>testSearchAllUsingId</mark> | 9.17 | 8.854 | 0.267 |
| <mark>testSearchAllUsingLastUpdated<mark> | 60.037 (timeout) | 8.741 | 0.153 |
| <mark>testSearchAllUsingLastUpdatedGeLe</mark> | N/A | 12.413 | 13.586 | 0.169 |
| <mark>testSearchAllUsingLastUpdatedMultipleGeLe</mark> | N/A | 11.915 | 12.456 | 0.472 |
| testSearchAllUsingLastUpdatedMultipleGeLeOneInvalidEach | N/A | 0.924 | 0.334 |
| <mark>testSearchAllUsingOneTag</mark> | 17.668 | 16.861 | 1.459 |
| <mark>testSearchAllUsingProfile</mark> | 21.292 | 15.647 | 0.789 |
| <mark>testSearchAllUsingSecurity</mark> | 14.826 | 15.319 | 0.566 | 
| <mark>testSearchAllUsingTag</mark> | 7.867 | 7.373 | 0.382 |

**Comment by prb112** [comment]
Resolved directly by a refactor to the DISTINCT elimination in https://github.com/IBM/FHIR/issues/1327
I left the 2pts as I did some research earlier this week.
