### ISSUE TITLE
Documentation: high-level architecture diagram

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#844]
Documentation: high-level architecture diagram

Add a High-Level Architecture Diagram or diagrams to the documentation 

CC: @JohnTimm

**Comment by prb112** [comment]
Added https://github.com/IBM/FHIR/wiki/Reference:-Architecture-Diagrams

**Comment by lmsurpre** [comment]
Looks good to me, thanks for adding

**Comment by prb112** [comment]
cool - if we need more I can add
