### ISSUE TITLE
Add DELETE operation to all resource in swagger page

### ISSUE THREAD

**Issue by smhgit** [IBM/FHIR#851]
Resources are missing DELETE operation.

E.g.:

![image](https://user-images.githubusercontent.com/10852598/77648605-17d45380-6f71-11ea-8db2-355086a4ab07.png)

**Comment by lmsurpre** [comment]
![image](https://user-images.githubusercontent.com/5478798/77794259-f0998700-7041-11ea-83a9-fd368308efbb.png)
