### ISSUE TITLE
Issues with DerbyMaster and derby.properties design

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#853]
**Describe the bug**
`fhir-persistence-schema` project has `com.ibm.fhir.database.utils.derby.DerbyMaster` which provides an abstraction for an AutoCloseable embedded derby instance thats used by both tests and "bootstrapping" code (when persistence type is derby and bootstrap is set to true--which is the default config).

Currently, whenever instantiated from a test, it logs the following warning:
`WARNING: Failed to create derby.properties file!`

Given the current design, this will always happen unless you happen to have a derby dir under the current working directory of the launched application.
And even then, derby will not use this derby.properties file unless its launched from that particular directory (like in the network derby case).

**To Reproduce**
Execute any test that invokes DerbyMaster

**Expected behavior**
DerbyMaster should have a more flexible design and we should have a better approach for providing derby.properties.

**Additional context**
Additionally, the current design of DerbyMaster doesn't seem compatible with our VersionHistoryService and, while adding a migration test for #833 I found that the DEBUG property doesn't work when launched as a test because derby only checks the working directory for the derby.properties file.

**Comment by albertwang-ibm** [comment]
yes, the adding of the properties file for derby is for the performance issue that we found in pipeline integration test, and there is always derby directory there, so it worked well for integration tests.
