### ISSUE TITLE
The search result parameter _count=0 results in a FhirPersistenceException

### ISSUE THREAD

**Issue by mjdisc** [IBM/FHIR#858]
When _count=0 is specified on a search query string, a FhirPersistenceException is returned.
To reproduce, try this:
https://us-south.wh-fhir.dev.cloud.ibm.com/wh-fhir-dev/api/v4/Patient?_count=0

This is the returned json:

``` json
{
    "resourceType": "OperationOutcome",
    "id": "ac-1e-cd-99-eba6558c-c9a6-435e-a4ae-b900a4ba2169",
    "issue": [
        {
            "severity": "fatal",
            "code": "exception",
            "details": {
                "text": "FHIRPersistenceException: Unexpected error while performing a search operation."
            }
        }
    ]
}
```

As stated in the FHIR spec, the expected behavior is this:
"if _count has the value 0, this shall be treated the same as _summary=count: the server returns a bundle that reports the total number of resources that match in Bundle.total, but with no entries, and no prev/next/last links."  See: https://www.hl7.org/fhir/search.html#count

**Comment by prb112** [comment]
We fixed a bug in the search when there is no populated data.  In this case, did you have data in the Patient table? 

Also, can you state the version you are using to test?

**Comment by mjdisc** [comment]
I tested this against https://us-south.wh-fhir.dev.cloud.ibm.com/wh-fhir-dev/api/v4 . So the version is whatever R4 version that server is running.  When I change _count=0 to _summary_count, in the response Bundle the total is 3282. So there are Patients in the db.

**Comment by prb112** [comment]
Great - Thanks - I think it's 4.0.1
