### ISSUE TITLE
DELETE non existing resource return 200 code with "fatal" issue

### ISSUE THREAD

**Issue by smhgit** [IBM/FHIR#864]
I don't know if this can be consider as a bug or not, but I would expect different code return if resource wasn't found (although technically, the command was successful)

![image](https://user-images.githubusercontent.com/10852598/77844137-79343680-71ac-11ea-94dd-d32e63440877.png)

**Comment by lmsurpre** [comment]
Usually best to turn to the spec for this sort of thing:
 https://www.hl7.org/fhir/r4/http.html#delete

In this case, I don't see much guidance on the "proper" behavior for deleting a resource that never existed, but there is this guidance on deleting a previously-deleted resource:
> Performing this interaction on a resource that is already deleted has no effect, and the server should return either a 200 OK if the response contains a payload, or a 204 No Content with no response payload.

In our case, the response contains a payload that explains that the resource doesn't exist, so I think we're OK to return a 200.

Also, we use the AEGIS TouchStone conformance-testing tool and we're passing all their delete tests, so thats a good sign.

However, one thing that I think we *should* clean up is the `OperationOutcome.issue.severity`...IMHO that should be `informational` (or `warning` at worst).

Some other options I'd also be ok with (if they pass touchstone tests):
A. return 404 for deleting a resource that doesn't exist and ever existed.  the downside here is that deleting a resource that doesn't exist behaves different from deleting a resource that did exist but was deleted
B. return 204 with no body by default.  This has the advantage of making the deletion of a non-existent resource consistent with the behavior of deleting a previously-deleted resource, but there there is a downside to that too (client might think they succeeded in delete when they actually performed the delete on the wrong id).

But even in option B, I think we'd want to return a 200 OK + an OperationOutcome warning if the user has set their return preference to `OperationOutcome` (https://www.hl7.org/fhir/http.html#ops)

**Comment by kmbarton423** [comment]
don't write an exception to the log

**Comment by lmsurpre** [comment]
It looks to me like we already dropped the severity of this OO to "warning":
```
{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "warning",
            "code": "not-found",
            "details": {
                "text": "Cannot find Patient with id 'Patient00002'."
            }
        }
    ]
}
```

Still need to check the logs to ensure we're not logging this like a server error.
Additionally, I think there is work to make this behave as expected when the delete is part of a batch/transaction bundle.

**Comment by lmsurpre** [comment]
With the latest changed from #2282, I confirmed that both of the following cases look good to me now:
* deleting a non-existent patient
* deleting an already-deleted patient

In both cases, we return a 200 OK with an appropriate warning, and no stack trace in the logs.

```
{
    "resourceType": "Bundle",
    "type": "batch-response",
    "entry": [
        {
            "response": {
                "status": "200",
                "outcome": {
                    "resourceType": "OperationOutcome",
                    "issue": [
                        {
                            "severity": "warning",
                            "code": "not-found",
                            "details": {
                                "text": "Cannot find Patient with id '{{patientid}}'."
                            }
                        }
                    ]
                }
            }
        }
    ]
}
```

the 'deleting a patient thats already been deleted' case also looks good to me:
```
{
    "resourceType": "Bundle",
    "type": "batch-response",
    "entry": [
        {
            "response": {
                "status": "200",
                "outcome": {
                    "resourceType": "OperationOutcome",
                    "issue": [
                        {
                            "severity": "warning",
                            "code": "deleted",
                            "details": {
                                "text": "Resource of type 'Patient' with id '1' is already deleted."
                            }
                        }
                    ]
                }
            }
        }
    ]
}
```
