### ISSUE TITLE
Build prototype of FHIR-to-OMOP mapping

### ISSUE THREAD

**Issue by JohnTimm** [IBM/FHIR#867]
Build FHIR-to-OMOP prototype based on mappings found here:
https://www.ohdsi.org/web/wiki/doku.php?id=projects:workgroups:mappings_between_ohdsi_cdm_and_fhir
and
http://hl7.org/fhir/us/cdmh/2019May/index.html

**Comment by JohnTimm** [comment]
Created prototype that implements the following FHIR-to-OMOP mappings:

`FHIR Condition Resource -> CONDITION_OCCURRENCE`
`FHIR Encounter Resource -> VISIT_OCCURRENCE`
`FHIR Organization Resource -> CARE_SITE, LOCATION`
`FHIR Patient Resource -> PERSON, LOCATION`
`FHIR Practitioner Resource -> PROVIDER`

The initial prototype generates CSV data compatible with OHDSI OMOP Common Data Model v6.0. Additional work will be needed to support CDM v5.3.1.

**Comment by lmsurpre** [comment]
@JohnTimm which branch is this on?

**Comment by JohnTimm** [comment]
Prototype is in this branch:
https://github.com/IBM/FHIR/tree/johntimm-master-omop
