### ISSUE TITLE
Create a static datasource option

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#916]
Our default configuration uses an XADataSource proxy.

This gives the IBM FHIR some great powers:
* Add new datasources at runtime without a server restart
* Communicate with different backends depending on the tenant
* Supports advanced "sharding" techniques to split the data across multiple backends

However, it also comes with a cost...mostly complexity:
* The proxy datasource (and its dependencies) need to be packaged in a shared lib to participate in liberty-managed transactions.  This is what prevents us from being just a normal ".war"
* Overhead of XADataSource for deployments that simply don't need it

I think the "tricky part" will be to simultaneously:
1. keep our multi-tenancy support without the FHIRProxyXADataSource; and
2. make it simple to configure the server to use the FHIRProxyXADataSource for when you do want it

**Comment by punktilious** [comment]
Great opportunity to clean up connection management in FHIRDbDAOImpl.

**Comment by prb112** [comment]
Moving to Sprint 20

**Comment by lmsurpre** [comment]
I'm opened https://github.com/IBM/FHIR/issues/1694 to make this new datasource behavior our default

**Comment by lmsurpre** [comment]
I reviewed the integration tests and confirmed the static datasource option is working there.
Additionally, these changes were included in the 4.5.0 and deployed to a few environments (without updating the config) and they continue to work as expected (using the proxy datasource).  Looks good.
