### ISSUE TITLE
DocumentReference content returned on read is not the same as was saved.

### ISSUE THREAD

**Issue by mjdisc** [IBM/FHIR#918]
I did a POST for creating a DocumentReference. The input looks like this:
``` json
{
	"resourceType": "DocumentReference",
	"subject": {
		"reference": "Patient/MJD-1"
	},
	"type": {
		"coding": [{
			"system": "http://loinc.org",
			"version": "2.61",
			"code": "68607-1"
		}]
	},
	"status": "current",
	"docStatus": "final",
	"content": [{
		"attachment": {
			"contentType": "text/plain",
			"data": "ABCDEF"
		}
	}]
}
```

That create ran successfully. I then did a read of that DocumentReference. I got this back:

``` json
{
    "resourceType": "DocumentReference",
    "id": "6a7efa25-40fc-4a39-a529-bcbeba624d05",
    "meta": {
        "versionId": "1",
        "lastUpdated": "2020-04-09T19:13:59.472Z"
    },
    "status": "current",
    "docStatus": "final",
    "type": {
        "coding": [
            {
                "system": "http://loinc.org",
                "version": "2.61",
                "code": "68607-1"
            }
        ]
    },
    "subject": {
        "reference": "Patient/MJD-1"
    },
    "content": [
        {
            "attachment": {
                "contentType": "text/plain",
                "data": "ABCDEA=="
            }
        }
    ]
}
```

Notice that content.attachment.data is not the same as what was originally passed in on the POST. Although ABCDEF is just junk test data that is not Base64 encoded, it is nonetheless valid Base64 data (I think). But not getting back the original input on a read is problematic.

I ran this test on: https://us-south.wh-fhir.dev.cloud.ibm.com/wh-fhir-dev/api/v4

**Comment by prb112** [comment]
@mjdisc I believe the behavior is correct (it's just treating the original content as [Base64Binary](https://www.hl7.org/fhir/datatypes.html#attachment))

```
data |   | 0..1 | base64Binary | Data inline, base64ed
-- | -- | -- | -- | --
```

**Comment by JohnTimm** [comment]
Per the Base64 encoding spec:
https://tools.ietf.org/html/rfc4648#page-5

```
   Special processing is performed if fewer than 24 bits are available
   at the end of the data being encoded.  A full encoding quantum is
   always completed at the end of a quantity.  When fewer than 24 input
   bits are available in an input group, bits with value zero are added
   (on the right) to form an integral number of 6-bit groups.  Padding
   at the end of the data is performed using the '=' character.  Since
   all base 64 input is an integral number of octets, only the following
   cases can arise:

   (1) The final quantum of encoding input is an integral multiple of 24
       bits; here, the final unit of encoded output will be an integral
       multiple of 4 characters with no "=" padding.
```

It appears to be padding during encoding.

**Comment by JohnTimm** [comment]
The Base64 validator here:
https://base64.guru/tools/validator

Tells me that, technically, `ABCDEF` is malformed as it should have padding and should instead be:
`ABCDEA==`

The Java Base64 is lenient, in that if you do not include padding in the encoded string, it will fix that when decoding the string.

**Comment by JohnTimm** [comment]
After discussing the with @mjdisc a bit, I think the approach is going to be validation of the encoded string looking for lack of proper padding. This will require changes to the CodeGenerator class and the generated Base64Binary class.

**Comment by prb112** [comment]
as John has a PR for this, I have added 4.2.0
