### ISSUE TITLE
Improve the docker image

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#923]
Follow-on from #837 

Currently, we install our own server.xml and our own server, then delete the defaultServer.
However, now that we're based on OpenLiberty, we should follow the guidance at https://github.com/OpenLiberty/ci.docker#building-an-application-image

Here's at least 3 things that I think we could clean up/take advantage of:

1.  The ibm-fhir-server container prints this warning during startup:
```
[AUDIT   ] CWWKG0102I: Found conflicting settings for defaultKeyStore instance of keyStore configuration.
  Property password has conflicting values:
    Secure value is set in file:/opt/ol/wlp/usr/servers/fhir-server/configDropins/defaults/keystore.xml.
    Secure value is set in file:/opt/ol/wlp/usr/servers/fhir-server/server.xml.
  Property password will be set to the value defined in file:/opt/ol/wlp/usr/servers/fhir-server/server.xml.
```

We might be able to workaround that by convincing Liberty not to mixin their own keystore.xml, but a better option would be to just let liberty generate its own keystore instead of pre-packaging ours.
For more info, see https://github.com/OpenLiberty/ci.docker/blob/master/SECURITY.md#providing-a-custom-keystore

2.  Annotation caching defined at https://developers.redhat.com/blog/2020/01/28/use-red-hat-openshifts-built-in-oauth-server-as-an-authentication-provider-in-open-liberty/

This should help us with the startup performance, which I feel is noticably slower since we moved to OpenLiberty 20.0.0.3 (not sure if its about OpenLiberty vs WebSphere Liberty or about 19.0.0.12 vs 20.0.0.3)

3.  Class caching (when using OpenJ9) as defined at https://github.com/OpenLiberty/ci.docker#openj9-shared-class-cache-scc

**Comment by lmsurpre** [comment]
Currently we use the "full" image.
There's a open issue with startup time on this image:
https://github.com/OpenLiberty/ci.docker/issues/174

However, it looks like this should be improved in future versions: https://github.com/OpenLiberty/ci.docker/pull/175

To move to the "kernel" version, we need to move our server name from `fhir-server` to `defaultServer` (or ask liberty to make their `configure.sh` script more flexible).

**Comment by lmsurpre** [comment]
#2196 addresses points number 2 and 3 from the description by extending `kernel-slim` instead of `full` and using the Liberty-managed `features.sh` and `configure.sh` to install the minimal set of required features and set up the shared class cache (respectively).

On the first point, I don't think we see this warning any more.  However, we continue to use our own self-signed example certificate (rather than using a liberty-generated one on the fly)...mainly because we have all the trust relationships set up between our client and server certs and this would require significant release automation to replicate.

**Comment by lmsurpre** [comment]
I also moved us onto the java 11 version of liberty (from java 8)

**Comment by d0roppe** [comment]
Deployed a new created docker image in the cloud and the the server seems to be up and running quite a bit faster than before. Marking this as closed.
