### ISSUE TITLE
Provide more resources for profile validation

### ISSUE THREAD

**Issue by smhdfdl** [IBM/FHIR#926]
**Is your feature request related to a problem? Please describe.**
IBM App Connect for Healthcare is using the jars from fhir-validation-distribution.zip to offer a FHIR resource validation capability for our users. While it's straightforward to create resources that force errors and warnings for basic validation failures, it is not so for Profile validation so it is not easy to create automated tests that exercise this. 

**Describe the solution you'd like**
For our testing of Profile validation we would like IBM FHIR to provide, for the FHIR core Profile and each fhir-ig-* Profile in the IBM FHIR repo, the following ...
1. A few resources that assert the Profile reference and fail Profile validation with errors. 
2. Same resources but which do not assert the Profile reference, the idea being that if the Profile reference was passed to FHIRValidator, it would then fail validation with same errors.
3. The above in both JSON and XML format.

Existing example https://github.com/IBM/FHIR/blob/master/fhir-ig-carin-bb/src/test/resources/JSON/EOB1.json is a great starting point.

**Describe alternatives you've considered**
Create the resources ourselves, which will take us a lot longer. The resources effectively exist in your unit tests, but as Java classes.

**Additional context**
As discussed with @JohnTimm and @prb112 .

**Comment by smhdfdl** [comment]
It would also be nice to have a specific guide on how to create and package a user-defined Profile as its own jar. This is alluded to in https://ibm.github.io/FHIR/guides/FHIRValidationGuide but I think it needs have a lot more detail.

**Comment by smhdfdl** [comment]
Might be a good idea for one of the resources in 1) above to be a contained resource?

**Comment by prb112** [comment]
@smhdfdl John has added the examples that were discussed. 
https://github.com/ibm/FHIR/commit/34f13dea456d40f04ecd99150104d3365351e7f0

XML Examples `fhir-ig-carin-bb/src/test/resources/XML/`
JSON Examples `fhir-ig-carin-bb/src/test/resources/JSON/`

Please let us know if you require any further details/changes updates..
