### ISSUE TITLE
Allow logging to slf4j

### ISSUE THREAD

**Issue by smhdfdl** [IBM/FHIR#932]
**Is your feature request related to a problem? Please describe.**
As user of the fhir-validation-distribution we would like incorporate info / warning / error log messages into our own logs.  

**Describe the solution you'd like**
Provide slf4j as a logging option.

**Describe alternatives you've considered**

**Additional context**
It looks like there is some Java logging used, but it does not appear to be universal. For example, FHIRValidator does not log and instead uses a public DEBUG static to switch on console output.

**Comment by JohnTimm** [comment]
We do not plan on moving from java.util.logging to slf4j. There is a JUL -> SLF4J bridge available here:
http://www.slf4j.org/api/org/slf4j/bridge/SLF4JBridgeHandler.html
This can be used in conjunction with:
http://logback.qos.ch/manual/configuration.html#LevelChangePropagator

**Comment by prb112** [comment]
Per discussion, we addressed any System.out calls and put as loggers and tuned the logging. 
Please let us know if we can further help.
