### ISSUE TITLE
Add an issue to the issues list if profile not found

### ISSUE THREAD

**Issue by smhdfdl** [IBM/FHIR#933]
**Is your feature request related to a problem? Please describe.**
When validating against a profile, it is not possible to tell whether a resource passed validation because it was genuinely valid or because it was invalid but the profile had not been loaded. This is silently ignored. False positives can result.

**Describe the solution you'd like**
Add an issue to the issues list if profile not found. A Warning issue would be acceptable, but some users might want an Error, so maybe make it configurable. 

**Describe alternatives you've considered**
A log message is useful, but does not allow the calling program to respond to the problem. If an issue is not the right way, then there needs to be some other way a program can discover what happened.
 
**Additional context**

**Comment by lmsurpre** [comment]
> Add an issue to the issues list if profile not found. A Warning issue would be acceptable, but some users might want an Error, so maybe make it configurable.

There's a couple different flavors of this:
1. the user has asked us to validate an instance and that instance claims it conforms to some profiles
2. the user has explicitly passed us a profile and asked us to validate the instance against that profile

In my opinion, the former should be a WARNING whereas the latter should be either an ERROR.
