### ISSUE TITLE
4.2.0 Release

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#957]
https://github.com/IBM/FHIR/wiki/Release-Guide

**Comment by prb112** [comment]
Lee raised a Fix for Docker
Paul raised a fix for Error 413 (too big a file) and Cleaned up the Automation 
... Successful Build... 
Lee officially released on GitHub
Paul posted the files and Published on Bintray

**Comment by prb112** [comment]
PR https://github.com/IBM/FHIR/pull/1049 move to 4.2.2-SNAPSHOT
