### ISSUE TITLE
FHIRNotificationService should emit event for delete

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#983]
**Is your feature request related to a problem? Please describe.**
While testing the new NATS-based notification component, I was surprised to find that we're not emitting NotificationEvents for the delete interaction.

**Describe the solution you'd like**
By default, we should fire a notification event when a delete occurs.
It could look something like this:
```
FHIRNotificationEvent {"lastUpdated":"2020-04-24T21:46:08.089Z","location":"Claim/1/_history/2","operationType":"delete","resourceId":"1"}
```

**Describe alternatives you've considered**
The main alternative would be to include a resource in the body of the event, either the full resource before the delete (which would match our current "history" behavior), or some kind resource "stub" ...a minimally valid resource of this type that includes certain fields like Meta.
In my opinion, the simplest thing to do would be to simply leave the resource field out of the event.

**Comment by prb112** [comment]
in `public class FHIRNotificationService implements FHIRPersistenceInterceptor {` one would need to implement the afterDelete notification event.
