### ISSUE TITLE
fhir-persistence-schema - Update for additional property 

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#986]
fhir-persistence-schema - Update for additional property  db.ssl

**Comment by festewart** [comment]
The property to specify on the command line is --prop sslConnection=true
I tested it successfully this morning - db.ssl did not work.
Here is an example of my invocation in case it helps:
java -cp ./fhir-persistence-schema-cli.jar -Djavax.net.ssl.trustStore=<trustStoreContainingDB2SignerCerts> -Djavax.net.ssl.trustStorePassword=<trustStorePassword> -jar ./fhir-persistence-schema-cli.jar --prop db.host=<dbHost> --prop db.port=<dbSSLPort> --prop db.database=<dbName> --prop user=<dbAdminUser> --prop password=<dbAdminUserPassword> --prop sslConnection=true
