### ISSUE TITLE
Documentation issue: Db2 - (transactional) does not exist in IBM Cloud

### ISSUE THREAD

**Issue by festewart** [IBM/FHIR#989]
On page https://github.com/IBM/FHIR/blob/master/docs/src/pages/guides/DB2OnCloudSetup.md
under Create a DB2 instance section it says:
3. Choose Db2 (transactional).

That does not exist in the catalog. I am not sure which db2 service you want to recommend - I suspect you were thinking "Db2" formerly DashDB for Transactions but am not sure

**Comment by prb112** [comment]
It's linked above intentionally.  I've moved the link to this resource and Lee has merged
