### ISSUE TITLE
Merge bulkimportexport project to bulkimportexport-webapp project

### ISSUE THREAD

**Issue by albertwang-ibm** [IBM/FHIR#99]
As parting of our effort to reduce the total number of projects.

**Comment by prb112** [comment]
is the intent to merge bulkimport-webapp into fhir-server? if not, I think this pattern is preferred.  


Then we can use 
```
JobOperator jobOperator = BatchRuntime.getJobOperator();
jobOperator.start("FhirBulkExportChunkJob", toProperties(properties));
```
private Properties toProperties(Map<String,String> props){
         Properties properties = new Properties();
         for(Entry<String, String> entry : props.entrySet()) {
             properties.put(entry.getKey(), entry.getValue());
         }
         return properties;
}
```
instead of the REST api.

**Comment by lmsurpre** [comment]
My comment to albert was that if we can't run it without the webapp then i don't see why we need both of the projects.  If its possibly to submit a job from the jar file without the webapp, then i agree it makes sense to keep separate.
I was looking for ways to keep the overall number of projects sane...

**Comment by prb112** [comment]
Yes, it's possible to submit without the webapp.  that's why I think we should use the above snippet to integrate with the operation framework instead of the REST call.
