### ISSUE TITLE
Need to be able to write tenant key to a file or specify your own tenant key

### ISSUE THREAD

**Issue by festewart** [IBM/FHIR#990]
In V4, a new tenantKey requirement was added for multi tenant support.
We are required to use the peristence API with the --allocate-tenant option to add tenant and get key.
The key is not output other than in a very verbose amount of other output which then requires any script that is attempting to automate the onboarding of a tenant to the FHIR server to grep  the output for a specific information message line of text and parse out the key.

If that message were to ever change the script would be broken. The current design does not lend itself to automation of user subscription and provisioning

My suggestion is two-fold, either or both of the items would make life easier for automation - like when provisioning a tenant for PDM which includes installing FHIR and provisioning the tenant there as well:
1. Add an option to output the tenant key to a file. E.g. --allocate-tenant <tenant> --tenantKeyOutputFile <path/file>

AND/OR

2. Allow the caller to "bring their own key". I.e. let the caller pass in the  tenant key to use - document any required format/valid characters in the persistence doc of course
E.g.
--allocate-tenant <tenant> --tenant-key <keyToUse>

**Comment by prb112** [comment]
Added bring your own feature and write-out if the key file doesn't exist. 
The code checks if a tenantkey already exists when allocating and adding a tenantkey

**Comment by prb112** [comment]
Merged in for 4.2.0
